- matsim/src/main/java/org/matsim/core/controler/OutputDirectoryHierarchy.java
The new error message describes another existing method to prevent the failure
that happens when the output directory exists on a newly started simulation.
> Updating the error message on failIfDirectoryExists.

- matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/QueueWithBuffer.java
using math.floor function before adding current time step to link travel time. This will
eliminate some of the rounding error (see following example) due to java double precision.
Math.floor( 60 + 59.99999999999999) will return 120.0 whereas 
Math.floor(59.99999999999999) + 60 will return 119.0
> using floor function before adding current time step to it. This will

- matsim/src/main/java/org/matsim/core/utils/io/OsmNetworkReader.java
- matsim/src/test/java/org/matsim/core/utils/io/OsmNetworkReaderTest.java
Two major changes are:
1.  the OSM lanes tag specifies the total no of lanes (i.e. in both directions). Therefore, for 2-way roads the numbers of lanes in each direction is 'lanes/2'. The osm maps of Poznan and Berlin follow this rule.
2. the access tag was added to prevent building links where no traffic is allowed
In particular, change 1 may result in reduced flow and storage capacities of some links in newly converted networks. 
These changes are also (being?) introduced by Michael Z. in josm-matsim-plugin
Besides that, a few smaller improvements/bugfixes were introduced.
> inprovements in OsmNetworkReader

- matsim/src/main/java/org/matsim/core/network/NetworkUtils.java
- matsim/src/main/java/org/matsim/core/scenario/MutableScenario.java
- matsim/src/main/java/org/matsim/core/scenario/ScenarioLoaderImpl.java
This is a fix for MATSIM-513: No way of choosing the link factory while loading a scenario with a time variant network
> scenario loading does not overwrite the link factory of a time variant

- contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/events/handlers/PersonArrivalDepartureHandler.java
- contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/manager/demand/CurrentTotalDemand.java
- contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/manager/demand/DemandHandler.java
this PR adds checks to avoid NullPointerExceptions in PersonArrivalDepartureHandler.java and CurrentTotalDemand.java in cases where the person ID passed with the event instance is not available in the handler instance variable used to track data about the agents actions.
The background is that the PersonEntersVehicleEvent and LinkLeaveEvent are also triggered by the relocation agents actions, and I think it would be confusing to track these in this way.
> Avoid null pointer exceptions

- contribs/hybridsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/QSimExternalTransitionLink.java
- matsim/src/main/java/org/matsim/core/config/groups/QSimConfigGroup.java
- matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/QLaneI.java
- matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/QLinkImpl.java
- matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/QLinkLanesImpl.java
- matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/QueueWithBuffer.java
- playgrounds/kai/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/AssignmentEmulatingQLane.java
- playgrounds/michalm/src/main/java/playground/michalm/telaviv/RunFlowCapEasingScenario.java
- playgrounds/vsptelematics/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/KNCALink.java
This pull request addresses the issue of buses running behind their schedule in sub-sampled scenarios.
Vehicles of size (in PCU) smaller than or equal to this threshold will be allowed to enter the buffer (QueueWithBuffer) even if flowcap_accumulate <= 0.
The default value is 0.0 meaning that all vehicles of non-zero sizes will be let into buffer only if flowcap_accumulate > 0.
Flow capacity easing prevents buses from waiting long time for entering the buffer in sub-sampled scenarios. For instance, for 10% scenario, a car (representing 10 cars) has a size of 1.0 PCU, a bus (representing 1 bus) has a size of 0.3 PCU, and link flow capacities are reduced to about 0.1 of the original capacity.
(1) If pcuThresholdForFlowCapacityEasing == 0, all buses moving just behind private cars wait long …
> Flow cap easing for buses

- .travis.yml
- tutorial/pom.xml
I'm having travis create the full set of packages, instead of only running the tests.
This would have picked up e.g. MATSIM-727. Now Javadoc generation is under test.
> Test the whole packaging. Fix Javadoc Errors.

- matsim/src/main/java/org/matsim/core/router/Dijkstra.java
NullPointerException was thrown if prevLink is null, because node n is the node from where the search started (happened for many-to-one search, where n is an ImaginaryNode)
> bugfix Dijkstra.addToPendingLinks -- prevLink may be null

- contribs/roadpricing/src/main/java/org/matsim/roadpricing/CalcPaidToll.java
- contribs/roadpricing/src/main/java/org/matsim/roadpricing/RoadPricingControlerListener.java
- contribs/roadpricing/src/main/java/org/matsim/roadpricing/RoadPricingWriterXMLv1.java
- contribs/roadpricing/src/test/java/org/matsim/roadpricing/CalcPaidTollTest.java
Tolls in roadpricing contrib used to be charged once per day. While this is useful for cars, it is not very useful for taxis or other modes where the driver may want to pass on the toll to the passenger.
> Charging tolls as they occur rather than once per day

- contribs/minibus/src/main/java/org/matsim/contrib/minibus/stats/GexfPOperatorCount.java
- contribs/minibus/src/main/java/org/matsim/contrib/minibus/stats/GexfPPaxCount.java
- contribs/minibus/src/main/java/org/matsim/contrib/minibus/stats/GexfPStat.java
- contribs/minibus/src/main/java/org/matsim/contrib/minibus/stats/GexfPStatLight.java
- contribs/minibus/src/main/java/org/matsim/contrib/minibus/stats/SimpleGexfPStat.java
The previous implementation only wrote setStart (that means start time
respectively start iteration) for XMLAttvalue values, so these
dynamically changing (at PConfigGroup.WRITE_GEXF_STATS_INTERVAL) values
overlapped, because no end time was defined and more and more values
were added. This caused Gephi to complain about the overlaps and not to
load the exported gefx files.
solution:
Add corresponding setEnd(iteration) to each XMLAttvalue
setStart(iteration), so start and end time/iteration are equal and can
not overlap.
This might lead to gaps if PConfigGroup.WRITE_GEXF_STATS_INTERVAL > 1,
for example:
first value: start=1, end=1; 
next value: start=10, end=10;
...
> fix .gefx file export in contrib/minibus/stats

- matsim/src/main/java/org/matsim/core/population/io/StreamingPopulationWriter.java
Bringing StreamingPopulateionWriter in line with the ordinary population writer.
> Streaming PopulationWriter writes now V6 output by default

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtAnalysisControlerListener.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DynModeTripsAnalyser.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtControlerCreator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/RunDrtExample.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/RunDrtScenario.java
- contribs/dvrp/pom.xml
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/DvrpConfigConsistencyChecker.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/DvrpConfigGroup.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dynagent/run/DynQSimConfigConsistencyChecker.java
- contribs/dvrp/src/main/java/org/matsim/contrib/util/BeanValidationConfigConsistencyChecker.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiConfigConsistencyChecker.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiConfigGroup.java
Use bean validation for simple config group validation instead of longish (often out-of-date and partially missing) sequences of 'if' statements in config checkers.
A couple of lines from of `DrtConfigGroup`:
```
//....
@Min(1)
private double maxTravelTimeAlpha = Double.NaN;// [-]
@PositiveOrZero
private double maxTravelTimeBeta = Double.NaN;// [s]
@NotNull
private OperationalScheme operationalScheme = OperationalScheme.door2door;
@NotNull
private String vehiclesFile = null;
@Positive
private int numberOfThreads = Runtime.getRuntime().availableProcessors();
//....
```
And the auto-generated checking result (when running DRT with empty dvrp and drt groups):
```
Exception in thread "main" javax.validation.ConstraintViolationException: Errors in config:
drt.maxTravelTimeBeta: must be greater …
```
> Config bean validation

- matsim/src/main/java/org/matsim/core/utils/misc/Time.java
- matsim/src/test/java/org/matsim/core/utils/misc/TimeTest.java
"hour" data type is now consistently "long" in both writeTime and parseTime functions and is now tested for.
> Hour data type is now consistent in both writeTime and parseTime.

- matsim/src/main/java/org/matsim/core/controler/AbstractController.java
- matsim/src/main/java/org/matsim/core/controler/ControlerUtils.java
- matsim/src/main/java/org/matsim/core/controler/OutputDirectoryLogging.java
To be able to use MATSim as a library, it helps to be able to redirect logging to other facilities. The by now most common way to do this is to use a logging API such as slf4j. Maybe at one point we should switch to that.
However, even now it is possible to redirect log4j to slf4j, and slf4j to anything, by using a "stub" log4j implementation to replace it (from the outside, via dependency management). We did that at Berkeley Lab.
_That_ however only works if MATSim refrains from using _very_ custom Log4j features in two places. This pull request removes those usages. I think they aren't very important any more. Let me know what you think.
> Remove custom use of log4j

- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/data/file/FleetProvider.java
A tiny PR, mostly because the last build on jenkins failed at the deployment phase:
http://ci.matsim.org:8080/job/MATSim_contrib_M2/6195/
> make FleetProvider.network private

- matsim/src/main/java/org/matsim/core/controler/PrepareForSimImpl.java
In prepareForSim, vehicles were created for every network mode however, it would throw exception if set of mainModes (qSimConfigGroup) and networkModes (planscalcroute) are different. Thus, now, vehicles in prepareForSim are created only for mainModes which is consistent with the placing of the vehicles in PopulationAgentSource.
> creating vehicles only for main modes rather than for every network mode

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/ZonalDemandAggregator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DefaultDrtOptimizer.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/LinearRebalancingTargetCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingParams.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingParamsConsistencyChecker.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingStrategy.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigConsistencyChecker.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModule.java
- contribs/drt/src/main/resources/drt_example/drtconfig_door2door.xml
- contribs/drt/src/main/resources/drt_example/drtconfig_stopbased.xml
- contribs/drt/src/main/resources/mielec_2014_02/mielec_drt_config.xml
- contribs/drt/src/test/java/org/matsim/contrib/drt/run/example/RunDrtExampleIT.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/run/example/RunOneSharedTaxiExampleIT.java
Add `MinCostFlowRebalancingParams` to `DrtConfigGroup`, where all parameters used by the min-cost-flow rebalancing are specified. If the parameter set is not specified - no rebalancing is performed.
There is no need to add `MinCostFlowRebalancingModule` to the controller manually - now it all happens automatically based on the config.
> add MinCostFlowRebalancingParams to DrtConfigGroup

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/VehicleData.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserter.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DetourLinksProvider.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ParallelMultiVehicleInsertionProblem.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ParallelPathDataProvider.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/PrecalculablePathDataProvider.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/StopBasedPathDataProvider.java
About 25% compared to the previous tests on TaxiBerlin (see #270 ).
Speed gains are mostly due to parallelisation of:
- insertion filtering (the new step 2 introduced in #270 )
- `VehicleData` creation
> Further DRT speed improvements

- contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/replanning/ChooseRandomTripMode.java
- contribs/socnetsim/src/main/java/org/matsim/contrib/socnetsim/sharedvehicles/replanning/OptimizeVehicleAllocationAtTourLevelAlgorithm.java
- matsim/src/main/java/org/matsim/core/controler/PrepareForSimImpl.java
- matsim/src/main/java/org/matsim/core/controler/XY2LinksForFacilities.java
- matsim/src/main/java/org/matsim/core/population/algorithms/ChooseRandomLegModeForSubtour.java
- matsim/src/main/java/org/matsim/core/population/algorithms/PersonPrepareForSim.java
- matsim/src/main/java/org/matsim/core/population/algorithms/XY2Links.java
- matsim/src/main/java/org/matsim/core/replanning/modules/SubtourModeChoice.java
- matsim/src/main/java/org/matsim/core/router/PlanRouter.java
- matsim/src/main/java/org/matsim/core/router/TripStructureUtils.java
- matsim/src/main/java/org/matsim/facilities/FacilitiesFromPopulation.java
- matsim/src/main/java/org/matsim/facilities/FacilitiesReaderMatsimV1.java
- matsim/src/main/java/org/matsim/facilities/FacilitiesWriterV1.java
- matsim/src/main/resources/dtd/facilities_v1.dtd
- matsim/src/test/java/org/matsim/core/router/TripStructureUtilsSubtoursTest.java
- matsim/src/test/java/org/matsim/facilities/ActivityFacilitiesSourceTest.java
- matsim/src/test/java/org/matsim/population/algorithms/ChooseRandomLegModeForSubtourTest.java
Here is a summary of the important changes:
- MATSIM-801: coord for facility is optional (however, there will be an exception if neither link nor coord is available)
- similar to XY2Links, there is now also XY2LinkForFacilities which sets linkId for facilities if not available already
- slowly moving towards the convention in which facilities are used before activities and activities are used as fall-back option
- same convention is used to identify the subTours in TripStructureUtils
> Facilities related changes

- contribs/noise/src/main/java/org/matsim/contrib/noise/handler/NoiseTimeTracker.java
only relevant for noise computations with simulated pt and without a bus
mode identifier
> minor bug fix in the noise contrib

- matsim/src/main/java/org/matsim/counts/CountsWriter.java
- matsim/src/main/resources/dtd/counts_v1.xsd
- matsim/src/test/java/org/matsim/counts/MatsimCountsIOTest.java
A new, empty counts container could be created and written out. But it could not be read back in because the XML-Schema defined that there must be at least 1 counting station in the file (why?), and because the (required) year was initially set to 0, which was not accepted as a valid year (actually, "1" would also not be accepted by the XML parser, but "0001" would have been accpted). Changing the year-attribute to int, so "0" is also supported.
Adding tests for these things.
> Fix some issues with Counts.

- contribs/signals/src/main/java/org/matsim/contrib/signals/builder/SignalsModule.java
was not bound as singleton before
> correct SignalEvent2ViaWriter

- contribs/minibus/src/main/java/org/matsim/contrib/minibus/hook/PControlerListener.java
> minibus: rename output transitVehicles file to "transitVehicles.xml.gz"

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DynModePassengerStats.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/run/example/RunDrtExampleIT.java
Apparently, rejected DRT trips are handled in a way that the person is teleported to it's destination. I think that's ok, but I don't really understand why the DefaultTeleportationEngine is taking over...
* minor changes to avoid a runtime exception thrown by some analysis class in case there are rejected trips
* adding a test in which the drt request of one person should be rejected
> Drt request rejection

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DefaultDrtOptimizer.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserter.java
Thanks for your changes @michalmac.
Let us additionally throw a person stuck and abort event, ok?
This way, we make sure the agent gets a bad score and the consequences of the rejection are more visible when analyzing events.
In the longterm, I would still say, we need a switch to either take the agents out of the simulation (current implementation) or teleport the agents to their destination (and additionally throw a person stuck event).
> throwing a person stuck and abort event in case a request is rejected

- contribs/av/src/main/java/org/matsim/contrib/av/maxspeed/DvrpTravelTimeWithMaxSpeedLimitModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/DrtRequestCreator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/vrpagent/DrtActionCreator.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetaxi/OneTaxiActionCreator.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetruck/OneTruckActionCreator.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetruck/RunOneTruckExample.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/DvrpConfigGroup.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/trafficmonitoring/DvrpTravelTimeModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/vrpagent/VrpLeg.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/vrpagent/VrpLegFactory.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/vrpagent/TaxiActionCreator.java
Now we can physically simulate truck or bike deliveries.
`RunOneTruckExample` shows how to set up a scenario where we use modes other than "car" and we do not transport passengers.
> add mobsimMode to support other modes than "car"

- contribs/av/src/main/java/org/matsim/contrib/av/robotaxi/scoring/TaxiFareConfigGroup.java
- contribs/av/src/main/java/org/matsim/contrib/av/robotaxi/scoring/TaxiFareHandler.java
This allows us to use the fare handler for taxi or drt.
Previously it used to be the mode from the dvrp config group, but since the mode was moved to the drt / taxi config group this handler was only working for taxi.
> fare computation: use mode from fare config group instead of the taxi config group

- contribs/taxi/src/main/java/org/matsim/contrib/taxi/data/TaxiRequest.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/data/validator/DefaultTaxiRequestValidator.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/data/validator/TaxiRequestValidator.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/DefaultTaxiOptimizer.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/DefaultTaxiOptimizerProvider.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/assignment/AssignmentTaxiOptimizer.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/rules/RuleBasedTaxiOptimizer.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/zonal/ZonalTaxiOptimizer.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/passenger/TaxiRequestRejectedEvent.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/passenger/TaxiRequestRejectedEventHandler.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiModule.java
- contribs/taxi/src/test/java/org/matsim/contrib/taxi/run/RunTaxiScenarioTestIT.java
adding the request validation functionality to the taxi module, similar to the drt module
@michalmac, I know you are planning to slim down the taxi contrib and reuse drt functionality. However, I need the request validation functionality right now and didn't really see an easy way other than copy-paste from the DRT module and rename + adjust.
I also added a test where a single agent's request is rejected.
Hope you are ok with my changes in the taxi module, at least for a temporary solution.
> Request validator for taxi

- contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/DefaultTaxiOptimizer.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiConfigGroup.java
allows to switch off detailed print out of warnings in case of passenger
request rejections
> adding a config parameter to taxi config group

- contribs/emissions/src/main/java/org/matsim/contrib/emissions/EmissionModule.java
URL.getFile() does not return a valid path to a file in the filesystem, but returns the filename-part of the URL. That filename-part uses a special encoding for certain characters (e.g. a whitespace is encoded as %20) which is only valid in URLs, but not in the local filesystem. Thus file-access in the local filesystem might file when using URL.getFile() when the path or filename contains whitespace or other special characters. Fix this by changing the file access to use the URLs instead of the filename-Strings.
> replace file access with URL instead of String/filename (AGAIN!!!)

- contribs/emissions/src/main/java/org/matsim/contrib/emissions/example/RunEmissionToolOnlineExampleV2.java
- contribs/emissions/src/main/java/org/matsim/contrib/emissions/example/archive/RunEmissionToolOfflineExample.java
- contribs/emissions/src/main/java/org/matsim/contrib/emissions/example/archive/RunEmissionToolOnlineExample.java
- contribs/emissions/src/main/java/org/matsim/contrib/emissions/roadTypeMapping/VisumHbefaRoadTypeMapping.java
URL.getFile() does not return a valid path to a file in the filesystem, but returns the filename-part of the URL. That filename-part uses a special encoding for certain characters (e.g. a whitespace is encoded as %20) which is only valid in URLs, but not in the local filesystem. Thus file-access in the local filesystem might file when using URL.getFile() when the path or filename contains whitespace or other special characters. Fix this by changing the file access to use the URLs instead of the filename-Strings.
> replace file access with URL instead of String/filename

- contribs/emissions/src/main/java/org/matsim/contrib/emissions/EmissionModule.java
bug fix in the previous updates related to MATSim-785; AFAIK, functionality related to fromFile for roadTypeMapping is meant for VISUM files; a blank HBEFARoadTypeMapperis not helpful. 
@joemolloy : have a look.
> MATSIM-785

- contribs/accessibility/src/test/java/org/matsim/contrib/accessibility/run/AccessibilityIntegrationTest.java
- contribs/minibus/src/test/java/org/matsim/contrib/minibus/integration/SubsidyTestIT.java
- matsim/src/main/java/org/matsim/core/utils/collections/QuadTree.java
- matsim/src/test/java/org/matsim/core/utils/collections/QuadTreeTest.java
Reduce memory consumption of QuadTree by not wrapping every single Leaf in a Node, but store multiple Leafs per Node (known as fan-out in tree data structures). Due to less random memory access, and less object creation, put- and get-performance actually improves measurably, as does the memory overhead imposed by the QuadTree.
> QuadTree performance and memory improvements

- matsim/src/test/java/org/matsim/core/controler/MatsimServicesImplTest.java
Test for a bug I found today: event.getServices().getIterationNumber() lags behind event.getIteration() starting from iteration 1 (in iteration 1: event.getServices().getIterationNumber() = 0 whereas event.getIteration() = 1) . Set to ignore to merge this test into master.
> Matsim services iteration number test

- contribs/noise/src/main/java/org/matsim/contrib/noise/utils/MergeNoiseCSVFile.java
label2time2rp2value stores rp id's as strings, but while filling the table in the xyt case, the writeFileReceiverPoint method was trying to access an id, producing a null point exception. 
Changed to this.label2time2rp2value.get(label).get(time).get(rp.toString()) as it should be.
> Small bug in MergeNoiseCSVFile

- contribs/noise/src/main/java/org/matsim/contrib/noise/data/NoiseContext.java
Due to rounding errors, the cosine was sometimes larger than one, leading to a NaN for the computed angle value and hence for the correction and all other subsequent values.
Quick fix, check if value > 1 or < -1 and set to 1 or -1 respectively.
> Check if cosine larger than one in angle immissions correction

- contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/qsim/CarsharingQsimFactoryNew.java
- contribs/hybridsim/src/main/java/org/matsim/contrib/hybridsim/simulation/HybridMobsimProvider.java
- contribs/integration/src/test/java/org/matsim/integration/weekly/fundamentaldiagram/CreateAutomatedFDTest.java
- contribs/multimodal/src/main/java/org/matsim/contrib/multimodal/MultimodalQSimFactory.java
- contribs/otfvis/src/main/java/org/matsim/pt/demo/AccessEgressDemo.java
- contribs/otfvis/src/main/java/org/matsim/pt/demo/BlockingStopDemo.java
- contribs/signals/src/main/java/org/matsim/contrib/signals/builder/Signals.java
- contribs/signals/src/test/java/org/matsim/contrib/signals/builder/QSimSignalTest.java
- contribs/signals/src/test/java/org/matsim/contrib/signals/builder/TravelTimeFourWaysTest.java
- contribs/socnetsim/src/main/java/org/matsim/contrib/socnetsim/jointtrips/qsim/JointQSimFactory.java
- matsim/src/main/java/org/matsim/core/controler/AllowsConfiguration.java
- matsim/src/main/java/org/matsim/core/controler/AllowsOverriding.java
- matsim/src/main/java/org/matsim/core/controler/Controler.java
- matsim/src/main/java/org/matsim/core/mobsim/qsim/QSimBuilder.java
- matsim/src/main/java/org/matsim/withinday/mobsim/WithinDayQSimFactory.java
- matsim/src/test/java/org/matsim/core/mobsim/qsim/AgentNotificationTest.java
- matsim/src/test/java/org/matsim/core/mobsim/qsim/components/QSimComponentsTest.java
- matsim/src/test/java/org/matsim/core/mobsim/qsim/jdeqsimengine/JDEQSimPluginTest.java
A proposal to deal with the missing capability to add overriding QSimModules from overriding ControlerModules.
The main thing is that this proposal standardizes the syntax between Controler and QSimBuilder, so that they can be pulled behind the same interface.
A consequence is that it would be addOverridingModule instead of addOverridingControlerModule in QSimBuilder.  I don't see this as a change to the better, but it is a necessity if I want to unify syntax, plus leave the older API unchanged.
> [do not merge] Allows overriding

- contribs/av/src/main/java/org/matsim/contrib/av/intermodal/RunTaxiPTIntermodalExample.java
- contribs/av/src/main/java/org/matsim/contrib/av/robotaxi/run/RunRobotaxiExample.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/MultiModeDrtMainModeIdentifier.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigConsistencyChecker.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigs.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtControlerCreator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/MultiModeDrtConfigGroup.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/MultiModeDrtModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/examples/RunMultiModeDrtExample.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/benchmark/DvrpBenchmarkModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetaxi/RunOneTaxiExample.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetaxionetruck/RunOneTaxiOneTruckExample.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetruck/RunOneTruckExample.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/AbstractDvrpModeQSimModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/ConfigConsistencyCheckers.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/DvrpModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/DvrpQSimComponents.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/Modal.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/MultiModal.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/benchmark/RunTaxiBenchmark.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/MultiModeTaxiConfigGroup.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/MultiModeTaxiModule.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiConfigConsistencyChecker.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiConfigGroup.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiControlerCreator.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/examples/RunMultiModeTaxiExample.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/examples/RunTaxiExample.java
Moved to DvrpQSimComponents to enable easier "scripting"
Additionally, generalise handling of multi-mode drt/taxi configs...
> move qsim component activation outside Dvrp(Benchmark)Module

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DefaultDrtOptimizer.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DrtOptimizer.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtControlerCreator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/RunDrtScenario.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/examples/RunDrtExample.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/examples/RunOneSharedTaxiExample.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/vrpagent/DrtActionCreator.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/run/examples/RunDrtExampleIT.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/tracker/OnlineDriveTaskTrackerImpl.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/tracker/OnlineTrackerListener.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/tracker/TaskTrackers.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/vrpagent/VrpLegFactory.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/DefaultTaxiOptimizer.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/DefaultTaxiOptimizerParams.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/TaxiOptimizer.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiModeQSimModule.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/vrpagent/TaxiActionCreator.java
- separate at the level of interfaces
- no need for active listening in most cases - currently schedules get updated before each optimisation
> separate OnlineTrackerListener from VrpOptimizater

- contribs/emissions/src/main/java/org/matsim/contrib/emissions/WarmEmissionAnalysisModule.java
- contribs/emissions/src/main/java/org/matsim/contrib/emissions/utils/EmissionsConfigGroup.java
- contribs/emissions/src/test/java/org/matsim/contrib/emissions/TestWarmEmissionAnalysisModule.java
- contribs/emissions/src/test/java/org/matsim/contrib/emissions/TestWarmEmissionAnalysisModuleTrafficSituations.java
The default is the fraction method validated in Hülsmann et al. (2011).
This pull request would return the previous method which took a fraction of freeflow and stop&go to reflect queuing time on links. An approach using all 4 traffic states is still available, but must be enabled in the emissions config with `isUsingFractionalApproach`
The functionality that was restored is (removed in commit [5c80fd ](https://github.com/matsim-org/matsim/commit/5c80fdf9849e995a1adeee9a62d0720e991287fa):
```
double distanceStopGo_km = (linkLength_km * stopGoSpeedFromTable_kmh * (freeFlowSpeed_kmh - averageSpeed_kmh)) / (averageSpeed_kmh * (freeFlowSpeed_kmh - stopGoSpeedFromTable_kmh));
double distanceFreeFlow_km = linkLength_km - distanceStopGo_km;
generatedEmissions = (distanceFreeFlow_km * …
```
> Provide the ability to choose between the fraction and average-speed approaches

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtModeAnalysisModule.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/run/examples/RunDrtExampleIT.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/AbstractDvrpModeModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/AbstractDvrpModeQSimModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/ModalProviders.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/dvrp/DvrpAuxConsumptionFactory.java
It is very easy to accidentally call `addMobsimListenerBinding()` instead of `addQSimComponentBinding()` in a QSim module nested inside a "standard" (controller) module.
I tried to prevent such cases in the future with: 99b4551 (for subclasses of `AbstractDvrpModeQSimModule`).
Maybe there is a cleaner approach that prevents adding controller-level bindings after the controller starts???
> fix: replace call addMobsimListenerBinding() with addModalQSimComponent()

- contribs/noise/src/main/java/org/matsim/contrib/noise/utils/ProcessNoiseImmissions.java
- matsim/src/main/java/org/matsim/core/config/groups/PlansCalcRouteConfigGroup.java
- matsim/src/main/java/org/matsim/pt/router/TransitRouterConfig.java
- matsim/src/test/java/org/matsim/core/config/groups/PlansCalcRouteConfigGroupTest.java
- matsim/src/test/java/org/matsim/pt/router/TransitRouterConfigTest.java
Implementation of `TransitRouterConfig` was such that it needed teleported walk routing activated.  Changed that (by using the access_walk params instead).
In the process, I removed the automagical clearing of default routing params.  I found that more awkward than helpful.  Now one can actively remove them one by one, or clear them all, or add to them.
> Kn let pt use access walk telep params

- matsim/src/main/java/org/matsim/core/network/filter/NetworkFilterManager.java
- matsim/src/test/java/org/matsim/core/network/filter/NetworkFilterManagerTest.java
This is a cleaned up PR #518 (without the commit relating to EV)
> network filter manager did not recreate link attributes

- contribs/drt/src/main/java/org/matsim/contrib/edrt/schedule/EDrtTaskFactoryImpl.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/tracker/OnlineDriveTaskTracker.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/tracker/OnlineDriveTaskTrackerImpl.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/AuxDischargingHandler.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/AuxEnergyConsumption.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/DriveDischargingHandler.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/DriveEnergyConsumption.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/EnergyConsumptions.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/LTHDriveEnergyConsumption.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/OhdeSlaskiAuxEnergyConsumption.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/OhdeSlaskiDriveEnergyConsumption.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/dvrp/TaskEnergyConsumptions.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/dvrp/tracker/OnlineEDriveTaskTracker.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ElectricFleetReader.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ElectricVehicleImpl.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ElectricVehicleSpecification.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/routing/EVNetworkRoutingModule.java
Main changes:
- add `OnlineDriveTaskTracker.getCurrentLinkEnterTime()`
- change `linkLeaveTime` to `linkEnterTime` in the `DriveEnergyConsumption.calcEnergyConsumption()` arguments to keep this interface consistent with the `TravelTime` and `TravelDisutility` interfaces (where the departure time is used)
- change `AuxEnergyConsumption.calcEnergyConsumption(double period, double timeOfDay)` args to `(double beginTime, double duration)`. `timeOfDay` does not suggest whether it is the begin or end, and so was used inconsistently over the workspace
> clean up XxxEnergyConsumption

- contribs/drt/src/main/java/org/matsim/contrib/edrt/run/EDrtControlerCreator.java
- contribs/drt/src/main/java/org/matsim/contrib/edrt/run/RunEDrtScenario.java
- contribs/drt/src/main/resources/mielec_2014_02/mielec_edrt_config.xml
- contribs/ev/src/main/java/org/matsim/contrib/ev/EvConfigGroup.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingModule.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/DischargingModule.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/OhdeSlaskiAuxEnergyConsumption.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/dvrp/EvDvrpIntegrationModule.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/temperature/TemperatureService.java
- contribs/ev/src/main/resources/config.xml
- contribs/taxi/src/main/java/org/matsim/contrib/etaxi/run/RunETaxiBenchmark.java
- contribs/taxi/src/main/java/org/matsim/contrib/etaxi/run/RunETaxiScenario.java
- contribs/taxi/src/main/resources/mielec_2014_02/mielec_etaxi_config.xml
- contribs/taxi/src/main/resources/mielec_2014_02/mielec_etaxi_config_assignment.xml
Mainly: size down `EvDvrpIntegrationModule`:
- remove all factory setters (use binding overriding instead)
- use `EvDvrpIntegrationModule` in addition to (not instead of) EvModule
> Guicier EV

- contribs/ev/src/main/java/org/matsim/contrib/ev/charging/FastThenSlowCharging.java
this is neccessary, e.g., for non-stationary chargers
> add possibility to calc charge without a charger

- matsim/src/main/java/org/matsim/core/config/CommandLine.java
allow for more than one hierarchy level in the parameter sets, allow for
the (quite common) case subpopulation=null in the scoring parameters
> minor change in the command line functionality

- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/path/VrpPaths.java
In my current use case I actually send vehicles to a parking spot after they drop off a passenger, but the links have separate capacities for parking and dropoff spots. So if the current link is selected as the parking spot, I actually want the vehicles to drive a loop and enter the link again, now with the "parking intention" rather "dropoff intention". Took me some time to figure out that vehicles were not moving at all in that case :)
> Make conversion to zero-length path optional

- contribs/hybridsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/HybridNetworkFactory.java
- contribs/hybridsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/QSimExternalTransitionLink.java
- matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/AbstractQLink.java
- matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/ConfigurableQNetworkFactory.java
- matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/QLinkImpl.java
- matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/QLinkLanesImpl.java
- matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/QueueWithBuffer.java
- matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/vehicle_handler/DefaultVehicleHandler.java
- matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/vehicle_handler/VehicleHandler.java
- matsim/src/test/java/org/matsim/core/mobsim/qsim/qnetsimengine/VehicleHandlerTest.java
This PR adds a new (optional in the sense of `LinkSpeedCalculator`) component to the Netsim. Basically, it represents a condition that decides whether a vehicle is actually allowed to arrive at a link if it `isWantingToArrive`. In the default case, the handler will always return `true`, which replicates the current behaviour that there is no restriction on where and when vehicles can arrive on a link:
```java
public interface VehicleHandler {
void handleVehicleDeparture(QVehicle vehicle, Link link);
boolean handleVehicleArrival(QVehicle vehicle, Link link);
void handleInitialVehicleArrival(QVehicle vehicle, Link link);
}
```
With this handler it is now possible to define additional dynamics: One can count the number of vehicles that have already entered the link and block once a certain …
> Vehicle handler

- matsim/src/main/java/org/matsim/withinday/utils/EditTrips.java
The constructor in `EditTrips` currently forces a particular log level for the class: 
https://github.com/matsim-org/matsim/blob/e5eecb76184401c35ed021a2a8be8fafea97403e/matsim/src/main/java/org/matsim/withinday/utils/EditTrips.java#L68-L69
This configuration should instead be done in the `log4j.xml`, for instance using something like:
```
<logger name="org.matsim.withinday.utils.EditTrips">
<level value="info"/>
</logger>
```
Forcing the log level in the constructor means any configuration coming from `log4j.xml` will always be overwritten and cannot be overridden at runtime. Presumably this is not what is intended.
> Remove forced log level in EditTrips constructor

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalSystem.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ParallelPathDataProvider.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/StopBasedPathDataProvider.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/AggregatedMinCostRelocationCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/DrtModeMinCostFlowRebalancingModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DefaultDrtRouteUpdater.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtRoutingModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/EmptyVehicleRelocator.java
- contribs/drt/src/main/java/org/matsim/contrib/edrt/run/EDrtModeModule.java
- contribs/drt/src/main/java/org/matsim/contrib/edrt/run/EDrtModeQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/edrt/scheduler/EmptyVehicleChargingScheduler.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/dvrp/EvDvrpFleetModule.java
- contribs/taxi/src/main/java/org/matsim/contrib/etaxi/ETaxiScheduler.java
- contribs/taxi/src/main/java/org/matsim/contrib/etaxi/optimizer/ETaxiOptimizerProvider.java
- contribs/taxi/src/main/java/org/matsim/contrib/etaxi/run/ETaxiModeModule.java
- contribs/taxi/src/main/java/org/matsim/contrib/etaxi/run/ETaxiModeQSimModule.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/DefaultTaxiOptimizerProvider.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiModeModule.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiModeQSimModule.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/scheduler/TaxiScheduler.java
- contribs/taxi/src/test/java/org/matsim/contrib/taxi/schedule/reconstruct/ScheduleReconstructionIT.java
- examples/scenarios/dvrp-grid/one_etaxi_benchmark_config.xml
- Each dvrp mode has its own DvrpMode-annotated network.
- By default, `@Named(DvrpRoutingNetworkProvider.DVRP_ROUTING) Network` is used by dvrp modes:
```
bindModal(Network.class).to(Key.get(Network.class, Names.named(DvrpRoutingNetworkProvider.DVRP_ROUTING)));
```
Because now the DvrpMode-annotated network is used in code instead, it gives an option to programmatically override the above binding, for instance, to restrict operations of some dvrp modes to a sub-network of the DVRP_ROUTING network.
This is not (yet?) supported via config.
> add DvrpMode-annotated network to taxi and drt

- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetaxi/OneTaxiModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetaxi/OneTaxiOptimizer.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetruck/OneTruckModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetruck/OneTruckOptimizer.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetruck/OneTruckRequestCreator.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/fleet/FleetModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/PassengerEngineQSimModule.java
- Add support for `DvrpMode`-annotated networks to dvrp `Fleet` and `PassengerEngine` (missing in the previous PR #581 ).
- Adapt generic dvrp examples (i.e. non-taxi and non-drt)
> add DvrpMode-annotated network

- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeModule.java
- contribs/drt/src/main/java/org/matsim/contrib/edrt/run/EDrtModeModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/benchmark/DvrpBenchmarkConfigConsistencyChecker.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetaxi/OneTaxiModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetruck/OneTruckModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/router/DvrpRoutingNetworkProvider.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/DvrpConfigGroup.java
- contribs/taxi/src/main/java/org/matsim/contrib/etaxi/run/ETaxiModeModule.java
- contribs/taxi/src/main/java/org/matsim/contrib/etaxi/run/RunETaxiBenchmark.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/benchmark/RunTaxiBenchmark.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiConfigGroup.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiModeModule.java
Example:
```
dvrpCfg.networkModes = "drt1,drt2"; // in the past, only one mode allowed here, now we have a set
drtCfg1.mode = "drt1";
drtCfg1.useModeFilteredSubnetwork = true; //new param
drtCfg2.mode = "drt2";
drtCfg2.useModeFilteredSubnetwork = true; //new param
taxiCfg.mode = "taxi";
taxiCfg.useModeFilteredSubnetwork = false; //new param
```
The DVRP network will consists of links with modes: "drt1" and/or "drt2"
Mode "drt1" will use a subnetwork of links with the mode "drt1"
Mode "drt2" will use a subnetwork of links with the mode "drt2"
Mode "taxi" will use the DVRP network. (no filtering)
====
For backward compatibility, the defaults for taxi and drt are: `useModeFilteredSubnetwork = false`
> Dvrp mode subnetworks via config

- matsim/src/main/java/org/matsim/core/router/NetworkRoutingInclAccessEgressModule.java
Prior to this the drt router created routes non_network_walk -> drt interaction -> drt interaction -> non_network_walk, because addBushwhackingLegFromLinkToFacilityIfNecessary silently adds a (second) interaction activity
> avoid adding a second interaction activity after an activity

- contribs/analysis/src/main/java/org/matsim/contrib/analysis/vsp/traveltimedistance/TravelTimeValidationRunner.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtRequestAnalyzer.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/util/chart/RouteCharts.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/util/chart/ScheduleCharts.java
- contribs/dvrp/src/main/java/org/matsim/contrib/util/chart/ChartSaveUtils.java
- contribs/freight/pom.xml
- contribs/freight/src/main/java/org/matsim/contrib/freight/usecases/analysis/LegHistogram.java
- contribs/integration/src/test/java/org/matsim/integration/weekly/fundamentaldiagram/CreateAutomatedFDTest.java
- contribs/parking/src/main/java/org/matsim/contrib/parking/parkingchoice/PC2/analysis/ParkingGroupOccupancies.java
- contribs/parking/src/main/java/org/matsim/contrib/parking/parkingchoice/lib/GeneralLib.java
- contribs/socnetsim/src/main/java/org/matsim/contrib/socnetsim/usage/analysis/CourtesyHistogramListener.java
- matsim/pom.xml
- matsim/src/main/java/org/matsim/analysis/LegHistogramChart.java
- matsim/src/main/java/org/matsim/core/utils/charts/ChartUtil.java
- matsim/src/main/java/org/matsim/counts/algorithms/CountSimComparisonKMLWriter.java
- matsim/src/main/java/org/matsim/counts/algorithms/graphs/CountsSimReal24Graph.java
- matsim/src/main/java/org/matsim/counts/algorithms/graphs/CountsSimRealPerHourGraph.java
- matsim/src/main/java/org/matsim/counts/algorithms/graphs/helper/OutputDelegate.java
- matsim/src/main/java/org/matsim/pt/analysis/RouteTimeDiagram.java
- matsim/src/main/java/org/matsim/pt/counts/obsolete/PtCountSimComparisonKMLWriter.java
- matsim/src/main/java/org/matsim/pt/counts/obsolete/PtCountsSimRealPerHourGraph.java
There are a couple of features missing in the old JFreeChart from 2014. This PR updates the version to current 1.5.0 from 2017.
@kainagel, @mrieser, @tduberne, @michalmac  This may probably have impact on third-party analysis tools. Do you think it is good to merge?
Some guidelines for fixing code after the update:
- Function calls containing the keyword `Base` or which have a general purpose have been transformed to `Default`, e.g. `setLinesVisible` -> `setDefaultLinesVisible`
- `ChartUtilities` was renamed to `ChartUtils`
> Update JFreeChart to version 1.5.0

- matsim/src/test/java/org/matsim/other/DownloadAndReadXmlTest.java
currently the http download from vsp public SVN doesn't work (re-directs, java does not accept re-directing), jwilk said he will forbid it anyway in the future
ignore http test
> Http downloads from the SVN server will be forbidden according to jwilk

- contribs/roadpricing/src/main/java/org/matsim/contrib/roadpricing/RoadPricingSchemeUsingTollFactor.java
- contribs/roadpricing/src/main/java/org/matsim/contrib/roadpricing/run/RunRoadPricingUsingTollFactorExample.java
URL.getFile() does not return a valid path to a file in the filesystem, but returns the filename-part of the URL. That filename-part uses a special encoding for certain characters (e.g. a whitespace is encoded as %20) which is only valid in URLs, but not in the local filesystem. Thus file-access in the local filesystem might file when using URL.getFile() when the path or filename contains whitespace or other special characters. Fix this by changing the file access to use the URLs instead of the filename-Strings.
> replace file access with URL instead of String/filename.

- contribs/ev/src/main/java/org/matsim/contrib/ev/example/RunEvExamplewithLTHConsumptionModel.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/infrastructure/LTHConsumptionModelReader.java
URL.getFile() does not return a valid path to a file in the filesystem, but returns the filename-part of the URL. That filename-part uses a special encoding for certain characters (e.g. a whitespace is encoded as %20) which is only valid in URLs, but not in the local filesystem. Thus file-access in the local filesystem might file when using URL.getFile() when the path or filename contains whitespace or other special characters. Fix this by changing the file access to use the URLs instead of the filename-Strings.
> fix integration tests

- matsim/src/main/java/org/matsim/core/utils/io/MatsimXmlWriter.java
add one additional method for writing XML elements in one line, so one can write something like `<description>abc</description> ` with the MatsimXmlWriter.
> add method for writing element with content in one line

- contribs/emissions/src/main/java/org/matsim/contrib/emissions/EmissionUtils.java
If the current `VehicleType` description is null, the updated description will include the expression `null `. This pull request just fixes that by first checking for null, and only augmenting the description if a prior descriprion exists.
> Emission description

- matsim/src/main/java/org/matsim/pt/utils/CreatePseudoNetwork.java
We recently had some scenarios in which pt was significantly delayed due to low link freespeed and link capacity in the pt network. 
Even the old value for link capacity was rather high for having traffic jam of pt vehicles at flowCapacityFactor=1, we don't have realistic queuing effects of pt links anyway, so rather avoid queuing effects (as these cause often unexpected and hard to find pt delays)
So I think higher defaults are good and will save us lots of hard to find delays in pt simulation. But we can still make this configurable if someone wants to use lower speeds and capacities.
>  CreatePseudoNetwork: link freeSpeed+capacity configurable, high defaults for both

- contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierVehicleTypeReader.java
minor fix: catch all subcases of 'cannot find declaration of element' exceptions and not only a specific one.
> minor fix: catch all subcases of 'cannot find declaration of element' exceptions and not only a specific one.

- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/StopBasedDrtRoutingModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeModule.java
- matsim/src/main/java/org/matsim/core/scoring/EventsToLegs.java
- matsim/src/test/java/org/matsim/core/scoring/EventsToLegsTest.java
Fix bugs:
1. vehicle2passengers were not cleaned between iterations (should be fine as long as no trip gets "interrupted" by QSim endTime  (the critical one)
2. relPosOnDepartureLinkPerPerson and relPosOnArrivalLinkPerPerson is not handled properly (when we have intermediate stops when sharing rides)
Improvements:
1. record routes for vehicles (instead for each agent) and later assign a sublist of links to passengers/drivers upon their arrival
2. add more unit tests (shared rides and special boundary cases)
> fix EventsToLegs

- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/ClosestAccessEgressStopFinder.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DefaultAccessEgressStopFinder.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeModule.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/routing/StopBasedDrtRoutingModuleTest.java
- matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorData.java
- matsim/src/main/java/org/matsim/pt/transitSchedule/TransitScheduleUtils.java
Make stop finder in DRT more similar to those in public transit routers, re-apply hard constraint for access/egress walk distance to drt to reduce number of passengers walking into drt service area for very long distances
* interpret maxWalkDistance as a real max, use quad tree to find drt stops
* do not factor in beeline distance factor in maximum distance
* set default value of maxWalkDistance to Double.MAX_VALUE, so default
behaviour is very similar to situation before this commit
* change StopBasedDrtRoutingModuleTest to new (respectively initial)
interpretation of maxWalkDistance
* maxWalkDistance was already a hard constraint until commit
d99ef91
> Drt stop search radius

- matsim/src/main/java/org/matsim/core/router/FallbackRoutingModuleDefaultImpl.java
- matsim/src/main/java/org/matsim/core/router/NetworkRoutingInclAccessEgressModule.java
non_network_walk instead of hard coded 2.0m/s, which creates a fallback
mode faster than walk, do not alter these old defaults as they would
change lots of test results etc. and are not necessarily wrong, e.g. in
Brandenburg in a coarse network)
> let fallback router use PlansCalcRouteConfigGroup mode params of

- matsim/src/main/java/org/matsim/core/scoring/functions/ScoringParameters.java
- matsim/src/main/java/org/matsim/core/utils/collections/ArrayMap.java
- matsim/src/test/java/org/matsim/core/utils/collections/ArrayMapTest.java
This helps reducing the memory consumption in cases where custom scoring functions use truly agent-specific scoring parameters (i.e. in cases here a lot of ScoringParameters objects exist), and should also be minimally faster due to fewer memory accesses needed than the previously used TreeMap.
> use a more efficient Map implementation for small maps in ScoringParams.

- matsim/src/main/java/org/matsim/core/controler/AbstractController.java
- matsim/src/main/java/org/matsim/core/mobsim/qsim/QSim.java
- matsim/src/main/java/org/matsim/utils/MemoryObserver.java
- matsim/src/test/java/org/matsim/utils/MemoryObserverTest.java
Replace QSim's memory reporting by the new MemoryObserver in the AbstractController. The QSim reported the memory usage every simulated hour, but in small scenarios this this was not much of relevance as it progressed very fast, and in large scenarios it was only partially of help, as the memory consumption during replanning was not observable. The new MemoryObserver will now just print out the memory usage every 60 seconds, allowing for a more consistent observation of the memory usage over all phases of a simulation.
> Add class MemoryObserver to regularly report on the used memory.

- matsim/src/main/java/org/matsim/facilities/FacilitiesReaderMatsimV1.java
- matsim/src/main/java/org/matsim/facilities/StreamingActivityFacilities.java
- matsim/src/test/java/org/matsim/facilities/StreamingActivityFacilitiesTest.java
Only add the facility to the facilities container once the facility is completely loaded, and not at the start when it's still missing activity options and attributes.
This allows for a special ActivityFacility implementation to handle one ActivityFacility after the other, without the need to load all into memory at the same time.
> Support for streaming facilities with a special data container.

- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigs.java
we don't have any scoring parameters for the default subpopulation
> don't add activitiy params for the default subpopulation (null) in case

- contribs/minibus/test/input/org/matsim/contrib/minibus/integration/PControlerTestIT/config_corr_s1_0.xml
- matsim/src/main/java/org/matsim/core/config/groups/PlansCalcRouteConfigGroup.java
- matsim/src/main/java/org/matsim/pt/router/TransitRouterConfig.java
- matsim/src/test/java/org/matsim/core/config/groups/PlansCalcRouteConfigGroupTest.java
It used to be the case that setting _any_ teleportation router would clear the default settings.  I removed that mechanism some time ago (but after r11.x), since it is automagic, and we try to reduce automagic.  However, I wanted to leave the teleportation default routers in place, since they provide a default for some of the speeds, unifying results for cases where users do not think deeply about the corresponding parameters.  Yet, I was not able to find a design that works both from code and from xml config file.  The reason roughly is the following:
1. assume you start with some config where you have the default teleportation routers
2. now you remove some of them
3. if you print this to output_config and then read it back in, and the first occurrence of a teleportation router clears …
> teleportation routers config go back to earlier design

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionCostCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/ClosestAccessEgressFacilityFinder.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DecideOnLinkAccessEgressFacilityFinder.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DefaultDrtRouteUpdater.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtRouteLegCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/StopBasedDrtRoutingModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/MultiModeDrtModule.java
- contribs/drt/src/main/java/org/matsim/contrib/edrt/run/MultiModeEDrtModule.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/routing/StopBasedDrtRoutingModuleTest.java
Since `StopBasedDrtRoutingModule` now can use different routing modules for access/egress and use different access/egress facility finders, we can simply emulate the original `DrtRoutingModule` with it, and hence the latter has been removed.
Thinking about renaming of `StopBasedDrtRoutingModule` to simple `DrtRoutingModule` (as it is now the only one)
> Only StopBasedDrtRoutingModule

- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/ClosestAccessEgressFacilityFinder.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtStopFacility.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtStopFacilityImpl.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtStopNetwork.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeModule.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/routing/DrtRoutingModuleTest.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/fleet/Fleet.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/fleet/Fleets.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ElectricFleet.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ElectricFleets.java
- contribs/taxi/src/main/java/org/matsim/contrib/etaxi/optimizer/assignment/AssignmentETaxiOptimizer.java
- contribs/vsp/src/main/java/playground/vsp/avparking/PrivateAVFleetGenerator.java
- matsim/src/main/java/org/matsim/core/utils/collections/QuadTrees.java
To be used instead of TransitSchedule for keeping bus stops. Depending on the case, it is empty (door2door) or contains all drt-allowed links in a given area (serviceAreaBased) or contains all stops provided in a separate file (stopBased).
The input file for the 3rd case uses "transit schedule" format (as before), but this may be changed at some point in the future.
===
7555ad4 adds a simple `QuadTrees` util for creating quad trees - I have seen almost exactly the same code in dozens of places (incl. contribs, playgrounds etc.). Have not yet refactored that duplication though.
> Add DrtStopNetwork

- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/NonNetworkWalkRouter.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/MultiModeDrtModule.java
- contribs/drt/src/main/java/org/matsim/contrib/edrt/run/MultiModeEDrtModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/AbstractDvrpModeModule.java
access/egress routing modules for each DRT mode can be set in the following way:
```
MapBinder<Direction, RoutingModule> mapBinder = modalMapBinder(Direction.class, RoutingModule.class);
//access DRT with taxi :-)
mapBinder.addBinding(Direction.ACCESS).to(Key.get(RoutingModule.class, Names.named("taxi")));
//provide some fancy dynamic way of routing the egress (sub-)trip
mapBinder.addBinding(Direction.EGRESS).toProvider(...);
```
When not set, a `non_network_walk` is inserted for both access and egress.
====
To be backward-compatible with the "no access/egress walks" option, set the following bindings:
```
mapBinder.addBinding(Direction.ACCESS).toInstance((fromFacility, toFacility, departureTime, person) -> Collections.emptyList()); …
```
> Customise access egress routing for drt

- matsim/src/main/java/org/matsim/core/router/LinkToLinkRoutingModule.java
- matsim/src/main/java/org/matsim/core/router/costcalculators/FreespeedTravelTimeAndDisutility.java
- matsim/src/main/java/org/matsim/core/router/util/LinkToLinkTravelTime.java
- matsim/src/main/java/org/matsim/core/trafficmonitoring/TravelTimeCalculator.java
- matsim/src/test/java/org/matsim/core/router/InvertertedNetworkRoutingTest.java
- matsim/src/test/java/org/matsim/core/trafficmonitoring/LinkToLinkTravelTimeCalculatorTest.java
About a year ago the traveltimes and traveltimescalculators were changed in order to not allow the router too use too small observed (from earlier iteration) speeds, i.e. that the routing travel time for a link can never be lower than when using the maximum speed of the vehicle.
This feature has now been introduced for link-to-link-traveltimes too. 
I'm still a newbie concerning these requests, so tell me if I'm doing something wrong.
> Routing obeying max speed of vehicle implemented for link-to-link TT's

- contribs/carsharing/src/test/java/org/matsim/contrib/carsharing/runExample/RunCarsharingIT.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dynagent/run/DynRoutingModule.java
- contribs/noise/src/test/java/org/matsim/contrib/noise/NoiseIT.java
- matsim/src/main/java/org/matsim/core/router/NetworkRoutingInclAccessEgressModule.java
bushwhacking (= non_network_walk) speed was fixed at 2m/s.  This will lead to failing tests when the walk mode is consolidated, since there it normally is 3/3.6m/s.  I am here making it settable, and setting it to the lower value for two test cases.  The tests then fail; the results are accepted accordingly so that they pass again.  Hope is that merging this change into branch `routingMode4` will fix one or two failing tests there.
> Adjust bushwhacking speed

- matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/ConfigurableQNetworkFactory.java
- matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/RunConfigurableQNetworkFactoryExample.java
Make ConfigurableQNetworkFactory only override defaults of QLink and QNode implementations if overrides are explicitly set. Otherwise just leave those defaults alone
> ConfigurableQNetworkFactory should only set explicitly set properties

- matsim/src/main/java/org/matsim/core/network/algorithms/NetworkSimplifier.java
- matsim/src/test/java/org/matsim/core/network/algorithms/NetworkSimplifierTest.java
In special cases, where link attributes were different in opposite directions of links, the simplification algorithm merged links it shouldn't had, resulting in networks no longer being routable.
> fix a bug in NetworkSimplifier resulting in corrupt networks.

- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtRoutingModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/MultiModeDrtMainModeIdentifier.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigs.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/routing/MultiModeDrtMainModeIdentifierTest.java
- matsim/src/main/java/org/matsim/core/router/FallbackRoutingModuleDefaultImpl.java
- matsim/src/main/java/org/matsim/core/router/TripRouter.java
With routing mode we do not need separate fallback modes any longer. This made some methods only introduced in september superfluous. Some calls to these methods could already be removed. However, others are necessary for the MultiModeDrtMainModeIdentifier to retrofit old plans (created from september to december 2019) for routing mode. Those are marked for deletion before the 12.0 relaese with the following comment:
`// #deleteBeforeRelease : only used to retrofit plans created since the merge of fallback routing module (sep'-dec'19)`
> Fallback routing: remove/mark for deletion methods no longer used since routing mode

- matsim/src/main/java/org/matsim/api/core/v01/Id.java
In response to https://github.com/matsim-org/matsim-code-examples/issues/241
Creation of new `Id`s is synchronized. However still `IdMap` and `IdSet` may not work correctly. The 
read-access to the array lists inside the `cacheIndex` map is not synchronised in the method `Id<T> get(int index, final Class<T> type)`, which may return nulls for already inserted ids.
Regarding a potential fix: I am not sure what was the idea behind these two collections?
- memory efficiency -- then we can add synchronisation on the array list inside the mentioned method
- computational efficiency -- then probably an array of `Id`s should be stored internally in `IdMap` and `IdSet` (and we can remove this method)
> synchronise Id creation

- matsim/src/test/java/org/matsim/vehicles/VehicleWriteReadTest.java
These 2 tests fail or succeed depending on the sequence of previous tests!
Cause: After switching from `LinkedHashMap` to `IdMap` (for storing vehicles inside the `VehiclesImpl` container), the order of vehicles returned by `VehiclesImpl.getVehicles()` is not fixed anymore. Now it depends on `Id.index`, which (in the default configuration that we use) depends on the execution of earlier unit tests.
> ignore VehicleWriteReadTest

- contribs/pom.xml
- matsim/pom.xml
try out as a temp fix for the failing jenkins pipeline: http://ci.matsim.org:8080/job/MATSim_M2/
> downgrade surefire/failsafe from 3.0.0-M4 to 2.22.2

- benchmark/pom.xml
- contribs/emissions/pom.xml
- contribs/freight/pom.xml
- contribs/multimodal/pom.xml
- contribs/pom.xml
- matsim/pom.xml
back to the old versions of maven plugin to (hopefully) make Jenkins happy... (This is meant only as a temp fix to get matsim snapshots being deployed again)
> revert: upgrade maven plugins to latest version

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionCostCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DefaultDrtRouteUpdater.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtMainLegRouter.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtRoutingModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeModule.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/routing/DrtRoutingModuleTest.java
Now all 3 stages (`enum Stage {ACCESS, MAIN, EGRESS}`) are customisable via a map binder: `Map<Stage, RoutingModule> stageRouters`.
The defaults for DRT are: walk router, DrtMainLegRouter and walk router, respectively
> Generalise drt routing

- matsim/src/test/java/org/matsim/testcases/MatsimTestUtils.java
- use TestWatcher instead of deprecated TestWatchman
- save output of parametrised tests in sudirs (named according to the index of the parameter set combination) --> fixes collisions in the filesystem when testing parametrised tests on windows (incl. appveyor)
> improve matsim test utils

- contribs/accessibility/src/main/java/org/matsim/contrib/accessibility/LinkLengthTravelDisutility.java
- contribs/accessibility/src/main/java/org/matsim/contrib/accessibility/costcalculators/FreeSpeedTravelTimeCostCalculator.java
- contribs/accessibility/src/main/java/org/matsim/contrib/accessibility/costcalculators/TravelDistanceCalculator.java
- contribs/accessibility/src/main/java/org/matsim/contrib/accessibility/costcalculators/TravelWalkTimeCostCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/DrtScheduleTimingUpdater.java
- contribs/eventsBasedPTRouter/src/main/java/org/matsim/contrib/eventsBasedPTRouter/TransitRouterNetworkWW.java
- contribs/otfvis/src/main/java/org/matsim/vis/otfvis/handler/OTFLinkAgentsHandler.java
- matsim/src/main/java/org/matsim/core/events/algorithms/SnapshotGenerator.java
- matsim/src/main/java/org/matsim/core/mobsim/jdeqsim/Road.java
- matsim/src/main/java/org/matsim/core/network/NetworkUtils.java
- matsim/src/main/java/org/matsim/core/network/algorithms/NetworkMergeDoubleLinks.java
- matsim/src/main/java/org/matsim/core/network/algorithms/NetworkWriteAsTable.java
- matsim/src/main/java/org/matsim/pt/router/TransitRouterNetwork.java
- matsim/src/main/java/org/matsim/withinday/trafficmonitoring/WithinDayTravelTime.java
- matsim/src/test/java/org/matsim/core/utils/misc/NetworkUtilsTest.java
- matsim/src/test/java/org/matsim/testcases/fakes/FakeLink.java
A first step towards https://matsim.atlassian.net/browse/MATSIM-1000
This PR removes unnecessary uses of `Time.UNDEFINED_TIME`. It only deals "obvious" occurrences of case 3 (discussed here: https://matsim.atlassian.net/browse/MATSIM-1000?focusedCommentId=37229&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-37229)
> Fewer undefined time uses

- contribs/ev/src/main/java/org/matsim/contrib/ev/routing/EvNetworkRoutingModule.java
- contribs/freight/src/test/java/org/matsim/contrib/freight/mobsim/StrategyManagerFactoryForTests.java
- contribs/vsp/src/main/java/playground/vsp/congestion/handlers/AdvancedMarginalCongestionPricingHandler.java
- matsim/src/main/java/org/matsim/core/router/costcalculators/OnlyTimeDependentTravelDisutility.java
continuation of  #807 
Almost all calls of "compute-like" methods with UNDEFINED_TIME passed as time are removed.
Probably the last remaining one:
https://github.com/matsim-org/matsim/blob/adc6e7209e747d29457455e1ad850cb945795d60/matsim/src/main/java/org/matsim/pt/router/TransitLeastCostPathTree.java#L294-L295
which I even cannot say if it works properly when called with UNDEFINED_TIME??
> Remove undefined time usages

- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigs.java
drtConfigs:remove if clause, instead always add drt stage activity type (even door2door now adds per default access and egress walks)
> drtConfigs:remove if clause, instead always add drt stage activity type

- matsim/src/main/java/org/matsim/api/core/v01/IdMap.java
- matsim/src/main/java/org/matsim/api/core/v01/IdSet.java
- matsim/src/test/java/org/matsim/api/core/v01/IdMapTest.java
- matsim/src/test/java/org/matsim/api/core/v01/IdSetTest.java
The internal classes for handling Ids (IdMap, KeySet, Entry, ...) do not fulfill the contracts for the Map, Set, Entry, ... interface for comparison and equals().
This pull request tries to fix this.
There still is an inconsistency with comparing two ids directly, which is done by String, while the new functions mostly use the id. However, after a short discussion with @mrieser this should not be a problem.
> Id set and map contracts

- contribs/analysis/src/main/java/org/matsim/contrib/analysis/kai/KNAnalysisEventsHandler.java
- contribs/commercialTrafficApplications/src/test/resources/config.xml
- contribs/signals/examples/tutorial/example90TrafficLights/useSignalInput/withLanes/config.xml
- contribs/signals/examples/tutorial/example90TrafficLights/useSignalInput/woLanes/config.xml
- contribs/socnetsim/src/main/java/org/matsim/contrib/socnetsim/framework/replanning/GroupStrategyManager.java
- matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptor.java
- matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorFactory.java
- matsim/src/main/java/org/matsim/api/core/v01/population/HasPlansAndId.java
- matsim/src/main/java/org/matsim/core/config/groups/PlansConfigGroup.java
- matsim/src/main/java/org/matsim/core/population/PopulationUtils.java
- matsim/src/main/java/org/matsim/core/population/algorithms/TripPlanMutateTimeAllocation.java
- matsim/src/main/java/org/matsim/core/replanning/GenericStrategyManager.java
- matsim/src/main/java/org/matsim/core/replanning/StrategyManager.java
- matsim/src/main/java/org/matsim/core/replanning/strategies/TimeAllocationMutatorModule.java
- matsim/src/main/java/org/matsim/core/scoring/functions/ScoringParameters.java
- matsim/src/main/java/org/matsim/core/scoring/functions/SubpopulationScoringParameters.java
- matsim/src/test/java/ch/sbb/matsim/routing/pt/raptor/RaptorStopFinderTest.java
- matsim/src/test/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorIntermodalTest.java
- matsim/src/test/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorTreeTest.java
- matsim/src/test/java/org/matsim/core/replanning/StrategyManagerSubpopulationsTest.java
- matsim/src/test/java/org/matsim/core/replanning/strategies/TimeAllocationMutatorModuleTest.java
now absorbed in `PopulationUtils.getSubpopulation(person)`.  Is this what you had in mind re https://matsim.atlassian.net/browse/MATSIM-206 ?
> make subpopulation attribute name no longer defineable

- matsim/src/main/java/org/matsim/core/controler/PrepareForSimImpl.java
- matsim/src/test/java/org/matsim/core/controler/PrepareForSimImplTest.java
old plan files without routing mode and using access_walk or egress_walk:
PrepareForSimImpl did not replace access_walk/egress_walk by non_network_walk before running the MainModeIdentifier. MainModeIdentifierImpl did not check for "access_walk" because TransportMode.access_walk = "non_network_walk" and later MainModeIdentifierImpl only checked for TransportMode.non_network_walk. The same reason made the test pass although input plan files with access_walk were not handled correctly.
> bug fix: Access egress walk backward compatibility

- matsim/src/main/java/org/matsim/core/controler/OutputDirectoryLogging.java
After moving to log4j2, tests on windows started to fail, e.g.
https://ci.appveyor.com/project/michalmac/matsim-libs/builds/31735619
BTW. This coincided with changing the repo name to matsim-libs, which probably deactivated CI on appveyor, hence the bug remained unspotted for a while...
> fix stopping log appenders (after migration to log4j2)

- matsim/src/main/java/org/matsim/core/scoring/EventsToLegs.java
- matsim/src/main/java/org/matsim/core/scoring/ExperiencedPlansServiceFactory.java
- matsim/src/main/java/org/matsim/core/scoring/ExperiencedPlansServiceImpl.java
Sometimes, there is a need to create experienced plans from finished simulation output, as they provide some very useful output, but are not written out by default.
This PR allows to do exactly this. 
A usage example will be pushed into code-examples afterwards.
> Experienced plans for postprocessing

- contribs/emissions/src/main/java/org/matsim/contrib/emissions/events/EmissionEventsReader.java
- contribs/eventsBasedPTRouter/src/main/java/org/matsim/contrib/eventsBasedPTRouter/waitTimes/WaitTimeCalculatorImpl.java
- contribs/eventsBasedPTRouter/src/main/java/org/matsim/contrib/eventsBasedPTRouter/waitTimes/WaitTimeCalculatorSerializable.java
- contribs/eventsBasedPTRouter/src/main/java/org/matsim/contrib/eventsBasedPTRouter/waitTimes/WaitTimeStuckCalculator.java
- contribs/locationchoice/src/main/java/org/matsim/contrib/locationchoice/frozenepsilons/PlanTimesAdapter.java
- contribs/roadpricing/src/main/java/org/matsim/contrib/roadpricing/RoadPricingSchemeWithTollAvoidance.java
- contribs/vsp/src/main/java/playground/vsp/andreas/bvgAna/level1/StopId2RouteId2DelayAtStopMapData.java
- contribs/vsp/src/main/java/playground/vsp/andreas/bvgAna/level2/VehiclePlannedRealizedMissedDepartures.java
- matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/RaptorUtils.java
- matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorCore.java
- matsim/src/main/java/org/matsim/analysis/PHbyModeCalculator.java
- matsim/src/main/java/org/matsim/api/core/v01/network/Link.java
- matsim/src/main/java/org/matsim/core/network/FixedIntervalTimeVariantAttribute.java
- matsim/src/main/java/org/matsim/core/network/FixedIntervalTimeVariantLinkFactory.java
- matsim/src/main/java/org/matsim/core/network/TimeVariantAttribute.java
- matsim/src/main/java/org/matsim/core/network/VariableIntervalTimeVariantAttribute.java
- matsim/src/main/java/org/matsim/core/network/VariableIntervalTimeVariantLinkFactory.java
- matsim/src/main/java/org/matsim/core/router/AStarLandmarks.java
- matsim/src/main/java/org/matsim/core/router/Dijkstra.java
- matsim/src/main/java/org/matsim/core/router/TripRouter.java
- matsim/src/main/java/org/matsim/core/scoring/functions/CharyparNagelLegScoring.java
- matsim/src/main/java/org/matsim/core/utils/misc/Time.java
- matsim/src/main/java/org/matsim/deprecated/scoring/functions/CharyparNagelLegScoring.java
- matsim/src/main/java/org/matsim/pt/analysis/TransitLoad.java
- matsim/src/main/java/org/matsim/pt/router/TransitLeastCostPathTree.java
- matsim/src/main/java/org/matsim/pt/transitSchedule/MinimalTransferTimesImpl.java
- matsim/src/main/java/org/matsim/utils/leastcostpathtree/LeastCostPathTree.java
- matsim/src/test/java/org/matsim/core/network/TimeVariantLinkImplTest.java
- matsim/src/test/java/org/matsim/core/utils/misc/TimeTest.java
- matsim/src/test/java/org/matsim/integration/timevariantnetworks/QSimIntegrationTest.java
The last in the series of PRs, comes after: #970 
This is a collection of smaller commits with tiny changes addressing the removal of the remaining uses of the undefined time constant scattered all over the code.
Depending on the case, the undefined time has been replaced with NaN, -Inf or null (after boxing).
> Finalise removal of undefined time

- contribs/emissions/src/main/java/org/matsim/contrib/emissions/ColdEmissionHandler.java
cold emission handler must be added to the events manager to throw cold emission events. I think it was accidentally removed.
@joemolloy @kainagel
> cold emission handler must be added to events manager

- contribs/av/src/test/java/org/matsim/contrib/av/robotaxi/fares/taxi/TaxiFareHandlerTest.java
- matsim/src/main/java/org/matsim/core/events/ParallelEventsManager.java
Due to race conditions, the `ParallelEventsManager` would sometimes fail to properly `flush()` events that would themselves introduce new events in the Manager. This would mean that calling `flush()` would produce unexpected outcomes. This patch fixes these issues, and ensures that `flush()` now offers true synchronization barrier semantics, as well as proper event flush semantics.
This patch also fixes a small issue in the `ParallelEventsManager` where `EventHandler`s would be added to the same `EventsManager`. Now the `EventHandler`s should be uniformly distributed among the available `EventsManager`s.
> Fixed the ParallelEventsManager

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserter.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DetourPathCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DrtInsertionSearch.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DrtInsertionSearchParams.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionSearch.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionSearchParams.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionSearchQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/KNearestInsertionsAtEndFilter.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/MultiInsertionDetourPathCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ParallelMultiVehicleInsertionProblem.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/edrt/run/EDrtModeQSimModule.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiConfigGroup.java
- contribs/vsp/src/test/java/org/matsim/integration/drtAndPt/PtAlongALine2Test.java
- examples/scenarios/dvrp-grid/eight_shared_taxi_config.xml
- examples/scenarios/dvrp-grid/multi_mode_one_shared_taxi_config.xml
- examples/scenarios/dvrp-grid/one_shared_taxi_config.xml
- examples/scenarios/dvrp-grid/one_taxi_and_one_shared_taxi_config.xml
- examples/scenarios/mielec/mielec_drt_config.xml
- examples/scenarios/mielec/mielec_edrt_config.xml
- examples/scenarios/mielec/mielec_serviceArea_based_drt_config.xml
- examples/scenarios/mielec/mielec_stop_based_drt_config.xml
`DrtInsertionSearchParams` parameter set is specified per `DrtConfigGroup` and is meant to customise the `DrtInsertionSearch`, exactly the same as the taxi optimiser params are used to choose and parametrise the taxi optimiser.
The existing search procedure (renamed into `ExtensiveInsertionSearch` as it iterates through a quite comprehensive set of potential insertions) requires providing a `ExtensiveInsertionSearchParams` parameter set.
The following line was added to all DRT configs:
```
<parameterset type="drt">
<parameterset type="ExtensiveInsertionSearch"/>
...
</parameterset>
```
Adding this single line without specifying any parameters means that `ExtensiveInsertionSearch` will use the default values for parameters: `admissibleBeelineSpeedFactor` and `nearestInsertionsAtEndLimit`. …
> Introduce DrtInsertionSearchParams

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveDrtInsertionSearch.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionSearchParams.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionSearchQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SingleInsertionDetourPathCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeQSimModule.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/DefaultTaxiOptimizerProvider.java
- contribs/vsp/pom.xml
An alternative to `ExtensiveInsertionSearch`. It uses beeline distances to find the best potential insertion and then evaluates the selected one. Therefore per each request insertion, it runs 4 one-to-one least-cost path searches, instead of 4 many-to-one searches.
> SelectiveInsertionSearch prototype

- contribs/accessibility/pom.xml
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveDrtInsertionSearch.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionSearch.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionSearchParams.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionSearchQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SingleInsertionDetourPathCalculator.java
- contribs/freight/pom.xml
- contribs/integration/pom.xml
After running some experiments, it turned out that the beeline metric used to (pre)select the best insertion may lead to selecting an insertion that violates the time windows for already accepted requests, which in the end leads to rejecting the newly submitted request.
Therefore, the beeline metric should be rather restrictive (below 1.0) than admissible (above 1.0) to avoid such situations. This gives slight preference towards appending new requests at the end of vehicle schedules and reduces the risk of (pre)selecting an infeasible insertion. This also gives more balanced utilisation of vehicles across the whole fleet. On the other hand, it may reduce ride sharing rates.
Replacing the beeline metric with a more precise travel time estimation is definitely worth some investigation. For …
> Improve selective insertion search

- matsim/src/main/java/org/matsim/core/router/NetworkRoutingInclAccessEgressModule.java
- matsim/src/main/java/org/matsim/core/router/util/PreProcessLandmarks.java
We need to fail as the computed `LandmarksData` is incomplete.
BTW. A timeout also does not establish the happen-before relationship between the executor threads and the caller thread (yet another reason to fail...)
Just wondering if we have ever reached these 10 minutes... :-)
> Fail on landmarks preprocess timeout

- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeModule.java
- contribs/taxi/src/main/java/org/matsim/contrib/etaxi/ETaxiScheduler.java
- contribs/taxi/src/main/java/org/matsim/contrib/etaxi/run/ETaxiModeQSimModule.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiConfigGroup.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiModeModule.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiModeQSimModule.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/scheduler/TaxiScheduler.java
- contribs/taxi/src/test/java/org/matsim/contrib/taxi/optimizer/TaxiOptimizerTests.java
In:
- replanning (drt and taxi legs)
- DVRP optimiser (taxi occupied trips)
As a result: `AStarEuclideanOverdoFactor` is removed from `TaxiConfigGroup`
> Switch from euclidean to landmarks

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtGridUtils.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/DrtModeMinCostFlowRebalancingModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingParams.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/analysis/zonal/ZonalDemandAggregatorWithoutServiceAreaTest.java
zones for drt demand estimation can be read from a shape file. if they aren't, they are now restricted to the drt service area - if the latter is used. everything is configurable via MinCostFlowRebalancingParams
> RebalancingZoneGeneration

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtModeAnalysisModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/util/stats/DrtVehicleOccupancyProfileCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/util/stats/DrtVehicleOccupancyProfileWriter.java
- contribs/drt/src/main/java/org/matsim/contrib/edrt/run/MultiModeEDrtModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/util/TimeDiscretizer.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/dvrp/ChargingActivity.java
Now we can plot different activities not related to serving passengers (non-operating activities), such as charging:
> Flexible vehicle occupancy time profiles

- contribs/av/src/main/java/org/matsim/contrib/av/intermodal/RunTaxiPTIntermodalExample.java
- contribs/av/src/main/java/org/matsim/contrib/av/robotaxi/run/RunDrtAndTaxiExample.java
- contribs/av/src/main/java/org/matsim/contrib/av/robotaxi/run/RunRobotaxiExample.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtControlerCreator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/RunDrtScenario.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/examples/RunDrtExample.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/examples/RunMultiModeDrtExample.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/examples/RunOneSharedTaxiExample.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/analysis/zonal/ZonalDemandAggregatorWithoutServiceAreaTest.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/DvrpQSimComponents.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/RunTaxiScenario.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiControlerCreator.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/examples/RunMultiModeTaxiExample.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/examples/RunTaxiExample.java
- contribs/taxi/src/test/java/org/matsim/contrib/taxi/run/RunTaxiScenarioTestIT.java
- adapt `Drt/TaxiControlerCreator` to the multi-mode case
- reduce code duplication
- reduce the use of `TaxiConfigGroup.getSingleModeTaxiConfig()`
> Standardise multi mode dvrp use

- contribs/av/src/main/java/org/matsim/contrib/av/robotaxi/fares/drt/DrtFareConfigGroup.java
- contribs/av/src/main/java/org/matsim/contrib/av/robotaxi/fares/drt/DrtFareModule.java
- contribs/av/src/main/java/org/matsim/contrib/av/robotaxi/fares/taxi/TaxiFareConfigGroup.java
- contribs/av/src/main/java/org/matsim/contrib/av/robotaxi/fares/taxi/TaxiFareModule.java
(both for taxi and drt)
This means single-mode fare configs need to be enclosed by the  multi-mode one (parent config group).
> Only multi-mode fares configs

- matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorCore.java
- matsim/src/test/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorTest.java
Originally, the transfer leg (non_network_walk) was left out if the two
pt-legs ended and started at exactly the same TransitStopFacility, as in
this case the distance and thus the travel time were always 0. But now
with MinimalTransferTimes, the transfer time can actually be more than
zero seconds, so it makes sense to include these legs always. And also
for consistency and simplified analysis.
> Always add a transfer between two pt legs.

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/PreviousIterationZonalDRTDemandAggregator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingParams.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/analysis/zonal/ZonalDemandAggregatorWithoutServiceAreaTest.java
Motivation: Make PreviousIterationZonalDRTDemandAggregator compatible with drt-speed-up module.
To achieve that DepartureEvents of the drt-speed-up mode should be considered drt demand. Changes:
- add a param drtSpeedUpMode to rebalancing config
- consider DepartureEvents of the drt-speed-up in PreviousIterationZonalDRTDemandAggregator
I adapted the existing test, but I'm not sure whether zone 4 is really the right zone for the new "drt_teleportation" mode demand starting from link 147 (no way to graphically check this).
> Drt-Speed-Up compatibility with drt rebalancing

- matsim/src/main/java/org/matsim/analysis/ModeStatsControlerListener.java
This pull request adds a getter method for modeHistories. I need access to this collection for the dynamicShutdown module I am working on. I did not change the access modifier of modeHistories to private, since I am not sure what effects that would have down the line.
> added getter for modeHistories

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/VehicleDataEntryFactoryImpl.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/depot/Depots.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionCostCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/schedule/DrtDriveTask.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/schedule/DrtStayTaskEndTimeCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/schedule/DrtStopTask.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/schedule/DrtTaskBaseType.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/schedule/DrtTaskFactory.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/schedule/DrtTaskFactoryImpl.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/schedule/DrtTaskType.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/DrtScheduleInquiry.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/EmptyVehicleRelocator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/RequestInsertionScheduler.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/vrpagent/DrtActionCreator.java
- contribs/drt/src/main/java/org/matsim/contrib/edrt/EDrtActionCreator.java
- contribs/drt/src/main/java/org/matsim/contrib/edrt/optimizer/EDrtVehicleDataEntryFactory.java
- contribs/drt/src/main/java/org/matsim/contrib/edrt/schedule/EDrtChargingTask.java
- contribs/drt/src/main/java/org/matsim/contrib/edrt/schedule/EDrtDriveTask.java
- contribs/drt/src/main/java/org/matsim/contrib/edrt/schedule/EDrtTaskFactoryImpl.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingWithQueueingAndAssignmentLogic.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/BatteryImpl.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ElectricVehicleImpl.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ImmutableElectricVehicleSpecification.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/schedule/TaxiTaskType.java
Similar change to the ones done for taxi in #1063 
Within this PR the following task types has been introduced:
- `EmptyVehicleRelocator.RELOCATE_VEHICLE_TASK_TYPE` defined as `new DrtTaskType("RELOCATE", DRIVE);` ==> will be treated by the standard optimiser as a `DRIVE` task (the standard optimiser supports fleet rebalancing)
- `EDrtChargingTask.TYPE` defined as `new DrtTaskType("CHARGING", null);` ==> will not be handled by the standard optimiser (must be handled by the e-DRT optimiser, otherwise an exception will be thrown inside the standard optimiser due to the undefined base type)
> Extendable drt task types

- contribs/taxi/src/main/java/org/matsim/contrib/etaxi/ETaxiScheduler.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/schedule/TaxiEmptyDriveTask.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/schedule/reconstruct/ScheduleBuilder.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/scheduler/TaxiScheduler.java
Additionally:
- introduce the `DRIVE_TO_CHARGER` task type, so we can differentiate such tasks from the standard "empty" drives to pickups  (both having `EMPTY_DRIVE` as the base type).
> customise TaskType of TaxiEmptyDriveTask (only base type must == EMPTY_DRIVE)

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtModeAnalysisModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/util/stats/DrtVehicleOccupancyProfileCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/util/stats/DrtVehicleOccupancyProfileWriter.java
- contribs/drt/src/main/java/org/matsim/contrib/edrt/run/MultiModeEDrtModule.java
Task types contain more information and are also defined for legs (not only activities). So now we can generate nicer stats and plots that also include vehicle relocation (rebalancing).
> Use task types in drt occupancy profiles

- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/DefaultPassengerEngine.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/PassengerRequestCreator.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/PassengerRequestValidator.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/vrpagent/VrpAgentLogic.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/passenger/SubmittedTaxiRequestsCollector.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiConfigGroup.java
- contribs/taxi/src/test/java/org/matsim/contrib/taxi/schedule/reconstruct/ScheduleReconstructionIT.java
Adds synchronisation on the optimiser to:
- calling `VrpOptimiser.submitRequest()` from `DefaultPassengerEngine.validateAndSubmitRequest()`
- `VrpAgentLogic.computeNextAction()`
In many cases the synchronisation could be even more fine-grained and probably done entirely on the optimiser side. However, there are already some "unusual" corner cases (a few examples: (1) switching to "an idle task" is immediately converted into a relocation to the "globally" best depot, (2) submitting a request immediately calls global re-optimisation). So I think it is better to move the responsibility of synchronisation to the "framework" rather than requiring (or rather hoping) that each optimiser implementation would provide thread-safety on its own.
Final notes:
- request ID creation uses `AtomicInteger` …
> enable using DefaultPassengerEngine in multi-threaded QSim

- contribs/osm/src/main/java/org/matsim/contrib/osm/networkReader/LinkProperties.java
- contribs/osm/src/main/java/org/matsim/contrib/osm/networkReader/OsmNetworkParser.java
- contribs/osm/src/main/java/org/matsim/contrib/osm/networkReader/OsmSignalsParser.java
- contribs/osm/src/main/java/org/matsim/contrib/osm/networkReader/SupersonicOsmNetworkReader.java
Made LinkProperties and some utility methods public, so they can be re-used for network creation.
> OSM Reader: Public link properties

- contribs/osm/src/main/java/org/matsim/contrib/osm/networkReader/OsmNetworkParser.java
- contribs/osm/src/main/java/org/matsim/contrib/osm/networkReader/SupersonicOsmNetworkReader.java
- contribs/osm/src/test/java/org/matsim/contrib/osm/networkReader/OsmBicycleReaderTest.java
- contribs/osm/src/test/java/org/matsim/contrib/osm/networkReader/OsmNetworkParserTest.java
- contribs/osm/src/test/java/org/matsim/contrib/osm/networkReader/OsmSignalsParserTest.java
- contribs/osm/src/test/java/org/matsim/contrib/osm/networkReader/SupersonicOsmNetworkReaderTest.java
- contribs/osm/src/test/java/org/matsim/contrib/osm/networkReader/Utils.java
Make sure the 'preserveNodeWithId' filter takes precedence over the spatial filter.
* Fix unit tests to actually test this feature. The test osm-networks were not complex enough, so the tests didn't catch this case
* A lot of test fixing due to the more complex example osm-networks
> Make preserveNodeWithId work

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/ActivityLocationBasedZonalDemandAggregator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/EqualVehicleDensityZonalDemandAggregator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/FirstActivityCountAsZonalDemandAggregator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/PreviousIterationZonalDRTDemandAggregator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/TimeDependentActivityBasedZonalDemandAggregator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/DrtModeMinCostFlowRebalancingModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingParams.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/analysis/zonal/ZonalDemandAggregatorWithoutServiceAreaTest.java
- matsim/src/main/java/org/matsim/core/router/NetworkRoutingInclAccessEgressModule.java
1) New ZonalDemandAggregator that attempts to emulate population numbers by number of first activities per zone
2) test the new demandAggregator 
3) Shorten enum values for ZonalDemandAggregatorType
BTW, maybe we should rename *ZonalDemandAggregator to *ZonalDemandEstimator
...
> Drt rebalancing

- contribs/ev/src/main/java/org/matsim/contrib/ev/EvModule.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/charging/VehicleChargingHandler.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/AuxDischargingHandler.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/DischargingModule.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/DriveDischargingHandler.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/example/RunEvExample.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/example/RunEvExamplewithLTHConsumptionModel.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/stats/ChargerPowerCollector.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/stats/EvStatsModule.java
- matsim/pom.xml
- matsim/src/main/java/org/matsim/core/events/MobsimScopeEventHandler.java
- matsim/src/main/java/org/matsim/core/events/MobsimScopeEventHandling.java
- matsim/src/main/java/org/matsim/core/events/MobsimScopeEventHandlingModule.java
- matsim/src/main/java/org/matsim/core/mobsim/DefaultMobsimModule.java
- matsim/src/main/java/org/matsim/core/mobsim/qsim/AbstractQSimModule.java
- matsim/src/test/java/org/matsim/core/events/MobsimScopeEventHandlingTest.java
Some event handlers are created before each mobsim (i.e. bound inside `AbstractQSimModule`s), mainly because they operate on data which is also created just before the mobsim. This is typical in DVRP, EV and related modules. Such handlers need to be removed after the mobsim ends.
This PR simplifies/standardises adding and removing such handlers. To add such a handler, use `AbstractQSimModule.addMobsimScopeEventHandlerBinding()` in exactly the same way "typical" handlers are added via `AbstractModule.addEventHandlerBinding()` and declare it as `MobsimScopeEventHandler` (which is a sub-interface of `EventHandler`). The rest happens automatically.
> add support for qsim-scoped event handlers

- contribs/freight/src/main/java/org/matsim/contrib/freight/utils/FreightUtils.java
- contribs/freight/src/test/java/org/matsim/contrib/freight/jsprit/DistanceConstraintFromVehiclesFileTest.java
- contribs/freight/src/test/java/org/matsim/contrib/freight/jsprit/DistanceConstraintTest.java
- contribs/freight/src/test/java/org/matsim/contrib/freight/jsprit/IntegrationIT.java
- contribs/freight/src/test/java/org/matsim/contrib/freight/utils/FreightUtilsTest.java
Preliminary note: The (VRPs of the) different carriers are solved independently. 
This PR replaces the functionality of solving problems from "one after the other" to parallel handling of the carriers. This speeds up solving freight cases with more than one carrier  
Thanks to @tschlenther for providing this piece of code.
I added the number of shipments to counterMap, to ensure that the carriers are sorted by their number of total tasks (shipments or services) and not only by the number of services. @tschlenther : This is maybe something you should have a look at your code.
> Freight: Parallel solving of VRPs

- matsim/src/main/java/org/matsim/analysis/CalcLegTimes.java
This reverts commit bcfa2aa9
The issue #1032 probably was caused by checking out the repo with `core.autocrlf=true` (i.e. always convert line endings to CRLF). This modifies the versioned "expected" output file to which the actual output file is compared in `CalcLegTimesTest`. Since we want to use `\n` in MATsim, it is best to set `core.autocrlf=input`
> Revert "presumably fix CalcLegTimesTest on Winodws"

- matsim/src/test/java/org/matsim/core/mobsim/qsim/QSimTest.java
To prevent failures on AppVeyor. I could not reproduce the issues locally, and the output from AppVeyor is too small to point to the right place in code, but this is quite likely the reason.
> increase events queue size in "event-intense" QSim tests

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/ZonalIdleVehicleCollector.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/ZonalIdleVehicleXYVisualiser.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/DrtModeMinCostFlowRebalancingModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/schedule/DrtTaskBaseType.java
Switch event handling from activity start/end events to task started/ended events. This is now possible after #1098. These task-oriented events are much handier for tracking dvrp vehicle states.
> Refactor drt event handlers

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/FleetSizeWeightedByPopulationShareDemandAggregator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/DrtModeMinCostFlowRebalancingModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingParams.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/analysis/zonal/ZonalDemandAggregatorWithoutServiceAreaTest.java
The population based demand estimator now scales the estimate value down by total number of inhabitants in drt service area and multiplies it with fleet size. The resulting demand estimate value represents the number of vehicle desired in that zone.
That is in line with the other Demand Aggregators and leads to a consistenst meaning/interpretation for the alpha parameter.
The alpha parameter can thus be interpreted as "how many vehicles do i want to relocate per estimated demand unit" where estimated demand unit is either vehicles or drt rides (depending on which DemandAggregator you chose).
Moreover, as fleet size is now possibly subject to change over iterations (when enabling optDrt - currently located in an external repository), demand aggregators relying on fleet size are not bound …
> Demand Aggregators

- matsim/src/main/java/org/matsim/core/controler/AbstractController.java
That's hardly a reason to stop the run, and on some operating systems
just opening the file in an editor could already lead to an exception
as the file gets locked by the editor and can thus not be updated by MATSim.
> Catch the exception and continue if stopwatch.txt could not be written.

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/EqualVehicleDensityZonalDemandAggregator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/FleetSizeWeightedByPopulationShareDemandAggregator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/DrtModeMinCostFlowRebalancingModule.java
This PR reverts some of the changes in #1106:
All aggregators are bound as singleton (no need for multiple instantiation as pointer to FleetSpecification object stays up to date)
> Demand aggregators point to FleetSpecification object and are bound as singletons

- matsim/src/main/java/org/matsim/analysis/IterationTravelStatsControlerListener.java
- matsim/src/main/java/org/matsim/analysis/PHbyModeCalculator.java
- matsim/src/main/java/org/matsim/analysis/PKMbyModeCalculator.java
- matsim/src/main/java/org/matsim/core/mobsim/hermes/Realm.java
- matsim/src/main/java/org/matsim/core/mobsim/hermes/ScenarioImporter.java
- matsim/src/test/java/org/matsim/core/mobsim/hermes/HermesRoundaboutTest.java
- matsim/src/test/java/org/matsim/core/mobsim/hermes/HermesTest.java
* make deterministic pt in hermes truely deterministic, independent of network used
* board passengers at departure time, not arrival time
Also (unrelated to the rest):
* write out pkm & ph mode stats after every iteration. makes analysis easier while run is running.
> Various Hermes PT improvements

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/PreviousIterationZonalDRTDemandAggregator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/TimeDependentActivityBasedZonalDemandAggregator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DefaultDrtOptimizer.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/RebalancingParams.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/DrtModeMinCostFlowRebalancingModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/LinearRebalancingTargetCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingStrategy.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingStrategyParams.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeModule.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/analysis/zonal/ZonalDemandAggregatorWithoutServiceAreaTest.java
Goal: simplify adding new rebalancing strategies.
The idea is to have a relatively generic parameter set (`RebalancingParams`) and then additionally define all strategy-specific params inside `RebalancingStrategyParams`.
Common params are:
- interval
- minServiceTime
- maxTimeBeforeIdle
- cellSize
- rebalancingZonesShapeFile
- rebalancingZonesGeneration
For the min-cost-flow rebalancing the specific params are: 
- targetAlpha
- targetBeta
- zonalDemandAggregatorType
> split rebalancing params into RebalancingParams and RebalancingStrategyParams

- matsim/src/main/java/org/matsim/core/mobsim/hermes/ScenarioImporter.java
- matsim/src/test/java/org/matsim/core/mobsim/hermes/HermesTest.java
...as the interaction activities take one second.
Also: Use single stream when creating PT vehicles.
> decrease teleport times in hermes

- .travis.yml
- appveyor.yml
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalSystem.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalWaitTimesAnalyzer.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZone.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/EqualVehicleDensityZonalDemandAggregator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/FleetSizeWeightedByPopulationShareDemandAggregator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/PreviousIterationZonalDRTDemandAggregator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/TimeDependentActivityBasedZonalDemandAggregator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/ZonalIdleVehicleCollector.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/ZonalIdleVehicleXYVisualiser.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/AggregatedMinCostRelocationCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/LinearRebalancingTargetCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingStrategy.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostRelocationCalculator.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/analysis/zonal/DrtGridUtilsTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalSystemTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/analysis/zonal/ZonalDemandAggregatorWithoutServiceAreaTest.java
It replaces `String` that was used for representing zones. As a result, many methods have now more meaningful signatures. Also some places in code are simplified as DrtZone gives access to further data (no need to query the `ZonalSystem`).
> Introduce drt zone

- contribs/drt/src/main/java/org/matsim/contrib/edrt/run/EDrtModeQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/edrt/schedule/EDrtStayTaskEndTimeCalculator.java
Possibly the answer to #1132.
Basically it is copied and adopted from `ETaxiStayTaskEndTimeCalculator`.
Was not sure about whether to the check of TaskType is right or if the base type shoult be checked instead:
`if (task.getTaskType().equals(EDrtChargingTask.TYPE))`
> EDrtStayTaskEndTimeCalculator

- contribs/emissions/src/main/java/org/matsim/contrib/emissions/WarmEmissionHandler.java
> Fix emissions calculation if vehicle uses the same link twice within a trip.

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/DrtModeMinCostFlowRebalancingModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingStrategy.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingStrategyParams.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/targetcalculator/LinearRebalancingTargetCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/targetcalculator/RebalancingTargetCalculator.java
- pass in rebalancable vehicles
- return `DrtZone -> Integer` mapping (instead of separate calls for each zone)
- configure the calculator type in `MinCostFlowRebalancingStrategyParams`
> Refactor rebalancing target calculator

- contribs/drt/pom.xml
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtGridUtils.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtModeZonalSystemModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalSystem.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZone.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZoneTargetLinkSelector.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/MostCentralDrtZoneTargetLinkSelector.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/RandomDrtZoneTargetLinkSelector.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/demandestimator/EqualVehicleDensityZonalDemandEstimator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/demandestimator/PreviousIterationDRTDemandEstimator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/AggregatedMinCostRelocationCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/DrtModeMinCostFlowRebalancingModule.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/analysis/zonal/DrtGridUtilsTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalSystemTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/rebalancing/demandestimator/ZonalDemandEstimatorWithoutServiceAreaTest.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/charging/VehicleChargingHandler.java
DrtZones have now information on all links inside of them.
@michalmac as you decided to include the field `Map<Id<Link>,Link>`, and as we already can think of at least 2 ways of setting a target link for a zone, i thought maybe we want to have a flexible way of determining a target link for each zone.
That way, we do not need a `targetLink` field inside `DrtZone`.
Instead, we have the interface `DrtZoneTargetLinkSelector` which is currently only used for rebalancing but could also be used for other purposes,
I implemented 2 variants: 
1. choose a random link (each time you query the selector)
2. always choose the most central link
default is 2.
I put the binding and the interface as well as both implementations into the zonal package.
If you think that this rather belongs into …
> Add links to drt zones

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZone.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/demandestimator/EqualVehicleDensityZonalDemandEstimator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/demandestimator/FleetSizeWeightedByActivityEndsDemandEstimator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/demandestimator/FleetSizeWeightedByPopulationShareDemandEstimator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/demandestimator/PreviousIterationDRTDemandEstimator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/demandestimator/ZonalDemandEstimator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/targetcalculator/EqualRebalancableVehicleDistributionTargetCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/targetcalculator/LinearRebalancingTargetCalculator.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/rebalancing/demandestimator/ZonalDemandEstimatorWithoutServiceAreaTest.java
- support creating dummy zones (for including vehicles being outside the zonal system into the rebalancing procedure). The idea: when running rebalancing we could treat each of them as a dummy zone and even assume a reduced (negative??) cost of moving them to the actual DRT zones.
- remove special handling of `expectedDemand==0` from `LinearRebalancingTargetCalculator` (It was used in the past, when grid zones were generated also for areas without any links. Now such zones are filtered out, also for non-grid zonal systems)
- make `ZonalDemandEstimator` return `ToDoubleFunction` (instead of `ToIntFunction`). Demand predictions should be precise, not necessarily integer values (for a given area and time bin). It's the goal of the target calculator to come up with an integer number of …
> Support dummy zones & refactor demand estimators

- matsim/src/main/java/org/matsim/core/config/consistency/VspConfigConsistencyCheckerImpl.java
- matsim/src/main/java/org/matsim/utils/objectattributes/ObjectAttributesConverter.java
So far, only writing of map or collection object attributes has been supported.
By checking whether the given class of the object attribute is an implementation of java.util.Map or java.util.Collection the corresponding converter can be retrieved (after directly querying the converters map for the exact object attribute class).
That means, for an example, that now an object attribute with a denoted type "java.util.ArrayList" can be read in, if the the value is denoted in json syntax and elements are strings.
Moreover, a comment in `VspConfigConsistencyCheckerImpl` was updated.
> Support reading of map and collection object attributes

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalSystem.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingStrategyParams.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
An exception was thrown in DrtZonalSystem.createFromPreparedGeometries() because grouping can not be performed for null keys. As we currently ecxplicitly allow for null return values in getGeometryIdForLink(), we need to filter null keys before grouping.
> Fix DrtZonalSystem

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/demandestimator/PreviousIterationDRTDemandEstimator.java
In situations where the service area is larger or different than the DrtZonalSystem, we might have drt departures outside of the DrtZonalSystem. We used to handle that by ignoring the departure in PreviousIterationDRTDemandEstimator. This PR is a return back to that logic.
> handle drt departures outside of DrtZonalSystem

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalSystem.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/DrtModeMinCostFlowRebalancingModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingStrategy.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingStrategyParams.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/targetcalculator/DemandEstimatorAsTargetCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/targetcalculator/EqualRebalancableVehicleDistributionTargetCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/targetcalculator/EqualVehicleDensityTargetCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/targetcalculator/EqualVehiclesToPopulationRatioTargetCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/targetcalculator/RebalancingTargetCalculator.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/rebalancing/targetcalculator/EqualVehicleDensityTargetCalculatorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/rebalancing/targetcalculator/EqualVehiclesToPopulationRatioTargetCalculatorTest.java
Main changes:
- change rebalancing target value type from int to double
- apply alpha-beta linear scaling to all target calculators (when called from `MinCostRebalancingStrategy`)
- cleanups and fixes in EqualVehiclesToPopulationRatioTargetCalculator
> Improvements in drt target calculators

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/RebalancingUtils.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/DrtModeMinCostFlowRebalancingModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingStrategy.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingStrategyParams.java
A dummy (single-vehicle) zone is created for each such vehicle. These dummy zones provide a supply of rebalancable vehicles, but the demand is 0. So vehicles will either stay where they are or will be relocated to areas with a negative vehicle surplus.
By doing this, the service area can be bigger than the zonal system used for rebalancing.
> Include vehicles outside zonal system in rebalancing

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtAnalysisControlerListener.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/AggregatedMinCostRelocationCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/DrtModeMinCostFlowRebalancingModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingStrategy.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/ZonalRelocationCalculator.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/DefaultPassengerEngine.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/PassengerEngineQSimModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/TeleportingPassengerEngine.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/AbstractDvrpModeQSimModule.java
This enables simulating DVRP without actually calling the optimiser 
A potential application: speeding up DRT, see some discussion here: https://github.com/matsim-org/matsim-libs/pull/1057#issuecomment-653741087
> Add teleporting passenger engine

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DrtModeOptimizerQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeQSimModule.java
- matsim/src/main/java/org/matsim/core/mobsim/framework/AbstractMobsimModule.java
- matsim/src/main/java/org/matsim/core/mobsim/qsim/QSimBuilder.java
- matsim/src/main/java/org/matsim/core/mobsim/qsim/QSimProvider.java
- matsim/src/test/java/org/matsim/core/controler/corelisteners/ListenersInjectionTest.java
Background:
- Some parameters in configs define iteration-specific behaviour of MATSim (e.g. do something only in certain iterations)
- mobsim (guice) modules are installed anew while instantiating a mobsim in each iteration, the scope of injection is one mobsim simulation
Providing the current iteration number to mobsim modules will add a context for interpreting the config (which is already available to mobsim modules) and simplify implementing a conditional behaviour, like switching on/off certain mobsim components/features depending on the iteration number.
Possible first application: switching off the vrp optimiser to speedup the mobsim (passengers are teleported instead). Currently this behaviour is hacked by replacing drt legs in plans before mobsim starts …
> provide AbstractMobsimModule with iteration number

- matsim/src/main/java/org/matsim/core/events/EventsManagerImpl.java
- remove obsolete searching for handlers of Event interfaces: after changing `Event` from an interface to a class (quite a few years ago), the class hierarchy of events is now a tree, so scanning the parent classes is enough
- increase type-safety of event handling in EventsManagerImpl (references to event classes are now of the type `Class<? extends Event>`)
Side effect:
- registering an event handler with a method `handleEvent(X event)` where `X` is neither `Event` nor its subclass will throw an exception (having such a method is either a bug or a really bad code smell given our design decisions wrt registering handlers)
> Clean up internal handling of event (handlers) in EventsManagerImpl

- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/fleet/FleetControlerListener.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/fleet/FleetModule.java
Dump out resulting dvrp fleet (which is possibly subject to change over iterations) at the end of the simulation.
See also https://github.com/matsim-vsp/opt-drt/issues/3
> dump out dvrp fleet at shutdown

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/demandestimator/PreviousIterationDRTDemandEstimator.java
- contribs/freight/pom.xml
Hello Michal, 
I had a build error (see my previous email) with the matsim-lib (the freight module, which I have not touched before). I tried different methods to solve it. The build error was finally solved after I deleted one line in the pom file (see the commit). I guess that line is the reason for the build error, but I'm not sure. Could you have a look? Thanks!
> remove maven source plugin from freight

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/demandestimator/PreviousIterationDRTDemandEstimator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/demandestimator/ZonalDemandEstimator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/DrtModeMinCostFlowRebalancingModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingStrategyParams.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/targetcalculator/DemandEstimatorAsTargetCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/targetcalculator/EqualRebalancableVehicleDistributionTargetCalculator.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/rebalancing/demandestimator/PreviousIterationDRTDemandEstimatorTest.java
Replace `ToDoubleFunction<DrtZone> getExpectedDemandForTimeBin(double time)` with `ToDoubleFunction<DrtZone> getExpectedDemand(double fromTime, double estimationPeriod)`
`demandEstimationPeriod` parameter was added to `MinCostFlowRebalancingParams`. Not all rebalancing strategies need to know that. Some actually do not use any demand estimation. So I decided to not have it one level above - i.e. in `RebalancingParams`.
> Refine demand estimator interface

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/demandestimator/PreviousIterationDRTDemandEstimator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/speedup/DrtSpeedUp.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/speedup/DrtSpeedUpParams.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/speedup/DrtTeleportedRouteCalculator.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/rebalancing/demandestimator/PreviousIterationDRTDemandEstimatorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/speedup/DrtSpeedUpTest.java
This is an integration of drt-speed-up (https://github.com/matsim-vsp/drt-speed-up) into DRT.
The main idea: the teleporting passenger engine will move passengers instead of calling the optimiser to send a vehicle. This allows a very straightforward re-implementation of drt-speed-up.
This is a draft PR until the new functionality gets covered by tests.
> Integrate drt speedup into drt

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtRequestAnalyzer.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/speedup/DrtSpeedUp.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/speedup/DrtSpeedUpTest.java
As mentioned here: https://github.com/matsim-org/matsim-libs/pull/1193#issuecomment-707842382, this PR adds unit tests for drt-speed-up, where instead of running actual matsim, each iteration is replaced with:
1. stub DrtRequestAnalyzer.getPerformedRequestSequences() (to fake simulation)
2. call iter end event (to trigger drt-speed-up postprocessing)
3. assert currentAvgWaitingTime and currentAvgInVehicleBeelineSpeed
@vsp-gleich @ikaddoura I left a few notes inside `DrtSpeedUp`.
The most important one: I expect potential race conditions between drt-speed-up and opt-drt at the end of an iteration (the former using the fleet size to build stats about the current iteration, while the latter adapting the fleet size for the next iteration). My suggestion: move opt-drt adaptations to the …
> Test new drt-speed-up

- matsim/src/main/java/org/matsim/core/events/MatsimEventsReader.java
- matsim/src/main/java/org/matsim/core/utils/io/IOUtils.java
- matsim/src/test/java/org/matsim/core/utils/io/IOUtilsTest.java
Short PR to allow the EventReader to read "xml.lz4" files.
Also, this changes the lz4 format from block to frame format:
As described in this [thread](https://groups.google.com/forum/#!topic/lz4c/1g4cK5Yz_uU), the frame format can be used with the lz4 command line tools and has better interoperability.
I also did some benchmarks and noticed a quite significant regression in reading performance in MATSm 13.
Code snipped run on file with roughly 10 mio events
```java
EventsManager manager = EventsUtils.createEventsManager();
manager.initProcessing();
EventsUtils.readEvents(manager, XML_INPUT + compression);
```
|Benchmark|Mode|Samples|Score|Score Error (99,9%)|Unit|Param: compression|
|-----------|------|---------|-----|-------------------|-----|---------------------|
|MATSIm …
> LZ4 Improvements

- contribs/dvrp/pom.xml
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/router/DvrpGlobalRoutingNetworkProvider.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/DvrpConfigGroup.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/DvrpModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/ZonalSystems.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/DvrpTravelTimeMatrix.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/DvrpTravelTimeMatrixParams.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/DvrpTravelTimesMatrixModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/TravelTimeMatrices.java
- contribs/dvrp/src/test/java/org/matsim/contrib/zone/skims/DvrpTravelTimeMatrixTest.java
- contribs/dvrp/src/test/java/org/matsim/contrib/zone/skims/TravelTimeMatricesTest.java
- currently only free-speed car TTs
- calculated only if `DvrpTravelTimeMatrixParams` are present inside `DvrpConfigGroup`
- square-grid zones are created automatically (cell size: `DvrpConfigGroup.getTravelTimeMatrixParams().get().getCellSize()`)
- global because of computation time and memory usage (but can be "guice-configured" per mode)
The TT matrix will replace the use of beeline TTs in `DrtInsertionSearch`es (both extensive and selective)
> Add dvrp global TT matrix

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DetourTimeEstimator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionSearch.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionSearchParams.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionSearchQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionSearch.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionSearchQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/benchmark/DvrpBenchmarkModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/router/DvrpGlobalRoutingNetworkProvider.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/router/DvrpModeRoutingNetworkModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/DvrpConfigGroup.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/DvrpModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/util/NetworkAreaFiltering.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/ZonalSystems.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/DvrpGlobalTravelTimesMatrixProvider.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/DvrpTravelTimeMatrixParams.java
- contribs/vsp/src/test/java/org/matsim/integration/drtAndPt/PtAlongALine2Test.java
- examples/scenarios/dvrp-grid/multi_mode_one_shared_taxi_config.xml
- examples/scenarios/dvrp-grid/one_shared_taxi_config.xml
- examples/scenarios/mielec/mielec_drt_config.xml
- examples/scenarios/mielec/mielec_edrt_config.xml
- examples/scenarios/mielec/mielec_serviceArea_based_drt_config.xml
- examples/scenarios/mielec/mielec_stop_based_drt_config.xml
- matsim/src/main/java/org/matsim/core/network/filter/NetworkFilterManager.java
Compute travel time matrices (using auto-generated grid zones) in order to:
1. stop using beeline distances and TTs in DRT and taxi (insertion, relocation etc.)
2. get more accurate results for `SelectiveInsertionSearch` to minimise rejections.
**Changes in configs**
1. `DvrpTravelTimeMatrixParams` is added to the DVRP config. If not provided this is assumed as default (200 m as the cell size):
```
<parameterset type="travelTimeMatrix">
<param name="cellSize" value="200"/>
</parameterset>
```
Currently there is only 1 global free-speed TT matrix with one exception: if drt/taxi uses a mode-filtered network, a separate matrix is created for such a mode.
2. `estimatedDrtSpeed` and `estimatedBeelineDistanceFactor` are removed from the DRT config.
**Performance**
Since currently only the …
> Replace beeline TT with TT matrix in DRT

- contribs/freight/src/main/java/org/matsim/contrib/freight/events/eventhandler/LSPVehicleLeavesTrafficEventHandler.java
This lead to failures in the dfg-project since PR #1180
> In one LSP...EVentHandler the "extends EventHandler" was missing.

- contribs/emissions/src/main/java/org/matsim/contrib/emissions/ColdEmissionAnalysisModule.java
- contribs/emissions/src/main/java/org/matsim/contrib/emissions/WarmEmissionAnalysisModule.java
- contribs/emissions/src/main/java/org/matsim/contrib/emissions/utils/EmissionsConfigGroup.java
this is a quick fix for #1226 allowing to choose a (lower) level for the consistency check of the hbefa values.
Additionally I added some NotNull checks inside the ColdEmissionsAnalysisModule (on the way)
Notes: 
- There is still no check for consistency of the coldEmissions table
- One times ion the future, one should / may  add another (smarter) consistency check --> see discussion in #1226
> quick fix for #1226: emissions: introduce a switch for level of consitency check

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/MultiInsertionDetourPathCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SingleInsertionDetourPathCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtRoute.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtRouteCreator.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/routing/DrtRoutingModuleTest.java
Also:
- refactor `DrtRoute` methods
- use `OptionalTime` for times stored inside `DrtRoute`
> Remove fixed travel time estimate from detour calculation

- contribs/freight/src/test/java/org/matsim/contrib/freight/utils/FreightUtilsTest.java
- examples/scenarios/freight-chessboard-9x9/carrierPlans.xml
- examples/scenarios/freight-chessboard-9x9/carrierPlansWithoutRoutes.xml
- examples/scenarios/freight-chessboard-9x9/carrierPlansWithoutRoutesAndBigVehicles.xml
- examples/scenarios/freight-chessboard-9x9/multipleCarriers_withoutTW_withDepots_withoutPlan.xml
- examples/scenarios/freight-chessboard-9x9/singleCarrierFiveActivities.xml
- examples/scenarios/freight-chessboard-9x9/singleCarrierFiveActivitiesWithoutRoutes.xml
- examples/scenarios/freight-chessboard-9x9/singleCarrierOneActivity.xml
- examples/scenarios/freight-chessboard-9x9/singleCarrierOneActivityWithoutRoutes.xml
- examples/scenarios/freight-chessboard-9x9/singleCarrierPlanBigVehicles.xml
- examples/scenarios/freight-chessboard-9x9/vehicleTypes.xml
... to the current code:
- add the (new) NumberOfJspritIterations as Attribute to the carriers
- adapt one test to that: e.g. remove the manually setting of this (previously missing) attributes
- Update the vehicleTypes.xml from the old freight specific format to the regular MATSim vehicleDefinitions_v2.0 scheme
This PR is also done as preparation for updating the RunFreightExample in [matsim-code-examples](https://github.com/matsim-org/matsim-code-examples).
> Update freight example scenario

- contribs/vsp/src/main/java/playground/vsp/scoring/IncomeDependentUtilityOfMoneyPersonScoringParameters.java
- contribs/vsp/src/test/java/playground/vsp/scoring/IncomeDependentUtilityOfMoneyPersonScoringParametersTest.java
This PR introduces a new implementation of `ScoringParametersForPerson` which accounts for agent-specific values for marginalUtilityOfMoney.
This functionality relies on person attributes.
The resulting marginal utility of money is computed as:
mgnUtilityOfMoney = averageIncome / personalIncome
Note that the global average income is dynamically computed based on the population. However, e.g. in cases of heterogenous spatial distribution, it is possible to provide an agent-specific relevant income attribute. The value of this attribute then replaces global value for average income in the equation formulated above.
Be aware that all agents that have the personal income attribute is taken into account. If no such attribute is found for a person, the subpopulation's scoring parameters are …
> income-dependent marginal utility of money in PersonScoringParameters

- .travis.yml
As discussed in https://github.com/matsim-org/matsim-libs/pull/1247
The idea is that Travis always tests updated branches, but also pull requests if they come from a fork. We do not want to let Travis test every PR, because this would lead to doubly running the test for the branch and for the PR in most cases.
> Enable building PRs from forks in Travis

- .github/workflows/verify-push.yaml
- matsim/src/test/java/org/matsim/core/network/algorithms/NetworkSimplifierTest.java
Enable a GitHub Actions workflow for pushes to branches.
If the diff between the pushed commit and the master branch`(*)` is limited to contribs, only they are built (less than 15 min. built time). Otherwise also matsim is built (less than 30 min).
`(*)` For pushes to master the diff is done against the most recent commit before that push.
I will reconfigure the checks and make the new workflow required (instead of the travis one) for merging to master.
Sorry for not putting this into a discussion. The ongoing development is stalled, so it needs to be fixed asap. We can later revise some decisions.
==
In the next step I would like to configure the workflow for merging to master. Verifying such pushes is not time critical, so I was thinking about running them using a (very) limited number …
> verify pushes to branches with GH Actions

- contribs/otfvis/pom.xml
Fixes #972. I uploaded the patched JOGL version, as discussed in #972, to our Bintray, and switched OTFVis to that version.
As it's a bit messy to do this since it uses the Maven classifier feature for the different platform versions, here is the command line for the native binary JARs (starting from the cloned web site as suggested in #972). Use this if we want to repeat this for another version, or add more platform JARs such as AMD (since I don't know how to build the JAR that holds all of the platform JARs):
```
mvn deploy:deploy-file -Durl="https://api.bintray.com/maven/matsim/matsim/JOGL/;publish=1" \
-DrepositoryId=matsim \
-Dfile=jogamp.org/deployment/archive/master/gluegen_937-joal_660-jogl_1506-jocl_1147/jar/jogl-all-natives-windows-i586.jar \
-DgroupId=org.jogamp.jogl \ …
```
> Switch to patched JOGL version

- appveyor.yml
The new GH Actions CI is too fast for appveyor (esp. when combined with auto-merge):
https://ci.appveyor.com/project/michalmac/matsim-libs/history
Two problems:
- PR branches are already gone (-> therefore: build only master, which should be fine as the main goal is to detect some win-linux incompatibilities that pop up from time to time)
- even when processing only pushes to master, the appveyor is too slow ( -> therefore `clone_depth` is set to 5, which should be enough for short peaks)
> limit appveyor builds to master; increase clone_depth

- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/Matrix.java
Hello Michal, 
I have a suggestion on changing the descrption of the Error message. The original error message may cause some confusion between the DRT zonal system and the DVRP travel time matrix zones. This happened to me these days and I have spent quite some time "debugging" a non-exsiting bug in DRT zonal system generation...
Perhaps it is a good idea to seperate it into two different error information (i.e. one for DRT zonal system and one for the DVRP travel time zones)?
Or perhaps shall we also make the DVRP travel time matrix also depends on shapefile? For example, for the Vulkaneifel scenario, the network of the whole northwestern Germany is used. The default cell size of 200 for the DVRP travel time matrix will yield more than 60,000 zones, which is above limit.
Thanks!
> Update the error message of the zone systems (when there are too many zones)

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserter.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DrtRequestInsertionRetryParams.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DrtRequestInsertionRetryQueue.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DrtRequestInsertionRetryQueueTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/run/examples/RunDrtExampleIT.java
Inspired by https://github.com/matsim-org/matsim-libs/pull/1247
Main differences:
- minimal in terms of required changes in the existing code: the request retry is handled within the `insertion` package (insertion procedure), and so it does not involve changes in the event processing or adding another passenger engine
- request rejection events are not triggered until the final attempt
- the next retry time is computed individually for each unsuccessful request and the requests are queued accordingly (instead of running every N seconds the retry procedure for all unsuccessful requests)
> add DRT request insertion retry functionality

- contribs/bicycle/src/main/java/org/matsim/contrib/bicycle/BicycleLinkSpeedCalculatorDefaultImpl.java
- contribs/bicycle/src/test/java/org/matsim/contrib/bicycle/BicycleLinkSpeedCalculatorTest.java
- contribs/osm/src/main/java/org/matsim/contrib/osm/networkReader/OsmBicycleReader.java
Having an infrastructure speed factor of 0.5 as a default seemed to be un intuitive. Make it optional for this reason.
> Speed factor for bikes not mandatory

- matsim/src/main/java/org/matsim/api/core/v01/IdMap.java
- matsim/src/main/java/org/matsim/core/events/ParallelEventsManager.java
- matsim/src/main/java/org/matsim/core/mobsim/hermes/Agent.java
- matsim/src/main/java/org/matsim/core/mobsim/hermes/Hermes.java
- matsim/src/main/java/org/matsim/core/mobsim/hermes/HermesConfigGroup.java
- matsim/src/main/java/org/matsim/core/mobsim/hermes/Realm.java
- matsim/src/main/java/org/matsim/core/mobsim/hermes/ScenarioImporter.java
- matsim/src/main/java/org/matsim/core/utils/collections/ArrayMap.java
- matsim/src/main/java/org/matsim/core/utils/collections/IntArrayMap.java
- matsim/src/test/java/org/matsim/core/mobsim/hermes/HermesTransitTest.java
- matsim/src/test/java/org/matsim/core/utils/collections/IntArrayMapTest.java
Various changes and fixes for Hermes, see #1248. Mostly related to correctly support rarely used features of the transit schedule, e.g. support multiple stops on the same link, support circular routes, support additional links before the first or after the last stop in a transit route. For this, I had to rewrite parts of the ScenarioImporter. But I've also added several unit tests, so I'm hopeful I didn't break anything.
With all this work, I've also cleaned up the code a bit and optimized it in some places, e.g. using `double[]` instead of `ArrayList<Double>` at some place, using `int[]` instead of `ArrayList<Integer>` in some other place, reducing the number of instantiated ArrayList and HashMaps in various places. In general, the memory consumption of Hermes should now be considerably …
> Hermes fixes and improvements

- contribs/vsp/src/main/java/playground/vsp/scoring/IncomeDependentUtilityOfMoneyPersonScoringParameters.java
Hey @Janekdererste and @Mengzhuoxiao, i accidentally had a subpopulation filter in here, which is now gone. Please note this. You should  carefully set your income attributes to suitable agents only!
> remove subpopulation filter in IncomeDependentPersonScoringParams

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalWaitTimesAnalyzer.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/Feedforward/FeedforwardRebalancingStrategyParams.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/Feedforward/FeedforwardSignalHandler.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/demandestimator/NetDepartureReplenishDemandEstimator.java
**Major Bug fixing** for Feedforward Rebalancing Strategy:
1. No rebalance in the second iteration
Preoblem: The reset function in the demand estimator (which update the demand database based on previous iteration) is called after the calculation of feedforward signal. Therefore, the feedforward signal for 2nd iteration (i.e. Iteration #1) is always emtpy.
Fix: Add an update function in the demand estimator and it is called before the calculation of the feedforward signal.
2. Wrong surplus calculation
Problem: In the feedforward signal handler, the surplus calculation is wrong. It should be -1 * net departure. 
Fix: List<DrtZoneVehicleSurplus> vehicleSurpluses = zonalSystem.getZones().values().stream()
.map(z -> new DrtZoneVehicleSurplus(z, **(int) …
> Major Bug fixing for Feedforward Rebalancing Strategy

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtAnalysisControlerListener.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtTrip.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalSystem.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtStopFacilityImpl.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalSystemTest.java
**This Pull request is open for discussion**
When we determine wheter a link (i.e. DRT stops)  is within the service area, the coordinate of the "toNode" of the link is used (see DrtModeModule, line 229), Therefore, I think it is better to also use "toNode" of the link when determine the zone a link belongs to. If we use the link's coordinate, there are likely to be some requests within the service area but outside any of the zone. This will add some unwanted effect to the analysis. 
Alternatively, we can also change the way we determine whether a link is within the service area (i.e. change the code DrtModeModule).
Attention: the test will fail because this change will change the zone belonging of some links, which will make the test fail. If we want to implment this pull request, we …
> Get zone for link ID: use to node of the link

- contribs/emissions/src/main/java/org/matsim/contrib/emissions/WarmEmissionAnalysisModule.java
- contribs/emissions/src/main/java/org/matsim/contrib/emissions/utils/EmissionsConfigGroup.java
Fixing the method name for the string-setter in the config group. See issue #1296.
> Emissions config group method

- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtRoute.java
Currently, the maxWaitTime and directRideTime are dumped out in the format OptionalTime[%s]. This can not be parsed (with FloatingDecimal.parseDouble), which means, we can currently not read plans with drt routes.
This PR proposes to dump out only the numeric values of maxWaitTime and directRideTime (this is how it used to be) and throw an Exception is one of those is undefined. As legs are either routed or they aren't, it should be okay to throw an exception, shouldn't it?
> Write seconds in DrtRoute description 

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtAnalysisControlerListener.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtTripsAnalyser.java
As we have discussed before, it may be a good idea to add in this satisfaction rate into our analysis (See attached picture). 
Definition of satisfaction rate:
SR(x) = N(request with waiting time below x minutes)/N(total requests)
Here we have included SR(10) and SR(15), which are commonly used in different studies.
> Adding satisfaction rate to the drt analysis

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtTripsAnalyser.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalSystem.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/depot/Depots.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/RebalancingUtils.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/speedup/DrtTeleportedRouteCalculator.java
A few remaining `link.coord` cases that were not part of https://github.com/matsim-org/matsim-libs/pull/1287
Additionally, I also changed the handling of empty arrays in `getPercentageWaitTimeBelow()`. Now it returns `NaN` to be consistent with all other stats (this is a contract behind all stats computations in `DescriptiveStatistics`).
> Finalise switch to link to node coord

- contribs/commercialTrafficApplications/scenarios/grid/jointDemand_population.xml
- contribs/commercialTrafficApplications/src/main/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/commercialJob/CommercialJobGenerator.java
- contribs/commercialTrafficApplications/src/main/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/commercialJob/CommercialTrafficChecker.java
- contribs/commercialTrafficApplications/src/main/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/commercialJob/JointDemandUtils.java
- contribs/commercialTrafficApplications/src/test/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/TestScenarioGeneration.java
Rather than using a string represenation with a convention-based delimiter, use Collection<String> as attribute type within jointDemand package. This requires reformatting of input data but is more robust.
> String collection attribute in joint demand package

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionSearch.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionCostCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionSearch.java
It's mostly underestimation, because the detour TTs are computed using the dvrp free-flow TT matrix while the replaced drive TTs are path-based.
This issue had an impact on the insertion pre-filtering step. The final insertion selection is executing using precise TTs (taken from computed paths).
> DRT: avoid systematic (under)estimation errors of detour time loss

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionCostCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionDetourTimeCalculator.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionDetourTimeCalculatorTest.java
- extract `InsertionDetourTimeCalculator` from `InsertionCostCalculator` so that the latter can be easily replaced with some other definitions (giving more flexibility wrt. the optimisation objective function)
- add unit tests for `InsertionDetourTimeCalculator`
> Cleanup and unit-test insertion detour calculation

- contribs/freight/src/main/java/org/matsim/contrib/freight/Freight.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/controler/CarrierModule.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/usecases/chessboard/RunPassengerAlongWithCarriers.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/utils/FreightUtils.java
- contribs/freight/src/test/java/org/matsim/contrib/freight/carrier/CarrierModuleTest.java
and clean up things afterwards.
---
This avoids that carriers can be registered on twice ways and it is unclear what do do.
> Take carriers out of carrier module constructor

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/MultiInsertionDetourPathCalculator.java
It does not work properly with relaxed max wait/travel time rejections.
After this fix the one-to-many path search reaches further, so some slight increase in computation time may be observed.
> fix: remove time-based termination criteria from multi insertion path calculator

- contribs/vsp/src/main/java/playground/vsp/flowEfficiency/AVFlowEfficiencyImpact.java
- contribs/vsp/src/main/java/playground/vsp/flowEfficiency/BunchingFlowEfficencyImpact.java
Currently, TransitQVehicle.getDriver().chooseNextLinkId() must not be called several times (in a row). So we need to handle transit vehicles explicitly and can not model impacts of the direction on flow efficiency. See also #1338 for a discussion point.
> handle TransitQVehicles in SituationalFlowEfficiencyImpact examples

- contribs/freight/pom.xml
- contribs/integration/pom.xml
- contribs/vsp/pom.xml
a potential fix for https://github.com/matsim-org/matsim-libs/issues/1343#issuecomment-760895531
> use 13.0-SNAPSHOT instead of matsim.version var as version in POMs

- contribs/emissions/scenarios/sampleScenario/testv2_Vehv1/config_average.xml
- contribs/emissions/scenarios/sampleScenario/testv2_Vehv1/config_detailed.xml
- contribs/emissions/src/main/java/org/matsim/contrib/emissions/example/RunAverageEmissionToolOfflineExample.java
- contribs/emissions/src/main/java/org/matsim/contrib/emissions/example/RunDetailedEmissionToolOfflineExample.java
by adding `eventsManager.initProcessing()` and `eventsManager.finishProcessing(), see #1342 
Also done: 
- Align the code of both offlineExamples;
- add a note for usage of old EventsManager (if using larger scenarios with more events) see: #1091   
- add config parameter to the testv2_Vehv1 configs, to ensure that the hbefaVehicleDescription is read correctly
> Make EmissionToolOfflineExamples writing output again

- matsim/src/main/java/org/matsim/utils/objectattributes/ObjectAttributesConverter.java
- matsim/src/test/java/org/matsim/utils/objectattributes/ObjectAttributesConverterTest.java
Fixes #1348 
Object attributes of type Map and of type Collection can now be empty without provoking a crash in ObjectAttributesConverter.
I added tests.
> Convert empty collection and empty map object attributes

- contribs/emissions/src/test/java/org/matsim/contrib/emissions/TestPositionEmissionModule.java
- matsim/src/main/java/org/matsim/core/api/experimental/events/EventsManager.java
- matsim/src/main/java/org/matsim/core/events/EventsUtils.java
- matsim/src/main/java/org/matsim/core/events/ParallelEventsManager.java
- matsim/src/main/java/org/matsim/core/events/SimStepParallelEventsManagerImpl.java
- matsim/src/main/java/org/matsim/core/mobsim/hermes/Hermes.java
- matsim/src/main/java/org/matsim/core/mobsim/hermes/Realm.java
- matsim/src/test/java/org/matsim/core/events/EventsHandlerHierarchyTest.java
- matsim/src/test/java/org/matsim/core/events/EventsManagerImplTest.java
- matsim/src/test/java/org/matsim/core/events/ParallelEventsManagerTest.java
- matsim/src/test/java/org/matsim/core/events/SimStepParallelEventsManagerImplTest.java
Rollback some changes to the EventManagers that have been introduced recently and during the integration of hermes.
* `createEventsManager()` returns the single threaded variant again
* Added `createParallelEventsManager()` for users who want to create the parallel variant
* Reverted `SimStepParallelEventsManagerImpl` to the old implementation again. (cf. #1341). @tschlenther already reported some problems in the berlin scenario
* The parallel events manager checks for correct usage of `.initProcessing()`. 
This PR closes #1342, #1347, #1091
> Rollback event manager changes

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionCostCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionDetourTimeCalculator.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionDetourTimeCalculatorTest.java
- Some code simplification, where the direct pickup->dropoff detour is handled separately. Despite ending up with a few more LOCs, the new version simplifies computating additional time information.
- Based on the above: compute expected pickup/dropoff times (in addition to the existing ones: pickup/dropoff time losses). They will be used in
> DRT: simplify input data creation for insertion cost calculation; compute pickup/dropoff times for evaluated insertions

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DrtModeOptimizerQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionSearch.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionSearchQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionCostCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionDetourTimeCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionSearch.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionSearchQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/edrt/run/EDrtModeOptimizerQSimModule.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionCostCalculatorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionDetourTimeCalculatorTest.java
The existing soft constraint calculation did not capture all possible special cases (e.g. pickup is included into ongoing/planned stop task -> no additional time loss wrt stop task) when computing the expected departure/arrival times for an incoming request (given insertion points).
The new approach to insertion cost computation uses `DetourTimeInfo`, where most of the critical data is already pre-computed (by `InsertionDetourTimeCalculator`, see #1357 ).
This PR may lead to slightly different results obtained by DRT (e.g. fewer rejections if they are enabled).
> DRT: fix soft constraint calculation

- matsim/src/main/java/org/matsim/core/scoring/functions/CharyparNagelLegScoring.java
Logic similar to the money scoring function; allow to plug together a scoring context in which the person specific marginal utility of money is used. mainly meant as a fall back in case the person specific scoring parameters approach uses up too much memory...
> add constructor which allows for marginal utility of money

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DrtModeOptimizerQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/CostCalculationStrategy.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionSearch.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionSearchQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionCostCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionSearch.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionSearchQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/edrt/run/EDrtModeOptimizerQSimModule.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/CostCalculationStrategyTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionCostCalculatorTest.java
Main change: `CostCalculationStrategy` becomes a standalone interface, putting some more spotlight on it as a way of making DRT more flexible.
BTW. The recent changes in `CostCalculationStrategy.calcCost()` open up modelling the following use cases:
- allow exceeding the vehicle operation time (i.e. scheduling tasks beyond the vehicle's `serviceEndTime`)
- shifting focus from minimising the fleet workload to maximising the service quality (i.e. calculating impact on all scheduled requests and the new one).
> DRT: move CostCalculationStrategy outside InsertionCostCalculator

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/CostCalculationStrategy.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/CostCalculationStrategyTest.java
Otherwise, do not check if the current slack time is long enough (can be even negative)
In other words: if vehicle is behind its schedule and will stop operations after the desired `serviceEndTime`, we can still add more requests if they are picked up and dropped off at the already planned stops (so it does not incur additional delays).
This change is applied to both default cost strategies: `RejectSoftConstraintViolations` and `DiscourageSoftConstraintViolations`.
> DRT: check slack time iff insertion ends in time loss

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserter.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/DrtRequest.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/RequestInsertionScheduler.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/util/DrtRequestTimeConstraintViolations.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/passenger/TaxiRequest.java
Reason: Requests should be unmodifiable input (so this is not a place for storing planning/execution details)
Additionally: hide pickup/dropoff tasks from `TaxiRequest` to prepare for removal. We cannot remove them completely yet, as the taxi request also contains status (which depends on these tasks).
> DRT: Remove pickup dropoff from drt request

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DrtModeOptimizerQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/DefaultRequestInsertionScheduler.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/RequestInsertionScheduler.java
- contribs/drt/src/main/java/org/matsim/contrib/edrt/run/EDrtModeOptimizerQSimModule.java
- more flexibility in handling an extended set of DRT tasks (such as charging, driver breaks...)
- easier writing of unit tests (now we can easily implement `RequestInsertionScheduler` instead of mocking it)
> DRT: make RequestInsertionScheduler an interface

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/BestInsertionFinder.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/KNearestInsertionsAtEndFilter.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/KNearestInsertionsAtEndFilterTest.java
- contribs/dvrp/src/main/java/org/matsim/contrib/util/PartialSort.java
- contribs/dvrp/src/main/java/org/matsim/contrib/util/StraightLineKnnFinder.java
- contribs/dvrp/src/test/java/org/matsim/contrib/util/PartialSortTest.java
- contribs/taxi/src/main/java/org/matsim/contrib/etaxi/optimizer/assignment/AssignmentETaxiOptimizer.java
@luchengqi7 I adapted `KNearestInsertionsAtEndFilter` so that it uses `vehicleId` as a tiebreaker if two or more vehicles are equally distant so that we can hopefully be able to reproduce DRT runs.
> DVRP: use custom comparator in PartialSort to allow for deterministic tie-breaking

- contribs/emissions/src/main/java/org/matsim/contrib/emissions/EmissionModule.java
looks like there was a typo introduced in #1303
Fixing it by setting the default value to false --> if not set based on a config value to true, there is no need to create the average value table.
> Emissions: Minor fix in decision if average table is needed or not

- matsim/src/main/java/org/matsim/lanes/LanesUtils.java
- matsim/src/test/java/org/matsim/lanes/LanesUtilsTest.java
The current lane implementation always expect one incoming lane. 
If one wants to make it of zero length and let the other lanes start immediately the code does not handle the order correcty. Occasionally it would work depending on the order the lanes have been added / written in the xml file.
This PR fixes the behavior and adds a test for this case.
> Fix lane order for certain lanes to link assignments

- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/trafficmonitoring/DvrpOfflineTravelTimeEstimator.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/trafficmonitoring/DvrpOfflineTravelTimes.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/trafficmonitoring/DvrpTravelTimeModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/util/TimeDiscretizer.java
- contribs/dvrp/src/test/java/org/matsim/contrib/dvrp/trafficmonitoring/DvrpOfflineTravelTimeEstimatorTest.java
- contribs/dvrp/src/test/java/org/matsim/contrib/dvrp/trafficmonitoring/DvrpOfflineTravelTimesTest.java
Use the existing `@Named(DvrpTravelTimeModule.DVRP_INITIAL) TravelTime` binding to provide the DVRP travel times loaded from a file. It's way more flexible.
> DVRP: provide initial dvrp travel times via binding

- contribs/eventsBasedPTRouter/src/main/java/org/matsim/contrib/eventsBasedPTRouter/TransitRouterNetworkWW.java
- matsim/src/main/java/org/matsim/api/core/v01/network/Link.java
- matsim/src/main/java/org/matsim/core/network/LinkImpl.java
- matsim/src/main/java/org/matsim/core/network/NetworkUtils.java
- matsim/src/main/java/org/matsim/core/router/util/AbstractRoutingNetworkLink.java
- matsim/src/main/java/org/matsim/pt/router/TransitRouterNetwork.java
- matsim/src/test/java/org/matsim/testcases/fakes/FakeLink.java
While working on special DVRP links (for fixed-demand fixed-traffic repeatable simulations -- meant for e.g. benchmarking or debugging), I did some cleanups around `Link`:
The main changes:
- add `getCapacityPeriod()` to `Link`: since `Link` offers `getFlowCapacity()` and `getFlowCapacity(time)` that both return a capacity given a predefined capacity period, it makes sense to provide the information on what the capacity period is, so the API user can translate these values to some absolute numbers (e.g. per hour or per second).
- providing default implementation for `getFlowCapacityPerSec(time)` and `getFlowCapacityPerSec()` in the `Link` interface (using the introduced  `getCapacityPeriod()` method), so they do not need to be implemented in each `Link`-extending class.
Actually these two …
> cleanup Link interface

- contribs/accessibility/pom.xml
- contribs/accidents/pom.xml
- contribs/bicycle/pom.xml
- contribs/integration/pom.xml
- contribs/noise/pom.xml
- matsim/pom.xml
- matsim/src/test/java/org/matsim/core/utils/geometry/transformations/GeotoolsTransformationTest.java
- pom.xml
For `pt2matsim` we had a couple of cases where the current `geotools` version seems to be outdated (for certain EPSG codes, etc.). This PR updates `geotools` to version `24.2` and unifies the version across all packages.
> Update geotools to 24.2

- .github/workflows/deploy-on-pr-merge.yaml
- .github/workflows/deploy-on-release-created.yaml
- .github/workflows/verify-push.yaml
- pom.xml
First steps addressing issues in #1378:
- migrate to GitHub packages
- add workflows that automatically deploy snapshots and (GitHub) releases
I tested this setup on a toy repo that resembles the matsim repo structure: https://github.com/michalmac/try-out-github-packages.
I was able to deploy to GitHub packages and then use the deployed jars in another local project. One caveat though: a public read token needs to be used (this is a current limitation of GitHub Packages). This is the currently suggested approach by GitHub according to https://github.community/t/partial-support-for-maven-snapshots/115628/12:
```xml
<repository>
<id>github-public</id>
<url>https://public:xxxxxxxxxxxxxxxxx@maven.pkg.github.com/michalmac/try-out-github-packages/</url>
</repository>
```
GitHub offers some …
> deploy to GitHub Packages; add snapshot and release deployment workflows

- .github/workflows/deploy-on-pr-merge.yaml
- .github/workflows/deploy-on-release-created.yaml
Once the deployment has started, try to upload as many jars as possible. It should also help to identify the problematic jars/modules and simplify a potential manual re-deployment of the missing jars.
> fail at end while deploying jars

- contribs/cadytsIntegration/pom.xml
- contribs/commercialTrafficApplications/pom.xml
- contribs/eventsBasedPTRouter/pom.xml
- contribs/pseudosimulation/pom.xml
- contribs/vsp/pom.xml
- distribution/pom.xml
According to https://maven.apache.org/guides/mini/guide-naming-conventions.html we should use lowercase latter in artifact ids. We are violating this rule in: `cadytsIntegration`, `commercialTrafficApplications` and `eventsBasedPTRouter`.
Not obeying this rule causes problems with uploading artifacts to GitHub Packages. Also some mvn plugins may not work.
Since we are just about to bump to `14.0-SNAPSHOT`, I think this is the best moment to switch to lowercase (as we will avoid issues like `cadytsIntegration-13.0-SNAPSHOT` being different than `cadyts-integration-13.0-SNAPSHOT`, which would likely lead to some hard to find bugs).
> fix: change artifact ids to lowercase

- .github/workflows/deploy-on-release-created.yaml
to replace the manual step of uploading them. Here's an example:
https://github.com/michalmac/try-out-github-packages/releases
=====
After merging this PR, the release process is almost fully automated. The following steps are required:
1. Bump the snapshot version on the master branch (e.g. `13.0-SNAPSHOT` -> `14.0-SNAPSHOT`)
2. Create the release branch (stemming from the last commit before the bumping, e.g. `13.x`). Note: Do not change version from  `13.0-SNAPSHOT` to  `13.0` in POMs (this is done by the workflow, also for any subsequent fix releases, e.g. `13.0.1`)
3. Create release on the GitHub page: provide the version number as the tag (e.g. `13.0`), and choose the corresponding branch (e.g. `13.x`)
After clicking "Publish release", the release workflow will be triggered: …
> upload matsim (core) assembly as release asset

- .github/workflows/deploy-on-pr-merge.yaml
See discussion here: https://github.com/matsim-org/matsim-libs/issues/1378#issuecomment-804845481
The PR-labelled version (e.g. `14.0-PR1534`) is created and deployed on merging PR to master (and only master). This is how it looks on the test repo: https://github.com/michalmac/try-out-github-packages/packages/718303
The PR-labelled releases are meant to replace the weekly releases (and potentially even the standard snapshots). We could also think of publishing snapshots to GitHub Packages (for the developers who know all the risks behind) and PR-labelled versions to the matsim maven repo (for the general public)...
Happy to hear your thoughts :-)
> deploy PR-labelled versions

- contribs/freight/src/main/java/org/matsim/contrib/freight/controler/CarrierAgent.java
Since some time now, it is possible to set an attribute for each carrier that is meant to determine it's mode if transport. This PR now realises that the corresponding agents perform legs of the specified mode. If no mode had been set, TransportMode.car is the default.
@kt86
> freight carriers: set the leg mode according to CarrierUtils.getCarrierMode()

- .github/workflows/deploy-on-pr-merge.yaml
- .github/workflows/deploy-on-release-created.yaml
- pom.xml
A series of little improvements in the `deploy-***` workflows:
- bump the mvn assemby plugin so `assembly.skipAssembly` flag is respected
- prevent unnecessary re-compilation when deploying already created jars (unnecessary copying resources was the trouble maker)
- stop installing jars to local mvn repo (and later caching them) in GH Actions when deploying to the remote maven repo
> Workflow improvements

- matsim/src/main/java/org/matsim/run/gui/AsyncFileInputProgressDialog.java
- matsim/src/main/java/org/matsim/run/gui/ConfigEditor.java
- matsim/src/main/java/org/matsim/run/gui/GUnZipper.java
- matsim/src/main/java/org/matsim/run/gui/Gui.java
- matsim/src/main/java/org/matsim/run/gui/PopulationSampler.java
- matsim/src/main/java/org/matsim/run/gui/ScheduleValidatorWindow.java
Aims at fixing issues reported in #1462
This PR reworks the way long-running operations (non-GUI threads) interact with the GUI thread (Event Dispatch Thread, EDT). In the old implementation lots of calls to GUI components were made from outside the EDT, which is practically always non-thread-safe and may lead to some odd behaviour (incl. deadlocks). Now all operations on GUI components (in all dialogs) are only executed from the EDT.
Calling `Gui.show()` is now thread-safe. No need to change anything in other customised GUIs (e.g. `AccessibilityGUI`)
> fix swing EDT threading issues; minor fixes & improvements

- contribs/otfvis/src/main/java/org/matsim/vis/otfvis/gui/OTFControlBar.java
- contribs/otfvis/src/main/java/org/matsim/vis/otfvis/gui/OTFHostControl.java
- matsim/src/main/java/org/matsim/core/mobsim/framework/PlayPauseSimulationControl.java
This PR fixes #1447
Disabling the single/multi step buttons while playing in the async mode. It is still OK to click these buttons:
- in the sync mode (playing or paused)
- in the async mode (only when paused)
> fix(OTFVis): disable "stepForward" buttons while playing in async live mode

- matsim/src/main/java/ch/sbb/matsim/config/SwissRailRaptorConfigGroup.java
- matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/DefaultRaptorStopFinder.java
- matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/RaptorStopFinder.java
- matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptor.java
- matsim/src/test/java/ch/sbb/matsim/config/SwissRailRaptorConfigGroupTest.java
- matsim/src/test/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorIntermodalTest.java
We have been working with the intermodal feature of the SwissRailRaptor extensively lately. Through this work we have encountered few places where SRR could be improved. 
One of the biggest challenges with intermodal router is the computation time. Imagine a situation where you have a trip that is 1km long, but your search radius for a particular access/egress service is 5 km. It is hard to imagine that a person would search for a stop further than the length of the trip itself. Therefore, it would be good to have a settable parameter than can be used to limit the search radius depending on the length of the trip. Currently, however, this cannot easily be added, as the [RaptorStopFinder](https://github.com/matsim-org/matsim-libs/blob/1cd0cd7bb65e7af9fd7abfec0bf8e61cc90acf46/matsim/src/main …
> SwissRailRaptor with trip length awareness 

- matsim/src/main/java/org/matsim/analysis/ModeChoiceCoverageControlerListener.java
- matsim/src/test/java/org/matsim/analysis/ModeChoiceCoverageControlerListenerTest.java
ModeChoiceCoverage is a ControlerListener that does the following calculation in each iteration: the percentage of trips have used a certain mode at least once (or 5x, 10x, …) in all previous iterations. In essence, this tool can be used to check whether enough iterations have been completed for agents to make full use of the mode choice innovation strategy. The results of this analysis are printed as outputs in text-based and graphical forms.
> Migrated ModeChoiceCoverage analysis tool from matsim-berlin to matsim-libs

- contribs/vsp/pom.xml
- pom.xml
mvn enforcer has some issues with one transitive dependency of ` JavaAPIforKml` (used in `vsp`):
```
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce) @ vsp ---
[WARNING] Rule 2: org.apache.maven.plugins.enforcer.RequireReleaseDeps failed with message:
Found Banned Dependency: com.sun.xml.bind:jaxb-xjc:jar:2.2-SNAPSHOT
```
However, `JavaAPIforKml` depends on com.sun.xml.bind:jaxb-xjc:jar:2.2 (none-snapshot version)
> try to fix failing builds on jenkins (m2 cache issues?)

- matsim/src/main/java/org/matsim/core/config/groups/PlansCalcRouteConfigGroup.java
- matsim/src/main/java/org/matsim/core/config/groups/QSimConfigGroup.java
- matsim/src/main/java/org/matsim/core/controler/PrepareForSimImpl.java
- matsim/src/main/java/org/matsim/core/router/NetworkRoutingInclAccessEgressModule.java
In the xml config it says "teleportedModeParameters", in the code "ModeRoutingParams".  Adapting the code towards the xml config.  For the time being, the code provides the consistently named classes/methods _in addition_ to the existing ones, and sets the existing ones to deprecated.
Also, while cleaning up, disabling the old fallback parameters for a bushwhacking leg.  Now need to be explicitly defined.  I tried to provide a sufficiently expressive error message.
> Rename mode routing params to teleported mode params; remove fallback behavior for bushwhacking

- matsim/src/main/java/org/matsim/core/controler/PrepareForSimImpl.java
The old error messages only printed "null" in the message, giving no indication which type is missing.
> Better error message when vehicle type is missing

- .github/workflows/verify-push.yaml
This PR fixes the issue reported here: https://github.com/matsim-org/matsim-libs/pull/1540#issuecomment-858735196
This is a workaround for the limitations around GitHub actions statuses/checks. I added a more detailed comment in the workflow file.
The main cause of all the (maybe unnecessary?) complexity is that we want to run verify external PRs but not the internal ones (to avoid duplicated jobs).
> fix(CI): create "verify-all-jobs-successful (push-or-external-PR)" on the fly

- matsim/src/main/java/org/matsim/core/network/NetworkUtils.java
Some network converters store the original OSM Id as a String, and others as a Long. If the network used used a Long, then a ClassCastException was thrown. This pull request will (hopefully) fix that by changing the conversion to a String.
> Fix class cast

- .github/workflows/deploy-on-pr-merge.yaml
- .github/workflows/deploy-on-release-created.yaml
I noticed that javadoc is unnecessarily created for each PR-labelled version on 13.x.
Because the `pom.xml` files have changed on master after stemming out 13.x (e.g. a release profile was added), to keep master and 13.x builds behaving in the same way as master builds, we need little adjustments to the workflows on 13.x.
> make 13.x workflows consistent with those on master

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SingleInsertionDetourPathCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DefaultDrtRouteUpdater.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/EmptyVehicleRelocator.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/routing/DrtRoutingModuleTest.java
- contribs/dvrp/pom.xml
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetaxi/OneTaxiModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetaxi/OneTaxiOptimizer.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetruck/OneTruckOptimizer.java
- contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/sim/SetupParking.java
- contribs/taxi/src/main/java/org/matsim/contrib/etaxi/optimizer/ETaxiOptimizerProvider.java
- contribs/taxi/src/main/java/org/matsim/contrib/etaxi/run/ETaxiModeQSimModule.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/assignment/AssignmentRequestInserter.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/assignment/VehicleAssignmentProblem.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiModeModule.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiModeQSimModule.java
Only `BestDispatchFinder` (in taxi) still uses the old "fast" multi-node Dijkstra. Migrating from "fast" to "speedy" will be handled in a separate PR.
> DVRP: Switch to speedy routers

- matsim/src/main/java/org/matsim/core/router/NetworkRoutingInclAccessEgressModule.java
- matsim/src/main/java/org/matsim/core/router/NetworkRoutingModule.java
NetworkInclAccessEgressModule actually looks up the vehicle in the Scenario and passes it to router but then does not set it in the NetworkRoute. I am not sure if this is on purpose, but i suppose it is not. This is actually a problem for modes other than 'car', when later on the vehicleId can not be retrieved from the route and no vehicle can be parked/unparked in the qsim. See also [this issue in matsim-sharing](https://github.com/eqasim-org/matsim-sharing/issues/5). I see no good reason why not to set the vehicleId, please let me know if you have one.
> set vehicleId in NetworkRoute

- matsim/src/main/java/org/matsim/pt/transitSchedule/TransitRouteStopImpl.java
- matsim/src/main/java/org/matsim/pt/transitSchedule/TransitScheduleFactoryImpl.java
- matsim/src/main/java/org/matsim/pt/transitSchedule/api/TransitScheduleFactory.java
the variable type is already OptionalTime, but there is no setter accepting OptionalTime, only double. At first glance this might introduce more issues with TransitRouteStops having an undefined arrival or departure offset, but the public builder of TransitRouteStopImpl already sets those to OptionalTime.undefinedTime() by default and they remain undefined if the arrivalOffset setter of the builder is not called. Defined times for all but the first stop's arrival and the last stop's departure should be checked somewhere else, possibly during simulation startup.
> allow for setting arrivalOffset and departureOffset as OptionalTime in TransitRouteStop

- .github/workflows/deploy-on-pr-merge.yaml
Otherwise, PRs coming from forks do not have access to secrets (necessary to deploy to mvn repo)
> fix #1591 - run deploy-on-pr-merge in the context of base of PR

- contribs/ev/src/main/java/org/matsim/contrib/ev/EvConfigGroup.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ElectricFleetModule.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ElectricVehicleSpecification.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ElectricVehicleSpecificationWithMatsimVehicle.java
Three options:
- from a separate EV file (EV config) -- this is the existing approach
- from the "standard" matsim vehicles (if `QSimConfigGroup.VehiclesSource.fromVehiclesData` is selected)
- via a custom binding (e.g. generated vehicles)
> 3 ways of creating an EV fleet specification

- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/fleet/DvrpVehicleSpecification.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/fleet/DvrpVehicleSpecificationWithMatsimVehicle.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/fleet/FleetModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/fleet/ImmutableDvrpVehicleSpecification.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ElectricFleetModule.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ElectricVehicleSpecificationWithMatsimVehicle.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiConfigGroup.java
The following options are allowed
- separate DVRP vehicles file
- from matsim vehicles
- custom binding (e.g. generated vehicles)
Different DVRP modes can choose different strategies.
This PR is about DVRP vehicles and is similar to #1605 (that was about EVs).
> Dvrp vehicles from matsim vehicles

- contribs/commercialTrafficApplications/src/main/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/commercialJob/CommercialJobGenerator.java
- contribs/commercialTrafficApplications/src/main/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/commercialJob/DefaultCommercialJobGenerator.java
- contribs/commercialTrafficApplications/src/main/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/commercialJob/JointDemandModule.java
- contribs/commercialTrafficApplications/src/main/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/commercialJob/ScoreCommercialJobs.java
- contribs/commercialTrafficApplications/src/main/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/commercialJob/TourPlanning.java
- contribs/commercialTrafficApplications/src/test/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/commercialJob/DefaultCommercialJobGeneratorTest.java
In commercialTrafficApplications, 
1. the `CommercialJobGenerator` is extracted to an interface, with the `DefaultCommercialJobGenerator` bound
2. Tour planning can now be started with a custom implementation of `VehicleRoutingTransportCosts`, which at the current state have to extend `NetworkBasedTransportCosts` because this type is needed for routing the carrier plans :(
> make jointDemandPackage a bit more customizable

- .github/workflows/verify-push.yaml
To overcome (temporal?) issues with github workflows. See: #1614
Now we have `build1` and `build2` jobs instead of `build`. Actually, this is not lowering the parallelism, as I forgot to add `needs: build1` to `build2` (so `build1` would need to complete before `build2` could start)
> split job matrix into 2 smaller matrices

- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/path/LeastCostPathTreeStopCriteria.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/path/OneToManyPathCalculator.java
- contribs/dvrp/src/test/java/org/matsim/contrib/dvrp/path/LeastCostPathTreeStopCriteriaTest.java
Both stop criteria (maxTravelTime, allEndNodesReached) were used internally in `OneToManyPathCalculator`, which is a dvrp-specific path search (takes links as input and returns `PathData`). Now they can be used for other purposes, e.g. replacing the old multi-node dijkstra.
> Extract dijkstra tree stop criteria

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DefaultDrtOptimizer.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DrtModeOptimizerQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserter.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DrtRequestInsertionRetryQueue.java
- contribs/drt/src/main/java/org/matsim/contrib/edrt/run/EDrtModeOptimizerQSimModule.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/run/examples/RunDrtExampleIT.java
Fixes issue: reinsertion is not attempted until there is at least one new unplanned request
> DRT: fix handling of request insertion retry queue

- contribs/application/src/main/java/org/matsim/application/prepare/population/CloseTrajectories.java
- matsim/src/main/java/org/matsim/core/config/groups/PlansConfigGroup.java
- matsim/src/main/java/org/matsim/core/mobsim/jdeqsim/EndLegMessage.java
- matsim/src/main/java/org/matsim/core/utils/timing/TimeInterpretation.java
- matsim/src/test/java/org/matsim/core/mobsim/jdeqsim/TestMessageFactory.java
- matsim/src/test/java/org/matsim/core/utils/timing/TimeInterpretationTest.java
This PR adds a new option to the `plans` config group. It is called `tripDurationHandling` and controls how leg departure times are assumed during plan-based routing, e.g. in the `ReRoute` strategy. We look at situations where the first activity of a plan has an end time of 08:00:00, and the second one has an end time of 12:00:00. After both activities, there is a leg, which gets routed during `ReRoute` or in `PrepareForSim`. If the mode is slow, it may happen that the agent only arrives *after* the end time of the second activity. This also happens frequently when, initially, the network is heavily congested. In such a case, *currently*, MATSim would still route the second trip with a departure time of 12:00:00, as it is defined in the plan. This case is handled by the default setting …
> Add tripDurationHandling option to improve timing in plan-based routing

- contribs/dvrp/src/main/java/org/matsim/core/router/speedy/SpeedyMultiSourceALT.java
- contribs/dvrp/src/test/java/org/matsim/core/router/speedy/SpeedyMultiSourceALTBackwardTest.java
- contribs/dvrp/src/test/java/org/matsim/core/router/speedy/SpeedyMultiSourceALTForwardTest.java
- contribs/dvrp/src/test/java/org/matsim/core/router/speedy/SpeedyMultiSourceALTTest.java
An initial implementation of multi-source ALT that is a modified version of Speedy ALT adapted for many-to-one search. The search can be done both forward and backward (*). Start nodes are be described with the initial cost and start time.
This PR is mainly meant to communicate the latest developments in this area. The first use case of the multi-source ALT will be replacing the old multi-node search used for finding the nearest taxi/request (will be done in a separate PR). Potentially, this multi-source ALT could be moved from `dvrp` to the matsim core.
(*) Forward vs backward:
Forward: find the best request (from a set of open requests) for a given taxi
Backward: find the best taxi (from a set of available taxis) for a given request
> Speedy multi source alt

- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DefaultDrtRouteUpdater.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtRouteCreator.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/router/DefaultMainLegRouter.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/router/GenericRouteCreator.java
These changes make it possible to implement a custom extension of the `DrtRouteCreator` which bases waiting time on user-specific or even trip-specific requirements.
> Pass arguments in DRT route creation to allow trip-based requirements

- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiConfigGroup.java
No longer an experimental feature. AFAIK no issues reported so far.
> dvrp: remove warnings about running drt/taxi with multi-threaded QSim

- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/path/VrpPathWithTravelData.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/path/VrpPathWithTravelDataImpl.java
- contribs/taxi/src/main/java/org/matsim/contrib/etaxi/ETaxiScheduler.java
- contribs/taxi/src/main/java/org/matsim/contrib/etaxi/run/ETaxiModeQSimModule.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiConfigGroup.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiModeQSimModule.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/scheduler/TaxiScheduler.java
In some configurations, the taxi optimiser may not know the destination until the passenger is picked up. But we can obtain this information already on request submission and use it to pre-compute the origin-destination path in the background.
If sufficiently many threads are used, all such paths are found before the pickup simulation ends. Consequently, QSim is not (directly) slowed down by computing these paths.
4-6 threads is usually enough. It's recommended to specify a higher number than that if possible (see the new param in the taxi config) - of course, threads will probably be not 100% busy. By default, it is set to the number of available cores.
> Taxi: pre-compute origin-destination paths

- matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/AbstractAgentSnapshotInfoBuilder.java
I have recently noticed that `TestPositionEmissionModule` randomly fails (at least on Window machines: https://ci.appveyor.com/project/michalmac/matsim-libs/builds/40571932)
The problem is that not always the same `positionEmission` events are produced (resulting in different emission stats). This, in turn, is caused by `position` events (of agents travelling inside vehicles) not always having `vehicleId` set (for such events, no `positionEmission` is generated). After digging in a bit, it turned out that there are some race conditions when building `AgentSnapshotInfo`s.
> fix: stop re-using AgentSnapshotInfo builder to ensure thread safety

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtEventSequenceCollector.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtLeg.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtLegsAnalyser.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/speedup/DrtSpeedUpTest.java
Currently, we can collect only one event. However, nothing block us from setting up more than one fare handler per mode. If that is the case, there may be more than one fare-related event associated directly with a given request.
@vsp-gleich
> drt: collect multiple fare-related events for one request

- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/analysis/ExecutedScheduleCollector.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/analysis/ExecutedTask.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/schedule/Task.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/analysis/TaxiModeAnalysisModule.java
To (later) replace the use of actual tasks/schedule objects in analysis (e.g. in taxi).
> Construct executed tasks for analysis

- .github/workflows/verify-push.yaml
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/RandomDrtZoneTargetLinkSelector.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/analysis/zonal/RandomDrtZoneTargetLinkSelectorTest.java
Changing to `zulu` as `adopt` is not yet available. Let's see if we are (almost) ready for JDK 17.
> CI: switch to JDK 17 (zulu distro)

- contribs/analysis/src/main/java/org/matsim/contrib/analysis/vsp/traveltimedistance/HereMapsRouteValidator.java
Enable travel time validation with general input (i.e. coords, departure time). Originally, the travel time validator only take "CarTrip" and this restricts the way travel time validator can be used. After the modification, we can get validation with a more general input data. Meanwhile, the original method is retained.
> Enable travel time validation with general input (i.e. coords, departure time)

- contribs/accidents/src/main/java/org/matsim/contrib/accidents/AccidentCostComputationBVWP.java
- contribs/accidents/src/main/java/org/matsim/contrib/accidents/AccidentWriter.java
- contribs/accidents/src/test/java/org/matsim/contrib/accidents/RunTest.java
Cut down the number of decimal digits to 2, as we display Euro per link or per day respectively. This will decrease the output file size remarkably.
I also inserted a comment into `AccidentCostComputationBVWP` that clarifies that the current approach does not distinguish between railways and roes. Thus, in my opinion, we should currently ignore pt links....
> reduce file size in accidents analysis

- contribs/analysis/src/main/java/org/matsim/contrib/analysis/vsp/traveltimedistance/HereMapsRouteValidator.java
- contribs/analysis/src/main/java/org/matsim/contrib/analysis/vsp/traveltimedistance/TravelTimeDistanceValidator.java
- contribs/analysis/src/main/java/org/matsim/contrib/analysis/vsp/traveltimedistance/TravelTimeValidationRunnerPreAnalysis.java
- contribs/application/src/main/java/org/matsim/application/analysis/TravelTimeAnalysis.java
The empty network validation (which can be an important process in the pre-analysis) is now moved to the matsim-lib from the matsim kelheim. I will close the PR in the matsim kelheim. 
Once again, this valdiation allow us to validate the free flow speed of the network agianst online API. Small adaptiations are made to the TravelTimeValidation as well as the TravelTimeDistanceValidator interface in order to accommodate the new features. 
Nevertheless, the default values of the newly added parameters are set to the value that the original functionality of the scrpt remain unchanged if you use the original input argument.
> Add empty network validation

- matsim/src/main/java/org/matsim/core/config/groups/ControlerConfigGroup.java
- matsim/src/main/java/org/matsim/core/config/groups/LinkStatsConfigGroup.java
- matsim/src/test/java/org/matsim/analysis/LinkStatsControlerListenerTest.java
- matsim/src/test/java/org/matsim/core/config/groups/ControlerConfigGroupTest.java
- matsim/src/test/java/org/matsim/core/config/groups/LinkStatsConfigGroupTest.java
- matsim/src/test/java/org/matsim/integration/replanning/ResumableRunsIT.java
By default, event files, link stats and plans are written out every 10th iteration. In our experience, these files are rarely used from individual iterations and use up a lot of space. 
This PR increases the defaults to every 50th iteration.  An even higher value might also be considered.
> Increase default interval for writing files

- contribs/parking/src/main/resources/parkingsearch/config.xml
- matsim/src/main/java/org/matsim/core/config/ReflectiveConfigGroup.java
Otherwise all non-"true" values are considered "false".
Like here: https://github.com/matsim-scenarios/matsim-berlin/blob/5.5.x/scenarios/berlin-v5.5-1pct/input/drt/berlin-drt-v5.5-1pct.config.xml#L195. The intention was to actually apply the filtering to the "drt" mode (so the value was meant to be "true", but currently no filtering is done).
> config: accept only "true"/"false" strings as boolean values

- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/router/DvrpModeRoutingNetworkModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/SparseMatrix.java
Java Flight Recorder showed `binarySearch()` in the sparse matrix (extensively used in the selective insertion search) as the main and really huge hotspot. So I decided to add a simple (custom-made) hash table based on node indices to reduce the binary search. Interestingly, it was really hard to be significantly faster than the existing implementation (both when simulating Berlin with 6000 autonomous DRT buses and in micro-benchmarking), which proves that the profiles had some artefacts and the binary search is not the main issue.
BTW. Later on, I ran the same big scenario using a dense node-to-node matrix that reduced speed by less than 5%, which somehow confirmed the issue with profiling.
> dvrp: add index-based hash table to sparse row to minimise binary search

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DetourData.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DetourTime.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionProvider.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGenerator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionProvider.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DetourDataTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionProviderTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGeneratorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionProviderTest.java
As a preparation step for computing detour times already during insertion generation. That should allow early pruning of generated insertions based on available time slack. These changes will be handled in the upcoming series of PRs.
**Motivation**
When running big DRT scenarios (e.g. Berlin scenario with 6 000 vehicles, 270 000 requests) with the selective insertion search, most of the time is actually spent on generating and evaluating insertions using travel-time matrices. At the same time, computing the actual paths for the finally selected insertion has a relatively small impact on the total computation time. Therefore, earlier pruning of infeasible insertions should bring a substantial speedup for the selective insertion search.
> Simplify insertion generation

- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/edrt/optimizer/EDrtVehicleDataEntryFactory.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/optimizer/insertion/ShiftInsertionCostCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/VehicleDataEntryFactoryImpl.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/VehicleEntry.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/CostCalculationStrategy.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultInsertionCostCalculator.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/VehicleDataEntryFactoryImplTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/BestInsertionFinderTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/CostCalculationStrategyTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DefaultDrtInsertionSearchTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserterTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DetourDataTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionCostCalculatorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionDetourTimeCalculatorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGeneratorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/KNearestInsertionsAtEndFilterTest.java
As pointed out in #1758, in large scenarios the slowest part of the the selective search is evaluating all possible insertion points using matrix-based travel times (contrary to the extensive search where the actual path search takes more time). This PR focuses on faster evaluation of insertion points by using pre-computed slack times.
This reduces the QSim duration by ~10% (Berlin scenario with 6 000 vehicles, 270 000 requests) given the selective search is used. For the extensive search, some speedup should be also observed (but has not been measured).
> drt: pre-calculate and cache vehicle/stop slack times

- contribs/analysis/src/main/java/org/matsim/contrib/analysis/vsp/traveltimedistance/GoogleMapRouteValidator.java
- contribs/analysis/src/main/java/org/matsim/contrib/analysis/vsp/traveltimedistance/HereMapsRouteValidator.java
- contribs/analysis/src/main/java/org/matsim/contrib/analysis/vsp/traveltimedistance/NetworkTrip.java
- contribs/analysis/src/main/java/org/matsim/contrib/analysis/vsp/traveltimedistance/RunTraveltimeValidationExample.java
- contribs/analysis/src/main/java/org/matsim/contrib/analysis/vsp/traveltimedistance/TravelTimeDistanceValidator.java
- contribs/analysis/src/main/java/org/matsim/contrib/analysis/vsp/traveltimedistance/TravelTimeValidationRunner.java
- contribs/analysis/src/main/java/org/matsim/contrib/analysis/vsp/traveltimedistance/TravelTimeValidationRunnerPreAnalysis.java
- contribs/analysis/src/main/java/org/matsim/contrib/analysis/vsp/traveltimedistance/TripsExtractor.java
- contribs/application/src/main/java/org/matsim/application/analysis/TravelTimeAnalysis.java
- contribs/bicycle/src/main/java/org/matsim/contrib/bicycle/BicycleModule.java
The TravelTimeValidator now accepts two mode options: One for the mode of the MATSim trips to validate and one for the routing mode to be used in the API.
E.g. this allows to also validate bike trips.
> Configurable mode for travel time validation

- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/edrt/run/EDrtModeOptimizerQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/eshifts/run/ShiftEDrtModeOptimizerQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/eshifts/scheduler/EShiftTaskScheduler.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/optimizer/ShiftRequestInsertionScheduler.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/run/ShiftDrtModeModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/run/ShiftDrtModeOptimizerQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/scheduler/ShiftTaskScheduler.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DrtModeOptimizerQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionSearchQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/MultiInsertionDetourPathCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionSearchQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SingleInsertionDetourPathCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DefaultDrtRouteUpdater.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtRouteCreator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/DefaultRequestInsertionScheduler.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/EmptyVehicleRelocator.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetaxi/OneTaxiModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetruck/OneTruckModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/router/DvrpModeRoutingModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/router/GenericRouteCreator.java
- contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/routing/WithinDayParkingRouter.java
- contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/sim/SetupParking.java
- contribs/taxi/src/main/java/org/matsim/contrib/etaxi/ETaxiScheduler.java
- contribs/taxi/src/main/java/org/matsim/contrib/etaxi/optimizer/ETaxiOptimizerProvider.java
- contribs/taxi/src/main/java/org/matsim/contrib/etaxi/run/ETaxiModeQSimModule.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/DefaultTaxiOptimizerProvider.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiModeModule.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiModeQSimModule.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/scheduler/TaxiScheduler.java
Currently the `DVRP_ESTIMATED` travel times are based on the "collected" travel times for car **qsim mode** and used for all vehicles across all **dvrp modes**. This is one of a few obstacles preventing us from simulating heterogenous fleets.
As a first step, let's focus on a simplified use case: being able to customise travel times per dvrp mode. This PR introduces modal binding for TravelTime for each dvrp mode, where `DVRP_ESTIMATED` travel time is used by default, i.e.
```
bindModal(TravelTime.class).to(Key.get(TravelTime.class, Names.named(DvrpTravelTimeModule.DVRP_ESTIMATED)));
```
This default binding needs to be overridden to provide different travel times.
> Customise travel time by dvrp mode

- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/router/DvrpModeRoutingNetworkModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/DvrpGlobalTravelTimesMatrixProvider.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/DvrpTravelTimeMatrix.java
- contribs/dvrp/src/test/java/org/matsim/contrib/zone/skims/DvrpTravelTimeMatrixTest.java
Next step after #1775: In DRT we also use free-speed travel time matrices. However, if some vehicles move slower (e.g. AVs with some max speed imposed), we should be able to build such matrices with a custom travel time (e.g. with `QSimFreeSpeedTravelTimeWithMaxSpeedLimit`).
> dvrp: support creating non-free-speed travel time matrices

- matsim/src/main/java/org/matsim/core/mobsim/qsim/QSimProvider.java
- matsim/src/test/java/org/matsim/core/mobsim/qsim/AbstractQSimModuleTest.java
Calls to `Controler.addOverridingModule` currently allow multiple overrides, i.e. I can override a certain binding, e.g. `@Named("car") TravelTime` with one overriding module, and then with another one:
```
controler.addOverridingModule(new FirstModule());
controler.addOverridingModule(new SecondModule());
```
For `Controler.addOverridingQSimModule` currently only the first override works. The second one will complain that a binding is already defined. 
This PR adds the same functionality for QSimModules, they can now be overridden multple times. This is useful, e.g. when overriding a DrtOptimizer with a ShiftDrtOptimizer and then with a AlgorithmXYZOptimizer and similar cases.
> Allow overriding QSimModule bindings multiple times

- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/fleet/DefaultShiftDvrpVehicle.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/fleet/DvrpVehicle.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/fleet/DvrpVehicleImpl.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/vrpagent/VrpAgentSource.java
- contribs/dvrp/src/main/java/org/matsim/contrib/evrp/EvDvrpVehicle.java
If a dvrp vehicle has a reference to a matsim vehicle (e.g. when dvrp vehicles are created from the standard matsim vehicle input), the type of that matsim vehicle will be used to create a mobsim vehicle for the corresponding dvrp agent. Otherwise, the default vehicle type (annotated with `@Named(DVRP_VEHICLE_TYPE)`) will be used (current approach).
> dvrp: use matsim vehicle from dvrp vehicle specification to create mobsim vehicle

- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/fleet/FleetModule.java
- examples/scenarios/dvrp-grid/multi_mode_one_shared_taxi_config.xml
It is always possible to override the `FleetSpecification` modal binding to change the way vehicles are created (so-called "option 3") regardless of whether option 1 or 2 is selected inside `FleetModule`.
> dvrp: always try to read dvrp vehicles from matsim vehicles if dvrp-specific vehicle input is not provided

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtAnalysisControlerListener.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtEventSequenceCollector.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtLeg.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtLegsAnalyser.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalWaitTimesAnalyzer.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/DrtRequestCreator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/events/DrtRequestSubmittedEvent.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/speedup/DrtSpeedUp.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/fare/DrtFareHandlerTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/speedup/DrtSpeedUpTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/util/DrtEventsReadersTest.java
This PR modifies some DRT analysis functionality:
- Analysis is corrected for prebooking cases (before waiting time was calculated from the DrtRequestSubmissionEvent to the PassengerPickupEvent, now it is calculated from the PersonDepartureEvent to the PassengerPickupEvent). The PersonDepartureEvent can either come after the DrtRequestSubmissionEvent (= prebooking) or before (= instant).
- Currently, analysis assumes that requests are either rejected or scheduled. Other optimizers may reject requests after they have initially been scheduled (which also happens in reality with ridesharing operators). This is now taken into account, a request that is rejected at any time is regarded as "rejected".
- So far, analysis plots only show the unsharedRideTime vs. actualRideTime with constraint …
> Some DRT analysis improvements

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DetourTimeEstimator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionProvider.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionSearchQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionProvider.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionSearchQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SingleInsertionDetourPathCalculator.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DetourTimeEstimatorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DrtPoolingParameterTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/SingleInsertionDetourPathCalculatorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/run/examples/RunDrtExampleIT.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/path/OneToManyPathCalculator.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/path/OneToManyPathSearch.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/path/VrpPaths.java
- contribs/dvrp/src/test/java/org/matsim/contrib/dvrp/path/OneToManyPathCalculatorTest.java
This PR replaces the deprecated last link TT calculation with an improved estimation method. This is a follow up to changes made in #1771.
> DVRP: improved last link travel time computation

- contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/events/DrtRequestSubmittedEvent.java
The newly added attribute (latestPickupTime and latestDropOffTime) will become "NaN" if it doesnt appear in the events file (i.e. for previous runs). Before this PR, reading events from previous runs will fail because of the missing attribute in the DRT Request submitted event.
> Make the DRT request submitted events compatible with previous runs (output events)

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtModeAnalysisModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/edrt/schedule/EDrtStopTask.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/eshifts/run/EvShiftDrtControlerCreator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/eshifts/schedule/EDrtShiftChangeoverTaskImpl.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/run/ShiftDrtControlerCreator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/schedule/ShiftBreakTaskImpl.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/schedule/ShiftChangeoverTaskImpl.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/schedule/DefaultDrtStopTask.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/schedule/DrtStayTask.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/schedule/DrtStopTask.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/schedule/DrtTaskFactoryImpl.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/util/DrtEventsReaders.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/VehicleDataEntryFactoryImplTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserterTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DetourDataTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionDetourTimeCalculatorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGeneratorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/KNearestInsertionsAtEndFilterTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/util/DrtEventsReadersTest.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetaxi/OneTaxiOptimizer.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetaxi/OneTaxiServeTask.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetruck/OneTruckOptimizer.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetruck/OneTruckServeTask.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/schedule/AbstractTask.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/schedule/DefaultStayTask.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/schedule/StayTask.java
- contribs/dvrp/src/main/java/org/matsim/contrib/evrp/ChargingTaskImpl.java
- contribs/dvrp/src/test/java/org/matsim/contrib/dvrp/vrpagent/VrpAgentLogicTest.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/schedule/TaxiPickupTask.java
- contribs/taxi/src/main/java/org/matsim/contrib/taxi/schedule/TaxiStayTask.java
To allow more flexibility when implementing custom tasks (incl. mixing two different task types into one). See: https://github.com/matsim-org/matsim-libs/pull/1788#issuecomment-991355810
> Extract StayTask and DrtStopTask interfaces

- matsim/pom.xml
... dependabot does not care of that.
> bump log4j-1.2-api to 2.16.0

- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/optimizer/ShiftRequestInsertionScheduler.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/optimizer/insertion/ShiftInsertionCostCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/CostCalculationStrategy.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultDrtInsertionSearch.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultInsertionCostCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserter.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DetourDataLogging.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DetourPathCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DetourPathData.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DetourPathDataCache.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionDetourTimeCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGenerator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionWithDetourData.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/KNearestInsertionsAtEndFilter.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/MultiInsertionDetourPathCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SingleInsertionDetourPathCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/DefaultRequestInsertionScheduler.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/BestInsertionFinderTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DefaultDrtInsertionSearchTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserterTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DetourPathDataCacheTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DetourPathDataTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionProviderTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionCostCalculatorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionDetourTimeCalculatorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGeneratorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/KNearestInsertionsAtEndFilterTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/MultiInsertionDetourPathCalculatorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionProviderTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/SingleInsertionDetourPathCalculatorTest.java
A round of refactoring around making insertion generation and evaluation simpler and faster (see #1758 for some background).
The next steps will be about moving `DetourTimeInfo` computation to insertion generation, which will enable different speedups like:
- early pruning on violated time constraint
- re-use of pickup detour time info while iterating through dropoff insertion points.
> Refactor insertion detour data

- contribs/av/src/main/java/org/matsim/contrib/av/flow/AvIncreasedCapacityModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetruck/OneTruckModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/fleet/FleetModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/DvrpModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/trafficmonitoring/QSimFreeSpeedTravelTimeWithMaxSpeedLimit.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/vrpagent/VrpAgentSourceQSimModule.java
- contribs/dvrp/src/test/java/org/matsim/contrib/dvrp/passenger/DefaultPassengerEngineTest.java
- contribs/dvrp/src/test/java/org/matsim/contrib/dvrp/router/DiversionTest.java
- contribs/vsp/src/test/java/playground/vsp/flowEfficiency/HierarchicalFLowEfficiencyCalculatorTest.java
Based on #1822 (thanks @nkuehnel). Takes a few more steps for a complete transition, otherwise some examples would still try to override the dvrp-global vehicle type, but that binding would be ignored now.
BTW. We want to support more than one vehicle type per mode in the future (e.g. AVs and non-AVs in one DRT fleet). This is something that should work fine with the selective insertion search (DRT), but we need to introduce a few not so big changes to make it possible.
> Dvrp modal vehicle type

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtLeg.java
Actually, the plots wait time plots were still not displayed properly for prebooked requests. Now they are correct.
> Fix analysis of departure time with prebooked requests

- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/optimizer/ShiftRequestInsertionScheduler.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/optimizer/insertion/ShiftInsertionCostCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/Waypoint.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/BestInsertionFinder.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultDrtInsertionSearch.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultInsertionCostCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserter.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionProvider.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionSearchQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionDetourTimeCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGenerator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionWithDetourData.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/KNearestInsertionsAtEndFilter.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionProvider.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionSearchQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/DefaultRequestInsertionScheduler.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/BestInsertionFinderTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/CostCalculationStrategyTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DefaultDrtInsertionSearchTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserterTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionProviderTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionCostCalculatorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionDetourTimeCalculatorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGeneratorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/KNearestInsertionsAtEndFilterTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionProviderTest.java
A next step after #1819: detour time info is now computed inside insertion generator. The next step will be speeding up the insertion generation and evaluation (including early pruning of insertions and reusing computed data mentioned in #1819).
> DRT: calc detour info inside insertion generator

- contribs/osm/src/main/java/org/matsim/contrib/osm/networkReader/SupersonicOsmNetworkReader.java
- contribs/osm/src/test/java/org/matsim/contrib/osm/networkReader/SupersonicOsmNetworkReaderTest.java
- contribs/sumo/src/main/java/org/matsim/contrib/sumo/SumoNetworkConverter.java
- matsim/src/main/java/org/matsim/core/network/NetworkUtils.java
this handles the osm-parser part of #1823 
To figure out HBEFA road types in the emission contrib we want the original max speed tag from osm in the network.
> Allowed speed tag

- contribs/sharing/src/main/java/org/matsim/contrib/sharing/routing/InteractionPoint.java
- contribs/sharing/src/main/java/org/matsim/contrib/sharing/routing/SharingRoutingModule.java
- contribs/sharing/src/main/java/org/matsim/contrib/sharing/service/SharingUtils.java
- contribs/sharing/src/test/java/org/matsim/contrib/sharing/RunIT.java
This PR ensures that routes that starts and ends at the same InteractionPoint are returned as null. It make no sense to use a sharing mode, insteade agent should walk.
> Fix check in SharingRoutingModule

- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/eshifts/dispatcher/EDrtShiftDispatcherImpl.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/eshifts/run/ShiftEDrtModeOptimizerQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/eshifts/scheduler/EShiftTaskScheduler.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/analysis/BreakCorridorXY.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/analysis/ShiftDurationXY.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/dispatcher/DrtShiftDispatcherImpl.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/io/DrtShiftsWriter.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/optimizer/ShiftRequestInsertionScheduler.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/run/ShiftDrtModeOptimizerQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/run/ShiftDrtQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/scheduler/ShiftTaskScheduler.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/shift/DrtShift.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/shift/DrtShiftImpl.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/shift/DrtShiftSpecification.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/shifts/shift/DrtShiftSpecificationImpl.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/extension/shifts/ShiftsIOTest.java
- contribs/drt/src/test/resources/test/input/org/matsim/contrib/drt/extension/shifts/testShifts.xml
- optional drt shift breaks
- make sure that wait for shift stay tasks are initialized before setup of the shift dispatchers
> Make drt shift breaks optional

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtAnalysisControlerListener.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtEventSequenceCollector.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtLeg.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtLegsAnalyser.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/speedup/DrtSpeedUpTest.java
For bigger scenarios, creation of scatter plots could take quite some time. In particular, the recently added "Maximum wait time" plot was taking a lot of time as often all samples (drt legs) have the same max wait time (X value).
> Speedup drt plot generation

- matsim/src/main/java/org/matsim/core/router/speedy/LeastCostPathTree.java
Like in other speedy routers, use raw times internally.
> use raw time internally in LeastCostPathTree

- contribs/accessibility/src/main/java/org/matsim/contrib/accessibility/osm/OsmPoiReader.java
This PR allows to change the supported CompressionMethod (i.e. gz, bz2 or none). Quite usefull in order to save HDD storage. The previous implementation accessed only plain xml. This PR is retrofit, because old method signiture is maintained by the help of a wrapping function.
Best,
Steffen
> OsmPoiReader: Make CompressionMethod exchangeable

- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtRouteCreator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
Hey, this is a proposal for a max absolute detour time for drt requests such that max travel time becomes min(unsharedRideTime + maxAbsoluteDetour, maxTravelTimeAlpha * unsharedRideTime + maxTravelTimeBeta)
By default, maxAbsoluteDetour is set to positive infinity and therefore ignored.
> Proposal for max absolute detour time for drt

- contribs/sbb-extensions/src/main/java/ch/sbb/matsim/analysis/skims/CalculateSkimMatrices.java
@mfitz and I found that the current (example) implementation of the CalculateSkimMatrices does not write the caluclated outputs. 
An example invocation using outputs from [Londinium](https://github.com/arup-group/londinium) :
```
java -cp target/jar-with-dependencies.jar ch.sbb.matsim.analysis.skims.CalculateSkimMatrices
/londinium/data/lsoas/Londinium_LSOA_2004_London_Low_Resolution.shp 
LSOA_CODE 
/londinium/matsim/output_facilities.xml 
/londinium/matsim/output_network.xml.gz 
/londinium/matsim/output_transitSchedule.xml.gz 
/londinium/matsim/output_events.xml.gz 
/londinium/matsim/skims/ 
1 
1 
"09:00;10:00" "09:00;10:00" 
car,pt
```
Before this change, the output was only the zone_cordinates generated:
```
zone_coordinates.csv
```
This is despite logging showing that pt and car …
> Enable the writing of pt and car skim results

- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/eshifts/scheduler/EShiftTaskScheduler.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingEventSequenceCollector.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingWithQueueingLogic.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/charging/QuitQueueAtChargerEvent.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/charging/QuitQueueAtChargerEventHandler.java
Hi,
in some of our scenarios vehicles may want to leave the queue at a charger without having started the charging activity. This can happen, for example, when it was initially planned to charge the vehicle during a driver shift break and the queueing time exceeds the break duration.
The ChargingWithQueueingLogic already allows to remove vehicles that are not yet plugged:
https://github.com/matsim-org/matsim-libs/blob/ff60f269b30dc6e57d170d259599880f25bc2685/contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingWithQueueingLogic.java#L94-L106
However, our simulations crashed because the ChargingEventSequenceCollector does not yet seem to be designed for this case. This is what happens:
1. a vehicle is queued at a charger -> the ChargingEventSequenceCollector takes note of the …
> Fix for allowing evs to leave charging queue

- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/trafficmonitoring/QSimFreeSpeedTravelTime.java
As pointed out by @tthunig, the time spent on moving over a node is equal to the time step duration.
> fix(dvrp): change move-over-node time from 1 s to 1 time step in QSimFreeSpeedTravelTime

- contribs/signals/src/main/java/org/matsim/contrib/signals/analysis/SignalEvents2ViaCSVWriter.java
- contribs/signals/src/main/java/org/matsim/contrib/signals/controller/fixedTime/DefaultPlanbasedSignalSystemController.java
* write signal events for via only in iterations when also usual matsim events are written
* remove log info that a new signal plan starts (comes to often and dominates the logfile)
--> save run time
> reduce output by signals contrib

- matsim/src/main/java/org/matsim/facilities/FacilitiesWriterV1.java
Before, facilities looked like this:
```xml
<facility id="100053726" x="683175.6732123105" y="5338987.57620341">
<activity type="leisure">
</activity>
<activity type="other">
</activity>		<attributes>
<attribute name="type" class="java.lang.String">park</attribute>
</attributes>
</facility>
```
Now they look like this:
```xml
<facility id="100053726" x="683175.6732123105" y="5338987.57620341">
<activity type="leisure">
</activity>
<activity type="other">
</activity>
<attributes>
<attribute name="type" class="java.lang.String">park</attribute>
</attributes>
</facility>
```
The same issue appeared with the attributes in the `facilities` tag.
Before:
```xml
<facilities name="city">	<attributes>
<attribute name="coordinateReferenceSystem" class="java.lang.String">EPSG:25832</attribute> …
```
> Fix formatting in FacilitiesWriterV1

- matsim/src/main/java/org/matsim/core/controler/PrepareForSimImpl.java
- matsim/src/main/java/org/matsim/core/population/algorithms/PersonPrepareForSim.java
- matsim/src/test/java/org/matsim/population/algorithms/PersonPrepareForSimTest.java
As already stated in the code I do not see why it should be necessary to use a filtered network for mode car for searching nearest links based on activities' locations. The routing module structure offers route search with filtered mode networks anyways. Moreover, the usage of a "carNetworkOnly" leads to error prone routing e.g. in scenarios with SuperBlocks (or any scenario with care removed as allowed mode on some links).
> Switch ActivityLinkSearch from carOnlyNetwork to multimodal network

- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/preplanned/optimizer/PreplannedDrtModeOptimizerQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/preplanned/optimizer/PreplannedDrtOptimizer.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/preplanned/run/MultiModePreplannedDrtModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/preplanned/run/PreplannedDrtControlerCreator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/preplanned/run/PreplannedDrtModeModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/preplanned/run/RunPreplannedDrtExample.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/extension/preplanned/optimizer/RunPreplannedDrtExampleIT.java
Vehicle schedules are computed before simulation is started (could be even outside matsim). Then matsim (simulation) replays the pre-computed vehicle schedules.
This is a first operational prototype. There are a few TODOs that need to be addressed.
`RunPreplannedDrtExampleIT` gives an idea how to set up such a simulation (there are no assertions yet)
> prototype for simulating pre-planned DRT services

- matsim/src/main/java/org/matsim/facilities/FacilitiesReaderMatsimV2.java
- matsim/src/main/java/org/matsim/facilities/FacilitiesWriter.java
- matsim/src/main/java/org/matsim/facilities/FacilitiesWriterV2.java
- matsim/src/main/java/org/matsim/facilities/MatsimFacilitiesReader.java
- matsim/src/main/resources/dtd/facilities_v2.dtd
- matsim/src/test/java/org/matsim/facilities/FacilitiesParserWriterTest.java
- matsim/src/test/java/org/matsim/facilities/FacilitiesWriterTest.java
- matsim/src/test/java/org/matsim/facilities/MatsimFacilitiesReaderTest.java
This change adds support for reading and writing the z-component from/to `Coord`s in facilities files. 
Currently, nodes in networks and activities in plans support reading and writing of 3D-coordinates, but facilities do not. During runtime, it is possible to create an `ActivityFacility` with a 3D-coordinate, but once written to and read from a file, this component of the coordinate is currently lost.
This change adds
- `facilities_v2.dtd`
- `FacilitiesReaderMatsimV2`
- `FacilitiesWriterV2`
based on the corresponding *V1 files with a bit code added to support the third coordinate component.
> Enable reading and writing of 3D coordinates in facilities files

- contribs/sbb-extensions/src/main/java/ch/sbb/matsim/RunSBBExtension.java
- contribs/sbb-extensions/src/main/java/ch/sbb/matsim/mobsim/qsim/pt/SBBTransitEngineQSimModule.java
- contribs/sbb-extensions/src/test/java/ch/sbb/matsim/mobsim/qsim/SBBQSimModuleTest.java
- contribs/sbb-extensions/src/test/java/ch/sbb/matsim/mobsim/qsim/pt/SBBTransitQSimEngineIntegrationTest.java
- contribs/sbb-extensions/src/test/java/ch/sbb/matsim/mobsim/qsim/pt/SBBTransitQSimEngineTest.java
Changed the SBBTransitEngineQSimModule in order to implements QSimComponentsConfigurator. SBBTransitEngineQSimModule has been used till now as an QSimComponentsConfigurator but never implemeted the specified interface correctly.
> Add QSimComponentsConfigurator to SBBTransitEngineQSimModule

- contribs/shared_mobility/pom.xml
- contribs/shared_mobility/src/main/java/org/matsim/contrib/shared_mobility/analysis/SharingAnalysisModule.java
- contribs/shared_mobility/src/main/java/org/matsim/contrib/shared_mobility/analysis/SharingVehicleStatusTimeProfileCollectorProvider.java
- contribs/shared_mobility/src/main/java/org/matsim/contrib/shared_mobility/analysis/VehicleStateCollector.java
- contribs/shared_mobility/src/main/java/org/matsim/contrib/shared_mobility/analysis/VehicleStateCollectorImpl.java
- contribs/shared_mobility/src/main/java/org/matsim/contrib/shared_mobility/logic/SharingLogic.java
- contribs/shared_mobility/src/main/java/org/matsim/contrib/shared_mobility/run/SharingServiceModule.java
- contribs/shared_mobility/src/main/java/org/matsim/contrib/shared_mobility/service/SharingUtils.java
- contribs/shared_mobility/src/main/java/org/matsim/contrib/shared_mobility/service/events/AbstractSharingEvent.java
- contribs/shared_mobility/src/main/java/org/matsim/contrib/shared_mobility/service/events/SharingDropoffEvent.java
- contribs/shared_mobility/src/main/java/org/matsim/contrib/shared_mobility/service/events/SharingFailedDropoffEvent.java
- contribs/shared_mobility/src/main/java/org/matsim/contrib/shared_mobility/service/events/SharingFailedPickupEvent.java
- contribs/shared_mobility/src/main/java/org/matsim/contrib/shared_mobility/service/events/SharingPickupEvent.java
- contribs/shared_mobility/src/main/java/org/matsim/contrib/shared_mobility/service/events/SharingReservingEvent.java
- contribs/shared_mobility/src/main/java/org/matsim/contrib/shared_mobility/service/events/SharingReservingEventHandler.java
Similar to DRT, this PR adds time profiles for vehicle states. The states of shared vehicles are idle, reserved and booked.
> Introduce state profiles for shared mobility

- contribs/drt/src/main/java/org/matsim/contrib/drt/extension/preplanned/optimizer/PreplannedDrtOptimizer.java
- remove times from PreplannedRequest `equals()`
There may be differences between the time info in the initially planned requests and the actually submitted ones,
as there may be differences between planned legs and their actual execution in a mobsim.
- delay preplanned stop task so it starts after actual request arrives
The drt departure (-> request submission) should always happen before the corresponding stop task starts.
Therefore, the beginning of the pre-planned stop task is delayed by 1 second (~time step) so we avoid race conditions.
> preplanned drt optimizer: adapt for cases with access/egress walks

- contribs/application/src/main/java/org/matsim/application/MATSimAppCommand.java
- contribs/application/src/main/java/org/matsim/application/MATSimApplication.java
- contribs/application/src/test/java/org/matsim/application/MATSimApplicationTest.java
- contribs/application/src/test/java/org/matsim/application/TestCommand.java
This PR adds the possibility to overwrite a `preparePostProcessing` method in a `MATSimApplication`.
This method may return a list of `MATSimAppCommand` instances that will be run automatically after the simulation has finished.
> Post-process option MATSim Application

- contribs/commercialTrafficApplications/src/main/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/DefaultCommercialJobGenerator.java
Some scenarios might work with activities that reference to facilities and thus have no linkId. Instead, the facility provides the required linkId. This PR makes use from the PopulationUtils.decideOnLink method in order to handle those situations.
> Make DefaultCommercialJobGenerator run with facility linkId

- contribs/application/pom.xml
This is a new dependency added in #1952. However, #1952 was created from 14.0-SNAPSHOT (before 14.0 was released) but merged into 15.0-SNAPSHOT (after 14.0 was released), so it couldn't get bumped automatically.
This may be the reason why http://ci.matsim.org:8080/job/MATSim_GitHub/6502/ (ran for origin/master) failed. Let's see if it's resolved now.
> fix(application): bump freight to 15.0-SNAPSHOT

- matsim/src/test/java/org/matsim/core/mobsim/qsim/QSimEventsIntegrationTest.java
1. QSim did not reach the point at which our expected exception is thrown (due to a missing vehicle) and threw a different RuntimeException.
- Fixed the test (by adding the missing vehicle).
- Added assertions for specific error messages to make sure we only accept the expected exceptions.
2. Reduce the number of iterations, so we do not hit the timeout when executing on Jenkins, like here:
- http://ci.matsim.org:8080/job/MATSim_M2/5959/
- http://ci.matsim.org:8080/job/MATSim_M2/5954/
> Fix QSim events integration tests

- matsim/src/main/java/org/matsim/core/events/ParallelEventsManagerImpl.java
- matsim/src/test/java/org/matsim/core/mobsim/qsim/QSimEventsIntegrationTest.java
Similar to #1958 (commit 4c365390bb17b884e7364b065c9c4b610d38bda7), but this time it improves event handling in `ParallelEventsManagerImpl` (the previous PR did that for `SimStepParallelEventsManagerImpl`).
> core: propagate original exception cause in ParallelEventsManagerImpl

- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/MultiModeDrtConfigGroup.java
One of several changes in #1937 is adding `DrtShiftsParams` to `DrtConfigGroup`.
I would like to avoid doing that:
- Since this param set is used in the shifts extension, this change introduces a reverse dependency (standard drt depends on drt extensions). As a result, changes to this extension (incl. removal of it) may potentially impact the standard drt implementation.
- Following this change, we might also want to add param sets of other extensions to the drt config, which would result in `DrtConfigGroup` becoming bigger and bigger (and more fragile).
This PR a generic approach for making the drt config extendable/customisable:
- make `DrtConfigGroup` non-final (to allow extending it)
- add `Supplier<DrtConfigGroup>` to `MultiModeDrtConfigGroup` so we can instantiate any custom drt …
> drt: make DrtConfigGroup extendable/customisable

- contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierCapabilities.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierPlanXmlWriterV2.java
This pull request relates to issue #1987. It is not a “fix” because it (still) does not support the spirit of `FleetSize.INFINITE`. This pull request just makes more methods deprecated (for now) so that the code can be cleared as to what happens.
> VehicleType in CarrierCapabilities

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/VehicleDataEntryFactoryImpl.java
This bug only impacted cases when the fleet was varying over time. However, in most of our scenarios, we usually have a fixed fleet available from the beginning till the end of simulation.
> drt: fix lookAhead in creating VehicleEntries when no rejections due to max wait time

- contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/DefaultRequestInsertionScheduler.java
Temporarily disable the check to not block anyone on this issue:
See: https://github.com/matsim-org/matsim-libs/commit/a0b54682eeebc65daadea24051313537be322487#commitcomment-73594532
@luchengqi7 @diallitoz
> drt: (temp) disable time consistency check: insertion data vs scheduler

- matsim/pom.xml
versions 7.0.3 and 7.0.4 have issues with processing java records during compilation
> downgrade hibernate-validator to 7.0.2.Final

- .github/workflows/verify-push.yaml
Currently, it is 6 hours (default value). Given that we have 41 jobs and only 20 can be run at the same time, we can block all other workflows for up to 12 hours with just one git push.
After this change, this will be reduced to 1.5 hours (the worst case).
> ci: set timeout to 45 min per job in verify-push

- contribs/emissions/src/main/java/org/matsim/contrib/emissions/ColdEmissionAnalysisModule.java
A hard-to-debug NullPointerExcerption is handled with a better error message if the HbefaSizeClass is not set,. This relates to issue #1514.
> Error message

- .github/dependabot.yml
So dependabot will check for upgrades of github actions.
> deps: add github-actions ecosystem to dependabot

- .github/workflows/deploy-on-pr-merge.yaml
- .github/workflows/deploy-on-release-created.yaml
- .github/workflows/verify-push.yaml
Re setup-java: Since it uses actions/cache under hood for caching dependencies, we can skip a separate actions/cache step.
> Bump GitHub actions

- .github/workflows/code-coverage.yaml
The report is created by jacoco and then uploaded to CodeCov.
For testing purposes, the workflow is triggered on pushing to master. Later on we will switch to a weekly schedule.
> build: introduce weekly code coverage for matsim core

- .github/workflows/code-coverage.yaml
After confirming that the code-coverage workflow works fine, we can change the trigger so it is run weekly (Sun 3:30 UTC).
> build: run code-coverage weekly

- .github/workflows/deploy-weekly.yaml
To test this workflow, we run it on push to master and without the actual deployment.
This will be changed in the next commit.
> build: add workflow for weekly builds

- .github/workflows/deploy-weekly.yaml
Weekly builds will be triggered every Mon 0:30 UTC.
Before merging this one, I am going to disable the corresponding build pipeline on Jenkins http://ci.matsim.org:8080/view/All/job/Weekly%20Builds/ so we avoid deployment conflicts.
> build: trigger deploy-weekly each Mon

- matsim/src/main/java/org/matsim/analysis/PHbyModeCalculator.java
the travel-times in seconds got divided by 1000 instead of 3600 to get the value in hours.
> bugfix: ph_modestats.png showed wrong values

- pom.xml
It's been over 8 months now since Java 17 was released. Our code runs smooth on JDK 17, different tools, IDEs etc. already fully supports Java 17, and it's an LTS release. Lots of arguments for migrating to Java 17.
This is a draft PR so that we can discuss before we make the final decision.
> migrate from Java 11 to 17

- matsim/src/main/java/org/matsim/core/controler/PrepareForSimImpl.java
- matsim/src/main/java/org/matsim/core/population/algorithms/PersonPrepareForSim.java
- matsim/src/test/java/org/matsim/population/algorithms/PersonPrepareForSimTest.java
Reverting https://github.com/matsim-org/matsim-libs/pull/1917
This introduced incorrect assignments of agents, the intended functionality was implemented in a different PR and this one can now be reversed.
> Revert changes from PR1917

- matsim/src/main/java/org/matsim/core/controler/PrepareForSimImpl.java
- matsim/src/main/java/org/matsim/core/population/algorithms/PersonPrepareForSim.java
- matsim/src/test/java/org/matsim/population/algorithms/PersonPrepareForSimTest.java
* reverse changes from PR1917 because we do need carOnlyNetwork here
* incorrect placement of networkFilter caused PersonPrepareForSimTest.testRun_MultimodalNetwork to fail
Co-authored-by: simei94 <simonmeinhardt94@gmail.com>
(cherry picked from commit 1e43b2948f9c23a6c20e93ed38052ae139fe1537)
> Revert changes from PR1917 (#2080)

- matsim/pom.xml
- pom.xml
The same logging should be used across all modules (contribs). To make sure the same version is used everywhere, we need to have it as a direct dependency (instead of transitive).
> build(deps): move log4j deps from matsim to matsim-all pom.xml

- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/preplanned/optimizer/PreplannedDrtOptimizer.java
- contribs/drt-extensions/src/test/java/org/matsim/contrib/drt/extension/preplanned/optimizer/RunPreplannedDrtExampleIT.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/RequestQueue.java
- use records for fixed data classes
- introduce `PreplannedRequestKey` to better express how pre-planned requests are referenced/identified
> Refactor preplanned drt optimizer

- contribs/application/src/main/java/org/matsim/application/analysis/population/SubTourAnalysis.java
- contribs/application/src/main/java/org/matsim/application/prepare/population/FixSubtourModes.java
- matsim/src/main/java/org/matsim/core/config/groups/SubtourModeChoiceConfigGroup.java
- matsim/src/main/java/org/matsim/core/population/algorithms/ChooseRandomLegModeForSubtour.java
- matsim/src/main/java/org/matsim/core/replanning/choosers/ForceInnovationStrategyChooser.java
- matsim/src/main/java/org/matsim/core/replanning/modules/SubtourModeChoice.java
- matsim/src/main/java/org/matsim/core/router/TripStructureUtils.java
- matsim/src/test/java/org/matsim/core/router/TripStructureUtilsTest.java
Before this PR, subtours are determined by either location id or link id of activities.
This PR adds the option to also consider the coordinates of activities. 
Coordinates are matched by their distance, which enables to allow a little more fuzzy definition of a subtour.
This can be configured with a new setting `coordDistance` in the `SubtourModeChoiceConfigGroup`.
> Allow Subtours to use coordinates of activities

- contribs/drt/src/main/java/org/matsim/contrib/drt/fare/DrtFareHandler.java
Preferably use this method when implementing your own `DrtFareHandler`.
> drt: add util method for creating standardised money events (drt fare)

- contribs/emissions/src/main/java/org/matsim/contrib/emissions/analysis/EmissionsOnLinkEventHandler.java
- contribs/emissions/src/test/java/org/matsim/contrib/emissions/analysis/EmissionsOnLinkEventHandlerTest.java
We frequently require summed emissions per link-id to perform emissions analysis (generating `*.output_events.xml.gz`). In particular, the data structure `link2pollutants` calculates this for us. However, the code to produce `link2pollutants` is duplicated each time we do emission analysis for a different project.
In this commit the `link2pollutants` Map is generated by `EmissionsOnLinkHandler` and can be called by:
```
EmissionsOnLinkEventHandler handler = new EmissionsOnLinkEventHandler(10); 
handler.handleEvent(event);
handler.getLink2pollutants();
```
The required parameter `timeBinSizeInSeconds` (=10 in example) is for generating a similar data structure, but groups link emissions by time bins.
The class `EmissionsOnLinkHandlerTest` has been updated to include cases for testing the …
> include link2pollutants in emissions contrib

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/VehicleDataEntryFactoryImpl.java
With this update, the schedule of a DVRP can end with different types of task. 
This is necessary when we want to have partial DVRP schedule during the day. By not computing the full schedule whenever the schedule gets update, we can save some computational workload. This can also be helpful for customize DRT optimizer.
> Enable tasks other than Stay task at the end of DVRP schedule

- contribs/vsp/src/test/java/playground/vsp/ev/CreateUrbanEVTestScenario.java
- contribs/vsp/src/test/java/playground/vsp/ev/FinalSoc2VehicleTypeTest.java
Since #2111 the AppVeyor build (sometimes) fails. The reason could be that static field variables in `FinalSoc2VehicleTypeTest` are not final. While the test design is rather bad in the first place, this PR is an attempt for a hot fix for that by making the static field variables final. The functionality the test is for, is actually something that, in my opinion, could be moved forward to the ev contrib. In a separate PR, i will adress that. This way, we could get rid of the `FinalSoc2VehicleTypeTest` (design)
> Hot fix attempt: fix AppVeyor build

- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/router/DvrpRoutingModule.java
- contribs/dvrp/src/test/java/org/matsim/contrib/dvrp/router/RoutingTimeStructureTest.java
Previously we assumed 1 second for switching between leg and activity.
This is not the case for zero-duration activities. They are concluded immediately.
This commit fixes: #2112
> dvrp: fix routing module - execution of drt stage activity takes 0 seconds

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/VehicleDataEntryFactoryImpl.java
Now, we also want to include the "WaitForStopTask" in this loop. I think it makes sense to use the superclass DefaultStayTask when doing the casting, such that we can also accept custom tasks that are based on task type STAY.
> Accept custom task based on DefaultStayTask

- contribs/application/pom.xml
- contribs/application/src/main/java/org/matsim/application/analysis/travelTimeValidation/TravelTimePatterns.java
- contribs/application/src/main/java/org/matsim/application/prepare/network/CreateNetworkFromSumo.java
- contribs/application/src/main/java/org/matsim/application/prepare/pt/CreateTransitScheduleFromGtfs.java
- contribs/sumo/src/main/java/org/matsim/contrib/sumo/SumoNetworkConverter.java
* added CLI option for the SUMO converter to configure the free flow speed adjustment for urban links
* fix default prefix values for the gtfs converter command
* add allowed free speed to network generated from travel time api
> Free speed flow factor configurable from CLI

- matsim/src/main/java/org/matsim/core/scenario/ScenarioUtils.java
The `loadScenario` methods in `ScenarioUtils` load a scenario with all its containers (population, network, ...) from a config. However, it is not possible to supply [`AttributeConverter`](https://github.com/matsim-org/matsim-libs/blob/master/matsim/src/main/java/org/matsim/utils/objectattributes/AttributeConverter.java)s to be used during that process.
This change overloads the `loadScenario` methods with a map of `AttributeConverter` as additional argument, such that they will be used by the (private) [`ScenarioLoaderImpl`](https://github.com/matsim-org/matsim-libs/blob/master/matsim/src/main/java/org/matsim/core/scenario/ScenarioLoaderImpl.java) when loading the content of the containers.
> Allow loading of Scenario with AttributeConverters

- matsim/src/main/java/org/matsim/core/scenario/ScenarioLoaderImpl.java
Currently, the method `ScenarioLoaderImpl.loadHouseholds()` is not using the `AttributeConverter`s although other MATSim containers like population and network use them. This change also adds the supplied `AttributeConverter`s to the HouseholdsReader object before parsing the households file.
> Also add AttributeConverters to HouseholdsReader in ScenarioLoaderImpl

- matsim/src/main/java/org/matsim/core/network/algorithms/SubsequentLinksAnalyzer.java
- matsim/src/main/java/org/matsim/core/population/routes/CompressedNetworkRouteImpl.java
- matsim/src/test/java/org/matsim/core/population/routes/CompressedNetworkRouteTest.java
CompressedNetworkRoutes had a problem with routes containing loops (routes passing a node multiple times). This wasn't an issue when compressed network routes were originally developed for car traffic only, as it couldn't happen there, but now with public transport routes, such loops are possible.
> some bugfixes and improvements for CompressedNetworkRoutes

- contribs/freight/pom.xml
- pom.xml
log4j 1.x has been declared EOL and the slf4j authors strongly encourage to use slf4j-reload4j binding (instead of slf4j-log4j12).
Reload4j is a drop-in replacement for log4j version 1.2.7.
For more info see: https://www.slf4j.org/manual.html#swapping
> freight: switch to slf4j-reload4j and bump to 2.0.0

- contribs/freight/pom.xml
- pom.xml
At the same time, we have to downgrade slf4j-api to 1.7.36 (as 1.8+ is not yet supported by log4j-slf4j-impl)
> freight: switch from slf4j-reload4j (log4j 1.2) to log4j-slf4j-impl (log4j 2)

- contribs/freight/src/main/java/org/matsim/contrib/freight/controler/CarrierAgent.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/controler/CarrierAgentTracker.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/controler/CarrierDriverAgent.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/events/FreightEventCreator.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/events/FreightServiceEndEventCreator.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/events/FreightServiceStartEventCreator.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/events/FreightShipmentDeliveryEndEventCreator.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/events/FreightShipmentDeliveryStartEventCreator.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/events/FreightShipmentPickupEndEventCreator.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/events/FreightShipmentPickupStartEventCreator.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/events/FreightTourEndEventCreator.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/events/FreightTourStartEventCreator.java
... instead of the vehicleIds from the (carrier) tours. - They were neither unique nor consistent with the vehicleIds available in the mobsim
Now, the vehicleIds should be unique AND consistent to the MATSim (all)Vehicles container and the other vehicle-based events.
> freight: Use the vehicleId from the mobsim in freightEvents

- contribs/application/src/main/java/org/matsim/application/MATSimApplication.java
This PR provides only a minor change but allows to exchange the way how a scenario is loaded for the MATSimApplication. There is now a exchangeable createScenario(Config config) that is pre-configured with the orignal default behavior. However, this likewise protected method could be overridden and thus allows to load a scenario with attribute converters, which might be mandatory for some users (see #2148 from @marecabo).
> MATSimApplication with other loadScenario signatures

- contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierPlanWriter.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierPlanXmlParserV2_1.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierPlanXmlReader.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierPlanXmlWriterV2_1.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierVehicleTypeReader.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/Tour.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/controler/CarrierDriverAgent.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/events/FreightEventAttributes.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/events/FreightTourEndEvent.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/events/FreightTourEndEventCreator.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/events/FreightTourStartEvent.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/events/FreightTourStartEventCreator.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/jsprit/MatsimJspritFactory.java
- matsim/src/main/resources/dtd/carriersDefinitions_v2.1.xsd
With this PR, an `Id` for the carrier `Tour`s is added.
Now, we are able to identify specific tours of a carrier. It is done in a more or less stupid way: Using an int and increase it by one. 
- Since this is a minor change of the CarrierFileDefinition, I also provide an updated version (v2.1) including the corresponding Reader/Writer.
- The new `tourId` is also integrated to the FreightEvents. -> This is already used in [matsim-vsp/logistics](https://github.com/matsim-vsp/logistics)
The new Reader/Writer will need some junit testing. This will be added later -> I create an Issue for it.
> Freight introduce tour Ids

- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/DvrpConfigGroup.java
- matsim/src/main/java/org/matsim/core/config/ReflectiveConfigGroup.java
- matsim/src/test/java/org/matsim/core/config/ReflectiveConfigGroupTest.java
I noticed that we frequently use lists/sets of strings as parameters in config group. Now we can also handle them without (de)serialising from/to String.
A few notes on this feature:
- it helped simplifying `DvrpConfigGroup` in this commit: 13568f6456c42c6d01da5fb302fa5be263f03112
- it can be used not only with `Parameter`s (as in linked commit), but also with `StringGetter`s/`StringSetter`s:
```java
@StringGetter(NETWORK_MODES)
public Set<String> getNetworkModes() {
return networkModes;
}
@StringSetter(NETWORK_MODES)
public void setNetworkModes(Set<String> networkModes) {
this.networkModes = networkModes;
}
```
- it works with parameters of exactly these two types: `List<String>` and `Set<String>`. For example, it will not work with:
- `Collection<String>` (no information if this is a …
> Support string list/set in reflective config group

- matsim/src/main/java/org/matsim/core/network/NetworkImpl.java
The `SearchableNetwork` interface exposes the internal quad tree via `getQuadTree`. However, the quad tree is only initialized on demand. This leads to situations where `getQuadTree` returns null values. 
This pr checks for this case and builds the quad tree in case it was not initialized yet.
> Build quad trees in getters in case it is still null

- contribs/application/src/main/java/org/matsim/application/analysis/population/SubTourAnalysis.java
- matsim/src/main/java/org/matsim/core/population/algorithms/ChooseRandomLegModeForSubtour.java
Subtour mode choice filters candidates that have the same mode, but it did only check the first trip. The new behaviour will check all trips of the subtour and only filter if all are equal.
> Fix for subtour modechoice to make sure no useful candidates are not filtered

- matsim/src/main/java/org/matsim/vehicles/VehicleType.java
This change makes `VehicleType` also implement `Identifiable<VehicleType>`.
I was surprised to see, that `VehicleType` does not implement `Identifiable<VehicleType>` despite it having a `getId()` method and despite its id being used regularily. Let me know if this was deliberate.
> VehicleType should implement Identifiable<VehicleType>

- matsim/src/main/java/org/matsim/core/config/ReflectiveConfigGroup.java
- matsim/src/test/java/org/matsim/core/config/ReflectiveConfigGroupTest.java
- matsim/test/input/org/matsim/core/config/ReflectiveConfigGroupTest/testReadCollectionsIncludingEmptyString/config_with_blank_comma_separated_elements.xml
In response to https://github.com/matsim-org/matsim-libs/issues/2225
(De)serialisation rules:
- "null" (string) <-> `null` (pointer)
- blank string <-> empty collection
- blank element in a comma separated string - thrown exception during deserialisation
- blank element in a collection - thrown exception during serialisation
> core: disallow blank strings as elements of collections in config parameters

- matsim/src/main/java/org/matsim/core/config/ReflectiveConfigGroup.java
- matsim/src/test/java/org/matsim/core/config/ReflectiveConfigGroupTest.java
The issue was revealed by this failing build: https://ci.appveyor.com/project/michalmac/matsim-libs/builds/45047502
> core: ensure deterministic iteration order over set deserialised in ReflectiveConfigGroup

- contribs/freight/src/main/java/org/matsim/contrib/freight/controler/CarrierControlerListener.java
I need the `CarrierControlerListener` in the logistics project (upcoming contrib) and the current `LSP` design makes this necessary. (see https://github.com/matsim-vsp/logistics/pull/51)
Background: The `LSP` should take the scores of its `Carrier`(s) to generate its own (consistent) score. Therefore the carriers need to get scored. This is currently triggered by the `CarrierControlerListener,` which I now added to the `LSPModule.` To do that, it needs to be public :(
> Freight: Make CarrierControlerListener public

- examples/scenarios/freight-chessboard-9x9/singleCarrierFiveActivitiesWithoutRoutes_Shipments.xml
The other example files are all `Service` based.
Here is one, which contains `Shipment`s instead.
> Freight: Add an example file of a Carrier with Shipments

- contribs/application/src/main/java/org/matsim/application/MATSimApplication.java
This PR fixes a wrong handling of the iterations argument of a MATSimApplication. Without this fix and a given iterations argument, there would be always one iteration too less.
> Fix wrong iteration handling for MATSimApplication

- matsim/src/test/java/org/matsim/core/mobsim/qsim/qnetsimengine/QSimComponentsTest.java
The failures occurred on AppVeyor:
https://ci.appveyor.com/project/michalmac/matsim-libs/builds/45276082
https://ci.appveyor.com/project/michalmac/matsim-libs/builds/45299870
> core: fix QSimComponentsTest failing on Windows

- matsim/src/test/java/org/matsim/core/router/PseudoTransitRoutingModuleTest.java
Hopefully, the last fix as this is green on a non-master branch: https://ci.appveyor.com/project/michalmac/matsim-libs/builds/45315314
> core: fix PseudoTransitRoutingModuleTest failing on AppVeyor

- contribs/application/src/main/java/org/matsim/application/MATSimApplication.java
This change allows to customize the list of config groups that are changeable via the `CommandLine` class in custom classes that extend `MatsimApplication`.
This change is related to #2279 and is an effort in making the powerful config-changing-functionality of the `CommandLine` a bit more customizable when used in custom subclasses of `MATSimApplication`.
> Allow to override MATSimApplication.getConfigurableModules in subclasses

- matsim/src/main/java/org/matsim/core/config/CommandLine.java
- matsim/src/test/java/org/matsim/core/config/CommandLineTest.java
This change allows to change a parameter value in _all_ parameter sets of a specific type using the `CommandLine` class.
Currently, a value in a parameter set could be changed with the following command line arguments:
```bash
--config:planCalcScore.scoringParameters[performing=6.0].lateArrival=18
--config:planCalcScore.scoringParameters[performing=6.0].activityParams[activityType=dummy].priority=2.0
```
This change allows to set a parameter value (e.g., the `priority` value) for _all_ `activityParams` parameter sets like this:
```bash
--config:planCalcScore.scoringParameters[performing=6.0].activityParams[*=*].priority=2.0
```
This additional behavior is also helpful to set values in a parameter set whose type only appears _once_ in a config group. In that case, one does not need to know …
> Allow for changing parameter values in all parameter sets from command line

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/extensive/DetourPathDataCache.java
Proposal to make DetourPathDataCache reusable by making it public final
We are currently in the midst of implementing an alternative insertion heuristic and would like to re-use this class
> drt: make DetourPathDataCache reusable by making it public final

- contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/Battery.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ConvertInitialChargeToInitialSoc.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ElectricFleetModule.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ElectricVehicleSpecificationImpl.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ElectricVehicleSpecifications.java
- contribs/ev/src/test/java/org/matsim/contrib/ev/charging/FastThenSlowChargingTest.java
- contribs/ev/src/test/java/org/matsim/contrib/ev/charging/VariableSpeedChargingTest.java
- contribs/ev/test/input/org/matsim/contrib/ev/example/RunEvExample/evehicles.xml
- contribs/vsp/src/main/java/playground/vsp/ev/EVUtils.java
- contribs/vsp/src/main/java/playground/vsp/ev/RunUrbanEVExample.java
- contribs/vsp/src/main/java/playground/vsp/ev/UrbanEVTripsPlanner.java
- contribs/vsp/src/test/java/playground/vsp/ev/TransferFinalSocToNextIterTest.java
- examples/scenarios/dvrp-grid/one_etaxi_evehicles.xml
- examples/scenarios/holzkirchen/holzkirchenElectricFleet.xml
- examples/scenarios/mielec/etaxis-25.xml
- examples/scenarios/mielec/evehicles-10.xml
- examples/scenarios/mielec/evehicles-20.xml
As discussed in #2222, we want to define `initialSoc` instead of `initialEnergyInKWh`. This PR adapts both code and input files.
The input files were converted using `ConvertInitialChargeToInitialSoc`. Please use it for converting external input files (residing outside this repo).
> EV: migrate from initial charge to initial SOC in electric vehicle attributes

- contribs/application/src/main/java/org/matsim/application/MATSimApplication.java
- contribs/application/src/main/java/org/matsim/application/analysis/emissions/AirPollutionByVehicleCategory.java
- contribs/application/src/main/java/org/matsim/application/commands/ShowGUI.java
- contribs/emissions/src/main/java/org/matsim/contrib/emissions/ColdEmissionAnalysisModule.java
- contribs/emissions/src/main/java/org/matsim/contrib/emissions/ColdEmissionHandler.java
- contribs/emissions/src/main/java/org/matsim/contrib/emissions/EmissionModule.java
- contribs/emissions/src/main/java/org/matsim/contrib/emissions/WarmEmissionAnalysisModule.java
- contribs/emissions/src/main/java/org/matsim/contrib/emissions/example/CreateEmissionConfig.java
- contribs/emissions/src/main/java/org/matsim/contrib/emissions/utils/EmissionsConfigGroup.java
- contribs/emissions/src/test/java/org/matsim/contrib/emissions/TestColdEmissionsFallbackBehaviour.java
- contribs/emissions/src/test/java/org/matsim/contrib/emissions/TestWarmEmissionsFallbackBehaviour.java
- examples/scenarios/emissions-sampleScenario/testv2_Vehv1/config_average.xml
- examples/scenarios/emissions-sampleScenario/testv2_Vehv1/config_detailed.xml
- examples/scenarios/emissions-sampleScenario/testv2_Vehv2/config_average.xml
- examples/scenarios/emissions-sampleScenario/testv2_Vehv2/config_detailed.xml
- matsim/src/main/java/org/matsim/vehicles/VehicleUtils.java
mostly removing material that has been deprecated for many years
this may hick up, since it also changes material in matsim-examples: some config switches now do not exist any more and thus had to be removed from config files there.
> Emissions maintenance

- contribs/application/src/main/java/org/matsim/application/MATSimApplication.java
In a recent PR, some fields were renamed in the application contrib. 
One line was overseen, which makes sure the default value is set to the field.
> Fix renames in application contrib

- contribs/vsp/src/main/java/playground/vsp/simpleParkingCostHandler/ParkingCostHandler.java
* residential parking costs basically had no effects, as agents only paid them exaclte once, i.e. the memory set `hasAlreadyPaidDailyResidentialParkingCosts` was not cleared/initialized after each iteration
* distinguish residential and non-residential parking per `purpose` in the `PersonMoneyEvent`
* set `PersonMoneyEvent.reference` to corresponding link id
> Bug fix in ParkingCostHandler

- contribs/parking/README.md
- contribs/parking/src/main/java/org/matsim/contrib/parking/package-info.java
- contribs/parking/src/main/java/org/matsim/contrib/parking/parkingcost/RunParkingCostExample.java
- contribs/parking/src/main/java/org/matsim/contrib/parking/parkingcost/config/ParkingCostConfigGroup.java
- contribs/parking/src/main/java/org/matsim/contrib/parking/parkingcost/eventhandling/MainModeParkingCostVehicleTracker.java
- contribs/parking/src/main/java/org/matsim/contrib/parking/parkingcost/eventhandling/TeleportedModeParkingCostTracker.java
- contribs/parking/src/main/java/org/matsim/contrib/parking/parkingcost/module/ParkingCostModule.java
- contribs/parking/src/main/resources/parkingcosts/config.xml
- contribs/parking/src/test/java/org/matsim/contrib/parking/parkingcost/eventhandling/ParkingCostVehicleTrackerTest.java
- contribs/parking/src/test/java/org/matsim/contrib/parking/parkingcost/eventhandling/RideParkingCostTrackerTest.java
- contribs/parking/src/test/java/org/matsim/contrib/parking/parkingcost/eventhandling/RunParkingCostsExampleTest.java
- matsim/src/main/java/org/matsim/api/core/v01/events/PersonMoneyEvent.java
This PR adds the functionality to easily charge parking costs depending on link attributes. Both network and (pseudo)-teleported modes can be accessed.
Parking Charges are a major factor in mode choice - we have been using this code internally a long time and think it might be useful for others too. 
Effects of parking charges will depend on the handling of money events in the MATSim Scoring process.
> Add parking costs

- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/fiss/FISS.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/fiss/FISSConfigGroup.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/fiss/FISSQSimModule.java
- contribs/drt-extensions/src/test/java/org/matsim/contrib/drt/extension/fiss/RunFissDrtScenarioIT.java
This PR adds a config switch that disables FISS in the last iteration in order to generate events from all agents (even all car driving agents). This feature might be required for post processing analysis which requires all link enter and leave events to be available.
> Add switch off for FISS in the last iteration

- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtStopFacilityImpl.java
This can otherwise lead to confusing crashes :)
> Require linkId to be defined in DRT Stop Definitions

- contribs/freight/src/main/java/org/matsim/contrib/freight/controler/CarrierDriverAgent.java
There is no reason to create a new object (with slightly different information) instead of using the original `LinkEnterEvent` for the scoring function.
With the original `LinkEnterEvent`, the `vehicleTypeId` (and other information) will become consistent to the stuff in the event log. Since we are using the MATSim vehicles also in the freight contrib, we can access all relevant information from there - and thus need the vehicleId, that is available in the mobsim and e.g. the `allVehicles`-container.
> Freight: Hand over the original LinkEnterEvent instead of creating a new one

- contribs/otfvis/pom.xml
- pom.xml
I think we can re-enable enforcer (disabled in #2344). There was an issue with an SSL certificate that expired on 1/1/23 for the https://maven.geo-solutions.it/ maven repo. Therefore we could not download `com.sun:clibwrapper_jiio:jar:1.1` from there. I think shading (fat jar creation) might have been affected too.
> mvn: re-enable enforcer

- matsim/pom.xml
Due to the recent build failures related to downloading assertJ javadocs, e.g. https://github.com/matsim-org/matsim-libs/actions/runs/3859888596/jobs/6579827504
At this point, it's hard to say what is the issue. Versions 3.23.x (May '22) worked fine and the recent bumps to 3.24.x (Jan '23) caused this issue. So this seems to be the quickest fix until we have time to look deeper into it.
> mvn: disable external javadoc link auto detection

- contribs/application/pom.xml
The scope is already declared as `test` in the dependency management (in matsim-all POM).
> mvn: remove redundant test scope in assertj-core dependency declaration

- matsim/src/main/java/org/matsim/api/core/v01/IdCollectors.java
- matsim/src/main/java/org/matsim/api/core/v01/IdMap.java
- matsim/src/main/java/org/matsim/api/core/v01/IdSet.java
- matsim/src/test/java/org/matsim/api/core/v01/IdCollectorsTest.java
So we can collect streams to Id maps and sets:
```java
IdMap<Vehicle, Vehicle> map = vehicles.stream().collect(IdCollectors.toIdMap(Vehicle.class, Vehicle::id, v -> v)));
```
or
```java
IdSet<Vehicle> set = vehicles.stream().map(Vehicle::id).collect(IdCollectors.toIdSet(Vehicle.class));
```
> core: add collectors for IdSet and IdMap

- matsim/src/main/java/org/matsim/api/core/v01/IdMap.java
- matsim/src/main/java/org/matsim/api/core/v01/IdSet.java
- matsim/src/test/java/org/matsim/api/core/v01/IdMapTest.java
- matsim/src/test/java/org/matsim/api/core/v01/IdSetTest.java
We already have `IdMap.get(int index)`, so these two methods follow this patter.
These two methods are useful when checking termination criteria in speedy routers when we want to stop when one or more of the end nodes are reached. Currently, to do it efficiently, we need to create a `BitSet`, which is unnecessary if we already have an `IdSet` or `IdMap`.
> core: add IdSet.contains(int index) and IdMap.containsKey(int index)

- contribs/taxi/src/test/java/org/matsim/contrib/etaxi/run/RunETaxiBenchmarkTest.java
- contribs/taxi/src/test/java/org/matsim/contrib/taxi/optimizer/assignment/AssignmentTaxiOptimizerIT.java
They caused JVM seg faults (in one of the build pipelines). Since we stopped using Jenkins, we can re-enable them.
> taxi: un-ignore assignment tests that Jenkins could not run

- contribs/application/src/main/java/org/matsim/application/options/CountsOption.java
- contribs/application/src/main/java/org/matsim/application/prepare/counts/CreateCountsFromBAStData.java
replaced depricated methods in CountsOption and moved class to option package
allow missing column names in CreateCountsFromBASt because BASt data contains an empty column without column name
> Counts from bast maintenance

- contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/MissingEnergyEventHandler.java
I forgot to add `extend EventHandler` and so the handlers that implemented `MissingEnergyEventHandler` (among other handler interfaces) were not notified about `MissingEnergyEvent`s.
I wonder if that happens from time to time and not only to me, maybe then we should add some check that will at least log a warning while registering such a event handler.
This error only happens if an event handler implements **at least two** event handler interfaces and not all of the interfaces extend the top-lever `EventHandler` interface.
> ev: extend EventHandler in MissingEnergyEventHandler

- contribs/freight/src/main/java/org/matsim/contrib/freight/events/FreightEventsReaders.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/events/FreightTourEndEvent.java
- contribs/freight/src/main/java/org/matsim/contrib/freight/events/FreightTourStartEvent.java
For reading in the freight specific events.
It bases on the [DvrpEventsReaders](https://github.com/matsim-org/matsim-libs/blob/master/contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/util/DvrpEventsReaders.java).
Please not: It is not complete yet --> More Events-converter will come soon.
> Freight: Introduce an EventsReader for freight events

- contribs/freight/src/main/java/org/matsim/contrib/freight/events/FreightTourStartEvent.java
minor fix for #2404 
If the vehicleId is null in the events file, do not try to create an Id.
> Freight Events

- matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorCore.java
- change condition on which legs are skipped in order to work correctly with trees
- this fixes a problem in routes derived from tree calculations, if the second to last leg is a transfer walk in between two different stops.
- - Travel time calculations were correct, but the departure stop of the last leg was wrong
- RaptorRoutes derived from trees do not end with a walk leg (as opposed to routes calculated o to d), so only these have been affected, as the previously condition assumed a walk leg in the end.
> Tree Calculation in SRR could lead to invalid routes

- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/DvrpTravelTimeMatrixParams.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/FreeSpeedTravelTimeMatrix.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/TravelTimeMatrices.java
- contribs/dvrp/src/test/java/org/matsim/contrib/zone/skims/TravelTimeMatricesTest.java
Add `maxNeighborTravelTime` as another criterion (next to `maxNeighborDistance`) when calculating TT to all nodes in the neighbourhood in the sparse TT matrix. Satisfying only one criterion (either max distance or travel time) is enough to be considered a neighbour.
The TT matrix works reasonably well for urban areas. However, we have recently observed substantial estimation errors for rural areas. The errors were produced mainly along motorways. This is where two nodes may be very close to each other (and therefore considered to belong to one zone), but at the same time too far away (in terms of the network distance) to be considered neighbours and included in the sparse matrix (where accurate travel times are stored).
Adding `maxNeighborTravelTime` as a criterion helps reaching a bit …
> Dvrp: TT matrix with max TT neighbourhood criterion

- contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierPlanXmlWriterV2_1.java
- contribs/freight/src/test/java/org/matsim/contrib/freight/carrier/CarrierPlanXmlWriterV2Test.java
- contribs/freight/src/test/java/org/matsim/contrib/freight/carrier/CarrierPlanXmlWriterV2_1Test.java
- contribs/freight/test/input/org/matsim/contrib/freight/carrier/CarrierPlanXmlWriterV2Test/carrierPlansEquils.xml
- contribs/freight/test/input/org/matsim/contrib/freight/carrier/CarrierPlanXmlWriterV2_1Test/carrierPlansEquils.xml
- matsim/src/main/resources/dtd/carriersDefinitions_v2.1.xsd
The current version of the `CarrierPlanXmlWriterV2_1 `will now also write out
- the validation header
- the tourId
- tags <plans> </plans>: They were missing before :(
I also added a missing test for the current writer version, including a new checkFilesAreEqual (after read/write) (see #2196)
The XSD files has not had any information for `Attributes`, e.g. of the `Carrier` or the `Shipment`s or `Service`s -> I added those
Additionally, some small changes mostly regarding formating on the way, e.g. time format, indentation, etc. were done.
This PR closes #2421 for the current writer version.
> Freight: CarrierWriter - add validation, tourId and some small fixes

- contribs/vsp/src/main/java/playground/vsp/ev/UrbanVehicleChargingHandler.java
Add vehicles queued at the charger to the ongoing charging procedures.
Currently, we can observe the following issue:
- A vehicle gets queued at a charger (plugin interaction activity)
- A plugout interaction activity is executed while the vehicle is still in the queue
- Because the vehicle was not included in the ongoing charging procedures, it does not get removed from the charger logic
- The charging continues, often despite the vehicle moving somewhere in the network (!)
- At some point the vehicle gets fully charged and so the charging end event is triggered
- In response to this event, UrbanVehicleChargingHandler tries to remove the vehicle from the ongoing charging procedures, which causes an NPE (as the vehicle has not been registered there)
> vsp: fix UrbanVehicleChargingHandler

- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/Matrix.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/SparseMatrix.java
They had been already used before we changed their access to package protected. Therefore, now making them pubic again.
Ping @rakow, @steffenaxer, @luchengqi7
> dvrp: make Matrix and SparseMatrix public

- matsim/src/main/java/org/matsim/core/controler/ControlerDefaultsModule.java
Sets the Cache File directory used by ChartUtils to the tmp folder in the output directory
> Fixing #2463

- matsim/src/main/java/org/matsim/core/controler/corelisteners/DumpDataAtEndImpl.java
This change passes registered AttributeConverters to the HousholdWriter when dumping at the end of the simulation.
Currently, custom AttributeConverters are not passed to the HousholdsWriter, but they are, for example, when writing the population.
> Pass AttributeConverters to HouseholdsWriter

- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/edrt/run/EDrtControlerCreator.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/EDrtOperationsControlerCreator.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/eshifts/charging/ShiftOperatingVehicleProvider.java
- contribs/dvrp/src/main/java/org/matsim/contrib/evrp/OperatingVehicleProvider.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/AuxDischargingHandler.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/DischargingModule.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/DriveDischargingHandler.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/IdleDischargingHandler.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/routing/EvNetworkRoutingModule.java
- contribs/taxi/src/main/java/org/matsim/contrib/etaxi/run/RunETaxiBenchmark.java
- contribs/taxi/src/main/java/org/matsim/contrib/etaxi/run/RunETaxiScenario.java
To avoid confusion, because AUX energy consumption is also used in `DriveDischargingHandler`, that is:
- `DriveDischargingHandler` computes Drive+AUX energy consumption (simulated when a vehicle is moving)
- `IdleDischargingHandler` considers only AUX energy consumption (simulated when a vehicle is idle, e.g. a taxi at a rank)
> ev: rename AuxDischargingHandler to IdleDischargingHandler

- contribs/vsp/src/main/java/org/matsim/contrib/freight/analysis/CarrierLoadAnalysis.java
- contribs/vsp/src/main/java/org/matsim/contrib/freight/analysis/FreightAnalysisEventHandler.java
- contribs/vsp/src/main/java/org/matsim/contrib/freight/analysis/FreightAnalysisServiceTracking.java
- contribs/vsp/src/main/java/org/matsim/contrib/freight/analysis/FreightAnalysisShipmentTracking.java
- contribs/vsp/src/main/java/org/matsim/contrib/freight/analysis/FreightAnalysisVehicleTracking.java
- contribs/vsp/src/main/java/org/matsim/contrib/freight/analysis/FreightTimeAndDistanceAnalysisEventsHandler.java
- contribs/vsp/src/main/java/org/matsim/contrib/freight/analysis/Readme.md
- contribs/vsp/src/main/java/org/matsim/contrib/freight/analysis/RunFreightAnalysis.java
- contribs/vsp/src/main/java/org/matsim/contrib/freight/analysis/RunFreightAnalysisEventbased.java
Moving the new analysis used for teaching over to the vsp contrib.
The new analysis can directly access information from the freight events introduced in 2022/23.
At the same time, this PR deprecates the old analysis, which uses a lot of guessing due to missing information in the events.
> VSP: Update freight analysis 

- contribs/application/src/main/java/org/matsim/application/prepare/pt/CreateTransitScheduleFromGtfs.java
Resolve GTFS feed filename to URL first. 
Fix #2504 for windows.
> Fix CreateTransitScheduleFromGtfs on Windows

- .github/workflows/deploy-on-pr-merge.yaml
After discussions with some of you, it seems that stopping deploying SNAPSHOT versions is a good step towards increasing the maintainability and reproducibly.
Now the idea is to merge this PR shortly before we bump to `16.0-SNAPSHOT` on master, so `16.0-SNAPSHOT` will never get deployed.
Ping @Janekdererste (related to #2491 and #2492 )
> build: stop deploying SNAPSHOT versions on merging to master

- contribs/simulatedannealing/src/main/java/org/matsim/contrib/simulatedannealing/perturbation/ChainedPerturbatorFactory.java
- contribs/simulatedannealing/src/test/java/org/matsim/contrib/simulatedannealing/SimulatedAnnealingIT.java
- contribs/simulatedannealing/src/test/java/org/matsim/contrib/simulatedannealing/SimulatedAnnealingTest.java
Remove non-deterministic behaviour from `ChainedPerturbatorFactory` and `SimulatedAnnealingTest`.
> Remove (some) non-determinism from simulated annealing

- README.md
Since we stopped deploying snapshots in #2493.
> remove snapshot deployment badge from README.md

- contribs/common/src/main/java/org/matsim/contrib/common/util/WeightedRandomSelection.java
- contribs/common/src/test/java/org/matsim/contrib/common/util/WeightedRandomSelectionTest.java
Fixes issue reported in #2537 by throwing a more meaningful exception when the total weight is not positive.
> Fix weighted random selection

- contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierPlanXmlParserV2_1.java
- contribs/vsp/src/main/java/org/matsim/contrib/freight/analysis/CarrierPlanAnalysis.java
PlansXML-Tag: Actively "do nothing" when reading them in. This is done to avoid the warning, that an unknown tag was found (and ignored).
CarrierAnalysis: Add a small analysis, collecting some values (score, number of tours, number of jobs) from the `Carriers` and writing them out.
> Freight: Ignore plans-tags when reading carrierXML; add a small (VSP internal) analysis for carrier files

- contribs/dvrp/src/main/java/org/matsim/core/router/speedy/SpeedyMultiSourceALTFactory.java
- matsim/src/main/java/org/matsim/core/router/speedy/SpeedyALTFactory.java
By default, the number of landmarks is set to 16. This leads to errors if the number of nodes in the network is less than 16. See: https://github.com/matsim-org/matsim-maas/issues/105
This PR limits the number of landmarks so that it never exceeds the number of nodes.
> fix: ensure landmarks count is not greater than number of nodes

- matsim/src/main/java/org/matsim/core/config/ConfigGroup.java
This fix allows running RunIT (in shared_mobility) on Windows CI machines.
RunIT mixes the input data from two sources: matsim-examples (where the config is) and test/resources (e.g. shared_vehicles_mobility.xml). This works on IDEs, but not in regular maven (eg. when running CI). As a result the following URL is constructed (GitHub Actions, windows-latest):
```
jar:file:/C:/Users/runneradmin/.m2/repository/org/matsim/matsim-examples/16.0-SNAPSHOT/matsim-examples-16.0-SNAPSHOT.jar!/D:/a/matsim-libs/matsim-libs/contribs/shared_mobility/target/test-classes/org/matsim/contrib/shared_mobility/shared_vehicles_mobility.xml
```
instead of
```
/D:/a/matsim-libs/matsim-libs/contribs/shared_mobility/target/test-classes/org/matsim/contrib/shared_mobility/shared_vehicles_mobility.xml
```
> core: improve handling of absolute paths on windows

- .github/workflows/full-integration.yaml
We have been recently experiencing lots of failing builds on AppVeyor. Most of the failures were caused by the 1-hour timeout, while a few of them by the differences in the testing environment (i.e. windows instead of linux).
This PR enables the windows builds to GitHub Actions that have much longer timeouts (6h). This also allows us to run integrations tests (right now we run only the "base" unit tests on AppVeyor).
See #2577 and #2580.
> Run full integration on windows latest

- contribs/ev/src/main/java/org/matsim/contrib/ev/EvConfigGroup.java
A 15-second interval is still high enough for good simulation accuracy and for online decision making (e.g. stopping charging when the target SOC is reached).
> ev: reduce default frequency of charging simulation (and of EnergyChargedEvents)

- contribs/vsp/src/main/java/org/matsim/contrib/vsp/scenario/SnzActivities.java
Activity types accomp_other, accomp_children which are present in some vsp scenarios have been added.
> Add missing activity types in vsp contrib

- contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierPlanXmlWriterV2_1.java
Use the `Id` of the `Shipment` or `Service` directly, when writing out the `Plan` of the `Carrier.` 
Also print out an ERROR, if the `Shipment` or `Service` in the Plan is not contained in the list of `Shipment` or `Service`  of the Carrier itself.
> Freight: CarrierWriter improvement/simplification

- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/companions/DrtCompanionRideGenerator.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/companions/DrtCompanionUtils.java
This PR adds some additional information to the companion agent person attributes. Might be required if one needs to deal with fare discounts for additional riders.
**Additional Group Size:** How many companions are additionally added.
**Additional Group Part:** Is the index of an additionally added companion.
> Add group size and part information

- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/companions/DrtCompanionRideGenerator.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/companions/DrtCompanionUtils.java
This pr introduces a `drtCompanionType` attribute which gets attached to the created companion persons in `DrtCompanionRideGenerator` and responds to the comments from #2640.
> Add drtCompanionType attribute

- contribs/vsp/src/main/java/org/matsim/contrib/freight/analysis/RunFreightAnalysisEventbased.java
@kt86 Ich hatte das Problem, dass bei mir die Analyse nicht lief, weil er defaultmäßig immer als GlobalCRS Altlantis genommen hatte, dann aber bei der Transformation zum networkCRS keine Transformation fand. Ich hoffe, die Erweiterung des constructors passt für dich
> add CRS to constructor of FreightAnalysis

- matsim/src/main/java/org/matsim/core/population/io/ParallelPopulationReaderMatsimV6.java
- matsim/src/main/java/org/matsim/core/population/io/ParallelPopulationReaderMatsimV6Runner.java
- matsim/src/main/java/org/matsim/core/population/io/PopulationReader.java
- matsim/src/main/java/org/matsim/core/population/io/PopulationReaderMatsimV6.java
- matsim/src/main/java/org/matsim/utils/objectattributes/ObjectAttributesConverter.java
- matsim/src/main/java/org/matsim/utils/objectattributes/attributable/AttributesXmlReaderDelegate.java
This PR reactives an idea from @cdobler, who developed the `ParallelPopulationReaderMatsimV4`. The basic idea was, to have one read thread an one or many processing threads. I reactivated this idea and cleaned the code. I even benchmarked this approach and the loading runtime of a population can be saved by approx. 40 %, which is in my eyes quite significant.
> Parallel Population Reader

- matsim/src/main/java/org/matsim/core/population/PopulationUtils.java
This adds a simple helper method `PopulationUtils.removeSubpopulation()`, that removes the `PopulationUtils.SUBPOPULATION_ATTRIBUTE_NAME` from a person. 
Adding this (trivial) helper helps to avoid using the `SUBPOPULATION_ATTRIBUTE_NAME` attribute directly, as its comment states, it should not be public.
https://github.com/matsim-org/matsim-libs/blob/f3d59d70fcec7f675f2e32d415862afed5e1c9b1/matsim/src/main/java/org/matsim/core/population/PopulationUtils.java#L88-L92
Bonus: Converted some spaces to tabs for indentation
> Add PopulationUtils.removeSubpopulation()

- matsim/src/main/java/org/matsim/vehicles/VehicleUtils.java
This change adds the method `VehicleUtils.hasVehicleId(Person person, String mode)` that checks whether a person has a designated vehicle for a specific mode assigned - without throwing an exception.
Motivation for this method is, that
* the existing methods `getVehicleIds` and `getVehicleId` always throw an exception, if the `"vehicles"` attribute is not filled with a `PersonVehicles` object, and
* the attribute name `VehicleUtils.VEHICLE_ATTRIBUTE_KEY = "vehicles"` is private, so for checking it manually, a hard-coded copy of the `"vehicles"` string is required, which is ugly.
> Add VehicleUtils.hasVehicleId() method

- matsim/src/main/java/org/matsim/analysis/TripsAndLegsCSVWriter.java
- matsim/src/test/java/org/matsim/analysis/TripsAndLegsCSVWriterTest.java
There was a clause that disabled RoutingModeMainModeIdentifier in the trip csv, because the routing mode was not available at that time. Since the routing mode is now also part of the experienced leg, it can be used without any errors.
> Allow RoutingMode as MainModeIdentifier in trips csv 

- contribs/application/src/main/java/org/matsim/application/analysis/population/TripAnalysis.java
- contribs/application/src/main/java/org/matsim/application/analysis/traffic/TrafficAnalysis.java
When filtering with shp file, now the crs is respected to transform coordinates if necessary.
> Apply coordinate transformation in TrafficAnalysis class

- matsim/src/main/java/org/matsim/core/population/io/ParallelPopulationReaderMatsimV6.java
- matsim/src/main/java/org/matsim/core/population/io/ParallelPopulationReaderMatsimV6Runner.java
- matsim/src/test/java/org/matsim/core/population/io/StreamingPopulationAttributeConversionTest.java
This PR adds now also the parallel reading functioanlity to the streaming population reader. Within an other PR I will add a new, much faster XML Parser that handels xml files with DTD validation. In the attached plot you can see the performance improvements. Benchmark reads for testing the hamburg-v3.0-25pct-base.output_plans.xml.gz
@mrieser thanks for supporting me! Great teamwork.
> Parallel Streaming Population Reader

- matsim/src/main/java/org/matsim/core/utils/io/MatsimXmlParser.java
This PR changes the setFeature method call to use standard feature. "http://xml.org/sax/features/validation". There were reports, that the usage of featureName "validation" is not working on every machine. So this should be now more robust.
> Set standard validation feature for WoodStox parser

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/plusOne/PlusOneRebalancingStrategy.java
PlusOneRebalancingStrategy calculates rebalancing decisions while listening to events. To prevent non-determinism caused by race conditions, the ongoing calculation does not consider events from the current time step.
> Reproducible plus one rebalancing

- matsim/src/main/java/org/matsim/core/utils/io/IOUtils.java
This change allows to change the global ZSTD compression level in `IOUtils`.
As new ZSTD compression levels (beyond the current 22) might be added in the future, I did not enforce an upper limit in the setter.
> Configurable ZSTD compression level

- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/path/OneToManyPathCalculator.java
Currently, there is a comment in `OneToManyPathCalculator` that already explains that having parallel links (same start and end node) may produce unexpected results when reconstructing the link sequence (see `constructLinkSequence`). 
Yesterday, I was debugging timing issues in DRT where I had a scenario in which I never managed to get the timing 100% congruent between insertion/scheduling and the simulation. After digging for several hours, I arrived at the comment in `OneToManyPathCalculator` so I thought it might be useful to have a check and a warning about the issue :)
> fix: warn for parallell links in OneToManyPathCalculator

- contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/DefaultRequestInsertionScheduler.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/run/examples/RunDrtExampleIT.java
Currently, there is an issue when using varying stop durations (`StopDurationEstimator` + `IncrementalStopDurationEstimator`) in the scheduling of the DRT tasks. Everything works well in the case when new tasks are created, but for stops to which pickups or dropoffs are added, only their own duration is updated and the scheduling finishes. This is fine if the `stopDuration` stays constant (e.g. 60s), but if the stop duration increases, this has an impact on the following tasks. So whenever the stop duration is updated during scheduling, we should use `ScheduleTimingUpdater` to repair the following start and end times. Otherwise, we have an inconsistent schedule. It may be repaired eventually somewhere, but if we have subsequent insertions in one iteration, this may lead to confusion. 
- …
> fix: repair treatment of extended stop durations in drt task scheduling

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DrtModeOptimizerQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/repeatedselective/DetourTimeEstimatorWithAdaptiveTravelTimes.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/repeatedselective/RepeatedSelectiveInsertionProvider.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/repeatedselective/RepeatedSelectiveInsertionSearch.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/repeatedselective/RepeatedSelectiveInsertionSearchParams.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/repeatedselective/RepeatedSelectiveInsertionSearchQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/selective/SingleInsertionDetourPathCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeModule.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/run/examples/RunDrtExampleIT.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/path/OneToManyPathSearch.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/AdaptiveTravelTimeMatrix.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/AdaptiveTravelTimeMatrixImpl.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/AdaptiveTravelTimeMatrixModule.java
This PR provides a novel insertion search implementation that is a blend between extensive and selective search. In a nutshell:
-	Introduction of a time dependent travel time cache (see AdaptiveTravelTimeMatrix) to get most accurate detour time estimates. First, I played around and developed a straightforward time dependent TravelTimeMatrix, but the initialization and updating is painful slow when having 30-time bins. Second, I developed an AdaptiveTravelTimeMatrix that gets initialized from the existing FreeSpeedMatrix but it is updated lazily within the insertion search whenever a regular calculatePaths method is called. As we have multiple millions routing calls over the iterations one can produce passively a travel time matrix that is quite accurate without addition runtime burden. 
- …
> Repeated selective insertion search

- contribs/shared_mobility/src/main/java/org/matsim/contrib/shared_mobility/examples/RunTeleportationBikesharing.java
- matsim/src/main/java/org/matsim/core/config/groups/PlansCalcRouteConfigGroup.java
After recent refactorings (#2646), ModeRoutingParams is now a deprecated subclass of TeleportedModeParams.
> core: accept TeleportedModeParams as arg in PlansCalcRouteConfigGroup.addTeleportedModeParams()

- contribs/common/src/main/java/org/matsim/contrib/common/timeprofile/ProfileWriter.java
Within latest drt refactoring, separators have been already adapted to the global separator, but the ProfileWriter that writes occupancy profiles has not been touched. This PR introduces now the usage of the global separator also in the ProfileWriter that is used in drt and taxi contrib. In my point of view, it would be useful, that csv and txt file writing is more harmonized in MATSim.
> Use global separator within ProfileWriter

- matsim/src/main/java/org/matsim/core/config/ReflectiveConfigGroup.java
- matsim/src/test/java/org/matsim/core/config/ReflectiveConfigGroupTest.java
This change adds support for automatic conversion of `LocalTime`, `LocalDate` and `LocalDateTime` parameters in `ReflectiveConfigGroup`.
> Add support for LocalTime, LocalDate and LocalDateTime to ReflectiveConfigGroup

- contribs/application/src/main/java/org/matsim/application/prepare/population/AdjustActivityToLinkDistances.java
- contribs/application/src/main/java/org/matsim/application/prepare/population/ExtractHomeCoordinates.java
- contribs/application/src/main/java/org/matsim/application/prepare/population/ResolveGridCoordinates.java
Make use of `CoordUtils.round` in some classes that generate coordinates. Keeping all digits makes population files unnecessarily large.
> Round randomly generated coordinates

- .github/dependabot.yml
This is to avoid having a lot of coexisting dependabot-triggered PRs (each addressing an individual version bump), which results in a lot of:
- CI builds (especially that we require PRs to be in sync with the master branch)
- PR-based releases deployed to our mvn repo
> deps: group dependabot version updates

- .github/workflows/deploy-on-pr-merge.yaml
Generate a complete dependency graph and submit the graph to the GitHub repository.
The goal is to improve security alerts from dependabot, because dependabot is not able to compute the complete dependency graph.
> build: submit dependency graph when deploy-on-pr-merge

- matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/DefaultRaptorStopFinder.java
- matsim/src/main/java/org/matsim/pt/transitSchedule/TransitScheduleUtils.java
- matsim/src/test/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorIntermodalTest.java
- matsim/src/test/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorTest.java
- matsim/src/test/java/org/matsim/core/scenario/ScenarioLoaderImplTest.java
Some public transport stops are more accessible than others. 
One typical example: Accessing a metro stop is often much more cumbersome than accessing a tram stop, because one has to go down several metres. 
So far, accessing stops by usually teleported walk routes, this could not be taken into account. Thus we could see in our models that taking trains or metros for very short trips is more popular than it should be if there is competing ground level public transport. 
This PR allows the introduction of access and egress times for each stop facility (not including transfers between public transport, as these allow an explicit definition of a transfer time).
Depending on your pt data source this may or may not be useful. The Swiss GTFS essentially treats all stop points as single stops, …
> Add stop access and egress times

- .github/dependabot.yml
We need to manually ignore all dependencies that we cannot update in each PR like this: https://github.com/matsim-org/matsim-libs/pull/2836 (as they keep re-appearing in new PRs). This works much better when dependency bumps are not grouped (dependabot somehow remembers what we have already ignored and does not propose updates).
> deps: stop grouping mvn dependencies version updates

- matsim/src/main/java/org/matsim/api/core/v01/IdAnnotations.java
- matsim/src/main/java/org/matsim/api/core/v01/IdDeSerializationModule.java
- matsim/src/test/java/org/matsim/api/core/v01/IdAnnotationsTest.java
- matsim/src/test/java/org/matsim/api/core/v01/IdDeSerializationModuleTest.java
This change adds a Module, that configures a Jackson `ObjectMapper` such that it can natively de-/serialize `Id<T>` classes, even when nested in Lists or Maps.
This is a prerequisite for storing link ids in the network for enabling turn restrictions in #2829.
```java
Map<Id<Link>, String> map = new LinkedHashMap<>();
map.put(Id.createLinkId("0"), "a");
map.put(Id.createLinkId("1"), "b");
// create & configure ObjectMapper
ObjectMapper objectMapper = new ObjectMapper();
objectMapper.registerModule(IdDeSerializationModule.getInstance());
// create & configure ObjectWriter
TypeFactory typeFactory = TypeFactory.defaultInstance();
MapType mapType = typeFactory.constructMapType(
Map.class, 
typeFactory.constructParametricType(Id.class, Link.class),
typeFactory.constructType(String.class)); …
```
> Add ObjectMapper Module for Id de-/serialization

- contribs/application/src/main/java/org/matsim/application/prepare/network/CreateGeoJsonNetwork.java
- contribs/simwrapper/src/main/java/org/matsim/simwrapper/SimWrapperListener.java
- contribs/simwrapper/src/main/java/org/matsim/simwrapper/SimWrapperRunner.java
1) include freight and drt in the mode filter when writing out geojson network. Otherwise, links that have no cars allowed, but drt, are not included for visualization
2) fix the lookup of implementations of `DashboardProvider`
3) (main method for SimWrapperRunner)
> Small fixes for analysis (simwrapper)

- contribs/minibus/src/test/java/org/matsim/contrib/minibus/integration/SubsidyTestIT.java
After switching to the speedy router, `SubsidyTestIT` started to behave non-deterministically. It's a "quick fix" following the similar fix in this commit:
```
non-deterministic test, allow for 2 outcomes... :-/ Marcel Rieser Yesterday 20:58 31fe21b6
```
> minibus: fix full integration on windows by adding another value to allowed results

- pom.xml
This is to get more consistent build behaviour across different machines. Mvn 3.6.3 is now 4 years old and sometimes does not work well with newer JDKs (16+).
> mvn: require mvn version 3.8+

- contribs/application/src/main/java/org/matsim/application/analysis/population/TripAnalysis.java
Disables the sampling for detecting the data type in trips csv, which leads to a crash in case it is wrong.
> Fix datatype error in TripAnalysis

- .github/workflows/full-integration.yaml
- support manually triggering of full-integration (useful if we do not want to wait for the scheduled build)
- run full-integration also on macos-latest
> Full integration on macOS

- contribs/accessibility/pom.xml
- contribs/noise/pom.xml
- contribs/vsp/pom.xml
- pom.xml
This is to keep all osmosis dependencies set to the same version and to get only one PR from dependabot when bumping osmosis.
> mvn: introduce osmosis.version property

- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/edrt/scheduler/EmptyVehicleChargingScheduler.java
The default EmptyVehicleChargingScheduler throws an error, if more than one charger has been deployed per link. If multiple chargers are available, a random charger is now selected in this PR.
> (edrt) Allow multi. chargers per link

- contribs/minibus/src/test/java/org/matsim/contrib/minibus/integration/SubsidyTestIT.java
The deploy-weekly build failed again. This is just a workaround without guarantee it will work in 100% cases.
> minibus: relaxing assertion to work around non-deterministic results

- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/FreeSpeedTravelTimeMatrix.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/TravelTimeMatrices.java
- contribs/dvrp/src/test/java/org/matsim/contrib/zone/skims/TravelTimeMatricesTest.java
When max duration and distance are set to zero, there is no point in computing the sparce matrix, which may be very time consuming for very large networks.
> dvrp: skip computing sparse TT matrix when not needed

- contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/DischargingModule.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/DriveDischargingHandler.java
This commit moves updating of the battery charge (SOC) to the main thread (i.e. outside the event handling threads) to avoid race conditions (and also to have events deterministically ordered).
> ev: move drive discharging from event handlers to mobsim

- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/DefaultPassengerEngine.java
- contribs/dvrp/src/test/java/org/matsim/contrib/dvrp/passenger/DefaultPassengerEngineTest.java
Due to race conditions, DefaultPassengerEngine may get notified about a rejection before, during or after its doSimStep() finishes. This means the rejection may be processed in the current or next time step.
To overcome this non-determinism, all rejections from the current time step are processed in the next time step.
> dvrp: fix non-deterministic PersonStuckEvent due to rejection

- matsim/src/main/java/org/matsim/run/gui/Gui.java
Our java gui internally calls java a second time in order to be able to add a larger memory request as VM argument.  I am now additionally adding the arguments
"--add-exports", "java.base/java.lang=ALL-UNNAMED",
"--add-exports", "java.desktop/sun.awt=ALL-UNNAMED",
"--add-exports", "java.desktop/sun.java2d=ALL-UNNAMED",
because this seems to be needed to make jogl work on windows.
> add VM arguments to second Java call from within the Gui to circumvent module encapsulation which breaks jogl on windows

- matsim/src/main/java/org/matsim/core/population/io/ParallelPopulationReaderMatsimV4.java
- matsim/src/main/java/org/matsim/core/population/io/ParallelPopulationReaderMatsimV6.java
- matsim/src/test/java/org/matsim/core/population/io/ParallelPopulationReaderTest.java
before, the reading of the population just continued, even if one of the reader-threads had an exception. Now, the exception from a reader-thread is propagated to the main-thread.
Closes #2929
> escalate exceptions during parallel population reading (Fix for #2929)

- contribs/drt-extensions/src/test/java/org/matsim/contrib/drt/extension/edrt/run/RunEDrtScenarioIT.java
After #2935 and #2939 attempt to reactivate quantitative assertions for the edrt/prebooking integration test.
> drt: reactivate edrt prebooking test with assertions

- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/estimator/DrtInitialEstimator.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/estimator/impl/BasicDrtEstimator.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/estimator/impl/ConstantDrtEstimator.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/estimator/impl/PessimisticDrtEstimator.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/estimator/run/DrtEstimatorConfigGroup.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/estimator/run/DrtEstimatorModule.java
- contribs/drt-extensions/src/test/java/org/matsim/contrib/drt/extension/estimator/MultiModaFixedDrtLegEstimatorTest.java
This PR extends the DRT estimator module with an additional interface to provide estimates, when no data is available yet. This functionality can be used to try pessimistic, optimistic or even estimates based on real data.
> Configurable initial DRT estimators

- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/insertion/DrtInsertionModule.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/insertion/constraints/VehicleRangeConstraint.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/insertion/distances/DistanceApproximator.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/insertion/distances/DistanceCalculator.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/insertion/distances/EuclideanDistanceApproximator.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/insertion/distances/InsertionDistanceCalculator.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/insertion/distances/RoutingDistanceCalculator.java
- contribs/drt-extensions/src/test/java/org/matsim/contrib/drt/extension/insertion/DrtInsertionExtensionIT.java
This PR makes it easy to further experiment with the distance objective and range constraint that comes with `drt-extensions/insertion`. It is now possible to flexibly configure the distance calculator with a custom logic. Furthermore, the distance approximator can be defined. While the calculator is used in the distance objective, both of them are used in the range constraint: If an approximator is defined (but it is optional), the range constraint is first evaluated with the approximator, which should be pessimistic. Only if a violation of the constraint is detected using this pessmistic (i.e. overestimating) setting, the more exact calculator is used that will perform a direct network routing by default. Both elements can now be configured by:
```java
DrtInsertionModule insertionModule …
```
> feat: customizable distance calculators for drt constraints

- matsim/src/main/java/org/matsim/analysis/TripsAndLegsWriter.java
#2955 removed the public constructor of the `TripsAndLegsWriter `. I would kindly ask to make this constructor again public. @jfbischoff developed this very valuable class, which is also a strong utility within post-processing tasks. 
However, post-processing would require the creation of a certain instance of this class. I observed in the recent past some changes that removed the visibility of classes and constructors. Maybe we require a general discussion about how to deal with this kind of an issue. Removing the visibility might be good in terms of code maintenance, however it pushes users/devs into the direction to make local code copies, which feels like a silent fork. In my eyes, MATSim is a framework that should allow users/devs to reuse code instead of making various replicas of …
> Make TripsAndLegsWriter public again

- contribs/freight/pom.xml
- contribs/freight/src/test/java/org/matsim/freight/carriers/jsprit/MatsimTransformerTest.java
This is to make sure we do not accidently use junit 4 in freight or other depending contribs (junit 4 was not in the test scope, because graphstream declared it not in that scope, and therefore it was transitively available in so many places).
> freight: stop transitively depending on junit 4

- contribs/ev/src/main/java/org/matsim/contrib/ev/charging/VehicleChargingHandler.java
Reported by Tobias Tietz:
```
java.util.ConcurrentModificationException: null
at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1628) ~[?:?]
at org.matsim.contrib.ev.charging.VehicleChargingHandler.notifyMobsimBeforeSimStep(VehicleChargingHandler.java:169) ~[classes/:?]
at org.matsim.core.mobsim.qsim.MobsimListenerManager.fireQueueSimulationBeforeSimStepEvent(MobsimListenerManager.java:107) ~[classes/:?]
at org.matsim.core.mobsim.qsim.QSim.doSimStep(QSim.java:390) ~[classes/:?]
at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:259) ~[classes/:?]
at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:125) ~[classes/:?]
at org.matsim.core.controler.AbstractController$8.run(AbstractControl …
```
> ev: fix ConcurrentModificationException in VehicleChargingHandler.notifyMobsimBeforeSimStep()

- matsim/src/main/java/org/matsim/core/config/ReflectiveConfigGroup.java
If a ConfigGroup based on ReflectiveConfigGroup has to add an unmapped parameter, usually an exception is thrown.
In some cases, it could make sense to provide special handling in such cases, e.g. to implement backward compatibility to older parameter names, to support a migration from older to newer parameters, etc.
This PR adds two methods `handleAddUnknownParam(...)` and `handleGetUnknownValue(...)` (matching `addParam(...)` and `getValue(...)`) that are designed to be overwritten. The default implementation reuses the existing logic in ReflectiveConfigGroup. Custom config groups can overwrite the methods and add custom functionality to deal with unknown parameters.
Fixes #2960
> Provides a way to provide custom handling for unknown parameters in ReflectiveConfigGroup

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/depot/Depots.java
This PR ensures a deterministic depot selection for eDrt in situation in which multiple depots are having the very same distance - unfortunately, yes this might happen 😓 and would cause a non-deterministic depot selection. Took me quite some time to narrow down this problem.
> Ensure deterministic depot selection

- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/companions/DrtCompanionRideGenerator.java
PR removes UUID in order to have reproducible event files.
> Remove uuid from DrtCompanionRideGenerator

- contribs/decongestion/pom.xml
- contribs/decongestion/src/main/java/org/matsim/contrib/decongestion/DecongestionModule.java
- contribs/decongestion/src/main/java/org/matsim/contrib/decongestion/routing/TollTimeDistanceTravelDisutility.java
- contribs/decongestion/src/main/java/org/matsim/contrib/decongestion/run/DecongestionRunExample.java
- contribs/decongestion/src/main/java/org/matsim/contrib/decongestion/run/DecongestionRunExampleFromConfig.java
- contribs/decongestion/src/test/java/org/matsim/contrib/decongestion/DecongestionPricingTestIT.java
rearrange package structure for reducing public footprint later
move toll router into decongestion module
replace eager singletons by normal singletons
do not bind classes directly if binding them to the interface also works
remove scenario argument for decongestion module (can and should be retrieved from injection)
add a more expressive test (existing tests did not fail if toll routing was removed)
> decongestion maintenance

- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/companions/DrtCompanionGroupIdentifier.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/companions/DrtCompanionModule.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/companions/DrtCompanionRideGenerator.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/companions/DrtCompanionUtils.java
This PR moves the PassengerGroupIdentifier information (stored in attributes) from the person level to the leg level. This is necessary, because an agent might travel with drt multiple times a day with different groups of companions. Each group needs to have its own PassengerGroupIdentifier.
> Moves PassengerGroupIdentifier for Drt Companions from Person to Leg

- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/companions/DrtCompanionRideGenerator.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/companions/DrtCompanionUtils.java
PR ensures that old PassengerGroupIdentifiers of initial rider legs are cleaned after each simulation.
> Clear PassengerGroupIdentifier (DrtCompanion)

- matsim/src/main/java/org/matsim/core/router/NetworkRoutingInclAccessEgressModule.java
in NetworkRoutingInclAccessEgressModule, the distance of the last link of a route was taken into account, whereas the travel time was not. This adjustment fixes this.
In the long-run, we should probably set more useful values for those relative positions on the link. But that is a bit more of a revolution :)
> improve traveltime calculation on last link of a route

- contribs/application/src/main/java/org/matsim/freightDemandGeneration/CarrierReaderFromCSV.java
- contribs/application/src/main/java/org/matsim/freightDemandGeneration/DemandReaderFromCSV.java
- contribs/application/src/main/java/org/matsim/freightDemandGeneration/FreightDemandGeneration.java
- contribs/application/src/test/java/org/matsim/freightDemandGeneration/DemandReaderFromCSVTest.java
fix error with population usage.
> Update freight generation

- matsim/src/main/java/org/matsim/core/network/NetworkUtils.java
There was no method to remove a `DisallowedNextLinks` attribute from a link. Now there is.
> Add method to remove DisallowedNextLinks attribute from link

- contribs/drt-extensions/src/test/java/org/matsim/contrib/drt/extension/edrt/run/RunEDrtScenarioIT.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/DefaultRequestInsertionScheduler.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/prebooking/PrebookingTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/run/examples/RunDrtExampleIT.java
There has been a bug when scheduling an insertion that has the same pickup and dropoff index (new dropoff directly following the new pickup along the stop sequence) just before a task with a prebooked pick-up. In that case, the *begin time* of the following pick-up task was illegally shifted to the past, or otherwise put, the fixed begin time of the prebooked task was not kept constant, thus blocking the vehicle for an unnecessary long time in a stop task. This PR fixes this issue, the performance of the prebooking scenario improves in the tests.
> fix(drt): scheduling a same-index insertion before a prebooked request

- contribs/drt-extensions/src/test/java/org/matsim/contrib/drt/extension/insertion/DrtInsertionExtensionIT.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGenerator.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGeneratorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/prebooking/PrebookingTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/run/examples/RunDrtExampleIT.java
Some rare insertions were missing when working with prebooking. These are insertions in which a request would be integrated in the stop sequence and where the *destination* of the new request equals the *origin* of a prebooked request before which it is supposed to be inserted. See `PrebookingTest::destinationEqualsPrebookedOrigin_*`.
> fix(drt): missing insertions for prebooking

- contribs/vsp/src/main/java/playground/vsp/ev/README.md
- contribs/vsp/src/main/java/playground/vsp/ev/UrbanEVModule.java
- contribs/vsp/src/main/java/playground/vsp/ev/UrbanEVTripsPlanner.java
- contribs/vsp/src/main/java/playground/vsp/ev/UrbanEVUtils.java
- contribs/vsp/src/test/java/playground/vsp/ev/UrbanEVTests.java
This PR adds the feature to define for which EV pre-planning for charging _during_ the drivers' activities should take place (as opposed to charging during a trip like it's done by the `EVNetworkRoutingModule`).
The definition is simply added as an `Vehicle` attribute.
Corresponding setters and getters are provided in the newly introduced `UrbanEVUtils`.
By default, it is assumed that all EV shall be replanned by the `UrbanEVTripsPlanner`, i.e. all EV shall be charged during activities and not legs. This default is set as, this behavior needs to be enabled by configuring the `UrbanEVModule` in the first place.
A corresponding test is included in `UrbanEVTests`.
> feat: define which EV to charge during activities

- contribs/application/src/main/java/org/matsim/application/options/ShpOptions.java
- contribs/application/src/test/java/org/matsim/application/options/ShpOptionsTest.java
Shp Index could only be queried for String attributes, now other datatypes are possible as well.
> Extend Shp Index with query methods for other datatypes

- contribs/application/pom.xml
- contribs/application/src/main/java/org/matsim/application/analysis/traffic/LinkStats.java
- contribs/application/src/main/java/org/matsim/application/prepare/CreateLandUseShp.java
- contribs/simwrapper/pom.xml
Update transitive pebble dependency, which hopefully works with java 21.
> Update pebble dependency

- contribs/common/src/main/java/org/matsim/contrib/common/util/WeightedRandomSelection.java
This adds a simple getter for the `totalWeight` property of the `WeightedRandomSelection` class. 
This is helpful in the case, where one receives a WRS object and does not know, whether calling `select()` will throw an exception if the total weight is 0. Now we can check this beforehand.
> Add getter for totalWeight to WeightedRandomSelection

- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/dashboards/DrtAnalysisPostProcessing.java
- contribs/drt-extensions/src/test/java/org/matsim/contrib/drt/extension/companions/RunDrtWithCompanionExampleIT.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtAnalysisControlerListener.java
Since the introduction of group bookings in drt, the customer stats were a bit inconsistent.
-> the "rides" column would count every passenger
-> the "rejections" are counted per request
A proposal would be to fix the customer stats such that:
-> there is a column rides_request which counts the number of served rides at the request level (similar to rejections)
-> and an additional column rides_pax which counts the total number of served passengers
(optionally) -> groupSize_mean which is the average group size of served requests (the division of the former two variables)
Any feedback is welcome
> account for group bookings in customer stats

- matsim/src/main/java/org/matsim/utils/objectattributes/attributeconverters/StringConverter.java
This PR makes the StringConverter threadsafe. There are currently hints that indicate a potential race condition as the same AttributeConverter references are used by all worker threads within the ParallelPopulationReaderMatsimV6
> Make StringConverter threadsafe

- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/fiss/FISS.java
When teleporting agents and vehicles with FISS, the travel time is computed from the congested travel times of the links of the route of the previous iteration. When querying the links' travel times, the person and vehicle have not been passed to the `TravelTime` object for consideration, which they now are.
> Pass person and vehicle to travel time query in FISS

- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/components/utils/NullWaitingTimeEstimator.java
- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/components/utils/PTWaitingTimeEstimator.java
- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/components/utils/ScheduleWaitingTimeEstimator.java
This change promotes the `double estimateWaitingTime(List<? extends PlanElement> elements)` method of the `ScheduleWaitingTimeEstimator` to its `PTWaitingTimeEstimator` interface as default implementation.
It was not part of the interface `PTWaitingTimeEstimator` before despite being public and being the most convenient way to use `ScheduleWaitingTimeEstimator`.
@sebhoerl Please let me know, if that is fine for you?
> Move method to PTWaitingTimeEstimator interface

- contribs/drt/src/main/java/org/matsim/contrib/drt/prebooking/PrebookingActionCreator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/prebooking/PrebookingStopActivity.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/prebooking/PrebookingTest.java
Since recently, we have the option to define pickup and dropoff durations per request using the `PassengerStopDurationProvider`. The stop logic with *prebooking* activated is that all persons enter the vehicle in parallel, taking into account the values obtained from that provider. The non-*prebooking* implementation does not make use of the interface yet (all dropoffs happen at the beginning of a stop with a fixed duration, all pickups happen at the end). So the following only affects simulations where *prebooking* is activated.
The following situation can arise:
- We have found a valid insertion for a new request
- The pickup is inserted into an existing stop in which 4 persons leave the vehicle (with capacity 4)
- The 4 persons will need 60s to leave the vehicle (from the stop duration …
> fix(drt): bugs with variable stop duration and prebooking stop logic

- contribs/small-scale-traffic-generation/src/main/java/org/matsim/smallScaleCommercialTrafficGeneration/prepare/CreateDataDistributionOfStructureData.java
- contribs/small-scale-traffic-generation/src/main/java/org/matsim/smallScaleCommercialTrafficGeneration/prepare/LanduseBuildingAnalysis.java
- contribs/small-scale-traffic-generation/src/main/java/org/matsim/smallScaleCommercialTrafficGeneration/prepare/LanduseDataConnectionCreator.java
- contribs/small-scale-traffic-generation/src/main/java/org/matsim/smallScaleCommercialTrafficGeneration/prepare/LanduseDataConnectionCreatorForOSM_Data.java
- contribs/small-scale-traffic-generation/src/test/java/org/matsim/smallScaleCommercialTrafficGeneration/TrafficVolumeGenerationTest.java
- contribs/small-scale-traffic-generation/src/test/java/org/matsim/smallScaleCommercialTrafficGeneration/prepare/LanduseBuildingAnalysisTest.java
- now it is possible to use different data sources because the assignment of the data categories of the input data and the used categories in the simulation can be set by the implementation
> Create interface for different landuse/building input data types for small-scale commercial traffic

- contribs/freight/src/main/java/org/matsim/freight/carriers/CarriersUtils.java
- now also logs the number of already solved carriers
> add some logging for VRP solving

- contribs/drt/src/test/java/org/matsim/contrib/drt/run/examples/RunDrtExampleIT.java
- matsim/src/main/java/org/matsim/core/utils/collections/QuadTree.java
- matsim/src/test/java/org/matsim/core/utils/collections/QuadTreeTest.java
try not to call Math.sqrt() for distance calculations, but work with the squared-distance where possible. Results in 2-3% faster getClosest()-calls.
> small performance improvement in QuadTree, code cleanup

- matsim/src/main/java/org/matsim/core/events/EventsReaderXMLv1.java
- matsim/src/test/java/org/matsim/core/events/EventsReadersTest.java
- matsim/src/test/resources/test/input/org/matsim/core/events/EventsReadersTest/events.xml
We (Moia) discovered that the reference attribute for personMoney events was always null when parsed by the EventsReaderv1 class. I added a hopefully-appropriate unit test for it in EventsReadersTest, and adjusted the events.xml fixture accordingly. 
Feedback is more than welcome!  cc @nkuehnel  @fzwick
> fix: personMoney event reference lookup missing in EventsReader

- contribs/simwrapper/src/main/java/org/matsim/simwrapper/SimWrapper.java
When adding dashboards to existing run outputs, Simwrapper normally would overwrite existing dashboards with the newly created noes. This change allows us to consider all available dashboards before adding the new one.
> simwrapper postprocessing dont overwrite existing dashboards

- contribs/application/src/main/java/org/matsim/application/options/CsvOptions.java
- contribs/application/src/test/java/org/matsim/application/options/CsvOptionsTest.java
When checking the delimiter by only reading the first csv line the method will fail for csv files with e.g. additional information like an EPSG (which is not in the delimiter separated format). Therefore, from now on the first 5 lines of the file will be read in to secure reading a line with delimiter separated data
> read first 5 lines of csv to check delimiter

- contribs/application/src/main/java/org/matsim/application/prepare/network/CreateGeoJsonNetwork.java
- matsim/src/main/java/org/matsim/core/utils/geometry/transformations/TransformationFactory.java
The `TransformationFactory` has some non-standard transformations and checks for conversions from/to WGS84. This method will now also accept EPSG:4326 .
> Recognize EPSG:4326 as equal to WGS84

- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZoneSystemParams.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/analysis/zonal/ReadOldConfigTest.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/DvrpTravelTimeMatrixParams.java
- examples/scenarios/kelheim/config-with-drt_old.xml
addresses https://github.com/matsim-org/matsim-libs/pull/3173#issuecomment-2134745460
> add backwards compatibility for dvrp matrix and drt zone system configs

- contribs/parking/src/main/java/org/matsim/contrib/parking/parkingproxy/LinearPenaltyFunctionWithCap.java
- contribs/parking/src/main/java/org/matsim/contrib/parking/parkingproxy/ParkingProxyModule.java
- contribs/parking/src/main/java/org/matsim/contrib/parking/parkingproxy/config/ParkingProxyConfigGroup.java
reduce amount of config parameters and not implemented options
> parkingProxy cleanup

- contribs/application/src/main/java/org/matsim/application/analysis/noise/NoiseAnalysis.java
- matsim/src/main/java/org/matsim/vehicles/MatsimVehicleReader.java
`NoiseAnalysis` matched `vehicles` from the run directory. In case of runs with dvrp, there are multiple of files matching that pattern. We need to make sure that the one, complete `output_vehicles` file is read.
> Debug noise analysis

- contribs/application/src/main/java/org/matsim/application/analysis/noise/NoiseAnalysis.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/dashboards/CreateDrtDashboard.java
- contribs/simwrapper/src/test/java/org/matsim/simwrapper/dashboard/NoiseDashboardTests.java
couldn't identify the correct *output_vehicles.xml.gz and there was no proper testing in `NoiseDashboardTests`.
Meanwhile fixed a typo in CreateDrtDashboard.
Tested with a proper Kelheim run. There, the noise link plot fails, but the GridMaps are correctly shown. Further debugging potentially comes with a new PR
> NoiseAnalysis

- matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorCore.java
- matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorData.java
- matsim/src/main/java/org/matsim/pt/transitSchedule/Constants.java
- matsim/src/main/java/org/matsim/pt/transitSchedule/TransitRouteStopImpl.java
- matsim/src/main/java/org/matsim/pt/transitSchedule/TransitScheduleReaderV2.java
- matsim/src/main/java/org/matsim/pt/transitSchedule/TransitScheduleWriterV2.java
- matsim/src/main/java/org/matsim/pt/transitSchedule/api/TransitRouteStop.java
- matsim/src/main/resources/dtd/transitSchedule_v2.dtd
- matsim/src/test/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorRestrictedBoardingAlightingTest.java
In reality, there are trains that call at stops but where it might not be allowed to enter or exit such trains. Examples are night trains, where on the first few stops, only boarding is allowed, while at the last few stops only alighting is allowed. This means that it is not allowed to use such night trains to just travel between the first few stops.
This commit adds two optional attributes `allowBoarding` and `allowAlighting` to TransitRouteStops, with the default value being true for backwards compatibility and when the attribute is not specified. SwissRailRaptor respects these attributes and will not return routes where agents would enter a vehicle at a route stop where boarding is not allowed, or where agents would exit a vehicle at a route stop where alighting is not allowed.
> Support TransitRouteStops where boarding or alighting is not allowed

- contribs/application/src/main/java/org/matsim/application/CommandRunner.java
- contribs/application/src/main/java/org/matsim/application/analysis/population/TripByGroupAnalysis.java
The TripAnalysis for subgroups will now also work if the provided mode shares do not sum to 1 in each group.
> Norm mode shares in TripAnalysis

- contribs/drt/src/main/java/org/matsim/contrib/drt/prebooking/PrebookingModeQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/prebooking/unscheduler/ComplexRequestUnscheduler.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/prebooking/AbandonAndCancelTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/prebooking/PrebookingTest.java
Hey @sebhoerl  I was playing around with the prebooking module - not sure if this was really missing or it was supposed to be bound elsewhere but when choosing the complex request unscheduler in prebooking there was a (modal) binding missing for the LeastCostPathCalculator
This also crashed when choosing this unscheduler in the matsim-code-example
> add router binding for complex request unscheduling

- contribs/application/src/main/java/org/matsim/freightDemandGeneration/DemandReaderFromCSV.java
- contribs/application/src/main/java/org/matsim/freightDemandGeneration/FreightDemandGeneration.java
- add missing case for Enum of population sampling
- add functionality to split a generated job in different jobs if the job demand is higher than the max capacity of each carrier vehicle
> Changes for freight demand generation

- matsim/src/main/resources/dtd/lspsDefinitions_v1.xsd
As noted by Billy in https://github.com/simwrapper/simwrapper/issues/215#issuecomment-2231201659 there was a not needed layer... this is now removed here in the definition file... 
Reader/Writer will be adapted in the logistics repo, once this PR is merged and the files are updated on the website. -- see also the issue https://github.com/matsim-vsp/logistics/issues/266
> Update LspsDefinition: remove one layer of "LSPs"

- contribs/freight/src/main/java/org/matsim/freight/carriers/controler/CarrierVehicleReRouter.java
- contribs/freight/src/main/java/org/matsim/freight/carriers/jsprit/NetworkBasedTransportCosts.java
- contribs/freight/src/main/java/org/matsim/freight/carriers/jsprit/VehicleTypeDependentRoadPricingCalculator.java
- contribs/freight/src/test/java/org/matsim/freight/carriers/jsprit/NetworkBasedTransportCostsTest.java
Use the official ` RoadPricingScheme` from the roadPrinciing contrib instead of a self-build `VehicleTypeDependentRoadPricingCalculator` for calculating the `NetworkBasedTransportCosts`.
The vehicleType-dependency can be achieved by using the `TollFactor`.
The `VehicleTypeDependentRoadPricingCalculator` is now deprecated.
Adding also some tests for running the  `NetworkBasedTransportCosts` calculation with tolls.
> Roadpring in Freight

- contribs/application/src/main/java/org/matsim/application/MATSimApplication.java
- contribs/application/src/main/java/org/matsim/application/ShowGUI.java
- matsim/src/main/java/org/matsim/run/gui/Gui.java
The MATSim GUI always starts the matsim process in the directory where the config is.
This leads to confusing behavior when run from the command line via matsim application contrib. 
This PR adds a function so that the default working directory in the gui can be changed.
> Preserve the working directory when gui is run from cli

- contribs/application/src/main/java/org/matsim/application/analysis/noise/NoiseAnalysis.java
.. such that all subtypes of `work` and `home` are considered by default (we typically split activities into act types with typical durations, see `SnzActivities`)
> NoiseAnalysis: use asterisk for act type default

- matsim/src/main/java/org/matsim/core/router/NetworkRoutingProvider.java
post work of #3348. adapted the method for network consistency check such that 
is only run once at the beginning and not always when a trip router object is requested.
@rakow fyi
> network consistency only once

- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/shifts/dispatcher/DefaultShiftScheduler.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/shifts/dispatcher/DrtShiftDispatcherImpl.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/shifts/dispatcher/ShiftScheduler.java
- contribs/drt-extensions/src/test/java/org/matsim/contrib/drt/extension/operations/shifts/run/RunOnTheFlyShiftDrtScenarioIT.java
Bypass fleet object to allow usage of the Fleet instance without creating a qSimModule.
> DRT: Bypass Fleet object in schedule interface

- contribs/vsp/src/main/java/org/matsim/contrib/vsp/pt/fare/DistanceBasedPtFareParams.java
- contribs/vsp/src/main/java/org/matsim/contrib/vsp/pt/fare/FareZoneBasedPtFareParams.java
- contribs/vsp/src/main/java/org/matsim/contrib/vsp/pt/fare/PtFareConfigGroup.java
- contribs/vsp/src/main/java/org/matsim/contrib/vsp/pt/fare/PtFareModule.java
- contribs/vsp/src/main/java/org/matsim/contrib/vsp/pt/fare/PtTripWithDistanceBasedFareEstimator.java
- contribs/vsp/src/test/java/org/matsim/contrib/vsp/pt/fare/FareZoneBasedPtFareHandlerTest.java
Writing the PtFareConfigGroup to file and read in again gave errors. This PR adds a test and fixes the error.
> Fix pt fare config write to and read from config file

- contribs/freight/src/main/java/org/matsim/freight/carriers/controler/CarrierDriverAgent.java
This issue came up, when working on the logistics project.
The CarrierDriverAgent passes only certain events to its scoring function.
With this PR, we add some more events, that gets passed through.
> Fix CarrierScoring with toll

- matsim/src/main/java/org/matsim/core/scoring/PlansScoringImpl.java
- matsim/src/main/java/org/matsim/core/scoring/PlansScoringModule.java
- matsim/src/test/java/org/matsim/core/scoring/EventsToScoreTest.java
Before the bugfix of this branch, MSA was not active, even if it was switched on via the config. The reason for this is that the NewScoreAssigner was recreated every iteration and therefore could not save any information across iterations. There was a test for MSA, but it did not create a complete controller, but only tested the scoring via EventsToScore individually, where the NewScoreAssigner was bound differently (correctly).
With the changes to this branch there is 1. a test that tests MSA scoring on a standard controller run (this test fails without the changes to this branch) and 2. the NewScoreAssigner is now bound as a singleton in the PlansScoringModule and is no longer recreated in PlansScoringImpl.
This change will probably affect a lot of your runs!
> Fix a (severe) bug in MSA scoring

- contribs/drt/src/main/java/org/matsim/contrib/drt/prebooking/PrebookingStopActivity.java
includes a performance related update by @sebhoerl proposed here:
https://github.com/matsim-org/matsim-libs/tree/feat/improve-prebooking-stop-activity
in addition, it adds a check to notifyPassengersAreReadyForDeparture in the prebooking stop activity such that only pickups are queued if they are still contained in expectedPickups. Otherwise it can happen that a request is abandoned in the same second as it is picked up, throwing an exception:
1. a request is part of a prebooking stop activity and registered in the expectedPickups map.
2. the vehicle arrives before the agent
3. the vehicle waits until the abandon voter votes for abandonment (e.g., after 10 mins) at time t, the request is removed from the expected pickups map and registers the abandonment at the prebookingmanager (no …
> update prebooking stop activity

- matsim/src/main/java/org/matsim/pt/utils/CreatePseudoNetwork.java
In PR #3357 loop-links have been added to PT pseudo networks. These loop links had not the correct mode, which is fixed in this PR.
> Use correct transit modes in pt pseudo network

- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/modules/DiscreteModeChoiceModule.java
- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/modules/UtilitiesWriterHandler.java
- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/modules/config/DiscreteModeChoiceConfigGroup.java
- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/modules/utils/ExtractPlanUtilities.java
- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/replanning/DiscreteModeChoiceAlgorithm.java
This PR allows a the DiscreteModeChoice Module, part of the discrete_mode_choice contrib, to output a file `dmc_utilities.csv` during iterations and at the end of the simulations. This file contains the utilities computed by the DMC models for each person, it has a header `person_id;utility`. 
The generation interval of this file during the iterations can be specified through the `writeUtilitiesInterval` parameter in the DiscreteModeChoice config group. 
This functionality is achieved by storing the utility as a plan attribute. This means that output population files also contain the utility. To generate the CSV file containing the utitlies from a population file, the `modules.utils.ExtractPlanUtilities` can be used.
> feat: DiscreteModeChoiceModule writes utilities as an output

- matsim/src/main/java/org/matsim/pt/utils/CreatePseudoNetwork.java
- matsim/src/main/java/org/matsim/pt/utils/CreatePseudoNetworkWithLoopLinks.java
@davibicudo @jfbischoff: The new pt pseudo network creator with loop-links is creating invalid schedules according to the TransitScheduleValidator. Especially, the network routes seem to be incorrect now.
I would appreciate, if you fix this issue and also add a test case for it. In this PR, I restored the old functionality and moved your new code to a separate class.
> Revert to old pseudo pt network creator

- contribs/application/src/main/java/org/matsim/application/prepare/network/params/NetworkParamsOpt.java
- contribs/application/src/main/java/org/matsim/application/prepare/network/params/ref/IndividualParams.java
- contribs/application/src/main/java/org/matsim/application/prepare/pt/CreateTransitScheduleFromGtfs.java
- contribs/application/src/test/java/org/matsim/application/prepare/pt/CreateTransitScheduleFromGtfsTest.java
Add network free speed model with one individual parameter for each link. This allows to fine-tune network speeds to individual scenarios (without the ability to generalize).
> Add additional network freespeed model

- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/DvrpTravelTimeMatrixParams.java
@nkuehnel 
In the DvrpConfigGroup class, the getTravelTimeMatrixParams() method creates a DvrpTravelTimeMatrixParams on the fly if it doesn't already exist (meaning it wasn't in the XML input or it wasn't added by the script that created the DvrpConfigGroup). 
However, when a DvrpTravelTimeMatrixParams is created in the above mentioned method, no ZoneSystemParams is created inside it. Which then causes a NullPointerException whenever the ZoneSystemParams  is requested and used. 
To address this, this PR continues the same approach of creating the params on the fly by creating a SquareGridZoneSystemParams with a cellSize of 200m, as was the default in the old implementation.
> chore: default zoning params in DvrpTravelTimeMatrixParams

- contribs/sumo/src/main/java/org/matsim/contrib/sumo/SumoNetworkConverter.java
- contribs/sumo/src/main/java/org/matsim/contrib/sumo/SumoNetworkFeatureExtractor.java
- contribs/sumo/src/main/java/org/matsim/contrib/sumo/SumoNetworkHandler.java
- contribs/sumo/src/test/java/org/matsim/contrib/sumo/SumoNetworkConverterTest.java
The SUMO Network converter now allows writing additional attributes found in the network. This is especially useful when osm attributes such as smoothness, surface, cycleway etc. should be kept
> Write additional attributes when using SUMO network converter

- contribs/cadytsIntegration/src/main/java/org/matsim/contrib/cadyts/car/PlansTranslatorBasedOnEvents.java
Fix memory leak in cadtys, which stored all plans ever encountered without any use to do so.
> Fix memory leak in cadyts

- contribs/application/src/main/java/org/matsim/application/ApplicationUtils.java
- contribs/simwrapper/src/main/java/org/matsim/simwrapper/dashboard/OverviewDashboard.java
- contribs/simwrapper/src/main/java/org/matsim/simwrapper/dashboard/PublicTransitDashboard.java
Some dashboards were not working correctly because the file matching patterns were expecting a run id in the filename.
> fix glob patterns in dashboards for runs without run id

- contribs/application/pom.xml
- contribs/application/src/main/java/org/matsim/application/prepare/pt/AdjustSameDepartureTimes.java
- contribs/application/src/main/java/org/matsim/application/prepare/pt/CreateTransitScheduleFromGtfs.java
- matsim/src/main/java/org/matsim/pt/utils/TransitScheduleValidator.java
This PR extends the existing `TransitScheduleValidator` with a few more plausibility checks:
- Every route should have a departure (will result in exception when running the simulation, otherwise)
- Validate travel times between stops. If there are unrealistic high speeds, stops are probably mapped to the wrong location.
Also, the `CreateTransitScheduleFromGtfs` cli was extended to allow incorporating external classes to fix such issues in the input data.
Added utility class that can fix issues in the schedule where multiple stops have the same arrival and departure times
> Additional transit schedule validations

- matsim/src/main/java/org/matsim/core/trafficmonitoring/TravelTimeCalculatorModule.java
- matsim/src/test/java/org/matsim/core/router/NetworkRoutingInclAccessEgressModuleTest.java
- matsim/src/test/java/org/matsim/core/trafficmonitoring/TravelTimeCalculatorModuleTest.java
During initialization, a `TravelTimeCalculator` is created for every network mode defined in the routing. However, not every of these modes are necessarily run on the network as well.  E.g. there could be routed only modes like, walk, bike, or ride that have a fixed travel time.
These will have a calculator installed that never does anything, but still takes up computing resources because it will process a lot of events.
In this PR the behavior is changed, so that a travel time calculator is only installed for analyzed modes, which can already be defined in the travel time config.
> Avoid creating unnecessary travel time calculators

- matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/QueueWithBuffer.java
- matsim/src/test/java/org/matsim/core/mobsim/qsim/qnetsimengine/QueueWithBufferTest.java
I added some unit tests for `QueueWithBuffer` because I was interested in the effects of different traffic dynamics settings. The test suite is not exhaustive, but the way we set up all the infrastructure could be used, in case someone wants to refactor something.
This tests:
- StorageCapacity on init for `queue` and `kinematicWaves`
- Time until storage capacity is freed on the upstream end, when a vehicle leaves the queue for `queue` and `kinematicWaves`
> Add tests some tests for QueueWithBuffer

- matsim/src/test/java/org/matsim/examples/simple/PtScoringTest.java
this test has been failing on Windows in the full-integration pipeline for a while: 
https://github.com/matsim-org/matsim-libs/actions/workflows/full-integration.yaml
> Fix PtScoringTest on Windows

- contribs/application/src/main/java/org/matsim/application/analysis/population/TripAnalysis.java
- contribs/application/src/main/java/org/matsim/application/analysis/population/TripByGroupAnalysis.java
- contribs/simwrapper/src/test/java/org/matsim/simwrapper/dashboard/DashboardTests.java
Add two additional outputs to the trip analysis:
- Mode chains, which collects all used main modes during the day, eg. walk-pt-bike
- Mode share by purpose (e.g. by work, leisure etc..)
> Extend trip analysis

- matsim/src/main/java/org/matsim/core/controler/ControlerDefaultsModule.java
- matsim/src/main/java/org/matsim/core/controler/OutputDirectoryHierarchy.java
- matsim/src/test/java/org/matsim/core/controler/OutputDirectoryHierarchyTest.java
This change makes the temp dir from the `OutputDirectoryHierarchy` configurable via a system property `matsim.tempDir`. The default behavior remains unchanged if this property is not set.
Currently, the ImageIO cache directory is hard coded to a tmp folder inside the output folder via `OutputDirectoryHierarchy`. We learned, that ImageIO is using some random access methods to write its temporary files which causes issues when using [mountpoint-s3](https://github.com/awslabs/mountpoint-s3/blob/main/doc/TROUBLESHOOTING.md#random-writes) for the output folder.
> Add matsim.tempDir property for specifying ImageIO cache directory

- matsim/src/main/java/org/matsim/core/config/consistency/VspConfigConsistencyCheckerImpl.java
Some VSP consistency checks have been updated:
- Considering car availability does not produce a warning anymore
- Setting marginal utilities for bike and ride is now allowed
> Update VSP Consistency checker

- contribs/application/src/main/java/org/matsim/application/analysis/noise/NoiseAnalysis.java
- contribs/noise/src/main/java/org/matsim/contrib/noise/NoiseConfigGroup.java
fixes #3519 (IMO) by 
1. setting (VSP-related) defaults for `noiseParameters.setNetworkModesToIgnoreSet` 
2. introducing consistency checks / warnings
3. clarfying comments in `NoiseAnalysis` and 
For further details please read #3519
> noiseAnalysis: defaults for networkModesToIgnore + consistency checks/warnings

- contribs/application/src/main/java/org/matsim/application/prepare/network/params/ApplyNetworkParams.java
- contribs/emissions/src/main/java/org/matsim/contrib/emissions/OsmHbefaMapping.java
- contribs/osm/src/main/java/org/matsim/contrib/osm/networkReader/LinkProperties.java
- contribs/sumo/src/main/java/org/matsim/contrib/sumo/SumoNetworkConverter.java
The SUMO network converter now also recognizes service, path and cycleway links, which allows adding bike infrastructure if necessary.
> Add more linktypes to the SUMO converter

- matsim/src/main/java/org/matsim/vehicles/VehicleUtils.java
- needed for the latest update of #3532 
- for the defaultVehicleType we should set a networkMode to get no exception
> add networkMode to defaultVehicleType

- contribs/ev/src/main/java/org/matsim/contrib/ev/infrastructure/Charger.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/infrastructure/ChargerDefaultImpl.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/infrastructure/ChargerReader.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/infrastructure/ChargerSpecification.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/infrastructure/ChargerWriter.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/infrastructure/ChargingInfrastructureModule.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/infrastructure/ImmutableChargerSpecification.java
- contribs/ev/src/test/java/org/matsim/contrib/ev/infrastructure/ChargerReaderWriterTest.java
- matsim/src/main/resources/dtd/chargers_v1.dtd
This PR makes `ChargerSpecification` and indirectly `Charger` attributable. The functionality is provided to read and write chargers with attributes just like it works for persons, facilities, etc. 
While doing this, the PR also adds a general unit test for reading/writing chargers, plus another one where attributes are used.
The DTD for the chargers is changed in this PR. I don't think we need to introduce a v2, because the basic structure is not changed, only the attributes are added as an optional feature. But may somebody who is more familiar with how DTDs are handled can comment on this?
> feat: make chargers attributable

- matsim/src/main/java/org/matsim/facilities/FacilitiesWriterV1.java
- matsim/src/main/java/org/matsim/facilities/FacilitiesWriterV2.java
The FacilitiesWriter creates surprisingly large files when using ZST compression, because flush is called too early. This PR fixes the problem, analog to https://github.com/matsim-org/matsim-libs/issues/2764.
> Flush FacilitiesWriter only at the end to reduce Filesize

- matsim/src/main/java/org/matsim/pt/utils/CreateVehiclesForSchedule.java
Restores the old behavior of `CreateVehiclesFromSchedule` with the option to specify a different network mode.
> introduce now necessary network mode to generated vehicles

- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/router/DvrpModeRoutingNetworkModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/DvrpModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/DvrpTravelTimeMatrixParams.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/FreeSpeedTravelTimeMatrix.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/SparseMatrix.java
- contribs/dvrp/src/test/java/org/matsim/contrib/zone/skims/FreeSpeedTravelTimeMatrixTest.java
When working with large scenarios, calculating the dvrp global and mode-specific free-speed matrices takes a lot of time, especially when parametric studies are run in which this has to happen at every simulation start-up. 
This PR introduces the possibility to cache the calculated free-speed matrices using the `cachePath` parameter in the respective `DvrpTravelTimeMatrixParams`. If the file does not exist, the matrix calculation is performed as usual and saved. If the file exists already, the matrix is read from the file. This way, when setting a global path, the calculation will be performed once in the parametric simulation series and then only read for all subsequent runs. There are various verifications included in the reading code to make sure that the travel times contained in the …
> feat(dvrp): cached free-speed matrices

- contribs/decongestion/pom.xml
Use §{project.parent.version}, because the expression ${parent.version} is deprecated.
(This warning came from the log of the weekly builds: 
)
> Update deprecated expression in pom of decongestion contrib

- contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/DeterminismTest.java
- matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorCore.java
- matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorData.java
- matsim/src/test/java/ch/sbb/matsim/RaptorDeterminismTest.java
Hi @mrieser,
@sebhoerl  and I noticed that some of our simulations were not determinstic (i.e, running the same simulation twice did not necessarily generate the same events and plans). After investigating we found out that there are at least 2 places in SwissRailRaptor that are not deterministic. 
- `DefaultRaptorStopFinder.findStops` does not always return the same stops, we tracked this down to the initialization of the stops `QuadTree` in `SwissRailRaptorData.create` where stops are retrieved from a `HashMap`. We replaced it by a `LinkedHashMap` to always have the same order. 
- After this fix, raptor still does not always return the same elements, we tracked this down to `SwissRailRaptorCore.calcLeastCostRoute` where some `HashMap` objects are also built then looped over, which we …
> Fix: Non-deterministic behaviour of SwissRailRaptor

- contribs/common/src/main/java/org/matsim/contrib/common/zones/systems/grid/square/SquareGridZoneSystem.java
Initialize index to links once at the beginning, instead of doing again and again the same lookup.
> Improve SquareGridZoneSystem performance

- contribs/application/pom.xml
- contribs/application/src/main/java/org/matsim/application/prepare/pt/CreateTransitScheduleFromGtfs.java
- matsim/src/main/java/org/matsim/pt/utils/CreatePseudoNetworkWithLoopLinks.java
- matsim/src/test/java/org/matsim/pt/utils/CreatePseudoNetworkWithLoopLinksTest.java
- The`CreatePseudoNetworkWithLoopLinks` class now creates valid network routes
- Loop links need to be part of the network route
- Attributes of the loop links should be more reasonable now
- Added test case to check if schedule is valid
- Updated gtfs2matsim and `CreateTransitScheduleFromGtfs`accordingly:
- Added option to choose how the pseudo network should be created
- Added option to define how stops should be merged
@jfbischoff
> Improve PT pseudo network with loop links

- contribs/drt-extensions/src/test/java/org/matsim/contrib/drt/extension/operations/shifts/run/RunPrebookingShiftDrtScenarioIT.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/prebooking/logic/AttributeBasedPrebookingLogic.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/prebooking/PrebookingTestEnvironment.java
A colon was missing in the attribute-based prebooking logic. And a convenience setter has been added.
> fix(drt): names in attribute-based prebooking

- contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingModule.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingPriority.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingWithQueueingAndAssignmentLogic.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingWithQueueingLogic.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ElectricFleetSpecificationDefaultImpl.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ElectricVehicleSpecificationDefaultImpl.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/infrastructure/ChargingInfrastructureSpecificationDefaultImpl.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/reservation/ChargerReservationManager.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/reservation/ChargerReservationModule.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/reservation/ReservationBasedChargingPriority.java
This PR makes three modifications to the `ev` contrib:
**Testing**
- Some classes are made `public` as we need them to construct comprehensive unit tests for the `ev` contrib in later PRs.
**Charging priorities**
- The `ChargingPriority` is introduced: it is used for managing the charging queue, which, currently, is a simple FIFO. With `ChargingPriority` we now traverse the queuing vehicles and let them pass on to charging if the `ChargingPriority` returns `true`. This means that we can retain certain vehicles if others should get plugged with a higher priority than them.
**Reservations**
- A useful implementation of `ChargingPriority` is provided, which is `ReservationBasedChargingPriority`
- As soon as a vehicle enters the queue of a charger, it is checked whether there is space and …
> feat(ev): add charging priorities and reservations

- contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingWithQueueingLogic.java
Fixes a bug introduced in #3587 when removing a queued vehicle from a charger, but which was not covered by the existing unit tests. In a follow-up PR we'll push comprehensive tests for the `ev` contrib, which allowed us to detect this issue.
> fix(ev): unqueuing a vehicle

- contribs/freight/src/main/java/org/matsim/freight/carriers/CarrierShipment.java
The Builder infrastructure for creating a CarrierShipment **without** an Id of the shipment has now been deprecated for years. 
Thus, it gets removed now.
> Freight (Carrier): Remove long-time deprecated Builder

- contribs/application/src/main/java/org/matsim/application/options/ShpOptions.java
- matsim/src/main/java/org/matsim/core/utils/gis/GeoFileReader.java
Adds support for using GeoPackage via URLs in `ShpOption` as well as `GeoFileReader`. 
URLs are not natively supported, and the content will be saved to a temporary file instead.
> Support GeoPackage via URL

- contribs/informed-mode-choice/src/main/java/org/matsim/modechoice/replanning/SelectSubtourModeStrategy.java
- contribs/informed-mode-choice/src/main/java/org/matsim/modechoice/search/TopKChoicesGenerator.java
- contribs/informed-mode-choice/src/test/java/org/matsim/modechoice/replanning/SelectVsRandomSubtourTest.java
- matsim/src/test/java/org/matsim/core/replanning/choosers/BalancedInnovationStrategyChooserTest.java
- Some new RNG based tests fail on the integration test.  The tolerances have been increased, so they should pass there as well.
- Improve estimation of daily costs for PT trips that don't include any real PT leg.
> IMC Maintenance + Test Fixes

- matsim/src/test/java/ch/sbb/matsim/RaptorDeterminismTest.java
We had a couple of regression test failures, presumably because of time limits, see #3687 .  On my local machine, `RaptorDeterminismTest#testRaptorDeterminism` took so long that I interrupted it.  I counted 20sec per 10000 agents, and it goes  to 100'000 agents (i.e. 200sec ≈ 3min 30sec).   I don't know how computing times on my laptop compare to github actions, but this seems more than we can afford.  **As a quick fix, I reduced the test to 10'000 agents.**  
However, I am sceptical in general if we can have such "shotgun tests" as part of the normal regression suite.  We used to have the *IT tests, which were run separately and only about once a week.  I do not know if that functionality still works.
> reduce to 10000 persons

- matsim/src/main/java/org/matsim/core/scoring/EventsToActivities.java
- matsim/src/main/java/org/matsim/core/scoring/EventsToLegs.java
This PR makes use of IdMaps and the code avoids now the creation of multiple exp. act or leg while looping over handlers. Each handler should get the same instance of an object. One could even think to make the act or leg immutable, as the scoring should just read something and not modify information.
> Minor improvments within scoring 

- matsim/src/main/java/org/matsim/core/router/speedy/LeastCostPathTree.java
the comingFrom[nodeIndex] data structure is exposed and used for path construction in the OneToManyPathCalculator. However, some nodes may internally be reached via colored nodes which are not known outside the speedy graph structure. So make sure to always return the uncolored node id index
> fix turn restriction related bug in LeastCostPathTree

- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeModule.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/router/DvrpModeRoutingNetworkModule.java
Following #3716, this PR fixes another edge case regarding DVRP travel times matrices: By default, the path configured in the `DvrpTravelTimeMatrixParams` is used when the travel time matrix is generated for DVRP. However, DRT may allow the user to `useModeFilteredSubnetwork` to filter the network by the DRT mode. In that case, still the same path was used, although a different matrix (the one only for DRT) should be written at that point. This PR introduces a new config option `travelTimeMatrixCachePath` in the `DrtConfigGroup` which now lets the user define specifically where the mode-specific matrix is saved if `useModeFilteredSubnetwork` is active.
> fix(dvrp): edge case for cached TT matrices

- matsim/src/main/java/org/matsim/core/network/turnRestrictions/DisallowedNextLinksUtils.java
- matsim/src/test/java/org/matsim/core/network/DisallowedNextLinksUtilsTest.java
With the introduction of the `DisallowedNextLinks` attribute to network links (#2855) in order to model turn restrictions, there can be more opportunities for inconsistency within a network.
You could already use `DisallowedNextLinksUtils.isValid(Network)` to check and print these inconsistencies.
Now all invalid `DisallowedNextLinks` attributes can be fixed/removed with `DisallowedNextLinksUtils.clean(Network)`.
> Add cleaning method for DisallowedNextLinks

- contribs/informed-mode-choice/src/main/java/org/matsim/modechoice/search/TopKChoicesGenerator.java
Fix a null pointer exception in case no plan candidates have been generated.
> Fix in IMC when no plan candidate is feasible

- contribs/drt-extensions/src/test/java/org/matsim/contrib/drt/extension/reconfiguration/CapacityReconfigurationTest.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtModeAnalysisModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/load/DvrpLoadParams.java
It makes more sense to control the analysis interval for multidimensional loads / capacities inside the DvrpLoadParams instead of the main DRT config group.
> chore: move config option for load analysis

- matsim/src/test/java/ch/sbb/matsim/RaptorDeterminismTest.java
Following #3687 and #3688, I have reworked the code of the integration test to avoid loading more than 2 samples/scenarios at the same time in memory. This makes the memory usage independent of the number of samples that are compared.
Previously with 5 samples with the limit of 10000 agents being compared, the heap size peaked at 800Mb, now it peaks at 400Mb with any number of samples and without the limit of 10000 agents. 
Depending on the amount of memory available for the IT, the garbage collector might not even kick in now and that could reduce the run time. With this in mind, I reset the number of samples to 10 as 5 samples were not always enough to identify some of the non-deterministic behaviour I encountered in the past.  
I propose to test and adjust the number of samples if …
> Chore: optimizing memory usage of TestRaptorDeterminism IT

- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/FreeSpeedTravelTimeMatrix.java
During simulations at MOIA we noticed that for some scenarios, when there is no pre-calculated freespeed cache, it can be costly to create on the fly. For a filtered service area depicting Hamburg it took 122s just to write the freespeed TT cache file (excluding calculation time). 
With this implementation that falls to 18 seconds, albeit still using only a single core so there is still room for improvement. 
I *could* also provide a strawman parallelised implementation brings the time down to ~2s (on an 8 core Macbook M2), but it adds significant complexity to the code.
> Improve write speed in FreeSpeedTravelTimeMatrix

- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/preplanned/run/PreplannedDrtModeModule.java
- contribs/drt-extensions/src/test/java/org/matsim/contrib/drt/extension/estimator/MultiModalDrtLegEstimatorTest.java
- contribs/drt-extensions/src/test/java/org/matsim/contrib/drt/extension/reconfiguration/CapacityReconfigurationTest.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtModeAnalysisModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeModule.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/estimator/DrtEstimateAndTeleportTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/teleportation/DrtTeleportationTest.java
The `DvrpLoadParams` and `DrtEstimatorParams` parameter sets in the `DrtConfigGroup` are initialized directly with the attributes declaration. This causes an inconsistency with the base `ConfigGroup` class as these two parameter sets are not recorded in the `ConfigGroup.parameterSetsPerType` attribute. Which can cause a crash if the method `removeParameterSet` is called with one of the two sets mentioned above.
This PR fixes this by initializing the parameter sets in the constructor by calling the `addParameterSet` method.
> fix: properly initializing DvrpLoadParams and DrtEstimatorParams in DrtConfigGroup

- contribs/drt/src/main/java/org/matsim/contrib/drt/prebooking/PrebookingManager.java
- matsim/src/main/java/org/matsim/api/core/v01/events/PersonStuckEvent.java
The implementation for making agents stuck if their prebooked request is rejected was still not ideal:
- When an agent is on a leg, the next activity is set to an infinite end time, which makes the ActivityEngine let the agent go to sleep like on a regular end of day (without a specific *stuck* event). In that case, it would be nice to have the source of ending the day being identified as being stuck.
- When an agent is on an activity, we ended the activity in the same way, but additionally created a *stuck* event (nice!). However, we call `AgentCounter.decLiving` which is also called by the `ActivityEngine` which sends the agent to sleep. In consequence, the counter is called twice and in some particular situations (no fixed end time), this makes the simulation stop too early because the …
> fix: prebooking setting agents stuck

- contribs/application/src/main/java/org/matsim/application/prepare/population/PersonNetworkLinkCheck.java
- contribs/application/src/main/java/org/matsim/application/prepare/scenario/CreateScenarioCutOut.java
- contribs/application/src/test/java/org/matsim/application/prepare/scenario/CreateScenarioCutOutTest.java
- contribs/application/test/input/org/matsim/application/prepare/scenario/CreateScenarioCutOutTest/withEvents/cut_change_events.xml
- matsim/src/main/java/org/matsim/core/population/algorithms/PersonPrepareForSim.java
This PR improves the scenario cutout and adds functionality to remove invalid link ids from a population.
- New `PersonNetworkLinkCheck` class
- When links are removed from a network, all occurrences of it must be removed from the population or the simulation will most likely crash.
- Some previously existing classes only check network routes, but this implementation checks all routes and activities as well.
-  The `CreateScenarioCutOut` writes a lot less network change events, by only writing events when an actual change in speed has occurred.
> Improved Scenario Cutout

- contribs/commercialTrafficApplications/src/main/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/TourPlanning.java
- contribs/freight/src/main/java/org/matsim/freight/carriers/CarrierImpl.java
- contribs/freight/src/main/java/org/matsim/freight/carriers/CarrierPlan.java
- contribs/freight/src/main/java/org/matsim/freight/carriers/CarrierPlanReaderV1.java
- contribs/freight/src/main/java/org/matsim/freight/carriers/CarrierPlanXmlParserV2.java
- contribs/freight/src/main/java/org/matsim/freight/carriers/CarrierPlanXmlParserV2_1.java
- contribs/freight/src/main/java/org/matsim/freight/carriers/CarriersUtils.java
- contribs/freight/src/main/java/org/matsim/freight/carriers/controller/CarrierVehicleReRouter.java
- contribs/freight/src/main/java/org/matsim/freight/carriers/jsprit/MatsimJspritFactory.java
- contribs/freight/src/main/java/org/matsim/freight/carriers/usecases/chessboard/InitialCarrierPlanCreator.java
- contribs/freight/src/main/java/org/matsim/freight/carriers/usecases/chessboard/SelectBestPlanAndOptimizeItsVehicleRouteFactory.java
- contribs/freight/src/main/java/org/matsim/freight/logistics/resourceImplementations/CarrierSchedulerUtils.java
- contribs/freight/src/main/java/org/matsim/freight/logistics/resourceImplementations/DistributionCarrierScheduler.java
- contribs/freight/src/main/java/org/matsim/freight/logistics/resourceImplementations/MainRunCarrierScheduler.java
- contribs/freight/src/test/java/org/matsim/freight/carriers/jsprit/FixedCostsTest.java
- contribs/freight/src/test/java/org/matsim/freight/carriers/jsprit/IntegrationIT.java
- contribs/freight/src/test/java/org/matsim/freight/carriers/jsprit/MatsimTransformerTest.java
- contribs/freight/src/test/java/org/matsim/freight/carriers/jsprit/SkillsIT.java
- contribs/freight/src/test/java/org/matsim/freight/carriers/utils/CarrierControllerUtilsIT.java
- contribs/freight/src/test/java/org/matsim/freight/carriers/utils/CarrierControllerUtilsTest.java
- contribs/freightreceiver/src/main/java/org/matsim/freight/receiver/ReceiverTriggersCarrierReplanningListener.java
The backpointer to the carrier will be set, when using the addPlan() method.
This method is called anyway when creating a Carrier with a CarrierPlan. 
So one now can create a `CarrierPlan` and then add it later to a `Carrier.`
This is now analogous as it is done with Persons and their Plans.
> Freight (Carrier): CarrierPlan does not need the Carrier in the constructor 

- contribs/drt/src/main/java/org/matsim/contrib/drt/prebooking/PrebookingManager.java
follow up on #3758 which incorrectly removed the agents from the stuck on activity queue even if they haven't reached the activity yet
> hotfix stucked prebooking agents

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/demandestimator/PreviousIterationDrtDemandEstimator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/DrtModeMinCostFlowRebalancingModule.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/rebalancing/demandestimator/PreviousIterationDrtDemandEstimatorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingStrategyTest.java
The PreviousIterationDrtDemandEstimator is a very mysterious and powerful class and it's mystery is exceeded only by it's power.
We identified other cases where an estimation of the drt demand of the previous iteration may be helpful (besides min cost flow rebalancing, that is). To avoid duplication we would like to re-use the class in other places.
However, one of our use case needs the demand in the replanning step, i.e., between the iterations. We would therefore like to change the behavior such that the estimator consolidates _after_ an iteration instead of _before_ the next one by adding the IterationEndsListener interface
Let me know if there is any objection
> Consolidate PreviousIterationDrtDemandEstimator at the end of the iteration

- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/shifts/dispatcher/AssignShiftToVehicleLogic.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/shifts/dispatcher/DefaultAssignShiftToVehicleLogic.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/shifts/dispatcher/DefaultShiftScheduler.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/shifts/dispatcher/DefaultShiftStartLogic.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/shifts/dispatcher/DrtShiftDispatcher.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/shifts/dispatcher/DrtShiftDispatcherImpl.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/shifts/dispatcher/ShiftScheduler.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/shifts/dispatcher/ShiftStartLogic.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/shifts/io/DrtShiftsReader.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/shifts/io/DrtShiftsWriter.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/shifts/shift/DrtShift.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/shifts/shift/DrtShiftImpl.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/shifts/shift/DrtShiftSpecification.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/shifts/shift/DrtShiftSpecificationImpl.java
- contribs/drt-extensions/src/test/java/org/matsim/contrib/drt/extension/operations/shifts/ShiftsIOTest.java
- contribs/drt-extensions/test/input/org/matsim/contrib/drt/extension/operations/shifts/testShifts.xml
adds the option to define a shift type.
this may be used for specialized (driver) shifts, e.g., for wheelchair accessible vehicles or otherwise specialized personnel
in addition, this can also be used to model remote operator or maintenance shifts in autonomous settings
> DRT shifts: add shift type

- matsim/src/main/java/org/matsim/analysis/IterationTravelStatsControlerListener.java
A rather nasty bug, as trips and legs were written in every iteration.
> do not write trips and legs in every iteration

- contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/DefaultDvrpLoadFromTrip.java
very minor thing, but I believe the variable names were supposed to be swapped
> DVRP: swap variable names in DVRP load from trip

- contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ElectricFleet.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ElectricFleetUtils.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/strategic/README.md
- contribs/ev/src/main/java/org/matsim/contrib/ev/strategic/StrategicChargingUtils.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/strategic/scoring/ChargingPlanScoring.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/strategic/scoring/ChargingPlanScoringParameters.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/withinday/WithinDayEvEngine.java
- contribs/ev/src/test/java/org/matsim/contrib/ev/strategic/utils/TestScenarioBuilder.java
- contribs/vsp/src/main/java/playground/vsp/ev/RunUrbanEVExample.java
1. This PR mainly provides additional documentation on the `ev` contrib.
2. Some typos are fixed.
3. A utility method to define a vehicle type to be electric is introduced in `ElectricFleetUtils.setElectricVehicleType` (which delegates to `VehicleUtils`).
4. Some potential bugs in the sevc packages are commented. I will point out those below.
5. The ReadMe is updated. 
It does feel a little ... confusing that one has to call the` _Within_DayEVEngine` to activate strategic charging behavior (to me and to people from Lund TH). Having said that, it does make sense that the charging behavior functionality resides in the within-day package, rather than in the strategic package. I wonder whether it should be in its own package, but probably not.
> ev: improve documentation, provide utility function and comments

- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/components/constraints/LinkAttributeConstraint.java
- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/components/constraints/ShapeFileConstraint.java
- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/components/constraints/SubtourModeConstraint.java
- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/components/constraints/TransitWalkConstraint.java
- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/components/constraints/VehicleTourConstraint.java
- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/components/constraints/VehicleTripConstraint.java
- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/constraints/CompositeTourConstraintFactory.java
- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/constraints/CompositeTripConstraintFactory.java
- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/constraints/TourFromTripConstraintFactory.java
- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/mode_chain/DefaultModeChainGenerator.java
- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/nested/NestedLogitSelector.java
- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/utilities/MultinomialLogitSelector.java
- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/utilities/RandomSelector.java
This PR proposes some code cleanups in the discrete_mode_choice contrib. Mainly, the signatures of methods in Factory classes were modified to declare the specific implementation as a return type rather than the generic interface.
> chore: code cleanup in discrete_mode_choice contrib

- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/components/estimators/CumulativeTourEstimator.java
- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/constraints/CompositeTourConstraint.java
- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/constraints/TourFromTripConstraint.java
- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/tour_based/EfficientTourBasedModel.java
- contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/modules/ModelModule.java
- contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/examples/TestSiouxFalls.java
This PR proposed an alternative implementation of the `TourBasedModel` in the `discrete_mode_choice` contrib that aims to be more computationally efficient.
The default implementations follows 5 steps:
- 1 - enumerates all possible mode chains for a tour without routing the trips
- 2 - checks 'before estimation' constraints to filter out some alternatives
- 3 - performs the routing and the estimation of the tour
- 4 - checks 'after estimation' constraints to filter out more alternatives
- 5 - select the 'best' tour alternative according to the specified selector
The main drawback if the approach is that the explicit and independent enumeration of possible alternatives. Alternatives with the same modes for the first n-trips are not explicitly linked (even though the routing cache will …
> feat: EfficientTourBasedModel implementation alternative of the TourBasedModel in the discrete_mode_choice contrib

- matsim/src/main/java/org/matsim/core/config/ReflectiveConfigGroup.java
Previously, the annotation-based parameters were not listed in the error message.
> fix(core): correctly list registered params when adding unknown param

- matsim/src/main/java/org/matsim/core/controler/ControllerUtils.java
- matsim/src/main/java/org/matsim/core/controler/Injector.java
- matsim/src/main/java/org/matsim/core/events/EventsManagerImpl.java
This PR makes it so that the config file and the exhaustive logging of every individual event handler is only logged for debug level DEBUG or higher. This can be changed manually via environment variable and manually by the programmer.
Relates to: #3801
> chore: reduce logging of config, eventsmanager, injector [3801]

- contribs/ev/src/main/java/org/matsim/contrib/ev/strategic/StrategicChargingModule.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/strategic/replanning/innovator/RandomChargingPlanInnovator.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/strategic/scoring/ChargingPlanScoring.java
Use the central TimeInterpretation object when determining the travel time of a leg.
This ensures that 
1. the leg's route is queried in case that the travel time attribute of the leg itself is not set
2. the same logic is used as in other places/contribs
> chore: use TimeInterpretation for determination of leg travel time

- matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/RaptorUtils.java
- matsim/src/main/java/org/matsim/pt/router/TransitRouterConfig.java
The SwissRailRaptor needs teleportation walk params.  It takes them from the `walk` mode.  However, if one wants to route walk on the network, then these params do not exist.  I now first check `transit_walk` and then `non_network_walk` before checking walk ... so one can set one of the other two to meaningful values and then it will not check the walk teleportation param at al.
> feat: allow transit_walk or non_network_work teleportation params instead of walk teleportation params

- matsim/src/main/java/org/matsim/core/network/turnRestrictions/DisallowedNextLinksUtils.java
- matsim/src/test/java/org/matsim/core/network/turnRestrictions/TurnRestrictionsSimulationIT.java
This change adds an integration test that simulates on a network with turn restrictions and checks whether disallowed next links (introduced in [#2855](https://github.com/matsim-org/matsim-libs/issues/2855)) are not traversed by any agent.
There is currently one exception, see [#3804](https://github.com/matsim-org/matsim-libs/issues/3804), as the router starts routing from the toNode, turn restrictions on the startLink are not considered. 
This closes https://github.com/matsim-org/matsim-libs/issues/3795
> chore(turnrestrictions): Add integration test for simulation with turn restrictions

- matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/QueueWithBuffer.java
We think the maxFlowFromFdiag in QueueWithBuffer should be scaled with the flow capacity factor because this scales how much flow can be send/received per time.
Unfortunately, there are no tests failing when we make changes here, i.e. the qsim behavior with kinematic waves seems to be not suitable covered by tests. Still, simulation outcome of the Berlin scenario differs a lot when we scale the inflow capacity (car mode shares go significantly down!). This has to be investigated further! For now, we leave the inflow capacity (unscaled) as before.
> revert (QSim): multiplying the inflow capacity with the flow capacity factor

- .github/pull_request_template.md
Add a PR template that describes that we are using conventional commits. Start with the bare minimum.
> docs(GitHub): Add PR template

- .github/pull_request_template.md
I'd suggest to provide the list of possible/recommended types with a short explanation in the PR template. This is taken from the error message, when the Conventional Commits check fails.
> docs(GitHub): Add explanation of available types for Conventional Commits

- contribs/signals/src/main/java/org/matsim/codeexamples/runSignalsAndLanesOsmNetworkReader/RunSignalsAndLanesOsmNetworkReader.java
- contribs/signals/src/test/java/org/matsim/contrib/signals/network/SignalsAndLanesOsmNetworkReaderTest.java
- contribs/vsp/src/main/java/playground/vsp/andreas/utils/net/OSM2MATSim.java
- matsim/src/main/java/org/matsim/core/network/NetworkUtils.java
- matsim/src/main/java/org/matsim/core/network/algorithms/NetworkSimplifier.java
- matsim/src/main/java/org/matsim/core/network/algorithms/intersectionSimplifier/RunIntersectionSimplifier.java
- matsim/src/main/java/org/matsim/core/network/turnRestrictions/DisallowedNextLinksUtils.java
- matsim/src/test/java/org/matsim/core/network/DisallowedNextLinksUtilsTest.java
When simplifying networks with turn restrictions #2855 we need to ensure that the `DisallowedNextLinks` objects are adjusted when merging links.
This change adds the required logic for merging links with turn restriction info and makes it the default through a new method `NetworkUtils.simplifyNetwork(Network)` at most places where the `NetworkSimplifier` has been used without these adaptions.
https://github.com/matsim-org/matsim-libs/blob/583570c48ff5828452e053bdd6a4b05199cf1461/matsim/src/main/java/org/matsim/core/network/NetworkUtils.java#L890-L901
> feat(core): Simplify network with turn restrictions

- matsim/src/main/java/org/matsim/core/mobsim/qsim/QSim.java
- matsim/src/main/java/org/matsim/core/population/PopulationImpl.java
- matsim/src/main/java/org/matsim/core/population/PopulationUtils.java
- matsim/src/main/java/org/matsim/core/scenario/ScenarioUtils.java
The scale attribute introduced here is meant for documentation purposes for now but could be consumed for analyses or for code consuming the data.
> feat(core): add option to add "scale" attribute to MATSim containers and introduce helper methods for population

- matsim/src/main/java/org/matsim/core/controler/ControllerUtils.java
- matsim/src/main/java/org/matsim/core/controler/Injector.java
- matsim/src/main/java/org/matsim/core/events/EventsManagerImpl.java
- matsim/src/main/java/org/matsim/core/router/PlanRouter.java
- matsim/src/main/resources/log4j2.xml
Configure log4j to optionally override the log level of the root logger **if** the LOG_LEVEL environment variable is set, **if unset** it will continue to default to info.
To make it easy to switch log levels when executing matsim remotely without recompiling code, for example to get more context on a crash. 
Relates to: #3801
> chore: respect log level environment var

- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/insertion/spatialFilter/SpatialRequestFleetFilter.java
Details:
- in some simulations it happened that the vehicles kept in the spatial tree were not available anymore in the simulation, resulting in an NPE
- not all DrtTastTypes have a baseType. This case is now handled by ignoring those tasks, rather than crashing.
> fix: small fixes in SpatialRequestFleetFilter

- matsim/src/main/java/org/matsim/core/replanning/inheritance/PlanInheritanceModule.java
Use the default delimiter from the globalConfigGroup insteaf of a custom version.
> refactor(PlanInheritanceModule): Make use of matsim default delimiter

- matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/RaptorRoute.java
- matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/RaptorStaticConfig.java
- matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/RaptorUtils.java
- matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorCore.java
- matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorData.java
- matsim/src/main/java/org/matsim/pt/routes/DefaultTransitPassengerRoute.java
- matsim/src/main/java/org/matsim/pt/routes/ExperimentalTransitRoute.java
- matsim/src/main/java/org/matsim/pt/routes/TransitPassengerRoute.java
- matsim/src/main/java/org/matsim/pt/transitSchedule/ChainedDepartureImpl.java
- matsim/src/test/java/ch/sbb/matsim/routing/pt/raptor/ScrambleTransitSchedule.java
- matsim/src/test/java/ch/sbb/matsim/routing/pt/raptor/StripTransitSchedule.java
- matsim/src/test/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorChainedDepartureTest.java
- matsim/src/test/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorDataTest.java
- matsim/src/test/java/org/matsim/pt/routes/DefaultTransitPassengerRouteTest.java
- matsim/test/input/ch/sbb/matsim/routing/pt/raptor/network.xml
- matsim/test/input/ch/sbb/matsim/routing/pt/raptor/schedule.xml
This PR is a follow-up to #3901. The transit router now supports chained departures and finds connections without transfers if departures are chained. 
`DefaultTransitPassengerRoute` was modified to support these new routes that may consist of multiple sections.
Note that they are not handled by pt passengers and driver agents yet. Simulating these will be implemented in a later PR.
> feat(pt): Support chained depatures in routing

- matsim/src/main/java/org/matsim/core/network/turnRestrictions/TurnRestrictionsNetworkCleaner.java
some modes might get removed in the cleaning but get re-inserted if only colored versions of it persist.
> fix(core): update turn restrictions network cleaner to account for temporarily removed nodes

- matsim/src/main/java/org/matsim/core/network/turnRestrictions/TurnRestrictionsNetworkCleaner.java
- matsim/src/test/java/org/matsim/core/network/turnRestrictions/TurnRestrictionsNetworkCleanerTest.java
We noticed some inconsistencies when cleaning networks with the new TurnRestrictionNetworkCleaner, for example other allowed modes besides the cleaning mode should stay untouched and their DisallowedNextLinks objects as well.
> fix(core): Fix TurnRestrictionsNetworkCleaner when other modes are present

- matsim/src/main/java/org/matsim/core/network/turnRestrictions/TurnRestrictionsNetworkCleaner.java
- matsim/src/test/java/org/matsim/core/network/turnRestrictions/TurnRestrictionsNetworkCleanerTest.java
When coloring the network when expanding turn restrictions of the cleaning mode, new links are created. which had "car" as their default mode. This resulted in incorrect behavior when cleaning networks with cleaning modes other than car.
> fix(core): Color network mode-independent in TurnRestrictionsNetworkCleaner

- matsim/src/test/java/org/matsim/core/network/turnRestrictions/TurnRestrictionsNetworkCleanerTest.java
This change adds some tests that check that the `TurnRestrictionsNetworkCleaner` (and its `TurnRestrictionsContext`) are not affected by the order of links in a network, see https://github.com/matsim-org/matsim-libs/pull/3943.
> test(core): Add more tests and remove debug output for TurnRestrictionsNetworkCleaner

- matsim/src/main/java/org/matsim/core/config/ReflectiveConfigGroup.java
This PR ensures that exported collection fields – e.g., modes = {car, bike, walk} – are written in alphabetical order. Otherwise it could happen that a checked in cfg looks different than a newly generated cfg only because the order of a collection field has randomly change.
> chore(core): Ensure collection fields in cfgs are sorted

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/DrtModeMinCostFlowRebalancingModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/targetcalculator/RelativeDemandEstimatorAsTargetCalculator.java
This PR refines the rebalancing strategy based on relative demand. 
Before, the target number of vehicles to send to each zone was  
alpha * target(zone) + beta
where target(zone) was computed based on relative demand for that zone:
First a weight is computed 
w(zone) = demand(zone) / total_demand
and then 
target(zone) = w(zone) * number of rebalancable vehicles.
This only really made sense for beta = 0, because then all the rebalance vehicles could be distributed based on this logic.
But for beta > 0, we already send beta vehicles to each zone, so there are 
beta * number of zones  
fewer vehicles available for rebalancing based on the above logic.
This PR takes this into account and subtracts 
beta * number of zones
vehicles from the number of rebalance vehicles before applying the …
> feat(drt): refined the rebalancing strategy based on relative demand

- matsim/src/main/java/org/matsim/core/router/MultimodalLinkChooserDefaultImpl.java
Keep the constructor package-default so that it can only used via Guice.
Use MultimodalLinkChooserDefaultImpl as delegate inside GartenfeldLinkChooser.
> feat: make MultimodalLinkChooserDefaultImpl public so it can be used as delegate

- matsim/src/main/java/org/matsim/core/network/turnRestrictions/DisallowedNextLinksUtils.java
- matsim/src/test/java/org/matsim/core/network/DisallowedNextLinksUtilsTest.java
`DisallowedNextLinksUtils.clean(Network)` now 
* removes `DisallowedNextLinks` from loop links (same from and to nodes)
* removes those loop link ids from any disallowed link sequence.
> fix(core): Clean DisallowedNextLinks on loop links

- contribs/freight/src/main/java/org/matsim/freight/carriers/CarriersUtils.java
This fix adds a call of executor.shutdown().
As a result, the threads are called to shutdown and do not stay open and block the shutdown of the java run.
Without this, I had the issue, that (at least since version 2025w02) the simple runs including CarrierUtils.runJsprit(..) does not finish, even if all the code is executed.
> fix(freight(carriers)): shutdown all (open) threads from the JspritThreadPoolExecutor

- contribs/freight/src/main/java/org/matsim/freight/carriers/CarriersUtils.java
This PR reverts the changes in #3965 and uses another solution: Try-with-ressources.
After talking to KN, this is the better way and it also makes sure, that the threads gets closed.
> refactor(freight(carriers)): Use try-with-ressources block instead of manually call executor.shutdown

- contribs/drt/src/test/java/org/matsim/contrib/drt/routing/DrtRoutingModuleTest.java
- matsim/src/main/java/org/matsim/core/config/groups/RoutingConfigGroup.java
- matsim/src/main/java/org/matsim/core/router/DefaultRoutingModules.java
- matsim/src/main/java/org/matsim/core/router/TeleportationRoutingModule.java
- matsim/src/test/java/ch/sbb/matsim/routing/pt/raptor/RaptorStopFinderTest.java
- matsim/src/test/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorIntermodalTest.java
- matsim/src/test/java/org/matsim/core/router/TeleportationRoutingModuleTest.java
This PR allows users to define a `personSpeedAttribute` in the `RoutingParameter`s. If the option is set and a person has the corresponding attribute, the value will be used for teleportation routing instead of the global parameter, which was the only option previously. This allows to define speeds, for instance, based on the age of the person.
> feat(core): teleported mode speed by person

- contribs/application/src/main/java/org/matsim/application/analysis/population/ExperiencedPlansWriter.java
- matsim/src/main/java/org/matsim/core/config/groups/ScoringConfigGroup.java
- matsim/src/main/java/org/matsim/core/controler/Controler.java
Default for writing experienced plans is now `true`. It’s a bit of a hassle when the file isn’t in the output by default. Additionally added a MATSim application script for postprocessing in these cases.
> feat: enable experienced plans write by default and add matsim application class for postprocessing

- contribs/freight/src/main/java/org/matsim/freight/carriers/CarriersUtils.java
- contribs/freight/src/main/java/org/matsim/freight/carriers/jsprit/NetworkBasedTransportCosts.java
With this PR the Utils class `CarrierUtils.runJsprit(...)` now looks whether a `RoadPricingScheme` exists or not.
If it exists, it will be considered in the calculation of the `NetworkBasedCosts`.
If not, nothing changes.
This allows, to use the utils method also when running scenarios with tolls. (Before that, I used a copy of it and manually added the rpScheme -.-)
Closes #1367
> feat(freight:carriers): Take roadpricing into account when running jsprit from CarrierUtils.runJsprit(...)

- contribs/simwrapper/src/main/java/org/matsim/simwrapper/Header.java
- contribs/simwrapper/src/main/java/org/matsim/simwrapper/viz/Vehicles.java
- contribs/simwrapper/src/test/java/org/matsim/simwrapper/SimWrapperTest.java
- contribs/simwrapper/test/input/org/matsim/simwrapper/dashboard-0.yaml
The DRT vehicles animation class was missing from the set of available visualizations. This meant that users could not create a DRT dashboard from inside the simwrapper contrib.
This PR adds the Vehicle class and tests the proper creation of a DRT vehicles panel in a dashboard.
> fix(simwrapper): add missing "Vehicles" DRT animation

- contribs/roadpricing/src/main/java/org/matsim/contrib/roadpricing/RoadPricingUtils.java
For setting up an example where Jsprit uses the tolls with factor, I need to create an RoadPricingSchemeUsingTollFactor. Building this from code currently needs the rpSchemeImpl as argument. 
This was not creatable in a usefull way.
This is a bit hacky and therefore deprecated. But I need it for teaching in a few hours -.-
> refactor(roadPricing): Adding utils-method for creating a RoadPricingSchemeImpl

- matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/AbstractAgentSnapshotInfoBuilder.java
There is a "marker" facility to separately mark vehicles in OTFVis.  (I use this for teaching telematics; it is presumably not used elsewhere, and also not necessarily a stable feature.)
This was programmed in a way that agents with marker would be plotted at activities, even if plotting at activity was switched off.
I now changed that such that, if the general setting is such, agents at activities are not plotted, even if they are marked.
> fix: adjust use of marker in otfvis

- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/DrtWithExtensionsConfigGroup.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/preemptive_rejection/PreemptiveRejectionHandler.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/preemptive_rejection/PreemptiveRejectionModeQSimModule.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/preemptive_rejection/PreemptiveRejectionModule.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/preemptive_rejection/PreemptiveRejectionOptimizer.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/preemptive_rejection/PreemptiveRejectionParams.java
- contribs/drt-extensions/src/test/java/org/matsim/contrib/drt/extension/preemptive_rejection/RunPreemptiveRejectionIT.java
- contribs/drt-extensions/src/test/resources/org/matsim/contrib/drt/extension/preemptive_rejection/example.json
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DrtModeOptimizerQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGenerator.java
- examples/scenarios/mielec/vehicles-5-cap-2.xml
This PR adds **preemptive rejections** to the DRT extensions. They are an efficient way of controlling overall rejection rates in the following situations:
- *Service segmentation:* A couple of requests in *business class* are rejected more frequently than others because the dispatching constraints are stronger (no pooling, shorter wait time, ...). In that case, the new code allows rejecting requests of other booking classes *preemptively* to decrease business class rejections.
- *Equity:* There exist certain requests that are rejected with higher probability because they are harder to dispatch than others (wheelchair users, larger groups, ...). Then they can be defined as an individual booking class and the new feature can be used to *preemptively* reject standard requests to reduce …
> feat(drt-extension): preemptive rejection

- matsim/src/main/java/org/matsim/core/utils/io/MatsimXmlParser.java
This was disabled by default in https://github.com/FasterXML/woodstox/pull/212 and is required for the tests in #4040.
> fix(deps): re-enable resolveEntityRefs for SAX parser

- contribs/bicycle/src/main/java/org/matsim/contrib/bicycle/AdditionalBicycleLinkScoreDefaultImpl.java
- contribs/bicycle/src/main/java/org/matsim/contrib/bicycle/BicycleConfigGroup.java
- contribs/bicycle/src/main/java/org/matsim/contrib/bicycle/BicycleLinkSpeedCalculatorDefaultImpl.java
- contribs/bicycle/src/main/java/org/matsim/contrib/bicycle/BicycleModule.java
- contribs/bicycle/src/main/java/org/matsim/contrib/bicycle/BicycleUtils.java
- contribs/bicycle/src/main/java/org/matsim/contrib/bicycle/run/RunBicycleExample.java
- matsim/src/main/java/org/matsim/vehicles/Vehicles.java
This commit is setting a fair number of things within the bicycle contrib to deprecated (with comments), since I think that they are either no longer necessary, or they can now be done by the user without having to provide additional infrastructure.
adding a convenience method vehicles#addModeVehicleType( mode ) in passing
> fix: maintenance

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/repeatedselective/DetourTimeEstimatorWithAdaptiveTravelTimes.java
- contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/AdaptiveTravelTimeMatrixImpl.java
Fix for a rare corner case situation, that can create index out of bounds error. DepartureTime might get negative caused by a large negative pickupDetourInfo.pickupTimeLoss.
> fix(drt): Handle negative departure time corner case

- matsim/src/main/java/org/matsim/core/mobsim/qsim/QSim.java
- matsim/src/main/java/org/matsim/utils/MemoryObserver.java
Updates two of the common MATSim log statements:
1. renames "#veh:" to "#active agents" as this likely reflects better what is expressed. After all not every agent is a vehicular one
2. adds max memory statement to the memory observer to immediately see the upper bound of potential memory allocation
> refactor(core): update memory and qsim logging

- contribs/small-scale-traffic-generation/src/main/java/org/matsim/commercialDemandGenerationBasic/DemandGenerationSpecification.java
- contribs/small-scale-traffic-generation/src/main/java/org/matsim/commercialDemandGenerationBasic/DemandGenerationSpecificationForParcelDelivery.java
The interface and the specific implementation are used in zeroCUTS repository. That's why they still need to be public.
> fix: (freightGeneration): make classes public because they are used in other repositories

- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/extensive/ExtensiveInsertionSearchQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/parallel/RequestInsertWorker.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/repeatedselective/RepeatedSelectiveInsertionSearchQSimModule.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/selective/SelectiveInsertionSearchQSimModule.java
Further profiling showed that the new `ParallelUnplannedRequestInserter` benefits from indivudal InsertionProvider instances. Compared to PR #4102 runtime could be further reduced by 33 %.
> fix: Ensure individual InsertionProvider instances for ParallelUnplannedRequestInserter

- .github/workflows/deploy-weekly.yaml
**Problem:**
A rerun of a scheduled workflow seems to always use the same commit. (see #4153)
This leads to a situation where issues that let the build fail will prevent us from having a weekly release.
**Solution:**
I added the trigger `workflow_dispatch` to the `build-weekly` workflow. 
This enables the "run workflow" button for the workflow in GH actions, so we can start the workflow manually.
See: https://docs.github.com/de/actions/how-tos/manage-workflow-runs/manually-run-a-workflow
> build: Allow to manually start the weekly-build workflow

- contribs/sbb-extensions/src/main/java/ch/sbb/matsim/mobsim/qsim/pt/SBBTransitDriverAgent.java
- matsim/src/main/java/org/matsim/core/mobsim/qsim/pt/TransitDriverAgentImpl.java
Additional change to #4220, to catch situation when no departure is defined. This happens during umlauf between serving two transit routes.
> fix(pt): Catch when there is no chained departure (during umlauf)

- contribs/freight/src/main/java/org/matsim/freight/carriers/usecases/CarrierScorerEventBasedInclToll.java
- contribs/freight/src/main/java/org/matsim/freight/logistics/examples/multipleChains/ExampleTwoLspsGroceryDeliveryMultipleChainsWithToll.java
While working on the `logistic` package, I wrote a new event-based `CarrierScoringFunction`.
This PR now moves (and renames) this into the `carriers` package and makes it public to be accessible from different places.
> refactor(freight): move the carrier scoring function used in logistic to the carrier package and make it public

- contribs/ev/src/main/java/org/matsim/contrib/ev/strategic/StrategicChargingUtils.java
There was an error when reading lists of subscriptions for agents and tariffs for chargers in the strategic ev charging component.
> fix(ev): attribute list reading in sevc

- contribs/ev/src/main/java/org/matsim/contrib/ev/strategic/StrategicChargingConfigGroup.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/strategic/StrategicChargingModule.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/strategic/replanning/innovator/ChargingInnovationParameters.java
- contribs/ev/src/main/java/org/matsim/contrib/ev/strategic/replanning/innovator/RandomChargingPlanInnovator.java
- contribs/ev/src/test/java/org/matsim/contrib/ev/strategic/StrategicChargingTest.java
- contribs/ev/src/test/java/org/matsim/contrib/ev/strategic/utils/TestScenarioBuilder.java
- This PR adds the infrastructure to add dedicated parameter sets for different innovation strategies in strategic electric vehicle charging (sevc). 
- For the random innovation strategy, one can now define the inclusion probabilities for activities and legs.
- BREAKING CHANGE: In order to activate innovation, an innovation parameter set now needs to be added to the SEVC config group. For now, only the `RandomChargingPlanInnovator.Parameters` is available.
> feat(ev): add specific parameters for innovation startegy in sevc

- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/insertion/ConfigurableCostCalculatorStrategy.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/insertion/PromisedTimeWindowOfferAcceptor.java
- contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/preplanned/optimizer/PreplannedDrtOptimizer.java
- contribs/drt-extensions/src/test/java/org/matsim/contrib/drt/extension/insertion/spatialFilter/SpatIalRequestFleetFilterTest.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DrtRequestInsertionRetryQueue.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/constraints/DrtRouteConstraints.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/CostCalculationStrategy.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/extensive/MultiInsertionDetourPathCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/selective/SingleInsertionDetourPathCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/AcceptedDrtRequest.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/DefaultOfferAcceptor.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/DrtRequest.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/DrtRequestCreator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/PromisedPickupTimeWindowDrtOfferAcceptor.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DefaultDrtRouteConstraintsCalculator.java
- contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtRoute.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/DrtRequestInsertionRetryQueueTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/CostCalculationStrategyTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserterTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionCostCalculatorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGeneratorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGeneratorWithChangingCapacitiesTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/extensive/MultiInsertionDetourPathCalculatorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/selective/SingleInsertionDetourPathCalculatorTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/prebooking/PrebookingConstraintsTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/prebooking/VariableStopDurationTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/routing/DrtRoutingModuleTest.java
- contribs/drt/src/test/java/org/matsim/contrib/drt/scheduler/DefaultRequestInsertionSchedulerTest.java
As per #4161 there's a bug for drt constraints in the case of prebooking. When the constraints were changed to absolute time stamps, the time stamps did not take into account the offset between submission time and earliest/planned departure, meaning that the time windows were too narrow for prebooked trips, causing more rejections.
The main reason was that the prebooking manager correctly passes the actual departure time to the request creator, which sets the earliest start time accordingly. However, the latest start time was already determined in the route creator and did not account for the offset between submission and earliest departure.
I changed it back such that the constraints object uses relative constraints again, but still kept re-using the constraints object for creating the …
> fix(drt): make drt constrains relative again
