matsim-org/matsim-libs

matsim/src/main/java/tutorial/programming/example11PluggablePlanStrategyInCode/MyPlanSelector.java, matsim/src/main/java/tutorial/programming/example11PluggablePlanStrategyInCode/MyPlanStrategyFactory.java, matsim/src/main/java/tutorial/programming/example11PluggablePlanStrategyInCode/MyPlanStrategyModule.java, matsim/src/main/java/tutorial/programming/example11PluggablePlanStrategyInCode/RunPluggablePlanStrategyInCodeExample.java
=> Tutorial.example11 refresh

matsim/src/main/java/tutorial/programming/example21tutorialTUBclass/leastCostPath/RunLeastCostPathCalculatorExample.java, matsim/src/test/java/tutorial/programming/example21TUBclass/IntegrationTest.java
We've played around with a couple of tests in our own branches @MATSim advanced class in TUB.
Please ignore me (and all those e-mails that could follow up today).
=> Jb test branch

matsim/src/main/java/tutorial/programming/example07ControlerListener/RunControlerListenerExample.java, matsim/src/test/java/tutorial/programming/example07ControlerListener/ControlerListnerExampleTest.java
merging the junit test for controler listener to master
=> junit test for controler listner

matsim/src/test/java/tutorial/programming/example11PluggablePlanStrategyInCode/RunPluggablePlanStrategyInCodeExampleTest.java
Testcase lässt die "main" Methode für das RunPluggablePlanStrategyTutorial laufen
=> TestCase für RunPluggabelPlanStrategyTutorial erstellt

.travis.yml, matsim/src/main/java/tutorial/programming/personAttributes/RunPersonAttributesExample.java, matsim/src/test/java/tutorial/programming/personAttributes/RunPersonAttributesExampleTest.java
=> Tschlenther branch

matsim/src/test/java/tutorial/programming/eventsHandler/IntegrationTest.java
eventHandler Test for Tutorial
=> eventHandler Test

matsim/src/test/java/tutorial/programming/example16customscoring/TestCustomScoringExample.java
added a simple CustomScoringExampleTest
=> created TestCustomScoringExample

matsim/src/test/java/tutorial/programming/example11PluggablePlanStrategyInCode/MyPlanSelectorTest.java, matsim/src/test/java/tutorial/programming/example11PluggablePlanStrategyInCode/MyPlanStrategyFactoryTest.java
* Test casees für alle Methoden erstellt, die etwas anderes als Logging
machen.
=> Tutorial11:

contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/control/listeners/NoVehicleEventHandler.java, contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/events/NoVehicleCarSharingEvent.java, contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/events/StartRentalEvent.java, contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/manager/CarsharingManagerNew.java, contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/manager/supply/CompanyContainer.java, contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/manager/supply/FreeFloatingVehiclesContainer.java, contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/manager/supply/OneWayContainer.java, contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/manager/supply/TwoWayContainer.java, contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/manager/supply/VehiclesContainer.java
This PR adds more information (company ID, origin Link ID, destination Link ID) to the Carsharing StartRentalEvents and NoVehicleCarSharingEvent, which allows to log successful as well as failed rentals. Also, a NoVehicleCarSharingEvent event is fired if a reservation cannot be confirmed for some reason.
=> More info carsharing events

contribs/pom.xml, contribs/socnetsim/src/main/java/org/matsim/contrib/socnetsim/jointactivities/replanning/modules/randomlocationchoice/RandomJointLocationChoiceAlgorithm.java, matsim/pom.xml, matsim/src/main/resources/dtd/taxi_ranks_v1.dtd, matsim/src/test/java/org/matsim/core/router/TripStructureUtilsSubtoursTest.java, matsim/src/test/java/org/matsim/core/utils/misc/ConfigUtilsTest.java
travis did not complain, but perhaps I forgot something, Michael?
=> Switch to Java 8

matsim/pom.xml, matsim/src/main/java/org/matsim/core/controler/NewControler.java, matsim/src/main/java/org/matsim/core/utils/io/IOUtils.java, matsim/src/test/java/org/matsim/withinday/trafficmonitoring/TravelTimeCollectorTest.java, tutorial/pom.xml
the only reason why appveyor tests are currently not running is because ITs are failing, but all the windows related things should be fixed, so I'm merging this.
=> Appveyor failures

matsim/src/main/java/org/matsim/utils/objectattributes/attributeconverters/CoordConverter.java
put coordconverter in matsim main
=> Coord converter2 matsim

matsim/src/main/java/org/matsim/core/controler/PrepareForSimImpl.java
a warning will be given if a custom re-planning strategy is used.
=> a warning for custom strategy

matsim/src/main/java/org/matsim/core/config/groups/QSimConfigGroup.java, matsim/src/main/java/org/matsim/core/controler/PrepareForSimImpl.java
creating one vehicle corresponding to every network mode until the switch  (qsimConfigGroup.creatingVehiclesForAllNetworkModes) set to false.
=> vehicles in prepare for sim

contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/DynAgent/BenensonDynLeg.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/DynAgent/DistanceMemoryDynLeg.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/DynAgent/agentLogic/BenensonParkingAgentLogic.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/DynAgent/agentLogic/MemoryBasedParkingAgentLogic.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/DynAgent/agentLogic/ParkingAgentLogic.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/ParkingSearchStrategy.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/ParkingUtils.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/RunParkingSearchExample.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/evaluation/ParkingSlotVisualiser.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/evaluation/ParkingTuple.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/evaluation/ZoneParkingOccupationListener.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/manager/ZoneParkingManager.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/search/BenensonParkingSearchLogic.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/search/DistanceMemoryParkingSearchLogic.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/sim/ParkingAgentFactory.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/sim/ParkingSearchConfigGroup.java
created ParkingSearchConfigGroup, added some parking search strategy and some comments. RunExample is up to date. Merged the master into the branch..
=> Parking search

matsim/src/main/java/org/matsim/core/network/algorithms/NetworkSimplifier.java, matsim/src/test/java/org/matsim/core/network/algorithms/NetworkSimplifierPass2WayTest.java
=> Network simplifier

contribs/opdytsIntegration/src/test/java/org/matsim/contrib/opdyts/modeChoice/EquilOpdytsIT.java
reduce number of opdyts transition to reduce sim time for opdyts test
=> an attempt to cut simulation time for opdyts test

matsim/src/main/java/org/matsim/core/population/algorithms/PersonPrepareForSim.java, matsim/src/test/java/org/matsim/facilities/ActivityFacilitiesSourceTest.java
faced problem related to MATSIM-686
fixed bug related to MATSIM-724
=> Bug fix activity facilities

contribs/emissions/src/main/java/org/matsim/contrib/emissions/EmissionModule.java, contribs/emissions/src/main/java/org/matsim/contrib/emissions/WarmEmissionAnalysisModule.java, contribs/emissions/src/main/java/org/matsim/contrib/emissions/WarmEmissionHandler.java, contribs/emissions/src/main/java/roadTypeMapping/HbefaRoadTypeMapping.java, contribs/emissions/src/main/java/roadTypeMapping/OsmHbefaMapping.java, contribs/emissions/src/main/java/roadTypeMapping/VisumHbefaRoadTypeMapping.java, contribs/emissions/src/test/java/org/matsim/contrib/emissions/TestWarmEmissionAnalysisModule.java, contribs/roadpricing/src/main/java/org/matsim/roadpricing/RoadPricingSchemeUsingTollFactor.java
These two commits just make working with the emissions and road pricing packages easier. In particular, the generalisation of the HEBFA package allows for the direct correlation with OSM road types (What the swiss networks are built from, instead of just VISUM)
=> Updates to emissions and road pricing contribs for SCCER work

contribs/noise/src/main/java/org/matsim/contrib/noise/NoiseCalculationOnline.java, contribs/noise/src/main/java/org/matsim/contrib/noise/NoiseWriter.java, contribs/noise/src/main/java/org/matsim/contrib/noise/data/Grid.java, contribs/noise/src/main/java/org/matsim/contrib/noise/data/NoiseContext.java, contribs/noise/src/main/java/org/matsim/contrib/noise/data/NoiseReceiverPoint.java, contribs/noise/src/main/java/org/matsim/contrib/noise/handler/LinkSpeedCalculation.java, contribs/noise/src/main/java/org/matsim/contrib/noise/handler/NoiseReceiverPointImmision.java, contribs/noise/src/main/java/org/matsim/contrib/noise/handler/NoiseTimeTracker.java, contribs/noise/src/main/java/org/matsim/contrib/noise/handler/PersonActivityTracker.java, contribs/noise/src/test/java/org/matsim/contrib/noise/NoiseIT.java
memory- and performance-optimization; let tests write into separate directories
=> Noise performance

contribs/taxi/src/main/java/org/matsim/contrib/taxi/scheduler/TaxiScheduler.java, matsim/src/main/java/org/matsim/core/router/AStarEuclideanFactory.java, matsim/src/main/java/org/matsim/core/router/FastAStarEuclideanFactory.java
This somehow got lost during the latest DevMeet
=> reintroduce (Fast)AStarEuclideanFactory.overdoFactor

matsim/src/main/java/org/matsim/core/config/ConfigGroup.java, matsim/src/main/java/org/matsim/core/config/ConfigReaderMatsimV1.java, matsim/src/main/java/org/matsim/core/config/ConfigWriterHandlerImplV2.java, matsim/src/main/java/org/matsim/core/config/groups/CountsConfigGroup.java, matsim/src/main/java/org/matsim/core/config/groups/FacilitiesConfigGroup.java, matsim/src/main/java/org/matsim/core/config/groups/QSimConfigGroup.java, matsim/src/main/java/org/matsim/core/config/groups/TravelTimeCalculatorConfigGroup.java, matsim/src/main/java/org/matsim/core/controler/PrepareForSimImpl.java, matsim/src/main/java/org/matsim/core/controler/PrepareForSimMultimodalImpl.java, matsim/src/main/java/org/matsim/core/controler/corelisteners/DumpDataAtEndImpl.java, matsim/src/main/java/org/matsim/core/mobsim/jdeqsim/JDEQSimConfigGroup.java, matsim/src/main/java/org/matsim/core/mobsim/qsim/agents/PopulationAgentSource.java, matsim/src/main/java/org/matsim/core/mobsim/qsim/changeeventsengine/NewNetworkChangeEventsEngine.java, matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/QNetsimEngine.java, matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/QueueWithBuffer.java, matsim/src/main/java/org/matsim/core/population/io/PopulationReaderMatsimV4.java, matsim/src/main/java/org/matsim/core/population/io/PopulationWriterHandlerImplV5.java, matsim/src/main/java/org/matsim/core/population/io/PopulationWriterHandlerImplV6.java, matsim/src/main/java/org/matsim/core/router/util/AbstractRoutingNetwork.java, matsim/src/main/java/org/matsim/facilities/ActivityOptionImpl.java, matsim/src/main/java/org/matsim/pt/router/TransitLeastCostPathTree.java, matsim/src/main/java/org/matsim/pt/router/TransitRouterImpl.java, matsim/src/main/java/org/matsim/run/InitRoutes.java, matsim/src/main/java/org/matsim/run/XY2Links.java, matsim/src/main/java/org/matsim/withinday/controller/ExecutedPlansServiceImpl.java, matsim/src/main/java/org/matsim/withinday/replanning/identifiers/filter/EarliestLinkExitTimeFilter.java, matsim/src/main/java/org/matsim/withinday/trafficmonitoring/EarliestLinkExitTimeProvider.java
mostly inspired by FindBugs warnings.
=> some more code cleanup.

contribs/av/src/main/java/org/matsim/contrib/av/robotaxi/scoring/TaxiFareConfigGroup.java, contribs/av/src/main/java/org/matsim/contrib/av/robotaxi/scoring/TaxiFareHandler.java, contribs/av/src/main/resources/cottbus_robotaxi/config.xml, contribs/av/src/test/java/org/matsim/contrib/av/robotaxi/scoring/TaxiFareHandlerTest.java
=> making taxifareconfiggroup more adaptable to actual mode set in dvrp

matsim/src/main/java/org/matsim/counts/Counts.java
minor change
Is there any way to commit such atomic changes without going to a branch?
=> fixed the javadoc

matsim/src/main/resources/dtd/carrierVehicleTypes_v1.dtd
add new xml scheme to validate carrierVehicleTypes
=> Add carrier vehicle types xml scheme v1

contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/VehicleData.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/VehicleDataEntryFactoryImpl.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserter.java, contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/DrtRequestCreator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigConsistencyChecker.java, contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/scheduler/TaxiScheduler.java
=> Dvrp refactoring continued

contribs/signals/pom.xml, contribs/signals/src/test/java/org/matsim/contrib/signals/oneagent/ControlerTest.java, contribs/signals/src/test/java/org/matsim/contrib/signals/oneagent/QSimSignalTest.java
Hopefully make signal tests more stable on appveyor
=> Small fix in signal tests

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalSystem.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DefaultDrtOptimizer.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/TransportProblem.java, contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/run/examples/RunOneSharedTaxiExample.java, contribs/drt/src/test/java/org/matsim/contrib/drt/run/example/RunOneSharedTaxiExampleIT.java
min-cost-flow fleet rebalancing is enabled by default (just need to set `DrtConfigGroup.rebalancingInterval` to a positive number)
=> Rebalancing is default

matsim/src/main/resources/dtd/freightReceivers_v1.dtd
Adds a DTD for freight receivers.
=> Freight dtd

matsim/src/main/java/org/matsim/core/utils/io/OsmNetworkReader.java
setting the boolean useVspAdjustments after calling the constructor was
too late
=> adding a constructor

matsim/pom.xml, matsim/src/main/java/org/matsim/core/utils/io/IOUtils.java, matsim/src/test/java/org/matsim/core/utils/io/IOUtilsTest.java
* use getInputStream in getBufferedReader
* use getOutputStream in getBufferedWriter
* add lz4 to ioutils and pom
* extend testing; do not allow appending to exiting lz4-files
=> extend ioutils with lz4

contribs/otfvis/src/main/java/org/matsim/contrib/otfvis/OTFVis.java, contribs/signals/examples/tutorial/example90TrafficLights/useSignalInput/woLanes/config.xml, contribs/signals/src/main/java/tutorial/fixedTimeSignals/VisualizeSignalScenario.java, contribs/signals/src/main/java/tutorial/fixedTimeSignals/VisualizeSignalScenarioWithLanes.java
Use controler in signal tutorials instead of starting otfvis directly
=> signal tutorials

contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierShipment.java, contribs/freight/src/main/java/org/matsim/contrib/freight/jsprit/MatsimJspritFactory.java, contribs/freight/src/test/java/org/matsim/contrib/freight/jsprit/TestMatsimTransformer.java, contribs/freight/test/input/org/matsim/contrib/freight/jsprit/TestMatsimTransformer/grid-network.xml
- Implementation of (MATSim) shipments in creation of VehicleRoutingProblem for jsprit.
- Tests of MatsimJspritFactory
=> Freight shipments

contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/data/file/VehicleReader.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetaxi/OneTaxiOptimizer.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/trafficmonitoring/DvrpOnlineTravelTimeEstimator.java
otherwise only offline TT estimation is made
=> DVRP online TT estimation only during QSim

matsim/src/test/java/org/matsim/core/mobsim/qsim/NetsimRoutingConsistencyTest.java
=> Test consistency for routed travel times and Netsim travel times

contribs/otfvis/src/main/java/org/matsim/pt/demo/AccessEgressDemo.java, contribs/otfvis/src/main/java/org/matsim/pt/demo/BlockingStopDemo.java, matsim/src/main/java/org/matsim/core/mobsim/qsim/QSimUtils.java, matsim/src/test/java/org/matsim/core/mobsim/qsim/QSimUtilsTest.java
Previously, overrides did not work
=> Fix QSimUtils.createQSim with overrides

examples/scenarios/siouxfalls/config.xml
Change path to being relative to config.xml.
=> MATSIM-817 Fixed siouxfalls config

matsim/src/main/java/org/matsim/pt/analysis/TransitLoad.java, matsim/src/test/java/org/matsim/pt/analysis/TransitLoadTest.java
because the TransitStopFacility is used as identifier and no other identifier seems to be available in the events (schedule is not known by TransitLoad), return List by TransitStopFacility.
=> Pt transit load analysis: cater for lines which stop multiple times at the same TransitStopFacility

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DynModePassengerStats.java, contribs/drt/src/main/java/org/matsim/contrib/drt/data/validator/DefaultDrtRequestValidator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/data/validator/DrtRequestValidator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DefaultDrtOptimizer.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserter.java, contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/events/DrtRequestRejectedEvent.java, contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java, contribs/drt/src/main/java/org/matsim/contrib/drt/util/DrtRequestTimeConstraintViolations.java, contribs/drt/src/test/java/org/matsim/contrib/drt/run/example/RunDrtExampleIT.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/PassengerEngine.java
Main changes:
- standardise handling of both types of rejections (see #362 for discussion)
- add utils for calculating time constraint violations
- DrtRequestValidator return type changed from boolean to Set<String> that lists causes of constraint violations
=> improve request rejection handling

contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModule.java
=> bugfix to allow drt routing module to run for modes that arent drt

contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtMainModeIdentifier.java, contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtRoutingModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtStageActivityType.java, contribs/drt/src/main/java/org/matsim/contrib/drt/routing/StopBasedDrtRoutingModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java, contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtControlerCreator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModule.java, contribs/drt/src/test/java/org/matsim/contrib/drt/routing/DrtMainModeIdentifierTest.java
Let drt really use the mode set in DrtConfigGroup, set DrtStageActivityType accordingly
=> Drt mode setup bugfix

matsim/src/main/java/org/matsim/core/config/groups/PlansConfigGroup.java, matsim/src/main/java/org/matsim/core/population/VspPlansCleaner.java
(previous cleaning lead to crashes with DRT in replanning)
=> VspPlansCleaner update 

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtRequestAnalyzer.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DynModePassengerStats.java, contribs/drt/src/main/java/org/matsim/contrib/drt/data/DrtRequest.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserter.java, contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/DrtRequestCreator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/events/DrtRequestScheduledEvent.java, contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/events/DrtRequestSubmittedEvent.java, contribs/drt/src/main/java/org/matsim/contrib/drt/routing/ClosestAccessEgressStopFinder.java, contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java, contribs/drt/src/main/java/org/matsim/contrib/drt/run/MultiModeDrtQSimModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/schedule/DrtTask.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/schedule/Schedule.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/data/TaxiRequest.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/schedule/TaxiOccupiedDriveTask.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/schedule/TaxiTask.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/scheduler/TaxiScheduler.java
Now DrtRequest scheduled/submitted events have "mode"
=> run separate Drt event analysis per each mode

matsim/src/main/java/org/matsim/analysis/LegHistogram.java, matsim/src/main/java/org/matsim/core/config/groups/PlanCalcScoreConfigGroup.java, matsim/src/main/java/org/matsim/core/config/groups/StrategyConfigGroup.java, matsim/src/main/java/org/matsim/core/utils/io/MatsimXmlWriter.java, matsim/src/main/java/org/matsim/core/utils/io/XmlUtils.java, matsim/src/main/java/org/matsim/utils/objectattributes/attributable/AttributesXmlWriterDelegate.java, matsim/src/test/java/org/matsim/core/utils/io/MatsimXmlWriterTest.java
fixes an issue where attributes with special values were not properly encoded when writing to XML, resulting in correct XML files.
=> some minor fixes and improvements

contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierVehicle.java, contribs/freight/src/main/java/org/matsim/contrib/freight/jsprit/MatsimJspritFactory.java
Correct one exception statement and make one getter public
=> Freight minor fixes

contribs/drt/src/test/java/org/matsim/contrib/drt/run/examples/RunDrtExampleIT.java
and the test was not complaining; adjusted syntax + at least test if the passenger request
validator was called
=> the passenger request validator was not called in a test

matsim/src/main/java/org/matsim/core/mobsim/qsim/agents/BasicPlanAgentImpl.java
Also refactor duplicate code into getFacility method
=> Remove System.out.println statement

matsim/src/main/resources/dtd/freightReceivers_v1.dtd
Changed child elements from zero-or-one to zero-or-more.
=> Fixed dtd definition

contribs/ev/src/main/java/org/matsim/contrib/ev/temperature/TemperatureManager.java, matsim/src/main/java/org/matsim/core/utils/io/tabularFileParser/TabularFileParser.java, matsim/src/main/java/org/matsim/core/utils/io/tabularFileParser/TabularFileParserConfig.java
the new EV contrib failed the weekly builds as it did not properly support running in paths that contain spaces. Fixed.
=> fix EV to work on paths with spaces in it.

contribs/drt/src/main/java/org/matsim/contrib/edrt/run/RunEDrtScenario.java, contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/AuxDischargingHandler.java, contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/AuxEnergyConsumption.java, contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/DischargingModule.java, contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/DriveDischargingHandler.java, contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/OhdeSlaskiAuxEnergyConsumption.java, contribs/ev/src/main/java/org/matsim/contrib/ev/dvrp/DvrpAuxConsumptionFactory.java, contribs/ev/src/main/java/org/matsim/contrib/ev/dvrp/EvDvrpIntegrationModule.java, contribs/ev/src/main/java/org/matsim/contrib/ev/dvrp/TaskEnergyConsumptions.java, contribs/ev/src/main/java/org/matsim/contrib/ev/routing/EVNetworkRoutingModule.java, contribs/taxi/src/main/java/org/matsim/contrib/etaxi/run/RunETaxiScenario.java
(was always returning standard consumption values for dvrp vehicles)
=> Fix DvrpAuxConsumptionFactory

contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierVehicleType.java, contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierVehicleTypeWriter.java, contribs/freight/src/main/java/org/matsim/contrib/freight/jsprit/MatsimJspritFactory.java, contribs/freight/src/main/java/org/matsim/contrib/freight/jsprit/NetworkBasedTransportCosts.java, contribs/freight/src/main/java/org/matsim/contrib/freight/usecases/chessboard/CarrierScoringFunctionFactoryImpl.java, contribs/freight/src/main/java/org/matsim/contrib/freight/usecases/chessboard/TravelDisutilities.java, contribs/freight/src/test/java/org/matsim/contrib/freight/carrier/CarrierPlanReaderTest.java, contribs/freight/src/test/java/org/matsim/contrib/freight/carrier/CarrierVehicleTypeLoaderTest.java, contribs/freight/src/test/java/org/matsim/contrib/freight/carrier/CarrierVehicleTypeReaderTest.java, contribs/freight/src/test/java/org/matsim/contrib/freight/carrier/CarrierVehicleTypeTest.java, contribs/freight/src/test/java/org/matsim/contrib/freight/carrier/CarrierVehicleTypeWriterTest.java, contribs/freight/src/test/java/org/matsim/contrib/freight/jsprit/TestMatsimTransformer.java, contribs/freight/src/test/java/org/matsim/contrib/freight/mobsim/ScoringFunctionFactoryForTests.java, contribs/freight/src/test/java/org/matsim/contrib/freight/utils/TestFreightUtils.java
- make some values private -> use (new) getters
- new constructor for CarrierVehicleType.Builder for creating a immutable CarrierVehicleType basing on an exisitng one
- tests
=> CarrierVehicleTypes

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtRequestAnalyzer.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserter.java, contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/events/DrtRequestSubmittedEvent.java, contribs/drt/src/main/java/org/matsim/contrib/drt/routing/StopBasedDrtRoutingModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/util/DrtRequestTimeConstraintViolations.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/PassengerRequestAcceptedEvent.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/PassengerRequestAcceptedEventHandler.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/PassengerRequestScheduledEvent.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/PassengerRequestScheduledEventHandler.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/PassengerRequestSubmittedEvent.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/PassengerRequestSubmittedEventHandler.java, matsim/src/main/java/org/matsim/withinday/trafficmonitoring/WithinDayTravelTime.java, matsim/src/main/java/org/matsim/withinday/trafficmonitoring/WithinDayTravelTimeModule.java
within-day TT could be used by other routers (not defined inside the controller config), so checking against the config makes sense only in the module
=> move router type check from WithinDayTravelTime to WithinDayTravelTimeModule

.travis.yml
unit tests were not run (only ITs were run)
=> Re-enable surefire on travis

contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtControlerCreator.java, contribs/drt/src/main/java/org/matsim/contrib/edrt/optimizer/EDrtOptimizer.java, contribs/drt/src/main/java/org/matsim/contrib/edrt/run/EDrtModeQSimModule.java, contribs/drt/src/main/java/org/matsim/contrib/edrt/scheduler/EmptyVehicleChargingScheduler.java, contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/LTHDriveEnergyConsumption.java, contribs/ev/src/main/java/org/matsim/contrib/ev/dvrp/EvDvrpVehicle.java, contribs/ev/src/main/java/org/matsim/contrib/ev/temperature/TemperatureManager.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/RunTaxiScenario.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiControlerCreator.java, contribs/taxi/src/test/java/org/matsim/contrib/taxi/run/RunTaxiScenarioTestIT.java
Additionally, a couple of fixes in EV
=> Cleanup drt, taxi, ev

matsim/src/test/java/org/matsim/core/config/consistency/BeanValidationConfigConsistencyCheckerTest.java
to address https://github.com/matsim-org/matsim/pull/525#issuecomment-490868812
=> adapt BeanValidationConfigConsistencyCheckerTest for message internationalisation

contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/DriveDischargingHandler.java, contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/LTHDriveEnergyConsumption.java
*previously this would have crashed under certain circumstances
=> allow negative energy consumption

contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserter.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetaxi/OneTaxiOptimizer.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/PassengerEngine.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/PassengerRequestAcceptedEvent.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/PassengerRequestRejectedEvent.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/PassengerRequestScheduledEvent.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/DefaultTaxiOptimizer.java
Event; updating javadoc related to it
=> adding PersonId also to written and parsed PassengerRequestScheduled

contribs/emissions/src/main/java/org/matsim/contrib/emissions/analysis/EmissionGridAnalyzer.java
- use iterator instead of null signal during emissions generation
- added javadoc strings
=> emissions contrib - use iterator to cycle through emission time bins

contribs/ev/src/main/java/org/matsim/contrib/ev/routing/EVNetworkRoutingModule.java
This leads to more accurate results when simulating ERS
=> simulate pseudo EV consumption when calculating charging breaks

contribs/ev/src/main/java/org/matsim/contrib/ev/routing/EVNetworkRoutingModule.java
in reference to automerged previous PR :-)
=> +/- charge discharge confusion solved

matsim/src/main/resources/log4j.xml
change default log level in log4j.xml
=> reduce default log level from debug to info

contribs/analysis/src/main/java/org/matsim/contrib/analysis/kai/KNAnalysisEventsHandler.java, contribs/roadpricing/src/main/java/org/matsim/contrib/roadpricing/ControlerDefaultsWithRoadPricingModule.java, contribs/roadpricing/src/main/java/org/matsim/contrib/roadpricing/RoadPricingModule.java, contribs/roadpricing/src/main/java/org/matsim/contrib/roadpricing/RoadPricingModuleDefaults.java, contribs/roadpricing/src/main/java/org/matsim/contrib/roadpricing/RoadPricingSchemeImpl.java, contribs/roadpricing/src/main/java/org/matsim/contrib/roadpricing/RoadPricingSchemeUsingTollFactor.java, contribs/roadpricing/src/main/java/org/matsim/contrib/roadpricing/RoadPricingUtils.java, contribs/roadpricing/src/main/java/org/matsim/contrib/roadpricing/RoadPricingWriterXMLv1.java, contribs/roadpricing/src/main/java/org/matsim/contrib/roadpricing/run/RunRoadPricingExample.java, contribs/roadpricing/src/main/java/org/matsim/contrib/roadpricing/run/RunRoadPricingFromCode.java, contribs/roadpricing/src/test/java/org/matsim/contrib/roadpricing/CalcPaidTollTest.java, contribs/roadpricing/src/test/java/org/matsim/contrib/roadpricing/ModuleTest.java, contribs/roadpricing/src/test/java/org/matsim/contrib/roadpricing/PlansCalcRouteWithTollOrNotTest.java, contribs/roadpricing/src/test/java/org/matsim/contrib/roadpricing/RoadPricingControlerIT.java, contribs/roadpricing/src/test/java/org/matsim/contrib/roadpricing/RoadPricingIOTest.java, contribs/roadpricing/src/test/java/org/matsim/contrib/roadpricing/TollTravelCostCalculatorTest.java, contribs/roadpricing/src/test/java/org/matsim/contrib/roadpricing/run/RunRoadPricingExampleIT.java, contribs/roadpricing/src/test/java/org/matsim/contrib/roadpricing/run/RunRoadPricingFromCodeIT.java, contribs/roadpricing/src/test/java/org/matsim/contrib/roadpricing/run/RunRoadPricingUsingTollFactorExampleIT.java, matsim/src/main/resources/dtd/roadpricing_v1.dtd
Still going through the code to do some cleanup.
=> Roadpricing cleanup

matsim/src/main/java/org/matsim/core/router/StageActivityTypesImpl.java
=> all activity types that end with "interaction" are stage activity types

contribs/roadpricing/src/test/java/org/matsim/contrib/roadpricing/run/RunRoadPricingUsingTollFactorExampleIT.java
(I need to get an idea why our weekly builds are failing...)
=> print stack trace before failing

contribs/ev/src/main/java/org/matsim/contrib/ev/discharging/OhdeSlaskiDriveEnergyConsumption.java
fix https://matsim.atlassian.net/browse/MATSIM-924
=> increase max speed to 80 m/s in Ohde-Slaski EV consumption

matsim/src/main/java/org/matsim/core/router/NetworkRoutingInclAccessEgressModule.java
=> NetworkRoutingInclAccessEgressModule: "interaction"->stage act

matsim/src/main/java/org/matsim/core/population/io/PopulationWriterHandlerImplV4.java, matsim/src/main/java/org/matsim/core/population/io/PopulationWriterHandlerImplV5.java, matsim/src/main/java/org/matsim/core/population/io/PopulationWriterHandlerImplV6.java, matsim/src/test/java/org/matsim/core/population/io/PopulationV6IOTest.java
=> Make sure special characters are correctly encoded in XML.

matsim/pom.xml, matsim/src/main/java/org/matsim/analysis/PKMbyModeCalculator.java, matsim/src/main/java/org/matsim/analysis/TravelDistanceStatsControlerListener.java, matsim/src/main/java/org/matsim/analysis/TravelDistanceStatsModule.java, matsim/src/main/java/org/matsim/core/scoring/EventsToLegs.java, matsim/src/main/java/org/matsim/core/scoring/EventsToLegsAndActivities.java, matsim/src/test/java/org/matsim/core/scoring/EventsToLegsTest.java
adds apache CSV-commons as a maven dependency. I'd opt to make this the standard library for CSVs in MATSim.
=> Pkmanalysis

contribs/drt/src/main/java/org/matsim/contrib/edrt/run/EDrtModeQSimModule.java, contribs/drt/src/main/java/org/matsim/contrib/edrt/scheduler/EmptyVehicleChargingScheduler.java, contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingEstimations.java, contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingWithQueueingLogic.java, contribs/ev/src/main/java/org/matsim/contrib/ev/charging/FastThenSlowCharging.java, contribs/ev/src/main/java/org/matsim/contrib/ev/charging/FixedSpeedCharging.java, contribs/ev/src/main/java/org/matsim/contrib/ev/charging/VariableSpeedCharging.java, contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ElectricFleetReader.java, contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ElectricFleetWriter.java, contribs/ev/src/main/java/org/matsim/contrib/ev/infrastructure/Charger.java, contribs/ev/src/main/java/org/matsim/contrib/ev/infrastructure/ChargerImpl.java, contribs/ev/src/main/java/org/matsim/contrib/ev/infrastructure/ChargerReader.java, contribs/ev/src/main/java/org/matsim/contrib/ev/infrastructure/ChargerSpecification.java, contribs/ev/src/main/java/org/matsim/contrib/ev/infrastructure/ChargerWriter.java, contribs/ev/src/main/java/org/matsim/contrib/ev/infrastructure/ImmutableChargerSpecification.java, contribs/ev/src/main/java/org/matsim/contrib/ev/routing/EvNetworkRoutingModule.java, contribs/ev/src/main/java/org/matsim/contrib/ev/stats/ChargerOccupancyXYDataProvider.java, contribs/ev/src/test/java/org/matsim/contrib/ev/charging/FastThenSlowChargingTest.java, contribs/ev/src/test/java/org/matsim/contrib/ev/charging/VariableSpeedChargingTest.java, contribs/ev/test/input/org/matsim/contrib/ev/example/RunEvExample/chargers.xml, contribs/ev/test/input/org/matsim/contrib/ev/example/RunEvExample/evehicles.xml, contribs/taxi/src/main/java/org/matsim/contrib/etaxi/optimizer/assignment/AssignmentChargerPlugData.java, examples/scenarios/dvrp-grid/one_etaxi_chargers.xml, examples/scenarios/mielec/chargers-1-plugs-1.xml, examples/scenarios/mielec/chargers-1-plugs-2.xml, examples/scenarios/mielec/chargers-2-plugs-2.xml, matsim/src/main/java/org/matsim/core/utils/collections/Tuple.java, matsim/src/main/resources/dtd/chargers_v1.dtd, matsim/src/main/resources/dtd/electric_vehicles_v1.dtd
- rename the following charger attributes: `power` -> `plug_power` and `capacity` -> `plug_count` in chargers_v1.dtd
- make `plug_count` IMPLIED (default value is 1)
- change two upperCase attributes to snake_case (used by the majority of attributes) in electric_vehicles_v1.dtd
- ensure consistent naming of attributes in xml and Java code
- add comments to DTDs
- update input XML files
=> Improve ev dtds

contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java, contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeQSimModule.java, contribs/drt/src/main/java/org/matsim/contrib/edrt/optimizer/EDrtOptimizer.java, contribs/drt/src/main/java/org/matsim/contrib/edrt/run/EDrtModeQSimModule.java, contribs/drt/src/main/java/org/matsim/contrib/edrt/run/RunEDrtScenario.java, examples/scenarios/dvrp-grid/multi_mode_one_shared_taxi_config.xml, examples/scenarios/dvrp-grid/one_shared_taxi_config.xml, examples/scenarios/mielec/mielec_edrt_config.xml
1. Fix: https://matsim.atlassian.net/browse/MATSIM-957
2. Rename `requestRejection` to `rejectRequestIfMaxWaitOrTravelTimeViolated` in `DrtConfigGroup` (to be more precise about the cause of rejection since there may be other causes of request rejection)
=> Drt improve config

matsim/src/main/java/org/matsim/core/utils/io/IOUtils.java
file-handling with URLs isn't that hard, actually... just never use a method from URL that returns a String.
=> correctly handle spaces in file names.

.travis.yml, contribs/accessibility/src/test/java/org/matsim/contrib/accessibility/run/TinyAccessibilityTest.java, contribs/accessibility/src/test/java/org/matsim/contrib/accessibility/run/TinyMultimodalAccessibilityTest.java, contribs/vsp/src/main/java/playground/vsp/openberlinscenario/cemdap/output/ActivityTypes.java, contribs/vsp/src/main/java/playground/vsp/openberlinscenario/cemdap/output/Cemdap2MatsimUtils.java, contribs/vsp/src/main/java/playground/vsp/openberlinscenario/cemdap/output/CemdapActivityParser.java, contribs/vsp/src/main/java/playground/vsp/openberlinscenario/cemdap/output/CemdapOutput2MatsimPlansConverter.java, contribs/vsp/src/main/java/playground/vsp/openberlinscenario/cemdap/output/CemdapOutputAnalyzer.java, contribs/vsp/src/main/java/playground/vsp/openberlinscenario/cemdap/output/CemdapPersonParser.java, contribs/vsp/src/main/java/playground/vsp/openberlinscenario/cemdap/output/CemdapStopsParser.java, contribs/vsp/src/main/java/playground/vsp/openberlinscenario/cemdap/output/CemdapToursParser.java, contribs/vsp/src/main/java/playground/vsp/openberlinscenario/cemdap/output/Feature2Coord.java
the accessibility tests are non-deterministic, sometimes passing sometimes failing.
=> ignore nondeterministic tests

contribs/vsp/src/test/java/playground/vsp/modalCadyts/ModalDistanceAndCountsCadytsIT.java
=> re-enable test where jenkins was dying to check if this can now be avoided

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtAnalysisControlerListener.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtModeAnalysisModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtPassengerAndVehicleStats.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtTrip.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtTripsAnalyser.java
Stats generation did not work properly with multimodal DRT
=> Fix DRT Analysis

matsim/src/main/java/org/matsim/core/trafficmonitoring/TravelTimeDataArray.java
see the detailed commit message of commit 2b012b1 for technical explanation.
=> Saving memory in TravelTime calculation

contribs/freight/src/main/java/org/matsim/contrib/freight/Freight.java, contribs/freight/src/main/java/org/matsim/contrib/freight/FreightConfigGroup.java, contribs/freight/src/main/java/org/matsim/contrib/freight/controler/CarrierControlerListener.java, contribs/freight/src/main/java/org/matsim/contrib/freight/controler/CarrierModule.java, contribs/freight/src/main/java/org/matsim/contrib/freight/mobsim/FreightQSimFactory.java, contribs/freight/src/main/java/org/matsim/contrib/freight/mobsim/Visualiser.java, contribs/freight/src/main/java/org/matsim/contrib/freight/usecases/chessboard/RunChessboard.java, contribs/freight/src/main/java/org/matsim/contrib/freight/utils/FreightUtils.java, contribs/freight/src/test/java/org/matsim/contrib/freight/carrier/CarrierModuleTest.java, contribs/freight/src/test/java/org/matsim/contrib/freight/controler/EquilWithCarrierWithPassIT.java, contribs/freight/src/test/java/org/matsim/contrib/freight/controler/EquilWithCarrierWithoutPassIT.java, contribs/freight/test/input/org/matsim/contrib/freight/carrier/CarrierModuleTest/carrierPlansEquils.xml, contribs/freight/test/input/org/matsim/contrib/freight/carrier/CarrierModuleTest/network.xml, contribs/freight/test/input/org/matsim/contrib/freight/carrier/CarrierModuleTest/plans100.xml, contribs/freight/test/input/org/matsim/contrib/freight/carrier/CarrierModuleTest/vehicleTypes.xml
the reading of freight input files in the carrier module was in the wrong place.
trying to fix the access on FreightConfigGroup in CarrierModule.
introduce a test for CarrierModule that instantiates the CarrierModule and runs a simulation for all existing constructors
=> Fix carrier module

contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/PassengerEngine.java
In some few cases, DRT trips were done and removed from the list before processRequestScheduledEvents was called.
=> minor bugfix to PassengerEngine

contribs/pseudosimulation/src/main/java/org/matsim/contrib/pseudosimulation/RunPSim.java, contribs/pseudosimulation/src/main/java/org/matsim/contrib/pseudosimulation/distributed/MasterControler.java, contribs/pseudosimulation/src/main/java/org/matsim/contrib/pseudosimulation/distributed/listeners/events/transit/FullDeparture.java, contribs/pseudosimulation/src/main/java/org/matsim/contrib/pseudosimulation/distributed/listeners/events/transit/TransitPerformanceRecorder.java, contribs/pseudosimulation/src/main/java/org/matsim/contrib/pseudosimulation/distributed/listeners/events/transit/VehicleTracker.java, contribs/pseudosimulation/src/main/java/org/matsim/contrib/pseudosimulation/mobsim/PSim.java, contribs/pseudosimulation/src/main/java/org/matsim/contrib/pseudosimulation/mobsim/PSimProvider.java
-remove unused code
-remove commented out code
-a bit more type safety by using generics more often
=> Psim cleanup

contribs/carsharing/src/test/java/org/matsim/contrib/carsharing/runExample/RunCarsharingIT.java, matsim/src/main/java/org/matsim/core/config/groups/GlobalConfigGroup.java, matsim/src/main/java/org/matsim/core/mobsim/DefaultMobsimModule.java, matsim/src/main/java/org/matsim/core/mobsim/qsim/PreplanningEngine.java, matsim/src/main/java/org/matsim/core/population/PopulationUtils.java, matsim/src/main/java/org/matsim/core/population/algorithms/PersonPrepareForSim.java, matsim/src/main/java/org/matsim/core/router/FallbackRoutingModuleDefaultImpl.java, matsim/src/main/java/org/matsim/core/router/TeleportationRoutingModule.java, matsim/src/main/java/org/matsim/facilities/FacilitiesUtils.java
Introducing a (currently non-settable) config parameter for `relativePositionOnLink`.  There are currently various hardcoded fixes for this at several places.
=> Kn relative position on link

contribs/dvrp/src/main/java/org/matsim/contrib/dynagent/run/DynRoutingModule.java
Conflicts:
contribs/dvrp/src/main/java/org/matsim/contrib/dynagent/run/DynRoutingModule.java
after unresolved merge conflict in routingMode5, stage activities were
missing
=> trying to fix DynRoutingModule, making it similar to DrtRoutingModule

contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/QSimScopeForkJoinPoolHolder.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserter.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ParallelMultiVehicleInsertionProblem.java, contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeQSimModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/RequestInsertionScheduler.java, contribs/drt/src/main/java/org/matsim/contrib/edrt/run/EDrtModeQSimModule.java, contribs/dvrp/src/main/java/org/matsim/contrib/dynagent/DynAgent.java
and trigger RequestInsertionScheduler.initSchedule() from constructor
Addresses issues mentioned in #754
=> add QSimScopeForkJoinPoolHolder

matsim/src/main/java/org/matsim/run/gui/PopulationSampler.java
There was old code regarding population-streaming in it, that essentially bricked the population sampler in the GUI.
=> fix PopulationSampler and add support for .zst files

contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/VehicleData.java, contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/DrtRequest.java, contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/DrtRequestCreator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtRoute.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetaxi/OneTaxiRequest.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/optimizer/Request.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/PassengerEngine.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/PassengerRequestCreator.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/passenger/TaxiRequest.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/passenger/TaxiRequestCreator.java, matsim/src/main/java/org/matsim/core/mobsim/qsim/PreplanningEngine.java, matsim/src/main/java/org/matsim/core/mobsim/qsim/TripInfoRequestWithActivities.java, matsim/src/main/java/org/matsim/core/mobsim/qsim/interfaces/TripInfo.java, matsim/src/main/java/org/matsim/core/mobsim/qsim/interfaces/TripInfoRequest.java
MobsimPassengerAgent is replaced with passengerId and route in the arg list of RequestCreator.createRequest().
For pre-booked requests TripInfo will be used (instead of Route)
=> Refactor passenger request creation

contribs/otfvis/src/main/java/org/matsim/vis/otfvis/opengl/queries/QueryAgentPlan.java
cannot test this right now since matsim-berlin is behind matsim head.
=> make interaction labels shorter in otfvis

benchmark/pom.xml, contribs/emissions/pom.xml, contribs/freight/pom.xml, contribs/multimodal/pom.xml, contribs/pom.xml, matsim/pom.xml
This should solve issues with migrating to JDK11 on jenkins: https://matsim.atlassian.net/browse/MATSIM-882
=> upgrade maven plugins to latest versions

contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/DynAgent/agentLogic/ParkingAgentLogic.java
In response to [#256](https://github.com/matsim-org/matsim-code-examples/issues/256)
=> allow durations for Parking Agents.

matsim/src/main/java/org/matsim/vehicles/VehicleWriterV1.java, matsim/src/main/java/org/matsim/vehicles/VehicleWriterV2.java, matsim/src/test/java/org/matsim/vehicles/VehicleWriteReadTest.java, matsim/src/test/resources/test/input/org/matsim/vehicles/VehicleWriteReadTest/testVehicles_v1_withDefaultValues.xml, matsim/src/test/resources/test/input/org/matsim/vehicles/VehicleWriteReadTest/testVehicles_v2_withDefaultValues.xml
and re-enable VehicleWriteReadTest
=> sort vehicles and types when writing to file

contribs/roadpricing/src/main/java/org/matsim/contrib/roadpricing/RoadPricingModule.java, contribs/roadpricing/src/main/java/org/matsim/contrib/roadpricing/RoadPricingSchemeUsingTollFactor.java, contribs/roadpricing/src/main/java/org/matsim/contrib/roadpricing/run/RunRoadPricingUsingTollFactorExample.java
See JIRA #998. This is an intermediate fix while I’m still sorting out the roadpricingCleanup branch. With this fix the integration test at least is aware of the TollFactor that was loaded as part of the road pricing scheme.
=> Fix integration test

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtPassengerAndVehicleStats.java
This allows for changing fleet sizes.
=> decide in every iteration which vehicles should be monitored.

contribs/vsp/src/main/java/playground/vsp/andreas/utils/pt/TransitScheduleCleaner.java
(cannot handle stop attributes)
=> do not use custom osmBB.extended.TransitScheduleImpl; in 1 method

matsim/src/main/java/org/matsim/core/controler/Controler.java, matsim/src/main/java/org/matsim/core/controler/corelisteners/DumpDataAtEndImpl.java, matsim/src/main/java/org/matsim/core/mobsim/qsim/QSim.java, matsim/src/main/java/org/matsim/vehicles/VehicleUtils.java
Meant for emissions (etc.) computations
=> collect all vehicles and vehicle types when inserted into mobsim, keep them as a scenarioElement, and dump them at the end

matsim/src/main/java/org/matsim/vehicles/VehicleUtils.java
this is related to PR #794 and should make it work.
=> fix dumpAllVehicles: Add missing addScenarioElement method

contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DefaultDrtOptimizer.java, contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/RequestQueue.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/DefaultTaxiOptimizer.java
For backward compatibility, the default value is 0, i.e. no planning of advance requests. This is a beta feature and is not available via the config XML.
=> add DrtConfigGroup.advanceRequestPlanningHorizon

contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/DrtScheduleTimingUpdater.java, contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/RequestInsertionScheduler.java
in order to add prebooking to DRT
=> extend stop duration to actual earliestStartTime of advance requests

matsim/src/test/java/org/matsim/analysis/ModeStatsControlerListenerTest.java
move to a branch on original matsim repository
=> Created new test class for ModeStatsControlerListener

contribs/cadytsIntegration/src/test/java/org/matsim/contrib/cadyts/pt/CadytsPtIT.java, contribs/pseudosimulation/src/test/java/org/matsim/contrib/pseudosimulation/RunPSimTest.java, contribs/vsp/src/test/java/playground/vsp/cadyts/marginals/TripEventHandlerTest.java, matsim/src/main/java/org/matsim/core/config/groups/PlansConfigGroup.java, matsim/src/main/java/org/matsim/core/controler/PrepareForSimImpl.java, matsim/src/test/java/org/matsim/core/controler/PrepareForSimImplTest.java, matsim/src/test/java/org/matsim/core/mobsim/qsim/pt/TransitQueueSimulationTest.java, matsim/src/test/java/org/matsim/examples/PtTutorialIT.java, matsim/src/test/java/org/matsim/integration/population/NonAlternatingPlanElementsIT.java, matsim/src/test/java/org/matsim/pt/analysis/TransitLoadIntegrationTest.java
implement a config switch to explictly enable (instead of silently accepting) old plan input files without routing mode.
`setHandlingOfPlansWithoutRoutingMode`
=> Person prepare for sim

contribs/cadytsIntegration/src/main/java/org/matsim/contrib/cadyts/car/CadytsCarModule.java, contribs/cadytsIntegration/src/main/java/org/matsim/contrib/cadyts/car/CadytsContext.java, contribs/cadytsIntegration/src/main/java/org/matsim/contrib/cadyts/car/PlansTranslatorBasedOnEvents.java, contribs/cadytsIntegration/src/main/java/org/matsim/contrib/cadyts/general/CadytsBuilderImpl.java, contribs/cadytsIntegration/src/main/java/org/matsim/contrib/cadyts/general/CadytsConfigGroup.java, contribs/cadytsIntegration/src/main/java/org/matsim/contrib/cadyts/measurement/MeasurementCadytsContext.java, contribs/cadytsIntegration/src/main/java/org/matsim/contrib/cadyts/pt/CadytsBuilderImplGT.java, contribs/cadytsIntegration/src/main/java/org/matsim/contrib/cadyts/pt/CadytsPtContext.java, contribs/cadytsIntegration/src/main/java/org/matsim/contrib/cadyts/pt/CadytsPtCountsComparisonAlgorithm.java, contribs/cadytsIntegration/src/main/java/org/matsim/contrib/cadyts/pt/CadytsPtModule.java, contribs/cadytsIntegration/src/main/java/org/matsim/contrib/cadyts/pt/CadytsPtOccupancyAnalyzer.java, contribs/cadytsIntegration/src/main/java/org/matsim/contrib/cadyts/pt/CadytsPtOccupancyAnalyzerI.java, contribs/cadytsIntegration/src/main/java/org/matsim/contrib/cadyts/pt/TransitStopFacilityLookUp.java, contribs/cadytsIntegration/src/test/java/org/matsim/contrib/cadyts/car/AdHocCountsReaderCar.java, contribs/cadytsIntegration/src/test/java/org/matsim/contrib/cadyts/car/CadytsCarIT.java, contribs/cadytsIntegration/src/test/java/org/matsim/contrib/cadyts/pt/CadytsPtIT.java
pull apart cadyts4car and cadyts4pt.  The "cheap" way, i.e. by providing separate entries in cadytsConfig.  This was already halfway there.
=> maintenance around cadyts integration

matsim/src/main/java/org/matsim/facilities/FacilitiesFromPopulation.java
... with how they decide on links/coordinates
=> make automatic facility generation more standard

matsim/pom.xml
=> remove unnecessary dependencies

contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeQSimModule.java, contribs/drt/src/main/java/org/matsim/contrib/edrt/run/EDrtModeQSimModule.java
after introduction of `ScheduleTimingUpdater`
=> refactor bindings in EDrtModeQSimModule

contribs/decongestion/src/main/java/org/matsim/contrib/decongestion/DecongestionRunExample.java, contribs/decongestion/src/main/java/org/matsim/contrib/decongestion/DecongestionRunExampleFromConfig.java, contribs/decongestion/src/main/java/org/matsim/contrib/decongestion/routing/TollTimeDistanceTravelDisutility.java, contribs/decongestion/src/main/java/org/matsim/contrib/decongestion/routing/TollTimeDistanceTravelDisutilityFactory.java, contribs/decongestion/src/test/java/org/matsim/contrib/decongestion/DecongestionPricingTestIT.java, contribs/locationchoice/src/test/java/org/matsim/contrib/locationchoice/frozenepsilons/FrozenEpsilonLocaChoiceIT.java, contribs/locationchoice/src/test/java/org/matsim/core/router/BackwardFastMultiNodeTest.java, contribs/multimodal/src/main/java/org/matsim/contrib/multimodal/MultiModalModule.java, contribs/noise/src/main/java/org/matsim/contrib/noise/NoiseDefaultCarTravelDisutilityModule.java, contribs/noise/src/main/java/org/matsim/contrib/noise/NoiseTollTimeDistanceTravelDisutilityFactory.java, contribs/pseudosimulation/src/main/java/org/matsim/contrib/pseudosimulation/distributed/SlaveControler.java, contribs/roadpricing/src/main/java/org/matsim/contrib/roadpricing/RoadPricingModule.java, contribs/roadpricing/src/main/java/org/matsim/contrib/roadpricing/RoadPricingTravelDisutilityFactory.java, contribs/vsp/src/main/java/playground/vsp/airPollution/exposure/EmissionResponsibilityTravelDisutilityCalculatorFactory.java, contribs/vsp/src/main/java/playground/vsp/airPollution/flatEmissions/EmissionTravelDisutilityCalculatorFactory.java, contribs/vsp/src/main/java/playground/vsp/congestion/RunSimpleExample.java, contribs/vsp/src/main/java/playground/vsp/congestion/routing/CongestionTollTimeDistanceTravelDisutilityFactory.java, contribs/vsp/src/test/java/playground/vsp/congestion/AdvancedMarginalCongestionPricingIT.java, contribs/vsp/src/test/java/playground/vsp/congestion/MarginalCongestionHandlerFlowSpillbackQueueQsimTest.java, matsim/src/main/java/org/matsim/core/controler/ControlerDefaults.java, matsim/src/main/java/org/matsim/core/router/costcalculators/RandomizingTimeDistanceTravelDisutilityFactory.java, matsim/src/main/java/org/matsim/core/router/costcalculators/TravelDisutilityModule.java, matsim/src/main/java/org/matsim/utils/leastcostpathtree/LeastCostPathTree.java, matsim/src/test/java/org/matsim/core/router/FastMultiNodeTest.java, matsim/src/test/java/org/matsim/core/router/InvertertedNetworkRoutingTest.java, matsim/src/test/java/org/matsim/core/router/NetworkRoutingModuleTest.java, matsim/src/test/java/org/matsim/core/router/costcalculators/RandomizingTimeDistanceTravelDisutilityTest.java, matsim/src/test/java/org/matsim/integration/SimulateAndScoreTest.java
There were too many places where it remained unclear if calling code was honouring the `setSigma` command.  Thus changing the constructor to take the full config as argument.
=> WIP: Routing randomness

contribs/otfvis/src/main/java/org/matsim/vis/otfvis/OTFVisConfigGroup.java, contribs/otfvis/src/main/java/org/matsim/vis/otfvis/gui/ValueColorizer.java, contribs/otfvis/src/main/java/org/matsim/vis/otfvis/opengl/drawer/FastColorizer.java, contribs/otfvis/src/main/java/org/matsim/vis/otfvis/opengl/layer/OGLAgentPointLayer.java, contribs/otfvis/src/main/java/org/matsim/vis/otfvis/opengl/queries/QueryAgentPlan.java, contribs/vsp/src/main/java/playground/vsp/andreas/mzilske/pt/queuesim/GreedyUmlaufBuilderImpl.java, matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/AbstractAgentSnapshotInfoBuilder.java, matsim/src/main/java/org/matsim/vis/snapshotwriters/AgentSnapshotInfo.java
(the changes w.r.t. UmlaufBuilder should also be in some other PR, and thus be merged separately)
=> "Infection" coloring setting in otfvis

contribs/commercialTrafficApplications/src/main/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/commercialJob/CommercialJobGenerator.java, matsim/src/main/java/org/matsim/core/controler/PrepareForSimImpl.java, matsim/src/main/java/org/matsim/utils/objectattributes/attributable/AttributesUtils.java, matsim/src/main/java/org/matsim/utils/objectattributes/attributeconverters/StringStringMapConverter.java, matsim/src/main/java/org/matsim/vehicles/VehicleUtils.java, matsim/src/test/java/org/matsim/core/mobsim/qsim/NetsimRoutingConsistencyTest.java, matsim/src/test/java/org/matsim/core/mobsim/qsim/VehicleSourceTest.java, matsim/src/test/java/org/matsim/core/mobsim/qsim/qnetsimengine/DeparturesOnSameLinkSameTimeTest.java, matsim/src/test/java/org/matsim/core/mobsim/qsim/qnetsimengine/FlowCapacityVariationTest.java, matsim/src/test/java/org/matsim/core/mobsim/qsim/qnetsimengine/SeepageTest.java, matsim/src/test/java/org/matsim/utils/objectattributes/ObjectAttributesConverterTest.java, matsim/src/test/java/org/matsim/utils/objectattributes/attributable/AttributesUtilsTest.java
=> Fix attributes converter crashes

.travis.yml, contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/router/DvrpRoutingModule.java, matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorRoutingModule.java, matsim/src/main/java/org/matsim/core/mobsim/qsim/PreplanningEngine.java, matsim/src/main/java/org/matsim/core/population/PopulationUtils.java, matsim/src/main/java/org/matsim/core/router/NetworkRoutingInclAccessEgressModule.java, matsim/src/main/java/org/matsim/core/router/TransitRouterWrapper.java, matsim/src/test/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorModuleTest.java, matsim/src/test/java/org/matsim/examples/PtTutorialIT.java
=> Fix interaction activities

matsim/src/main/java/org/matsim/analysis/TripsAndLegsCSVWriter.java
last 12.0 snapshot version of matsim and dvrp refer to different commits and are not compatible with each other -> trigger new build
=> trigger build (remove empty line)

contribs/taxi/src/test/java/org/matsim/contrib/etaxi/run/RunETaxiScenarioIT.java, contribs/taxi/src/test/java/org/matsim/contrib/taxi/optimizer/assignment/AssignmentTaxiOptimizerIT.java
=> ignore RunETaxiScenarioIT.testAssignment() due to JVM crashes on Jenkins

contribs/hybridsim/pom.xml
simplify pom.xml (same way as it was done in the protobuf contrib)
=> switch to protobuf-maven-plugin in hybridsim

contribs/pom.xml, matsim/pom.xml, matsim/src/test/java/org/matsim/core/mobsim/qsim/qnetsimengine/RunConfigurableQNetworkFactoryExampleTest.java
=> change geotools url in matsim main project

contribs/dvrp/src/main/java/org/matsim/contrib/dynagent/DynAgent.java, matsim/src/main/java/org/matsim/core/events/ParallelEventsManager.java, matsim/src/main/java/org/matsim/core/mobsim/qsim/ActivityEngineDefaultImpl.java, matsim/src/main/java/org/matsim/core/mobsim/qsim/agents/ActivityDurationUtils.java, matsim/src/main/java/org/matsim/core/mobsim/qsim/agents/BasicPlanAgentImpl.java, matsim/src/main/java/org/matsim/core/mobsim/qsim/agents/PlanBasedDriverAgentImpl.java, matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/QueueWithBuffer.java, matsim/src/main/java/org/matsim/core/population/PopulationUtils.java, matsim/src/test/java/org/matsim/core/mobsim/qsim/AbstractQSimModuleTest.java, matsim/src/test/java/org/matsim/core/mobsim/qsim/qnetsimengine/FlowEfficiencyCalculatorTest.java, matsim/src/test/java/org/matsim/core/mobsim/qsim/qnetsimengine/QLinkTest.java, matsim/src/test/java/org/matsim/core/mobsim/qsim/qnetsimengine/VehicleHandlerTest.java
=> Optional time in QSim / agents

matsim/src/main/java/org/matsim/facilities/ActivityOptionImpl.java, matsim/src/main/java/org/matsim/facilities/FacilitiesFromPopulation.java, matsim/src/main/java/org/matsim/facilities/FacilitiesReaderMatsimV1.java, matsim/src/main/java/org/matsim/facilities/OpeningTime.java, matsim/src/main/java/org/matsim/facilities/OpeningTimeImpl.java
to use -/+Inf for start/end times instead of undefined time
Follow-up to: #967
=> refactor OpeningTime

contribs/locationchoice/src/main/java/org/matsim/contrib/locationchoice/frozenepsilons/DCActivityScoringFunction.java, contribs/pseudosimulation/src/main/java/org/matsim/contrib/pseudosimulation/distributed/scoring/CharyparNagelOpenTimesActivityScoringWithDiagnostics.java, matsim/src/main/java/org/matsim/core/scoring/functions/ActivityTypeOpeningIntervalCalculator.java, matsim/src/main/java/org/matsim/core/scoring/functions/ActivityUtilityParameters.java, matsim/src/main/java/org/matsim/core/scoring/functions/CharyparNagelActivityScoring.java, matsim/src/main/java/org/matsim/core/scoring/functions/FacilityOpeningIntervalCalculator.java, matsim/src/main/java/org/matsim/core/scoring/functions/OpeningIntervalCalculator.java, matsim/src/main/java/org/matsim/deprecated/scoring/functions/CharyparNagelActivityScoring.java, matsim/src/main/java/org/matsim/deprecated/scoring/functions/CharyparNagelOpenTimesActivityScoring.java, matsim/src/test/java/org/matsim/core/scoring/functions/CharyparNagelOpenTimesScoringFunctionTest.java
=> Optional time in activity scoring

contribs/drt/pom.xml, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGenerator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/DrtRequest.java, contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/DrtRequestCreator.java, contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGeneratorTest.java
However I was not able to confirm this bug: #912 (not a bug??)
=> add unit tests for InsertionGenerator

contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGenerator.java, contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGeneratorTest.java
=> add special handling of dropoffs coinciding with the existing stops

contribs/freight/src/test/java/org/matsim/contrib/freight/carrier/CarrierVehicleTypeLoaderTest.java, contribs/freight/src/test/java/org/matsim/contrib/freight/jsprit/DistanceConstraintFromVehiclesFileTest.java, contribs/freight/test/input/org/matsim/contrib/freight/jsprit/vehicleTypesForDCTest.xml
- add a new test for the distance constraint with loading vehicleTypes data from file
- improve an existing test: also check if assigned values are correct - this was intended by the name of the test methods but not done.
=> improve tests in freight

contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/nested/DefaultNest.java, contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/nested/DefaultNestStructure.java, contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/nested/DefaultNestedTourCandidate.java, contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/nested/DefaultNestedTripCandidate.java, contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/nested/Nest.java, contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/nested/NestCalculator.java, contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/nested/NestStructure.java, contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/nested/NestedLogitSelector.java, contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/nested/NestedUtilityCandidate.java, contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/nested/WrappingNestedUtilityCandidate.java, contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/models/ConstantTripEstimator.java, contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/models/MaximumUtilityTest.java, contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/models/MultinomialLogitTest.java, contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/models/NestedLogitTest.java, contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/models/RandomUtilityTest.java, contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/models/nested/NestCalculatorTest.java, contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/modules/config/ConfigTest.java
- Add nested logit model
- Add red bus / blue bus tests
- Add additional tests for different selectors
- ... from PR in former DMC repository
=> Add nested logit model + red bus / blue bus tests

matsim/src/main/java/org/matsim/core/replanning/strategies/TimeAllocationMutatorModule.java, matsim/src/main/java/org/matsim/core/trafficmonitoring/TravelTimeCalculator.java, matsim/src/main/java/org/matsim/core/trafficmonitoring/TravelTimeDataArray.java, matsim/src/main/java/org/matsim/guice/DependencyGraphControlerListener.java, matsim/src/main/java/org/matsim/vehicles/MatsimVehicleReader.java
mostly found during the debugging of some strange router issues (see https://github.com/matsim-org/matsim-code-examples/issues/314)
=> some optimizations and changes

matsim/src/main/java/org/matsim/core/network/NetworkCollector.java, matsim/src/main/java/org/matsim/core/network/NetworkUtils.java, matsim/src/test/java/org/matsim/core/network/NetworkCollectorTest.java
=> Add a Collector for networks

benchmark/pom.xml, contribs/pom.xml, distribution/pom.xml, matsim/pom.xml
so they are not deployed to the maven repository
=> don't attach release-zip files to build

contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/BestInsertionFinder.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DetourData.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ParallelPathDataProvider.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/path/OneToManyPathSearch.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/path/VrpPaths.java
cleanups + 1 bugfix: insertion with the max cost, instead of the min cost, was selected from pre-filtered  (candidate) insertions
=> Refactor drt

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtModeAnalysisModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/util/stats/DrtVehicleOccupancyProfileCalculator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/util/stats/DrtVehicleOccupancyProfileWriter.java
Transformed the schedule-based analysis into event-based analysis.
I tested with `RunMultiModeDrtExample` for 10 iterations. In each iteration, this implementation produces the exact same graphs. Not sure about the runtime implications for large scenarios as this now needs to cache a lot of information, like the vehicle occupancy, while waiting for the events.
@michalmac Let me know what you think!
=> Event-based occupancy analysis for DRT

contribs/drt/src/main/java/org/matsim/contrib/drt/util/stats/DrtVehicleOccupancyProfileCalculator.java
A simplification of the DRT occupancy analysis, mostly focusing on reducing set of events used to only:
- activity start/end events to track idle vehicles
- person enters/leaves vehicle events to track occupancy
Changing the way events are processed, also fixes the following 2 issues:
- a missing second ("vehicle enters traffic" happens a second later after "activity end"), as a result the top line in the stacked area charge was not flat
- missing activities: charging (stay) activities in e-DRT were not tracked (Note: now they are counted as non-idle with occupancy 0)
=> simplify vehicle state tracking in Drt occupancy analysis

contribs/av/.editorconfig, contribs/drt/.editorconfig, contribs/dvrp/.editorconfig, contribs/dvrp/pom.xml, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/vrpagent/AbstractTaskEvent.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/vrpagent/TaskEndedEvent.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/vrpagent/TaskEndedEventHandler.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/vrpagent/TaskStartedEvent.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/vrpagent/TaskStartedEventHandler.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/vrpagent/VrpAgentLogic.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/vrpagent/VrpAgentSource.java, contribs/dvrp/src/main/java/org/matsim/contrib/dynagent/IdleDynActivity.java, contribs/dvrp/src/main/java/org/matsim/contrib/dynagent/examples/random/RunRandomDynAgentExample.java, contribs/dvrp/src/test/java/org/matsim/contrib/dvrp/vrpagent/VrpAgentLogicTest.java, contribs/ev/.editorconfig, contribs/taxi/.editorconfig, examples/scenarios/dvrp-grid/generic_dvrp_one_taxi_config.xml, examples/scenarios/dvrp-grid/one_truck_config.xml
- emit `TaskStarted/EndedEvent` events for dvrp agents
- add unit tests for `VrpAgentLogic`
=> Task started ended events

matsim/src/main/java/org/matsim/api/core/v01/IdMap.java
* made ensure capacity adaptive to the number of Ids
* fix https://github.com/matsim-org/matsim-libs/issues/1044
=> adaptive IdMap-size

contribs/drt/src/main/java/org/matsim/contrib/drt/util/stats/DrtVehicleOccupancyProfileWriter.java, contribs/dvrp/src/main/java/org/matsim/contrib/util/CSVLineBuilder.java, contribs/dvrp/src/main/java/org/matsim/contrib/util/CompactCSVWriter.java, contribs/dvrp/src/main/java/org/matsim/contrib/util/XYDataCollector.java, contribs/dvrp/src/main/java/org/matsim/contrib/util/XYDataCollectors.java, contribs/dvrp/src/main/java/org/matsim/contrib/util/timeprofile/TimeProfileCharts.java, contribs/dvrp/src/main/java/org/matsim/contrib/util/timeprofile/TimeProfileCollector.java, contribs/dvrp/src/main/java/org/matsim/contrib/util/timeprofile/TimeProfiles.java, contribs/ev/src/main/java/org/matsim/contrib/ev/stats/ChargerOccupancyTimeProfileCollectorProvider.java, contribs/ev/src/main/java/org/matsim/contrib/ev/stats/ChargerOccupancyXYDataProvider.java, contribs/ev/src/main/java/org/matsim/contrib/ev/stats/IndividualSocTimeProfileCollectorProvider.java, contribs/ev/src/main/java/org/matsim/contrib/ev/stats/SocHistogramTimeProfileCollectorProvider.java, contribs/ev/src/main/java/org/matsim/contrib/ev/stats/VehicleTypeAggregatedSocTimeProfileCollectorProvider.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/util/stats/TaxiTimeProfiles.java
Refactor time profiles consists of `Map<String, Double>` instead of fixed-index Double[]
=> More flexible time profile stats

contribs/taxi/src/main/java/org/matsim/contrib/etaxi/ETaxiScheduler.java, contribs/taxi/src/main/java/org/matsim/contrib/etaxi/optimizer/assignment/AssignmentETaxiOptimizer.java, contribs/taxi/src/main/java/org/matsim/contrib/etaxi/optimizer/rules/RuleBasedETaxiOptimizer.java, contribs/taxi/src/main/java/org/matsim/contrib/etaxi/run/ETaxiModeQSimModule.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/TaxiOptimizationValidation.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/assignment/AssignmentRequestInserter.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/fifo/FifoRequestInserter.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/rules/RuleBasedRequestInserter.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/rules/RuleBasedTaxiOptimizer.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/zonal/ZonalRequestInserter.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/zonal/ZonalTaxiOptimizer.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiModeQSimModule.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/scheduler/TaxiScheduleInquiry.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/scheduler/TaxiScheduler.java
to simplify writing customised schedulers
=> extract TaxiScheduleInquiry from TaxiScheduler

contribs/otfvis/src/main/java/org/matsim/vis/otfvis/data/OTFServerQuadTree.java
Fixes access exception in the OTF server, since constructors of OTFDataReader are not public.
=> Fixes access exception in the OTF server

matsim/src/main/java/org/matsim/core/config/groups/PlansCalcRouteConfigGroup.java
changes to the data structure of a config parameter in PlansCalcRouteConfigGroup were not picked up by the parameter name and it's description...
=> correct config parameter and comment

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/FirstActivityCountAsZonalDemandAggregator.java
Avoid NullPointerException and some more logging
=> Debug NullPointerException

matsim/src/main/java/org/matsim/analysis/IterationTravelStatsControlerListener.java, matsim/src/test/java/org/matsim/analysis/IterationTravelStatsControlerListenerTest.java, matsim/src/test/java/org/matsim/analysis/Plans.java
some CRLF line endings issues with the existing "Plans.java" file fixed to LF
=> add score and type of first activity to output_persons.csv

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtModeAnalysisModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/util/stats/DrtVehicleOccupancyProfileCalculator.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/vrpagent/AbstractTaskEvent.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/vrpagent/TaskEndedEvent.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/vrpagent/TaskStartedEvent.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/vrpagent/VrpAgentLogic.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/vrpagent/VrpAgentSource.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/vrpagent/VrpAgentSourceQSimModule.java, contribs/dvrp/src/test/java/org/matsim/contrib/dvrp/vrpagent/VrpAgentLogicTest.java
This should simplify writing event handlers that are dedicated to a specific mode. Also tracking vehicles will now be easier.
Some ideas were already discussed here: #1075 .
=> add dvrpMode and linkId to task started/ended events

contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java
=> fix RebalancingParams instantiation bug

examples/scenarios/mielec/mielec_drt_config.xml, examples/scenarios/mielec/mielec_edrt_config.xml, examples/scenarios/mielec/mielec_serviceArea_based_drt_config.xml, examples/scenarios/mielec/mielec_stop_based_drt_config.xml
update the drt config in matsim examples after #1116
=> update drt configs after splitting rebalancing params into RebalancingParams and RebalancingStrategyParams

appveyor.yml, matsim/src/test/java/org/matsim/utils/MemoryObserverTest.java
- declare image as VS2019
- increase max memory to 4GB (some tests were failing from time to time, often with the OutOfMem errors)
=> Fix appveyor config

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtGridUtils.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtModeZonalSystemModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalSystem.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalSystemParams.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/RebalancingParams.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/DrtModeMinCostFlowRebalancingModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java, contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeModule.java, contribs/drt/src/test/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalSystemTest.java, contribs/drt/src/test/java/org/matsim/contrib/drt/analysis/zonal/ZonalDemandAggregatorWithoutServiceAreaTest.java, contribs/dvrp/src/main/java/org/matsim/contrib/dynagent/run/DynActivityEngine.java, examples/scenarios/mielec/mielec_drt_config.xml, examples/scenarios/mielec/mielec_edrt_config.xml, examples/scenarios/mielec/mielec_serviceArea_based_drt_config.xml, examples/scenarios/mielec/mielec_stop_based_drt_config.xml
This functionality was (too) tightly coupled with rebalancing. Now it is extracted from there.
Rebalancing strategies may use this zonal system for collecting demand data and making decisions.
=> Introduce zonal system params and DrtModeZonalSystemModule

contribs/commercialTrafficApplications/src/main/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/commercialJob/JointDemandUtils.java, matsim/src/main/java/org/matsim/utils/objectattributes/ObjectAttributesConverter.java, matsim/src/main/java/org/matsim/utils/objectattributes/attributeconverters/StringCollectionConverter.java, matsim/src/test/java/org/matsim/utils/objectattributes/attributeconverters/StringCollectionConverterTest.java
Added a converter which takes object attributes of type java.util.Collection.class with String elements.
Values have to be in json syntax.
For example: "["a","b"]
=> Support Collections as Object Attribute Type

contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/AggregatedMinCostRelocationCalculator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/DrtModeMinCostFlowRebalancingModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingStrategy.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingStrategyParams.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostRelocationCalculator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/RelocationCalculator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/TransportProblem.java
@luchengqi7 This PR is meant to simplify adding new or reusing existing `RelocationCalculator`s.
=> Clean up rebalnacing interfaces

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalSystem.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/demandestimator/PreviousIterationDRTDemandEstimator.java, contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/rebalancing/demandestimator/PreviousIterationDRTDemandEstimatorTest.java
- clean up
- remove limit on max time
- re-do unit tests (no need to run a controller)
=> Refine previous iteration DRT demand estimator

matsim/src/main/java/org/matsim/utils/objectattributes/ObjectAttributesConverter.java
check for string collection in ObjectAttributesConverter in order to read and write string collections
=> support string collections as ObjectAttributes

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtModeZonalSystemModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalSystemParams.java
We need this configurable as we ran into problems in some project setups where rebalancing was not able to help close accessibility gaps in the network
=> Make DrtZoneTargetLinkSelector configurable

contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingStrategyParams.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/targetcalculator/EqualVehicleDensityTargetCalculator.java
... as zonalDemandEstimatorType can not be set to null (otherwise NullPointerException)
=> comment out consistency check

contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/RebalancingUtils.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/AggregatedMinCostRelocationCalculator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/MinCostFlowRebalancingStrategy.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/mincostflow/TransportProblem.java
so that they can be reused in other rebalancing strategies
=> Expose min cost flow rebalancing internal methods

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtAnalysisControlerListener.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtPassengerAndVehicleStats.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtTrip.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtTripsAnalyser.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/BestInsertionFinder.java
- implement deterministic sort order for min cost insertion search (in order to achieve reproduciblity for single-threaded QSim simlations) <-- @tschlenther 
- refactor DrtPassengerAndVehicleStats (cleaning up and simplifying stuff before adapting it to the use with `TeleportingPassengerEngine`)
=> Deterministic DRT insertion 

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtPassengerAndVehicleStats.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/DefaultPassengerEngine.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/PassengerEngineQSimModule.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/TeleportingPassengerEngine.java
The next step will be adding support of passenger teleportation into DRT.
=> fully implement TeleportatingTassengerEngine

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtAnalysisControlerListener.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtRequestAnalyzer.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalWaitTimesAnalyzer.java
In case QSim ends before the request is actually handled
A few cleanups in drt output stats.
=> make pickup/dropoff events optional inside PerformedRequestEventSequence

contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/demandestimator/NetDepartureReplenishDemandEstimator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/plusOne/DrtModePlusOneRebalanceModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/plusOne/PlusOneRebalancingStrategy.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/DefaultPassengerEngine.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/PassengerEngineWithPrebooking.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/passenger/TeleportingPassengerEngine.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/QSimScopeObjectListener.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/QSimScopeObjectListenerModule.java, matsim/src/main/java/org/matsim/core/mobsim/qsim/DefaultTeleportationEngine.java, matsim/src/main/java/org/matsim/core/mobsim/qsim/TeleportationEngine.java, matsim/src/main/java/org/matsim/core/utils/collections/Tuple.java
use an internal instance of TeleportationEngine
=> Handle teleportation internally inside teleporting passenger engine

contribs/av/src/main/java/org/matsim/contrib/av/robotaxi/fares/drt/DrtFareHandler.java, contribs/av/src/test/java/org/matsim/contrib/av/robotaxi/fares/drt/DrtFareHandlerTest.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtModeZonalSystemModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalWaitTimesAnalyzer.java
A (final?) cleanup on the way to consistent handling of passenger-related events across all DRT stats.
=> Clean up drt event handling

examples/scenarios/chessboard/chessboard-chargers-1-plugs-1.xml
Chargers input file for usage in ev context
=> additional input file for example chessboard scenario

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtModeZonalSystemModule.java, contribs/dvrp/src/main/java/org/matsim/contrib/zone/SquareGrid.java, contribs/dvrp/src/main/java/org/matsim/contrib/zone/SquareGridSystem.java, contribs/dvrp/src/main/java/org/matsim/contrib/zone/ZonalSystem.java, contribs/dvrp/src/main/java/org/matsim/contrib/zone/util/NetworkWithZonesUtils.java, contribs/dvrp/src/test/java/org/matsim/contrib/zone/SquareGridTest.java, contribs/noise/pom.xml, contribs/taxi/src/main/java/org/matsim/contrib/etaxi/optimizer/rules/RuleBasedETaxiOptimizer.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/rules/RuleBasedTaxiOptimizer.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/zonal/ZonalTaxiOptimizer.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/optimizer/zonal/ZonalTaxiOptimizerParams.java, contribs/taxi/src/test/java/org/matsim/contrib/taxi/optimizer/zonal/ZonalTaxiOptimizerIT.java
Also: fix (eclipse only?) compile issues in `noise` wrt xml-apis being in 2 java modules.
=> Clean up square grid zonal system

contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/DvrpTravelTimeMatrix.java, contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/Matrix.java, contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/TravelTimeMatrices.java, contribs/dvrp/src/test/java/org/matsim/contrib/zone/skims/MatrixTest.java, contribs/dvrp/src/test/java/org/matsim/contrib/zone/skims/TravelTimeMatricesTest.java
It is specifically targeted for the DVRP needs and so may not fit to other applications.
=> implement faster and smaller Matrix for TTs between Zones

contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionSearchParams.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/MultiInsertionDetourPathCalculator.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/path/OneToManyPathCalculator.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/path/OneToManyPathSearch.java, contribs/dvrp/src/test/java/org/matsim/contrib/dvrp/path/OneToManyPathCalculatorTest.java
also enables it in DRT for searching path from vehicles to pickup location (limited by max wait time)
=> add maxTravelTime to OneToManyPathSearch

contribs/analysis/src/main/java/org/matsim/contrib/analysis/vsp/traveltimedistance/HereMapsRouteValidator.java, contribs/analysis/src/main/java/org/matsim/contrib/analysis/vsp/traveltimedistance/TravelTimeValidationRunner.java
The time window is now an optinal parameter for the travel time analysis. The comparison of travel time between the simulated trips and those based on the HERE database during some time interval (e.g. during night, during rush hours) can reveal more information and can be used to analyze if our network is well constructed.
=> Add time window as parameter to the travel time analaysis

matsim/src/main/java/org/matsim/core/utils/io/MatsimXmlParser.java, matsim/src/test/java/org/matsim/core/utils/io/MatsimXmlParserTest.java
https://en.wikipedia.org/wiki/XML_external_entity_attack
=> prevent XEE attacks (XML External Entity injection)

.github/workflows/verify-push.yaml, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/plusOne/DrtModePlusOneRebalanceModule.java
Let's test the new CI for PRs coming from forks.
=> bind LinkBasedRelocationCalculator as singleton

contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/rebalancing/plusOne/PlusOneRebalancingStrategy.java
1. requests are scheduled (--> events are emitted and processed in a separate thread)
2. rebalancing starts (--> this is the moment when both methods in the PlusOne strategy may be executed at the same time).
=> handle race conditions in PlusOneRebalancingStrategy

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalWaitTimesAnalyzer.java
Bug fixing: one delimiter is missing between line 96 and 97 (in the old code).
Besides, I have removed some empty space in front of the line  93-115/116
=> Small Bug fixing: One Delimiter missing in DrtZonalWaitTimesAnalyzer

contribs/emissions/src/main/java/org/matsim/contrib/emissions/EmissionModule.java, contribs/emissions/src/main/java/org/matsim/contrib/emissions/EmissionUtils.java, contribs/emissions/src/main/java/org/matsim/contrib/emissions/HbefaTrafficSituation.java, contribs/emissions/src/main/java/org/matsim/contrib/emissions/WarmEmissionAnalysisModule.java, contribs/emissions/src/main/java/org/matsim/contrib/emissions/package-info.java, contribs/emissions/src/test/java/org/matsim/contrib/emissions/TestWarmEmissionAnalysisModuleTrafficSituations.java
Introduced new traffic situation from HBEFA 4.1; made utils methods public.
=> Minor emission changes

contribs/pom.xml, matsim/pom.xml
preparation for resolving #1270
=> removing cobertura, adding jacoco maven plugins

contribs/pom.xml, matsim/pom.xml
=> need more changes to pom.mxl to run jacoco successfully

contribs/vsp/pom.xml, contribs/vsp/src/main/java/playground/vsp/flowEfficiency/AVFlowEfficiencyImpact.java, contribs/vsp/src/main/java/playground/vsp/flowEfficiency/BunchingFlowEfficencyImpact.java, contribs/vsp/src/main/java/playground/vsp/flowEfficiency/HierarchicalFlowEfficiencyCalculator.java, contribs/vsp/src/main/java/playground/vsp/flowEfficiency/LinkTurnDirectionAttributesFromGraphHopper.java, contribs/vsp/src/main/java/playground/vsp/flowEfficiency/SituationalFlowEfficiencyImpact.java, contribs/vsp/src/test/java/playground/vsp/flowEfficiency/HierarchicalFLowEfficiencyCalculatorTest.java
Infrastructure and examples to declare hierarchically situational impacts on flow efficiency. See also #1283
=> situational flow efficiency with some experimental examples

contribs/otfvis/pom.xml
Same as #1294 but for linux-amd.
=> add linux-amd gluegen-rt and jogl (referencing jars uploaded by michaz)

contribs/drt/src/main/java/org/matsim/contrib/edrt/optimizer/EDrtVehicleDataEntryFactory.java, contribs/drt/src/main/java/org/matsim/contrib/edrt/run/EDrtControlerCreator.java, contribs/drt/src/main/java/org/matsim/contrib/edrt/run/RunEDrtScenario.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/DvrpQSimComponents.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/MultiModals.java, contribs/ev/src/main/java/org/matsim/contrib/ev/dvrp/EvDvrpIntegrationModule.java, contribs/taxi/src/main/java/org/matsim/contrib/etaxi/run/RunETaxiBenchmark.java, contribs/taxi/src/main/java/org/matsim/contrib/etaxi/run/RunETaxiScenario.java
=> Multi mode e-DRT

contribs/taxi/src/main/java/org/matsim/contrib/etaxi/run/RunETaxiBenchmark.java, contribs/taxi/src/main/java/org/matsim/contrib/etaxi/run/RunETaxiScenario.java
Like #1305, but this time for taxi
=> support multi-mode e-taxi

contribs/drt/src/main/java/org/matsim/contrib/edrt/optimizer/depot/NearestChargerAsDepot.java, contribs/drt/src/main/java/org/matsim/contrib/edrt/run/EDrtModeOptimizerQSimModule.java, contribs/ev/src/main/java/org/matsim/contrib/ev/infrastructure/ChargingInfrastructures.java, contribs/taxi/src/main/java/org/matsim/contrib/etaxi/run/ETaxiModeQSimModule.java
@steffenaxer, this should fix #1301
=> Fix: network mode-filtering in e-DRT and e-taxi

examples/scenarios/berlin/config.xml, examples/scenarios/berlin/config_multimodal.xml, examples/scenarios/berlin/config_withinday.xml
=> define all necessary modes in config for old berlin scenario

contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DetourData.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DetourTimesProvider.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionCostCalculator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/MultiInsertionDetourPathCalculator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SingleInsertionDetourPathCalculator.java, contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DetourDataTest.java
Cost calculation should be less iffy now. Also fixes #913
=> DRT: Fix and cleanup insertion cost calculation

contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/Matrix.java
=> Remove max zone count limit in dvrp matrix

contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/VehicleDataEntryFactoryImpl.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/Waypoint.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionCostCalculator.java, contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionCostCalculatorTest.java, contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionDetourTimeCalculatorTest.java, contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGeneratorTest.java
The first round of the announced cleanup in the insertion cost calculation. Unit tests are added only for the already cleaned up part.
=> Clean up and test insertion cost calculator (part 1)

contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/components/utils/ScheduleWaitingTimeEstimatorTest.java, contribs/eventsBasedPTRouter/src/main/java/org/matsim/contrib/eventsBasedPTRouter/waitTimes/WaitTimeStuckCalculator.java, contribs/pseudosimulation/src/main/java/org/matsim/contrib/pseudosimulation/distributed/PlanSerializable.java, matsim/src/main/java/org/matsim/pt/routes/ExperimentalTransitRouteFactory.java, matsim/src/test/java/org/matsim/analysis/Plans.java
inspired by https://github.com/matsim-org/matsim-libs/issues/1365
=> deprecate ExperimentalTransitRouteFactory and replace it where possible

contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultDrtInsertionSearch.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionProvider.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionSearchQSimModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionProvider.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/SelectiveInsertionSearchQSimModule.java
The difference between the extensive and selective DRT search is actually only the prefiltering of insertions.
=> DRT: generalise insertion search with insertion providers

contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionProvider.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionSearchParams.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/KNearestInsertionsAtEndFilter.java, contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DefaultDrtInsertionSearchTest.java, contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DefaultUnplannedRequestInserterTest.java, contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/ExtensiveInsertionProviderTest.java, contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/ForkJoinPoolTestRule.java, contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/KNearestInsertionsAtEndFilterTest.java, contribs/dvrp/src/main/java/org/matsim/contrib/util/PartialSort.java, contribs/dvrp/src/test/java/org/matsim/contrib/util/PartialSortTest.java
Additionally:
- support k=0 in k-nearest filtering (and related classes)
- some smaller cleanups/improvements
=> DRT: add extensive insertion provider tests

contribs/commercialTrafficApplications/src/main/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/RunJointDemandCarExample.java, contribs/commercialTrafficApplications/src/main/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/RunJointDemandDRTExample.java, contribs/commercialTrafficApplications/src/main/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/commercialJob/JointDemandUtils.java, contribs/commercialTrafficApplications/src/test/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/RunJointDemandCarExampleIT.java, contribs/commercialTrafficApplications/src/test/java/org/matsim/contrib/commercialTrafficApplications/jointDemand/RunJointDemandDRTExampleIT.java
give users access to most of the functionality in JointDemandUtils.
also added integration tests
=> Make most methofds in JointDemandUtils public

contribs/freight/src/main/java/org/matsim/contrib/freight/controler/CarrierAgent.java
from warn to debug in `CarrierAgent`
=> Freight: reduce logging level 

contribs/drt/src/main/java/org/matsim/contrib/edrt/scheduler/EmptyVehicleChargingScheduler.java, contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingWithAssignmentLogic.java, contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingWithQueueingAndAssignmentLogic.java, contribs/ev/src/main/java/org/matsim/contrib/ev/dvrp/ChargingActivity.java, contribs/ev/src/main/java/org/matsim/contrib/ev/dvrp/ChargingTask.java, contribs/ev/src/main/java/org/matsim/contrib/ev/dvrp/ChargingTaskImpl.java, contribs/ev/src/main/java/org/matsim/contrib/ev/stats/ChargerOccupancyTimeProfileCollectorProvider.java, contribs/ev/src/main/java/org/matsim/contrib/ev/stats/ChargerOccupancyXYDataProvider.java, contribs/taxi/src/main/java/org/matsim/contrib/etaxi/ETaxiScheduler.java, contribs/taxi/src/main/java/org/matsim/contrib/etaxi/optimizer/assignment/AssignmentChargerPlugData.java
allow more flexibility for DRT charging logic
=> ChargingWithAssignmentLogicInterface

contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/events/handlers/PersonArrivalDepartureHandler.java, contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/manager/supply/OneWayContainer.java
fixing two bugs in one-way station car-sharing:
- parking is now properly made available after the agent enters the car-sharing vehicle
=> Carsharing patch

contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/runExample/RunCarsharing.java
the scenario has to be loaded after the carsharing factory has been
added
=> fixing the issue when input plans have carsharing trips

contribs/freight/test/input/org/matsim/contrib/freight/carrier/CarrierVehicleTypeReaderTest/vehicleTypes_v2.xml, matsim/src/main/java/org/matsim/core/mobsim/qsim/pt/TransitQVehicle.java, matsim/src/main/java/org/matsim/vehicles/VehicleCapacity.java, matsim/src/test/java/org/matsim/core/mobsim/hermes/HermesTransitTest.java, matsim/src/test/java/org/matsim/core/mobsim/qsim/pt/AbstractTransitVehicleTest.java
see https://github.com/matsim-org/matsim-libs/issues/1421
=> adapt error message about vehicle capacity

contribs/common/src/test/java/org/matsim/contrib/common/randomizingtransitrouter/RandomizingTransitRouterIT.java, contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/examples/TestSiouxFalls.java, contribs/minibus/src/test/java/org/matsim/contrib/minibus/integration/SubsidyTestIT.java, contribs/pseudosimulation/src/test/java/org/matsim/contrib/pseudosimulation/RunPSimTest.java, contribs/vsp/src/test/java/org/matsim/integration/drtAndPt/PtAlongALine2Test.java, contribs/vsp/src/test/java/playground/vsp/ptdisturbances/EditTripsTest.java, matsim/src/main/java/org/matsim/pt/config/TransitConfigGroup.java, matsim/src/test/java/org/matsim/examples/simple/PtScoringTest.java, matsim/src/test/java/org/matsim/pt/transitSchedule/TransitScheduleReprojectionIOTest.java
for a better out-of-the-box experience.
=> Make SwissRailRaptor the default transit router

.github/workflows/deploy-on-pr-merge.yaml, .github/workflows/deploy-on-release-created.yaml
hopefully fixing the issue so it can deploy to our maven repository
=> update deployment workflows

contribs/carsharing/README.md, contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/config/FreeFloatingConfigGroup.java, contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/config/OneWayCarsharingConfigGroup.java, contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/config/TwoWayCarsharingConfigGroup.java, contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/replanning/CarsharingSubTourPermissableModesCalculator.java, contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/replanning/ChooseRandomTripMode.java, contribs/carsharing/src/test/java/org/matsim/contrib/carsharing/runExample/RunCarsharingIT.java, contribs/carsharing/test/input/org/matsim/contrib/carsharing/runExample/RunCarsharingIT/config.xml
This pull request solves #1419, further cleans carsharing configuration and adds more documentation.
=> Carsharingpatch

contribs/hybridsim/pom.xml, contribs/protobuf/pom.xml
Hopefully solves #1451 (see also #1493).
@luchengqi7 I cannot test it, so please confirm if that issue is fixed or not.
=> bump os-maven-plugin to 1.7.0 (to fix protoc on Apple M1)

matsim/pom.xml, pom.xml
=> Guice 5.0.1

.github/workflows/deploy-on-pr-merge.yaml, .github/workflows/deploy-on-release-created.yaml, .github/workflows/verify-push.yaml, benchmark/pom.xml, contribs/pom.xml, examples/pom.xml, matsim/pom.xml, pom.xml
=> Move javadoc to release profile

contribs/application/src/main/java/org/matsim/application/options/SampleOptions.java, contribs/application/src/main/java/org/matsim/application/prepare/freight/ExtractRelevantFreightTrips.java, contribs/application/src/main/java/org/matsim/application/prepare/network/CreateNetworkFromSumo.java, contribs/application/src/main/java/org/matsim/application/prepare/population/CleanPopulation.java, contribs/application/src/main/java/org/matsim/application/prepare/population/TrajectoryToPlans.java, contribs/application/src/test/java/org/matsim/application/MATSimApplicationTest.java, contribs/sumo/src/main/java/org/matsim/contrib/sumo/SumoNetworkConverter.java
* Set CRS attribute if it was given
* Add service road type to sumo converter
* Reusable options to run scenario at different sample sizes
=> Extensions to matsim application

contribs/application/src/main/java/org/matsim/application/prepare/population/CleanPopulation.java
Command now throws an error if no operation was specified.
=> Improve clean population command

.github/workflows/deploy-on-pr-merge.yaml, .github/workflows/verify-push.yaml
Mostly meant to simplify building and releasing matsim on many long-lived branches (master, 13.x, etc). A short description commit by commit:
1. Actions workflows are executed using the definition from the current branch, so it is enough to refer to the actual base branch (like `master` or `13.x` etc.). Same changes will be applied to configs in 13.x (via a separate PR).
2. By adding `verify-all-jobs-successful` we can easily define one required check (in branch protection) for each branch. Right now we have to create a long list of all required checks (currently almost 40 !!!) and keep it updated (which means lots of manual edits and high chances of making it wrong). Additionally this list may be different for master, 13.x, 14.x and so on:
3. `benchmark` module was never included into …
=> Ci improvements

.github/workflows/deploy-on-pr-merge.yaml, .github/workflows/verify-push.yaml
Similar to #1540 merged to master (with some little adaptations for 13.x)
=> 13.x CI improvements

.github/workflows/deploy-on-pr-merge.yaml, .github/workflows/deploy-on-release-created.yaml, .github/workflows/verify-push.yaml
Related to #1521
Just before bumping to 16, let's make sure everything works smooth with 15.
=> CI: bump JDK to 15 in workflow configs

.github/workflows/deploy-on-pr-merge.yaml, .github/workflows/deploy-on-release-created.yaml, .github/workflows/verify-push.yaml, contribs/bicycle/pom.xml, contribs/freight/pom.xml, matsim/pom.xml, pom.xml
=> adapt 13.x to jdk 16 in workflows

contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/config/CarsharingConfigGroup.java, contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/config/FreeFloatingConfigGroup.java, contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/config/OneWayCarsharingConfigGroup.java, contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/config/TwoWayCarsharingConfigGroup.java, contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/manager/CarsharingManagerNew.java, contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/manager/supply/CompanyAgent.java, contribs/carsharing/src/main/java/org/matsim/contrib/carsharing/manager/supply/CompanyAgentImpl.java, contribs/carsharing/test/input/org/matsim/contrib/carsharing/runExample/RunCarsharingIT/config.xml
the manager now uses search radius from the config file for all three types of carsharing. Updated the config groups and added further documentation.
=> updating carsharing contrib

contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigGroup.java, contribs/drt/src/main/java/org/matsim/contrib/drt/run/MultiModeDrtConfigGroup.java, contribs/dvrp/src/main/java/org/matsim/contrib/util/ReflectiveConfigGroupWithConfigurableParameterSets.java, matsim/src/main/java/org/matsim/core/config/groups/QSimConfigGroup.java
typed setters in config groups; some FIXMEs (to write javadoc)
=> drt UI improvements

matsim/src/main/java/org/matsim/analysis/personMoney/PersonMoneyEventsAggregator.java, matsim/src/main/java/org/matsim/analysis/personMoney/PersonMoneyEventsAnalysisControlerListener.java, matsim/src/main/java/org/matsim/analysis/personMoney/PersonMoneyEventsAnalysisModule.java, matsim/src/main/java/org/matsim/analysis/personMoney/PersonMoneyEventsCollector.java
Adds aggregated personMoneyEvent table (PersonMoneyEventsAggregator) at each iteration and writes out all PersonMoneyEvents of the last iteration (PersonMoneyEventsCollector).
By default not installed, can be switched by installing PersonMoneyEventsAnalysisModule.
=> Person money event analysis

contribs/sbb-extensions/src/main/java/ch/sbb/matsim/analysis/skims/CalculateSkimMatrices.java
=> unify naming logic in skims

contribs/vsp/src/test/java/org/matsim/integration/drtAndPt/PtAlongALine2Test.java
also cherry-pick second commit from #1464. so this completes #1564
=> remove SwissRailRaptorModule but let use SRR by default in config

contribs/vsp/src/main/java/playground/vsp/pt/ptdisturbances/RunExamplePtDisturbances.java, contribs/vsp/src/main/java/playground/vsp/pt/transitRouteTrimmer/RunTransitRouteTrimmerBerlinExample.java, contribs/vsp/src/main/java/playground/vsp/pt/transitRouteTrimmer/RunTransitRouteTrimmerBerlinSimpleExample.java, contribs/vsp/src/main/java/playground/vsp/pt/transitRouteTrimmer/RunTransitRouteTrimmerGladbeckExample.java, contribs/vsp/src/main/java/playground/vsp/pt/transitRouteTrimmer/TransitRouteTrimmer.java, contribs/vsp/src/main/java/playground/vsp/pt/transitRouteTrimmer/TransitRouteTrimmerUtils.java, contribs/vsp/src/test/java/playground/vsp/pt/ptdisturbances/EditTripsTest.java, contribs/vsp/src/test/java/playground/vsp/pt/transitRouteTrimmer/TransitRouteTrimmerTest.java
=> Pt route trimmer

contribs/socnetsim/src/main/java/org/matsim/contrib/socnetsim/framework/replanning/modules/BlackListedTimeAllocationMutator.java
Fix #1588
That was indeed a bug introduced by refactoring (during conversion to `OptionalTime`).
=> fix handing of undefined time in BlackListedTimeAllocationMutator

matsim/src/main/java/org/matsim/analysis/TripsAndLegsCSVWriter.java
...seems to be a handy extension for custom columns
=> add personId to CustomTripsWriterExtension

contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/DefaultRequestInsertionScheduler.java
fix https://github.com/matsim-org/matsim-code-examples/issues/578
=> fix: properly handle delayed vehicles when inserting dropoffs

.github/workflows/verify-push.yaml
This reverts commit 21c6b44c
Seems that #1614 is not an issue anymore.
=> Revert "split job matrix into 2 smaller matrices"

contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/path/LeastCostPathTreeStopCriteria.java, contribs/dvrp/src/test/java/org/matsim/contrib/dvrp/path/LeastCostPathTreeStopCriteriaTest.java
Compared to the `allEndNodesReached`, this criterion detects cases when the first of the end nodes is reached. Each end node may be assigned some additional cost (that can be interpreted as an access or egress cost, depending on the search type: either forward or backward).
=> Stop multi-node dijkstra after finding least-cost end node

contribs/freight/src/main/java/org/matsim/contrib/freight/FreightConfigGroup.java, contribs/freight/src/main/java/org/matsim/contrib/freight/jsprit/MatsimJspritFactory.java
(hopefully) fix reading the vra algorithm file from matsim-examples
(make it at least the same way as it is for the other freight files)
=> Freight vrp algo reading

contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/components/estimators/AbstractTripRouterEstimator.java, contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/model/DiscreteModeChoiceTrip.java, contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/replanning/TripListConverter.java, contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/components/tour_finder/ActivityTourFinderTest.java, contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/models/MaximumUtilityTest.java, contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/models/MultinomialLogitTest.java, contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/models/NestedLogitTest.java, contribs/discrete_mode_choice/src/test/java/org/matsim/contrib/discrete_mode_choice/models/RandomUtilityTest.java, contribs/locationchoice/src/main/java/org/matsim/contrib/locationchoice/timegeography/RecursiveLocationMutator.java, contribs/minibus/src/main/java/org/matsim/contrib/minibus/performance/PPlanRouter.java, matsim/src/main/java/org/matsim/core/mobsim/qsim/PreplanningEngine.java, matsim/src/main/java/org/matsim/core/router/PlanRouter.java, matsim/src/main/java/org/matsim/core/router/TripStructureUtils.java, matsim/src/main/java/org/matsim/withinday/utils/EditTrips.java
... to encapsulate obtaining attributes for a trip so we can replace the process at a later time.
=> Add Trip.getTripAttributes

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtAnalysisControlerListener.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtEventSequenceCollector.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtLeg.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtModeAnalysisModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtModeZonalSystemModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/DrtZonalWaitTimesAnalyzer.java, contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/speedup/DrtSpeedUp.java, contribs/drt/src/test/java/org/matsim/contrib/drt/speedup/DrtSpeedUpTest.java
After series of refactorings, the old name is misleading.
=> drt: rename DrtRequestAnalyzer to DrtEventSequenceCollector

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/afterSimAnalysis/DrtIdleVehicleWriter.java
The previous code cannot analyse small event file. Now it is possible to do so.
=> Bug fixing in the Idle vehicle writer

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/afterSimAnalysis/DrtIdleVehicleWriter.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/afterSimAnalysis/DrtVehicleStoppingTaskWriter.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/afterSimAnalysis/StayTaskRecorder.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/afterSimAnalysis/StoppingTaskRecorder.java
In the visualisation (VIA), the vehicle will disappear when pick up or drop off passenger. The DRT vehicle writer will now also write the stop task (pick up and drop off) and that can be used by the visualisation.
=> Include stop task (pick up and drop off) in the drt stopping task writer

contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingEndEvent.java, contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingEndEventHandler.java, contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingEventSequenceCollector.java, contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingStartEvent.java, contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingStartEventHandler.java, contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingWithQueueingLogic.java, contribs/ev/src/main/java/org/matsim/contrib/ev/charging/QueuedAtChargerEvent.java, contribs/ev/src/main/java/org/matsim/contrib/ev/charging/QueuedAtChargerEventHandler.java
and:
- add the current battery charge to charging start/end events
- collect charging related events into sequences for later analysis (e.g. in e-drt or e-taxi)
=> Add queued at charger event

contribs/dvrp/src/main/java/org/matsim/contrib/util/stats/DurationStats.java, contribs/ev/src/main/java/org/matsim/contrib/ev/stats/EvStatsModule.java, contribs/taxi/src/main/java/org/matsim/contrib/etaxi/run/ETaxiBenchmarkStats.java, contribs/taxi/src/main/java/org/matsim/contrib/etaxi/run/RunETaxiBenchmark.java, contribs/taxi/src/main/java/org/matsim/contrib/etaxi/util/ETaxiStatsCalculator.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/benchmark/RunTaxiBenchmark.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/benchmark/TaxiBenchmarkStats.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/run/TaxiModeModule.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/util/stats/TaxiStatsCalculator.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/util/stats/TaxiStatsDumper.java
As in DRT, now both taxi and e-taxi stats are computed from collected events.
=> Compute taxi  stats from events

.github/workflows/verify-push.yaml, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/zonal/RandomDrtZoneTargetLinkSelector.java, contribs/drt/src/test/java/org/matsim/contrib/drt/analysis/zonal/RandomDrtZoneTargetLinkSelectorTest.java
=> 13.x jdk17 in GitHub actions

appveyor.yml
(currently latest on appveyor)
=> appveyor: change jdk from 11 to 16

contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/router/AttributeBasedStopFinder.java
A follow-up to #1641 (where the delegation to `ClosestAccessEgressFacilityFinder` was discussed)
=> dvrp: delegate to ClosestAccessEgressFacilityFinder from AttributeBasedStopFinder

contribs/drt/src/test/java/org/matsim/contrib/drt/run/examples/RunDrtExampleIT.java
Differences between "extensive" and "selective" are really minimal (assuming we use the free-speed estimates):
```java
.waitAverage(296.95)
.inVehicleTravelTimeMean(387.02)
.totalTravelTimeMean(683.97)
```
vs
```java
.waitAverage(293.47)
.inVehicleTravelTimeMean(389.71)
.totalTravelTimeMean(683.18)
```
=> drt: add tests comparing extensive and selective search for "no rejections" cases

contribs/emissions/src/main/java/org/matsim/contrib/emissions/PositionEmissionsModule.java
Thought the check was not correct but only couldn't read my code. Now, said check is in a separate method...
=> fix position emission module's consistency check.

contribs/analysis/src/main/java/org/matsim/contrib/analysis/vsp/traveltimedistance/CarTrip.java, contribs/analysis/src/main/java/org/matsim/contrib/analysis/vsp/traveltimedistance/NetworkTrip.java, contribs/analysis/src/main/java/org/matsim/contrib/analysis/vsp/traveltimedistance/RunTraveltimeValidationExample.java, contribs/analysis/src/main/java/org/matsim/contrib/analysis/vsp/traveltimedistance/TravelTimeValidationRunner.java, contribs/analysis/src/main/java/org/matsim/contrib/analysis/vsp/traveltimedistance/TravelTimeValidationRunnerPreAnalysis.java
- Update and standardise the title row name of the csv (tsv) file
- Change the delimiter from ";" to tab (csv --> tsv)
=> Updating the output of the travel time validation

contribs/emissions/src/main/java/org/matsim/contrib/emissions/example/CreateEmissionConfig.java, contribs/emissions/src/main/java/org/matsim/contrib/emissions/utils/EmissionsConfigGroup.java, contribs/vsp/src/main/java/playground/vsp/airPollution/exposure/EmissionResponsibilityCostModule.java, contribs/vsp/src/main/java/playground/vsp/airPollution/flatEmissions/EmissionCostModule.java, examples/scenarios/emissions-sampleScenario/testv2_Vehv1/config_detailed.xml, examples/scenarios/emissions-sampleScenario/testv2_Vehv2/config_detailed.xml
Trying to slowly get rid of deprecated boolean config options ...
=> RuntimeExceptions --> remove; deprecated --> RuntimeExceptions

contribs/application/src/main/java/org/matsim/application/analysis/LinkStats.java, contribs/application/src/main/java/org/matsim/application/options/ShpOptions.java
Added the implementation of "A Traffic Congestion Assessment Method for Urban Road Networks Based on Speed Performance Index" from @luchengqi7, into the existing link stats analysis class.
=> Added Congestion analysis

contribs/emissions/README.md, contribs/emissions/src/main/java/org/matsim/contrib/emissions/example/CreateEmissionConfig.java, contribs/emissions/src/main/java/org/matsim/contrib/emissions/utils/EmissionsConfigGroup.java, contribs/vsp/src/main/java/playground/vsp/airPollution/exposure/EmissionResponsibilityCostModule.java, contribs/vsp/src/main/java/playground/vsp/airPollution/flatEmissions/EmissionCostModule.java, examples/scenarios/emissions-sampleScenario/testv2_Vehv1/config_detailed.xml, examples/scenarios/emissions-sampleScenario/testv2_Vehv2/config_detailed.xml
Put the changes from #1765 and #1773 (added to the `13.x` branch) into master as well.
=> Emissions maintenance 

contribs/emissions/README.md, contribs/emissions/src/main/java/org/matsim/contrib/emissions/utils/EmissionsConfigGroup.java
minor changes:
- remove accidentally added import in #1765 
- Update preferred citations --> cite MATSim book
=> 13.x emissions maintenance kmt

contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/fleet/FleetModule.java, examples/scenarios/dvrp-grid/multi_mode_one_shared_taxi_config.xml, examples/scenarios/dvrp-grid/one_shared_taxi_matsim_vehicles.xml, examples/scenarios/dvrp-grid/one_shared_taxi_vehicles_A.xml, examples/scenarios/dvrp-grid/one_shared_taxi_vehicles_B.xml, examples/scenarios/dvrp-grid/one_shared_taxi_vehicles_C.xml
Now the example uses the standard vehicle specification (all 3 fleets in one file).
=> Update multi-mode drt example

contribs/drt/src/main/java/org/matsim/contrib/drt/schedule/DrtDriveTask.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetaxi/OneTaxiOptimizer.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetruck/OneTruckOptimizer.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/schedule/DefaultDriveTask.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/schedule/DriveTask.java, contribs/dvrp/src/test/java/org/matsim/contrib/dvrp/router/DiversionTest.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/schedule/TaxiEmptyDriveTask.java
Like #1800 but this time for drive tasks
=> dvrp: extract DriveTask interface

contribs/vsp/src/main/java/org/matsim/contrib/freight/analysis/FreightAnalysisEventHandler.java, contribs/vsp/src/main/java/org/matsim/contrib/freight/analysis/RunFreightAnalysis.java
... by making runAnalysis() public.
converted some indentations on the way.
=> Make freight analysis accessible

examples/scenarios/freight-chessboard-9x9/singleCarrierWithoutRoutes.xml
=> add singleCarrierWithoutRoutes.xml

examples/scenarios/freight-chessboard-9x9/singleCarrier.xml, examples/scenarios/freight-chessboard-9x9/singleCarrierWithoutRoutes.xml
This was missing in the carrier files :(
=> freight example: add jsprit iterations

contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierCapabilities.java, contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierImpl.java, contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierPlan.java, contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierPlanReaderV1.java, contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierPlanWriter.java, contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierPlanXmlParserV2.java, contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierPlanXmlReader.java, contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierPlanXmlWriterV1.java, contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierService.java, contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierShipment.java, contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierUtils.java, contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierVehicle.java, contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierVehicleType.java, contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierVehicleTypeLoader.java, contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierVehicleTypeReader.java, contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierVehicleTypeReaderV1.java, contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierVehicleTypeWriter.java, contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierVehicleTypes.java, contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/Carriers.java, contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/FreightConstants.java, contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/TimeWindow.java, contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/Tour.java, contribs/freight/src/main/java/org/matsim/contrib/freight/jsprit/MatsimJspritFactory.java, contribs/freight/src/main/java/org/matsim/contrib/freight/utils/FreightUtils.java
After #1849 there were some leftovers. Cleaning this up a bit, including some cleanup left and right.
This PR is focussed on the `Carrier` package.
Mainly done:
- remove commented out code
- make some stuff deprecated
- replace if by switch statement(s)
- make some things final (based on IntelliJ codeInspection)
- fixing some typos
- renaming some internal variable, e.g. for clarifying a bit more if it belongs to jsprit or MATSim
Some more cleanup PRs might follow.
=> Freight cleanup

contribs/sharing/src/main/java/org/matsim/contrib/sharing/analysis/SharingAnalysisModule.java, contribs/sharing/src/main/java/org/matsim/contrib/sharing/analysis/SharingLeg.java, contribs/sharing/src/main/java/org/matsim/contrib/sharing/analysis/SharingLegBuilder.java, contribs/sharing/src/main/java/org/matsim/contrib/sharing/analysis/SharingLegCollector.java, contribs/sharing/src/main/java/org/matsim/contrib/sharing/analysis/SharingLegCollectorImpl.java, contribs/sharing/src/main/java/org/matsim/contrib/sharing/analysis/SharingStatisticsAnalyzer.java, contribs/sharing/src/main/java/org/matsim/contrib/sharing/run/SharingModule.java, contribs/sharing/src/main/java/org/matsim/contrib/sharing/service/events/SharingPickupEvent.java, contribs/sharing/src/main/java/org/matsim/contrib/sharing/service/events/SharingVehicleEvent.java
This PR adds a basic AnalysisModule for the sharing contrib. The legs of all sharing modes are exported per iteration into all_sharingLegs.csv. The contents of this file holds to following information:
personId;departureTime;arrivalTime;sharingServiceId;distance;vehicleId;from_x;from_y;to_x;to_y
Best,
Steffen
=> Added basic SharingLeg analysis

contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DetourTimeEstimator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionDetourTimeCalculator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGenerator.java, contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/DetourTimeEstimatorTest.java, contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionDetourTimeCalculatorTest.java, contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGeneratorTest.java
so we can introduce time-dependent TT matrices
=> feat(drt): make DetourTimeEstimator time dependent

contribs/shared_mobility/src/main/java/org/matsim/contrib/shared_mobility/logic/SharingLogic.java, contribs/shared_mobility/src/main/java/org/matsim/contrib/shared_mobility/service/FreefloatingService.java, contribs/shared_mobility/src/main/java/org/matsim/contrib/shared_mobility/service/StationBasedService.java
This PR ensures that a reserved vehicle is released after drop off and asserts that a vehicle is only reserved once.
Best,
Steffen
=> Ensure one reservation per sharing vehicle

contribs/freight/src/main/java/org/matsim/contrib/freight/events/LSPFreightLinkEnterEvent.java, contribs/freight/src/main/java/org/matsim/contrib/freight/events/LSPFreightLinkLeaveEvent.java, contribs/freight/src/main/java/org/matsim/contrib/freight/events/LSPFreightVehicleLeavesTrafficEvent.java, contribs/freight/src/main/java/org/matsim/contrib/freight/events/LSPServiceEndEvent.java, contribs/freight/src/main/java/org/matsim/contrib/freight/events/LSPServiceStartEvent.java, contribs/freight/src/main/java/org/matsim/contrib/freight/events/LSPTourEndEvent.java, contribs/freight/src/main/java/org/matsim/contrib/freight/events/LSPTourStartEvent.java
Some fixes for the (LSP) Freight events
- some events has not had the correct events type -> fixed
- some events has had missing attributes -> fixed
- making more things final
=> Freight: fix some LSP Freight events

matsim/src/main/java/org/matsim/core/network/algorithms/NetworkSimplifier.java
This change allows to customize the merging of links when simplifying a network:
- A predicate `isMergable` can optionally be passed to the `NetworkSimplifier` to prevent links from being merged.
- A consumer `transferAttributes` can optionally be passed to the `NetworkSimplifier` to handle the merging of non-standard link attributes.
The motivation behind this stems from the [bicycle contrib](https://github.com/matsim-org/matsim-libs/tree/master/contribs/bicycle/src/main/java/org/matsim/contrib/bicycle) which has an [`BicycleOsmNetworkReaderV2`](https://github.com/matsim-org/matsim-libs/blob/master/contribs/bicycle/src/main/java/org/matsim/contrib/bicycle/network/BicycleOsmNetworkReaderV2.java) that attaches custom link attributes like `type` and `surface` for example. Currently, there …
=> Allow customizing of NetworkSimplifier

contribs/drt/src/main/java/org/matsim/contrib/drt/extension/preplanned/run/PreplannedDrtControlerCreator.java
Rebalancing would interfere with simulation of pre-calculated vehicle schedules.
=> drt: make sure rebalancing is disabled for pre-planned drt optimizer

contribs/vsp/src/main/java/org/matsim/contrib/freight/analysis/FreightAnalysisEventHandler.java
The vehicle pattern is not dependent on the vehType. 
Therefor filtering for it, was too restrictive --> removing it :)
=> Freight analysis: Minor fix - remove not needed filter for vehType.

contribs/drt/src/main/java/org/matsim/contrib/drt/passenger/PromisedPickupTimeWindowDrtOfferAcceptor.java
update of https://github.com/matsim-org/matsim-libs/pull/1954
in response to
https://github.com/matsim-org/matsim-libs/pull/1963
Left out the config parameter for now.
@michalmac I wasn't sure about the package location, it's not necessarily part of an extension.
=> DRT - promised pickup time window offer acceptor

contribs/ev/src/main/java/org/matsim/contrib/ev/charging/BatteryCharging.java, contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingPower.java
Answer the questions raised in #1960.
=> ev: add javadoc to ChargingPower and BatteryCharging

contribs/application/src/main/java/org/matsim/freightDemandGeneration/CarrierReaderFromCSV.java, contribs/application/src/main/java/org/matsim/freightDemandGeneration/DemandReaderFromCSV.java, contribs/application/src/test/java/org/matsim/freightDemandGeneration/CarrierReaderFromCSVTest.java
fix problem with duplicate vehicle Ids while the creation of vehicles for the carriers
=> fix problem with duplicate vehicle Ids

contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/DefaultRequestInsertionScheduler.java
I guess the second output message should be "timeFromScheduler"
=> Small bug fixing in the output message

contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/preplanned/run/PreplannedDrtModeModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeRoutingModule.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/router/DvrpModeRoutingModule.java
So it can be reused in the standard and pre-planned DRT
=> drt: extract DrtModeRoutingModule

contribs/application/src/main/java/org/matsim/application/prepare/population/ResolveGridCoordinates.java
In #1967, the history got messed up. This PR is a clean solution. In #1967, we decided to throw an exception if a non-car link is discovered during the process of attaching linkIds to activity coordinates.
=> ResolveGridCoordinates

contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/edrt/run/EDrtModeOptimizerQSimModule.java, contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/edrt/schedule/EDrtStayTaskEndTimeCalculator.java, contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/shifts/optimizer/ShiftRequestInsertionScheduler.java, contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/shifts/run/ShiftDrtModeOptimizerQSimModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DrtModeOptimizerQSimModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/DefaultIncrementalStopDurationEstimator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/IncrementalStopDurationEstimator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionDetourTimeCalculator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGenerator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/extensive/ExtensiveInsertionProvider.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/extensive/ExtensiveInsertionSearch.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/extensive/ExtensiveInsertionSearchQSimModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/selective/SelectiveInsertionProvider.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/selective/SelectiveInsertionSearch.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/selective/SelectiveInsertionSearchQSimModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeRoutingModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/schedule/DrtStayTaskEndTimeCalculator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/schedule/StopDurationEstimator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/scheduler/DefaultRequestInsertionScheduler.java, contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionDetourTimeCalculatorTest.java, contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionDetourTimeCalculatorWithVariableDurationTest.java, contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGeneratorTest.java, contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/extensive/ExtensiveInsertionProviderTest.java, contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/selective/SelectiveInsertionProviderTest.java
New attempt of 
https://github.com/matsim-org/matsim-libs/pull/1809
I tried to incorporate the ideas discussed in the old PR and for now chose "IncrementalStopDurationEstimator" over "AdditionalStopDuration" for naming the second interface.
@sebhoerl @michalmac let me know if this is what you envisioned.
=> drt - Variable stop durations

matsim/src/main/java/org/matsim/core/config/ReflectiveConfigGroup.java
Adapts #1991 to multi-level inheritance.
=> core: support multi-level inheritance of ReflectiveConfigGroup

matsim/src/main/java/org/matsim/core/config/groups/PlanCalcScoreConfigGroup.java, matsim/src/main/java/org/matsim/core/scoring/functions/ActivityUtilityParameters.java, matsim/src/main/java/org/matsim/core/scoring/functions/ScoringParameters.java
In particular, set relative score computation as default so it does not have to be set in user code.
=> change activity params defaults

contribs/vsp/pom.xml, contribs/vsp/src/main/java/playground/vsp/flowEfficiency/LinkTurnDirectionAttributesFromGraphHopper.java, pom.xml
See https://github.com/matsim-org/matsim-libs/pull/2010#issuecomment-1137829045
=> vsp: replace graphhopper-reader-osm 2.4 with graphhopper-core to 5.3

.github/workflows/code-coverage.yaml, README.md
Add badges to README.md for selected workflows and the test coverage.
=> GitHub actions code coverage 2

.github/workflows/full-integration.yaml
Run unit and integration tests for the release profile everyday at 0:30 UTC.
=> build: add full integration workflow

matsim/src/main/java/org/matsim/core/controler/Injector.java
I have used this multiple times for teaching, to illustrate the principle.  I also tried it from matsim code examples.  However, never used in production.
=> introduce method to create a minimal matsim injector

README.md
Hover the mouse over the badges to get more info. (You can also click them to see even more :-) )
=> Add tootips to badges

contribs/application/src/main/java/org/matsim/application/prepare/population/FixSubtourModes.java
- Option to fix all plans, and not only the selected one
- Catch exceptions and set all legs to walk, so it can be used in any circumstances
=> Improvements for the FixSubtourModes class

contribs/application/src/main/java/org/matsim/application/prepare/population/FixSubtourModes.java
- Additional option to check mass conservation of a whole plan
=> Improvements for FixSubtourModes

contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeModule.java
See: https://github.com/matsim-org/matsim-code-examples/issues/759
=> drt: support custom DrtFareHandlers

contribs/freight/src/main/java/org/matsim/contrib/freight/controler/CarrierAgent.java, contribs/freight/src/main/java/org/matsim/contrib/freight/controler/CarrierAgentTracker.java, contribs/freight/src/main/java/org/matsim/contrib/freight/controler/CarrierDriverAgent.java, contribs/freight/src/main/java/org/matsim/contrib/freight/controler/LSPEventCreator.java, contribs/freight/src/main/java/org/matsim/contrib/freight/controler/LSPEventCreatorUtils.java, contribs/freight/src/main/java/org/matsim/contrib/freight/controler/LSPServiceEndEventCreator.java, contribs/freight/src/main/java/org/matsim/contrib/freight/controler/LSPServiceStartEventCreator.java, contribs/freight/src/main/java/org/matsim/contrib/freight/controler/LSPShipmentDeliveredEventCreator.java, contribs/freight/src/main/java/org/matsim/contrib/freight/controler/LSPShipmentPickedUpEventCreator.java, contribs/freight/src/main/java/org/matsim/contrib/freight/controler/LSPTourEndEventCreator.java, contribs/freight/src/main/java/org/matsim/contrib/freight/controler/LSPTourStartEventCreator.java
Only small changes, but should be merged since I had some conflicts on the way to have a consolidated re-starting point.
=> hide LSP events a bit better

contribs/vsp/src/test/java/playground/vsp/ev/FinalSoc2VehicleTypeTest.java
IDs are automatically reset between unit tests (see: AutoResetIdCaches), so we do not transfer state between tests.
However, if we have some static fields that refer to IDs (e.g. scenario), we may run into some inconsistencies (two "identical" IDs, old and new, each having a different index).
The rule to avoid such issues in the future: keep tests independent (so the execution order does not matter) and therefore do not use static variables (except for immutable objects).
(This is my best guess what could be the reason. Let's see if this helps.)
=> vrp/ev: change scenario to non-static field in FinalSoc2VehicleTypeTest

contribs/application/src/main/java/org/matsim/application/prepare/population/FixSubtourModes.java, contribs/application/src/main/java/org/matsim/application/prepare/population/XYToLinks.java
* New xy to links command
* Fix where coord distance was not respected
=> Adding XY to links as app command

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/afterSimAnalysis/DrtVehicleStoppingTaskWriter.java
Enable custom DRT task type when setting up event readers
=> Update DRT stopping task writer

contribs/application/src/main/java/org/matsim/application/prepare/population/CheckCarAvailability.java, contribs/application/src/main/java/org/matsim/application/prepare/population/XYToLinks.java, matsim/src/main/java/org/matsim/core/population/algorithms/ChooseRandomLegModeForSubtour.java
* Added class to verify that car availability is correct (add fix if violated)
* Added car-only option to XYToLink class
=> Check for correct car availability 

matsim/src/main/java/org/matsim/core/utils/geometry/CoordUtils.java
see https://github.com/matsim-org/matsim-libs/pull/2139#issuecomment-1214838526
=> switch to atomic long for warning suppression counter

contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/shifts/analysis/efficiency/DrtShiftEfficiencyModeModule.java, contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/shifts/analysis/efficiency/ShiftEfficiencyAnalysisControlerListener.java, contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/shifts/analysis/efficiency/ShiftEfficiencyTracker.java, contribs/drt-extensions/src/test/java/org/matsim/contrib/drt/extension/shifts/analysis/efficiency/ShiftEfficiencyTest.java
- rides per drt shift 
- revenue per drt shift
=> add drt shift efficiency module (incl test)

matsim/src/main/java/org/matsim/core/population/algorithms/TripPlanMutateTimeAllocation.java, matsim/src/test/java/org/matsim/population/algorithms/TripPlanMutateTimeAllocationTest.java
Currently, the `TripPlanMutateTimeAllocation` class limits activities' durations to 24 hours. This change allows for configuring the latest endTime to a custom value (e.g., 30 hours). 24h still remains the default.
=> Make latest endTime configurable in TripPlanMutateTimeAllocation

contribs/application/src/main/java/org/matsim/application/prepare/population/TrajectoryToPlans.java
Fix when duration could go above maxTypicalDuration when merging overnight activities.
=> Fix in TrajectoryToPlans

contribs/analysis/src/main/java/org/matsim/contrib/analysis/time/TimeBinMap.java, contribs/analysis/src/test/java/org/matsim/contrib/analysis/time/TimeBinMapTest.java
Add getValue with default supplier. Something like computIfAbsent in Map
=> Add convenience method to time bin map

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/DrtAnalysisControlerListener.java, contribs/dvrp/src/main/java/org/matsim/contrib/util/stats/VehicleOccupancyProfileWriter.java, contribs/dvrp/src/main/java/org/matsim/contrib/util/stats/VehicleTaskProfileWriter.java, matsim/src/main/java/org/matsim/core/controler/OutputDirectoryHierarchy.java, matsim/src/main/java/org/matsim/core/controler/corelisteners/DumpDataAtEndImpl.java, matsim/src/main/java/org/matsim/core/utils/io/IOUtils.java
=> copy all drt analysis outputs from last iteration to output folder

contribs/freight/src/test/java/org/matsim/contrib/freight/mobsim/DistanceScoringFunctionFactoryForTests.java, matsim/src/main/java/org/matsim/core/controler/corelisteners/DumpDataAtEndImpl.java, matsim/src/main/java/org/matsim/vehicles/Vehicle.java, matsim/src/main/java/org/matsim/vehicles/VehicleUtils.java, matsim/src/test/java/org/matsim/core/config/ReflectiveConfigGroupTest.java
Just a few small cleanups in core.
=> Core cleanups

contribs/vsp/src/main/java/playground/vsp/ev/EVUtils.java, contribs/vsp/src/main/java/playground/vsp/ev/FinalSoc2VehicleType.java, contribs/vsp/src/main/java/playground/vsp/ev/MATSimVehicleWrappingEVSpecificationProvider.java, contribs/vsp/src/main/java/playground/vsp/ev/RunUrbanEVExample.java, contribs/vsp/src/main/java/playground/vsp/ev/UrbanEVTripsPlanner.java, contribs/vsp/src/test/java/playground/vsp/ev/FinalSoc2VehicleTypeTest.java
EVUtils assume the initialEnergyInKWh attribute is in VehicleType, whereas it should belong to Vehicle.
=> vsp: fix EV utils

contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/afterSimAnalysis/DrtVehicleStoppingTaskWriter.java, contribs/drt/src/main/java/org/matsim/contrib/drt/analysis/afterSimAnalysis/StoppingTaskRecorder.java
Merge the stop task and stay task into one single file; 
Add occupancy as another column.
=> Minor Update to DRT stopping task writer

contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ElectricVehicleSpecificationImpl.java, contribs/vsp/src/main/java/playground/vsp/ev/UrbanEVConfigGroup.java, contribs/vsp/src/main/java/playground/vsp/ev/UrbanEVTripsPlanner.java
Same as #2247, but this time in the vsp contrib (ev package).
=> Adapt ev naming in vsp contrib

contribs/dvrp/src/main/java/org/matsim/contrib/evrp/ChargingActivity.java, contribs/ev/src/main/java/org/matsim/contrib/ev/charging/ChargingWithQueueingLogic.java
Move the charging initialisation from DynActivityEngine to MobsimAfterSimStepListeners to solve issues mentioned in this PR: https://github.com/matsim-org/matsim-libs/pull/2264#issuecomment-1304918344
=> evrp: fix race condition around arrival and start of charging

matsim/src/test/java/org/matsim/core/mobsim/qsim/qnetsimengine/VehicleHandlerTest.java
https://ci.appveyor.com/project/michalmac/matsim-libs/builds/45313469
=> core: fix VehicleHandlerTest failing on AppVeyor

contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ConvertInitialChargeToInitialSoc.java, contribs/ev/src/main/java/org/matsim/contrib/ev/fleet/ElectricVehicleSpecificationImpl.java, contribs/vsp/src/main/java/playground/vsp/ev/UrbanEVTripsPlanner.java
=> ev: minor refactorings

matsim/src/main/java/org/matsim/core/network/algorithms/NetworkCalcTopoType.java
=> replace no-longer valid url with DOI-link

contribs/taxi/src/test/java/org/matsim/contrib/taxi/optimizer/TaxiOptimizerTests.java, contribs/taxi/src/test/java/org/matsim/contrib/taxi/optimizer/assignment/AssignmentTaxiOptimizerIT.java, contribs/taxi/src/test/java/org/matsim/contrib/taxi/optimizer/fifo/FifoTaxiOptimizerIT.java, contribs/taxi/src/test/java/org/matsim/contrib/taxi/optimizer/rules/RuleBasedTaxiOptimizerIT.java, contribs/taxi/src/test/java/org/matsim/contrib/taxi/optimizer/zonal/ZonalTaxiOptimizerIT.java, examples/scenarios/mielec/mielec_taxi_benchmark_config.xml
Prepping up for validating the actual events against the expected ones (as basic regression testing). Mainly reducing the level of customisability in favour of readability/maintainability.
=> Simplify TaxiOptimizerTests

matsim/src/main/java/org/matsim/core/population/ActivityImpl.java, matsim/src/main/java/org/matsim/core/population/InteractionActivity.java, matsim/src/main/java/org/matsim/core/population/LegImpl.java, matsim/src/main/java/org/matsim/core/population/routes/AbstractRoute.java, matsim/src/main/java/org/matsim/core/utils/misc/OptionalTime.java, matsim/src/main/java/org/matsim/pt/routes/DefaultTransitPassengerRoute.java
Three small fixes/improvements to handling of optional times in activities and legs.
=> OptionalTime in population

matsim/src/main/resources/dtd/lspsDefinitions_v1.xsd
First working version of lspDefinitions.xsd, subject to change
=> Added a xsd validation file for the Logistic Service Provide

contribs/application/src/main/java/org/matsim/application/prepare/population/SplitActivityTypesDuration.java, contribs/application/src/main/java/org/matsim/application/prepare/population/TrajectoryToPlans.java, contribs/application/src/test/java/org/matsim/application/prepare/population/SplitActivityTypesDurationTest.java
- Moved functionality to split activity types by duration to a separate class
- Option to convert end times to duration if below configured threshold
- Added test case
=> Class to split activitiy types by duration

contribs/freight/src/main/java/org/matsim/contrib/freight/carrier/CarrierPlanXmlWriterV2_1.java, matsim/src/main/resources/dtd/carriersDefinitions_v2.1.xsd
writeServices method discontinued if carrier contains no services
=> CarrierPlan will contain no services tag if services are empty

contribs/freight/src/test/java/org/matsim/contrib/freight/carrier/CarrierReadWriteV2_1Test.java, contribs/freight/test/input/org/matsim/contrib/freight/carrier/CarrierReadWriteV2_1Test/carriers.xml, contribs/freight/test/input/org/matsim/contrib/freight/carrier/CarrierReadWriteV2_1Test/vehicles.xml
=> Freight: set up of ReadWrite(-Read) tests for CarrierPlanXmlWriterV2_1

matsim/src/main/java/org/matsim/core/config/ConfigReaderMatsimV2.java, matsim/src/main/java/org/matsim/core/utils/io/MatsimXmlParser.java, matsim/src/test/java/org/matsim/core/config/ConfigReaderMatsimV2Test.java
No renaming was performed yet, I would do this only after the next big release, so we have time to update docs.
=> provide infrastructure to allow renaming config groups and params

matsim/src/main/resources/dtd/freightReceivers_v2.dtd
Added the freight receiver’s origin link Id.
=> Updated freight receiver DTD

contribs/application/src/main/java/org/matsim/application/prepare/pt/CreateTransitScheduleFromGtfs.java
Now tested on Windows machine and confirmed to be working
=>  Fix CreateTransitScheduleFromGtfs on Windows #2

contribs/informed-mode-choice/src/test/java/org/matsim/modechoice/replanning/SelectSingleTripModeStrategyTest.java
Fixes failing test on window in the imc contrib, due to process still holding file system lock.
=> Fix failing test on windows

contribs/drt/src/test/java/org/matsim/contrib/drt/run/examples/DrtAbortTest.java, examples/scenarios/mielec/plans_only_drt_rejection_test.xml, examples/scenarios/mielec/vehicles-rejection-test.xml
... But there are several things we still need to solve (potentially with Michal? As I remember, Injection does not work properly with mode specific DRT modules (Modal)).
=> The first running version for complete DRT rejection handling

contribs/common/src/main/java/org/matsim/contrib/common/timeprofile/ProfileWriter.java, contribs/common/src/main/java/org/matsim/contrib/common/timeprofile/TimeDiscretizer.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/analysis/VehicleOccupancyProfileView.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/analysis/VehicleTaskProfileView.java
instead of fixed-interval `TimeDiscretizer`
=> common: generalise ProfileWriter to use any time array

contribs/vsp/src/main/java/playground/vsp/simpleParkingCostHandler/ParkingCostConfigGroup.java
KN: changing of attribute names should only be possible via code but not via xml
=> parkingCostConfigGroup: disable setting and getting of attribute names via xml

matsim/src/main/java/org/matsim/run/gui/ExeRunner.java
This fixes issues with creating temp files on Windows (`File.createTempFile()`) in the matsim run process. For instance:
```
Caused by: java.io.IOException: Access is denied
at java.io.WinNTFileSystem.createFileExclusively(Native Method) ~[?:?]
at java.io.File.createTempFile(File.java:2170) ~[?:?]
at java.io.File.createTempFile(File.java:2216) ~[?:?]
at org.geotools.data.shapefile.files.ShpFiles.getStorageFile(ShpFiles.java:871) ~[matsim-maas-master-SNAPSHOT.jar:master-SNAPSHOT]
at org.geotools.data.shapefile.ShapefileDataStore.createSchema(ShapefileDataStore.java:291) ~[matsim-maas-master-SNAPSHOT.jar:master-SNAPSHOT]
at org.matsim.core.utils.gis.ShapeFileWriter.writeGeometries(ShapeFileWriter.java:57) ~[matsim-maas-master-SNAPSHOT.jar:master-SNAPSHOT]
... 10 more
```
This PR fixes …
=> core: pass all env vars from matsim GUI process to matsim run process

contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/companions/DrtCompanionUtils.java
This adds the small convenience method `DrtCompanionUtils.isDrtCompanion(Id<Person> personId)`.
=> Add DrtCompanionUtils.isDrtCompanion() method

contribs/application/src/main/java/org/matsim/application/analysis/traffic/TrafficAnalysis.java, contribs/application/src/main/java/org/matsim/application/analysis/traffic/TrafficStatsCalculator.java, contribs/simwrapper/src/main/java/org/matsim/simwrapper/dashboard/OverviewDashboard.java, contribs/simwrapper/src/main/java/org/matsim/simwrapper/viz/MapPlot.java, contribs/simwrapper/src/main/java/org/matsim/simwrapper/viz/Plotly.java
This PR extends the default dashboards.
=> Dasboards: Add map to overview, add volumes for individual modes

matsim/src/main/java/org/matsim/households/PersonHouseholdMapping.java
This change switches the map type in `PersonHouseholdMapping` from HashMap to IdMap.
=> Use IdMap in PersonHouseholdMapping

matsim/src/main/java/org/matsim/households/VehicleHouseholdMapping.java
The same as [`PersonHouseholdMapping`](https://github.com/marecabo/matsim-libs/blob/master/matsim/src/main/java/org/matsim/households/PersonHouseholdMapping.java), but for the household's vehicles.
=> Add VehicleHouseholdMapping helper

contribs/application/src/main/java/org/matsim/smallScaleCommercialTrafficGeneration/GenerateSmallScaleCommercialTrafficDemand.java, contribs/application/src/main/java/org/matsim/smallScaleCommercialTrafficGeneration/LanduseBuildingAnalysis.java, contribs/application/src/main/java/org/matsim/smallScaleCommercialTrafficGeneration/SmallScaleCommercialTrafficUtils.java, contribs/application/src/main/java/org/matsim/smallScaleCommercialTrafficGeneration/TrafficVolumeGeneration.java, contribs/application/src/main/java/org/matsim/smallScaleCommercialTrafficGeneration/TripDistributionMatrix.java, contribs/application/src/test/java/org/matsim/smallScaleCommercialTrafficGeneration/RunGenerateSmallScaleCommercialTrafficTest.java, contribs/application/src/test/java/org/matsim/smallScaleCommercialTrafficGeneration/SmallScaleCommercialTrafficUtilsTest.java, contribs/application/src/test/java/org/matsim/smallScaleCommercialTrafficGeneration/TrafficVolumeGenerationTest.java, contribs/application/src/test/java/org/matsim/smallScaleCommercialTrafficGeneration/TripDistributionMatrixTest.java, contribs/application/test/input/org/matsim/smallScaleCommercialTrafficGeneration/config_demand.xml, contribs/application/test/input/org/matsim/smallScaleCommercialTrafficGeneration/existingModels/existingModels.csv
- rename traffic types for small scale commercial traffic
- rename main class
=> Rename parts of small scale commercial traffic

matsim/src/main/java/org/matsim/core/population/io/ParallelPopulationReaderMatsimV6.java, matsim/src/main/java/org/matsim/core/population/io/PopulationReaderMatsimV6.java, matsim/src/test/java/org/matsim/core/population/io/PopulationV6IOTest.java
=> Fix CRS usage in ParallelPopulationReader

contribs/application/src/main/java/org/matsim/application/ApplicationUtils.java, contribs/application/src/main/java/org/matsim/application/analysis/traffic/CountComparisonAnalysis.java, contribs/simwrapper/src/main/java/org/matsim/simwrapper/Dashboard.java, contribs/simwrapper/src/main/java/org/matsim/simwrapper/dashboard/TrafficCountsDashboard.java, contribs/simwrapper/src/test/java/org/matsim/simwrapper/dashboard/TrafficCountsDashboardTest.java
This PR add a constructor that allows to use the traffic counts dashboard with any network modes.
=> Counts dashboard with configurable modes

contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/DynAgent/NearestParkingDynLeg.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/DynAgent/agentLogic/NearestParkingSpotAgentLogic.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/DynAgent/agentLogic/ParkingAgentLogic.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/ParkingSearchStrategy.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/ParkingUtils.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/evaluation/ParkingListener.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/evaluation/ParkingSlotManager.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/evaluation/ParkingSlotVisualiser.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/events/RemoveParkingActivityEvent.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/events/RemoveParkingActivityEventHandler.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/events/ReserveParkingLocationEvent.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/events/ReserveParkingLocationEventHandler.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/events/SelectNewParkingLocationEvent.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/events/SelectNewParkingLocationEventHandler.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/manager/FacilityBasedParkingManager.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/search/NearestParkingSpotSearchLogic.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/sim/ParkingAgentFactory.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/sim/ParkingManagerModule.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/sim/ParkingSearchConfigGroup.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/sim/ParkingSearchPopulationModule.java, contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/sim/ParkingSearchQSimModule.java, contribs/parking/src/main/resources/parkingsearch/config.xml
This PR contents updates for the parkingSearch part of the parking contrib (withInDayReplaning of parking search).
The development was part of the BENE project for simulating coach tours in Berlin; see: [https://github.com/matsim-vsp/bene](https://github.com/matsim-vsp/bene) 
Main functionality: methods for finding a parking slot if the driver knows the possible parking facilities.
=> Integrate updates for parking facility search.

contribs/application/pom.xml, contribs/application/src/main/java/org/matsim/application/analysis/traffic/TravelTimeAnalysis.java, contribs/application/src/main/java/org/matsim/application/analysis/traffic/traveltime/FetchRoutesTask.java, contribs/application/src/main/java/org/matsim/application/analysis/traffic/traveltime/RouteAPI.java, contribs/application/src/main/java/org/matsim/application/analysis/traffic/traveltime/SampleValidationRoutes.java, contribs/application/src/main/java/org/matsim/application/analysis/traffic/traveltime/TravelTimeComparison.java, contribs/application/src/main/java/org/matsim/application/analysis/traffic/traveltime/api/AbstractRouteValidator.java, contribs/application/src/main/java/org/matsim/application/analysis/traffic/traveltime/api/GoogleRouteValidator.java, contribs/application/src/main/java/org/matsim/application/analysis/traffic/traveltime/api/HereRouteValidator.java, contribs/application/src/main/java/org/matsim/application/analysis/traffic/traveltime/api/MapboxRouteValidator.java, contribs/application/src/main/java/org/matsim/application/analysis/traffic/traveltime/api/RouteValidator.java, contribs/application/src/main/java/org/matsim/application/analysis/traffic/traveltime/api/TomTomRouteValidator.java, contribs/application/src/main/java/org/matsim/application/analysis/traffic/traveltime/api/WoosMapRouteValidator.java, contribs/simwrapper/src/main/java/org/matsim/simwrapper/dashboard/TravelTimeComparisonDashboard.java, matsim/src/main/java/org/matsim/core/utils/geometry/CoordUtils.java
Adds new analysis classes for comparing travel times from online services against simulation
- New class to fetch and store multiple travel time APIs in parallel.
- More supported APIs
- Corresponding analysis and dashboard
- Deprecates the old TravelTimeAnalysis
=> Traveltime analysis rework

contribs/application/src/main/java/org/matsim/smallScaleCommercialTrafficGeneration/GenerateSmallScaleCommercialTrafficDemand.java, contribs/application/src/main/java/org/matsim/smallScaleCommercialTrafficGeneration/LanduseBuildingAnalysis.java, contribs/application/src/main/java/org/matsim/smallScaleCommercialTrafficGeneration/SmallScaleCommercialTrafficUtils.java, contribs/application/src/test/java/org/matsim/smallScaleCommercialTrafficGeneration/LanduseBuildingAnalysisTest.java, contribs/application/src/test/java/org/matsim/smallScaleCommercialTrafficGeneration/RunGenerateSmallScaleCommercialTrafficTest.java, contribs/application/src/test/java/org/matsim/smallScaleCommercialTrafficGeneration/TrafficVolumeGenerationTest.java
now the input is a Path to a certain config, instead of to a directory.
=> Change config load for small scale commercial traffic

matsim/src/main/java/org/matsim/core/population/io/AbstractPopulationWriterHandler.java, matsim/src/main/java/org/matsim/core/population/io/PopulationWriterHandlerImplV0.java, matsim/src/main/java/org/matsim/core/population/io/PopulationWriterHandlerImplV4.java, matsim/src/main/java/org/matsim/core/population/io/PopulationWriterHandlerImplV5.java, matsim/src/main/java/org/matsim/core/population/io/PopulationWriterHandlerImplV6.java
=> moved flush from writePerson to endPlans

.github/workflows/codeql.yml
Run [CodeQL](https://codeql.github.com/) analysis on pushing to master.
=> build: add CodeQL workflow on push to master

matsim/src/test/java/org/matsim/analysis/TripsAnalysisIT.java
=> add IT to ensure main_mode in output_trips.csv is not empty

contribs/simwrapper/src/main/java/org/matsim/simwrapper/dashboard/OverviewDashboard.java
Update dashboard to the new capitalization of the "iteration" column.
=> Fix overview dashboard

contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/DvrpConfigGroup.java
This PR allows to extend the DvrpConfigGroup similar to the DrtConfigGroup with configurable ParameterSets.
=> Extendable DvrpConfigGroup

matsim/src/main/java/org/matsim/core/controler/AbstractModule.java
Add useful comment to explain, why we have Multibinder attributes.
=> Refactor AbtractModule

contribs/application/src/main/java/org/matsim/application/options/ScenarioOptions.java, contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/estimator/MultiModalDrtLegEstimator.java, contribs/informed-mode-choice/src/main/java/org/matsim/modechoice/EstimateRouter.java, contribs/informed-mode-choice/src/main/java/org/matsim/modechoice/InformedModeChoiceConfigGroup.java, contribs/informed-mode-choice/src/main/java/org/matsim/modechoice/commands/GenerateChoiceSet.java, contribs/informed-mode-choice/src/main/java/org/matsim/modechoice/estimators/LegEstimator.java, contribs/informed-mode-choice/src/main/java/org/matsim/modechoice/replanning/MultinomialLogitSelector.java, contribs/informed-mode-choice/src/main/java/org/matsim/modechoice/search/TopKChoicesGenerator.java, contribs/informed-mode-choice/src/test/java/org/matsim/modechoice/replanning/MultinomialLogitSelectorTest.java
Small improvements for using drt estimators with informed mode-choice. 
- Ignore drt trips that don't contain actual drt legs
- Option to keep initial plan in GenerateChoiceSet class
=> Drt estimator improvements

contribs/matrixbasedptrouter/src/main/java/org/matsim/contrib/matrixbasedptrouter/FileUtils.java, contribs/matrixbasedptrouter/src/main/java/org/matsim/contrib/matrixbasedptrouter/PtMatrix.java, contribs/matrixbasedptrouter/src/test/java/org/matsim/contrib/matrixbasedptrouter/PtMatrixTest.java, matsim/src/test/java/org/matsim/core/mobsim/qsim/VehicleSourceTest.java, matsim/src/test/java/org/matsim/testcases/MatsimTestUtils.java
This PR fixes https://github.com/matsim-org/matsim-libs/actions/workflows/full-integration.yaml for Windows.
=> Fix full integration on windows

contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/companions/DrtCompanionGroupIdentifier.java, contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/companions/DrtCompanionModule.java, contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/companions/DrtCompanionParams.java, contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/companions/DrtCompanionRideGenerator.java, contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/companions/DrtCompanionUtils.java, contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/companions/MultiModeDrtCompanionModule.java
This PR implements the new PassengerGroupIdentifier for DrtCompanions.
=> DrtCompanion with PassengerGroupIdentifier

contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/companions/DrtCompanionRideGenerator.java, contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/companions/DrtCompanionUtils.java
PR moves the DRT_COMPANION_AGENT_PREFIX to DrtCompanionUtils
=> Move DRT_COMPANION_AGENT_PREFIX

contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/companions/DrtCompanionRideGenerator.java
Add support for scenarios with facilities
=> Make companion validation work with facilities

contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/companions/DrtCompanionRideGenerator.java
This PR ensures and validates identical departure times of drt companions
=> Validate leg departure time of companions

contribs/application/src/main/java/org/matsim/freightDemandGeneration/CarrierReaderFromCSV.java, contribs/application/src/main/java/org/matsim/freightDemandGeneration/DemandReaderFromCSV.java, contribs/application/src/main/java/org/matsim/freightDemandGeneration/FreightDemandGeneration.java, contribs/application/src/main/java/org/matsim/freightDemandGeneration/FreightDemandGenerationUtils.java, contribs/application/src/test/java/org/matsim/freightDemandGeneration/CarrierReaderFromCSVTest.java, contribs/application/src/test/java/org/matsim/freightDemandGeneration/DemandReaderFromCSVTest.java, contribs/application/src/test/java/org/matsim/freightDemandGeneration/FreightDemandGenerationUtilsTest.java
- adjust homeCoord detection
- use shape index instead of allFeatures
=> Update freight generation

contribs/vsp/src/main/java/org/matsim/freight/carriers/analysis/FreightTimeAndDistanceAnalysisEventsHandler.java, contribs/vsp/src/main/java/org/matsim/freight/carriers/analysis/RunFreightAnalysisEventBased.java, contribs/vsp/test/input/org/matsim/freight/carriers/analysis/FreightAnalysisEventBasedTest/runFreightAnalysisEventBasedTest/TimeDistance_perVehicle.tsv, contribs/vsp/test/input/org/matsim/freight/carriers/analysis/FreightAnalysisEventBasedTest/runFreightAnalysisEventBasedTest/TimeDistance_perVehicleType.tsv
add some additional columns, e.g. to simply visualization.
=> Update carriers analysis

contribs/application/src/main/java/org/matsim/application/ApplicationUtils.java, contribs/application/src/main/java/org/matsim/application/MATSimApplication.java, contribs/application/src/test/java/org/matsim/application/ConfigYamlUpdateTest.java, contribs/application/test/input/org/matsim/application/ConfigYamlUpdateTest/config.xml, contribs/application/test/input/org/matsim/application/ConfigYamlUpdateTest/params.yml
- Fix case where default args were not used
- Add more tests
=> Application contrib maintenance

contribs/vsp/src/main/java/org/matsim/contrib/vsp/scenario/SnzActivities.java
Small fix where interaction activities have been overwritten, which is not necessary.
=> Fix for activity setup in vsp contrib

matsim/src/main/java/org/matsim/utils/objectattributes/StringDoubleMap.java, matsim/src/main/java/org/matsim/utils/objectattributes/attributeconverters/StringDoubleMapConverter.java
Move the newly introduced StringDoubleMap one package up. Thanks @mrieser for the advice.
=> Move StringDoubleMap

contribs/application/src/main/java/org/matsim/application/prepare/network/params/ApplyNetworkParams.java, contribs/sumo/src/main/java/org/matsim/contrib/sumo/SumoNetworkConverter.java, contribs/sumo/src/main/java/org/matsim/contrib/sumo/SumoNetworkHandler.java
The sumo network converter now also adds truck to available modes if permissible.
=> Consider truck vehicle type in SUMO network converter

contribs/application/src/main/java/org/matsim/application/options/LanduseOptions.java, contribs/application/src/main/java/org/matsim/application/options/ShpOptions.java, contribs/application/src/main/java/org/matsim/application/prepare/freight/tripGeneration/DefaultLocationCalculator.java
ShpOptions.Index now allows having a predicate function to filter desired features instead of a fixed set of values.
=> More flexible filter in shp index

contribs/application/src/main/java/org/matsim/application/prepare/freight/tripExtraction/ExtractRelevantFreightTrips.java
- add the option to create different types (all, incoming, outgoing, intern, transit) of long-distance freight separately
=> Add option to create the different types of long-distance freight trips separately

contribs/freight/src/main/java/org/matsim/freight/carriers/CarriersUtils.java, contribs/freight/src/test/java/org/matsim/freight/carriers/CarriersUtilsTest.java, contribs/vsp/src/main/java/org/matsim/freight/carriers/analysis/CarrierPlanAnalysis.java, contribs/vsp/test/input/org/matsim/freight/carriers/analysis/FreightAnalysisEventBasedTest/runFreightAnalysisEventBasedTest/Carrier_stats.tsv
- adds the jsprit computation time for each carrier in the attributes of the carrier
=> Add carrier attribute for calculation time

.gitignore, contribs/dvrp/src/test/java/org/matsim/contrib/dvrp/path/OneToManyPathCalculatorTest.java, contribs/dvrp/src/test/java/org/matsim/core/router/speedy/SpeedyMultiSourceALTBackwardTest.java, contribs/dvrp/src/test/java/org/matsim/core/router/speedy/SpeedyMultiSourceALTForwardTest.java, matsim/src/main/java/org/matsim/core/network/DisallowedNextLinks.java, matsim/src/main/java/org/matsim/core/network/algorithms/TransportModeNetworkFilter.java, matsim/src/main/java/org/matsim/core/router/NetworkRoutingProvider.java, matsim/src/main/java/org/matsim/core/router/SingleModeNetworksCache.java, matsim/src/main/java/org/matsim/core/router/speedy/SpeedyGraphBuilder.java, matsim/src/test/java/org/matsim/core/router/speedy/SpeedyALTTest.java, matsim/src/test/java/org/matsim/core/router/speedy/SpeedyDijkstraTest.java, matsim/src/test/java/org/matsim/core/router/speedy/SpeedyGraphBuilderTest.java, matsim/src/test/java/org/matsim/core/router/speedy/SpeedyGraphTest.java
This is a contribution to #3024, in a separate PR to make comparison easier. Discussion should happen in original PR
=> Monomodal turn restrictions

contribs/drt/src/main/java/org/matsim/contrib/drt/prebooking/PrebookingStopActivity.java
This change improves the performance of `PrebookingStopActivity` a bit.
* Use PriorityQueue for `PrebookingStopActivity.leaveTimes`.
=> Performance improvements for PrebookingStopActivity

contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/dashboards/DrtAnalysisPostProcessing.java
=> account for group bookings in DrtAnalysisPostProcessing 

contribs/application/src/main/java/org/matsim/freightDemandGeneration/CarrierReaderFromCSV.java, contribs/application/src/main/java/org/matsim/freightDemandGeneration/DemandReaderFromCSV.java, contribs/application/src/main/java/org/matsim/freightDemandGeneration/FreightDemandGeneration.java, contribs/application/src/main/java/org/matsim/freightDemandGeneration/FreightDemandGenerationUtils.java
- fix some little bugs
- formatting
- adding comments
- cleanup
=> Modify freight demand generation tool

matsim/src/main/java/ch/sbb/matsim/config/SwissRailRaptorConfigGroup.java, matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/RaptorStaticConfig.java, matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorCore.java, matsim/src/main/java/ch/sbb/matsim/routing/pt/raptor/SwissRailRaptorData.java
Some clean-up based on @mrieser's comments on #3289 and a renaming to "adaptive" calculation, which seems clearer to me.
=> chore: cleanup adaptive transfers

contribs/small-scale-traffic-generation/src/main/java/org/matsim/smallScaleCommercialTrafficGeneration/GenerateSmallScaleCommercialTrafficDemand.java, contribs/small-scale-traffic-generation/src/main/java/org/matsim/smallScaleCommercialTrafficGeneration/SmallScaleCommercialTrafficUtils.java
- get mode from vehicleType instead of set in the code
=> Adjust mode selection for small scale commercial

contribs/common/src/main/java/org/matsim/contrib/common/zones/systems/grid/h3/H3ZoneSystem.java, contribs/common/src/main/java/org/matsim/contrib/common/zones/systems/grid/square/SquareGridZoneSystem.java, contribs/common/src/test/java/org/matsim/contrib/common/zones/systems/h3/H3DrtZonalSystemTest.java
greatly improves system generation run time
=> Optimize H3 Zone System initialization

contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/eshifts/scheduler/EShiftTaskScheduler.java, contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/shifts/dispatcher/DrtShiftDispatcherImpl.java, contribs/drt-extensions/src/test/java/org/matsim/contrib/drt/extension/fiss/RunFissDrtScenarioIT.java
This setup _should_ now work with electirc vehicles, shifts and prebooking
Lesson learned after hours of debugging:
priority queues do not iterate in the order as one may hope for T__T
=> make drt work with electric vehicles, shifts and prebooking

contribs/freight/src/main/java/org/matsim/freight/carriers/controler/CarrierAgent.java, contribs/freight/src/main/java/org/matsim/freight/carriers/controler/FreightAgentSource.java
Seems, like they were on WARN for some debug reasons... But it is normal wirk that is done there. So setting it to DEBUG.
Provide some more information in one of that log statements.
=> Freight: Reduce level of some log entries

contribs/vsp/src/main/java/org/matsim/contrib/vsp/pt/fare/DistanceBasedPtFareCalculator.java, contribs/vsp/src/main/java/org/matsim/contrib/vsp/pt/fare/FareZoneBasedPtFareCalculator.java, contribs/vsp/src/main/java/org/matsim/contrib/vsp/pt/fare/PtFareModule.java, contribs/vsp/src/test/java/org/matsim/contrib/vsp/pt/fare/DistanceBasedPtFareCalculatorTest.java, contribs/vsp/src/test/java/org/matsim/contrib/vsp/pt/fare/FareZoneBasedPtFareCalculatorTest.java
pt fares interpret file paths to fare zone shapes relative to config file
=> pt fares interpret file paths to fare zone shapes relative to config file

contribs/drt-extensions/src/test/java/org/matsim/contrib/drt/extension/edrt/run/RunEDrtScenarioIT.java, contribs/drt-extensions/src/test/java/org/matsim/contrib/drt/extension/operations/shifts/run/RunPrebookingShiftDrtScenarioIT.java, contribs/drt/src/main/java/org/matsim/contrib/drt/prebooking/PrebookingManager.java, contribs/drt/src/main/java/org/matsim/contrib/drt/prebooking/PrebookingModeQSimModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/prebooking/PrebookingParams.java, contribs/drt/src/test/java/org/matsim/contrib/drt/run/examples/RunDrtExampleIT.java
@sebhoerl as discussed earlier
=> Drt: make re-attempts of prebooking rejections optional

.github/workflows/deploy-dtds.yaml
GitHub Action to deploy DTDs to the matsim-website whenever a file inside the dtd-directory is changed
=> add github action to deploy dtds

contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/constraints/DrtRouteConstraints.java, contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DefaultDrtRouteConstraintsCalculator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtRouteConstraintsCalculator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/routing/DrtRouteCreator.java, contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtModeRoutingModule.java, contribs/drt/src/test/java/org/matsim/contrib/drt/routing/DrtRoutingModuleTest.java
See #3478. This is my proposal to have things more streamlined (at least in my opinion, but maybe there are good arguments against it). What do you think @nkuehnel?
=> feat: flexibilize structure of drt route constraints

contribs/application/src/main/java/org/matsim/freightDemandGeneration/DemandReaderFromCSV.java, contribs/application/src/main/java/org/matsim/freightDemandGeneration/FreightDemandGeneration.java, contribs/application/src/test/java/org/matsim/freightDemandGeneration/DemandReaderFromCSVTest.java
- removes a bug for one case of the freight generation tool if you want to increase the demand per person
- adds more tests based on the different cases
=> Fix freight generation tool bug

contribs/application/src/main/java/org/matsim/application/options/ShpOptions.java, contribs/application/src/main/java/org/matsim/application/prepare/scenario/CreateScenarioCutOut.java
In follow-up of #3506, the scenario cutout now also supports shp files with different coordinate systems than the scenario
=> Support CRS transformations for scenario cutout 

contribs/vsp/src/main/java/org/matsim/core/scoring/functions/PersonScoringParametersFromPersonAttributes.java, contribs/vsp/src/test/java/org/matsim/core/scoring/functions/PersonScoringParametersFromPersonAttributesNoSubpopulationTest.java, contribs/vsp/src/test/java/org/matsim/core/scoring/functions/PersonScoringParametersFromPersonAttributesTest.java
prior to that person specific asc replaced the subpopulation's asc
=> interpret person specific asc as offset in addition to the subpopulation's asc

contribs/application/src/main/java/org/matsim/application/prepare/scenario/CreateScenarioCutOut.java
The scenario cut-out class now correctly considers stationary agents as well.
=> Consider stationary agents in scenario cut-out

contribs/application/src/main/java/org/matsim/freightDemandGeneration/DefaultJobDurationCalculator.java, contribs/application/src/main/java/org/matsim/freightDemandGeneration/DemandReaderFromCSV.java, contribs/application/src/main/java/org/matsim/freightDemandGeneration/FreightDemandGeneration.java, contribs/application/src/main/java/org/matsim/freightDemandGeneration/FreightDemandGenerationUtils.java, contribs/application/src/main/java/org/matsim/freightDemandGeneration/JobDurationCalculator.java, contribs/application/src/test/java/org/matsim/freightDemandGeneration/DemandReaderFromCSVTest.java
- add interface with implementation to improve the calculation of a job duration
- add test for the case of combining jobs
=> Develop tool for freight generation

contribs/vsp/src/test/java/playground/vsp/cadyts/marginals/ModalDistanceAndCountsCadytsIT.java
.... otherwise, these keep falling on Windows :(
Relates to [#3535](https://github.com/matsim-org/matsim-libs/issues/3535)
=> Change Test Output dir for paramterized tests

examples/scenarios/logistics-2regions/2regions-network.xml
Needs to be done before the code base (#3590), because otherwise it is not available for the tests on matsim-libs :(
=> Logistics: add (example) network file for logistics to matsim-examples

.github/workflows/deploy-dtds.yaml
I used the wrong comments signs -.-
=> Fix error in deploy-dtds.yaml

.github/workflows/full-integration.yaml
keeps on failing at certain tests.
solves https://github.com/matsim-org/matsim-libs/issues/3535 for the time being.
=> disable macOS build

contribs/ev/src/main/java/org/matsim/contrib/ev/stats/ChargingProceduresCSVWriter.java, contribs/ev/src/main/java/org/matsim/contrib/ev/stats/EvStatsModule.java
- Fixes special case in `ChargingProceduresCSVWriter` when a vehicle is still queued at the end of the day
- Makes `EvConfigGroup.timeProfiles` disable *all* profiles (some were not covered before)
=> feat/fix(ev): minor changes

contribs/application/src/main/java/org/matsim/application/prepare/pt/CreateTransitScheduleFromGtfs.java
Adapt `CreateTransitScheduleFromGtfs` to also work with loop links.
=> Calculate correct link speed when using PT loop links

contribs/informed-mode-choice/src/main/java/org/matsim/modechoice/InformedModeChoiceConfigGroup.java, contribs/informed-mode-choice/src/main/java/org/matsim/modechoice/InformedModeChoiceModule.java, contribs/informed-mode-choice/src/main/java/org/matsim/modechoice/PlanModelService.java, contribs/informed-mode-choice/src/main/java/org/matsim/modechoice/commands/StrategyOptions.java, contribs/informed-mode-choice/src/main/java/org/matsim/modechoice/estimators/TripScoreEstimator.java, contribs/informed-mode-choice/src/main/java/org/matsim/modechoice/pruning/PlanScoreThresholdPruner.java, contribs/informed-mode-choice/src/test/java/org/matsim/modechoice/search/TopKMinMaxTest.java
Add functionality to define `TripScoreEstimator` to informed-mode-choice contrib, which are applied to all trips regardless of mode.
=> IMC Trip Score Estimator

contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/router/DvrpModeRoutingNetworkModule.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/DvrpModule.java, contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/FreeSpeedTravelTimeMatrix.java, contribs/dvrp/src/test/java/org/matsim/contrib/zone/skims/FreeSpeedTravelTimeMatrixTest.java
I had some trouble with file paths that contained spaces " "
=> Use URL instead of path string in matrix cache

matsim/src/test/java/org/matsim/core/replanning/choosers/BalancedInnovationStrategyChooserTest.java
This (hopefully) fixes the full integration test which has different rng sequences.
=> Fix full integration tests

contribs/application/src/main/java/org/matsim/freightDemandGeneration/CarrierReaderFromCSV.java, contribs/application/src/main/java/org/matsim/freightDemandGeneration/DemandReaderFromCSV.java, contribs/application/src/main/java/org/matsim/freightDemandGeneration/FreightDemandGeneration.java, contribs/freight/src/main/java/org/matsim/freight/carriers/CarriersUtils.java, contribs/small-scale-traffic-generation/src/main/java/org/matsim/smallScaleCommercialTrafficGeneration/GenerateSmallScaleCommercialTrafficDemand.java
- adds an analysis of a generated freight demand before running Jsprit
=> Add analysis to freight demand generation

contribs/application/src/main/java/org/matsim/freightDemandGeneration/DemandGenerationSpecificationForParcelDelivery.java
Fixes a difference between planned and distributed demand because of rounding errors.
=> fix rounding difference to demandToDistribute

contribs/freight/src/main/java/org/matsim/freight/carriers/CarriersUtils.java, contribs/freight/src/main/java/org/matsim/freight/carriers/analysis/CarriersAnalysis.java
- integrates the freight analysis folder into the analysis folder structure of the simwrapper module
=> change Path of default freight analysis

.github/workflows/code-coverage.yaml, .github/workflows/deploy-on-pr-merge.yaml, .github/workflows/deploy-on-release-created.yaml, .github/workflows/deploy-weekly.yaml, .github/workflows/full-integration.yaml, .github/workflows/verify-push.yaml
This reverts commit 31ed6dbac4ba0c7cb28250a6e5f9a07dbb5c4e4f. (Based on the discussion with @rakow, see #3689)
=> Revert "Increase mvn memory within github action (#3689)"

contribs/application/src/main/java/org/matsim/freightDemandGeneration/DemandReaderFromCSV.java, contribs/application/src/test/java/org/matsim/freightDemandGeneration/DemandReaderFromCSVTest.java
- the previous code had some problems if an home coord and the nearest link are in different districts (if they are used in the simulation)
=> Fix link selection for freight demand generation

contribs/application/src/main/java/org/matsim/freightDemandGeneration/DemandReaderFromCSV.java
- checks the max vehicleCapacity of the fleet of a carrier when jobs are combined
=> Check vehicle capacity for combining jobs

contribs/freight/src/main/java/org/matsim/freight/logistics/LSPConstants.java, contribs/freight/src/main/java/org/matsim/freight/logistics/io/LSPPlanXmlParserV1.java, contribs/freight/src/main/java/org/matsim/freight/logistics/resourceImplementations/DistributionServiceStartEventHandler.java, contribs/freight/src/main/java/org/matsim/freight/logistics/resourceImplementations/LSPTourEndEventHandler.java, contribs/freight/src/main/java/org/matsim/freight/logistics/shipment/LoggedLspShipmentHandle.java, contribs/freight/src/main/java/org/matsim/freight/logistics/shipment/LoggedLspShipmentLoad.java, contribs/freight/src/main/java/org/matsim/freight/logistics/shipment/LoggedLspShipmentTransport.java, contribs/freight/src/main/java/org/matsim/freight/logistics/shipment/LoggedLspShipmentUnload.java, contribs/freight/src/main/java/org/matsim/freight/logistics/shipment/ScheduledLspShipmentHandle.java, contribs/freight/src/main/java/org/matsim/freight/logistics/shipment/ScheduledLspShipmentLoad.java, contribs/freight/src/main/java/org/matsim/freight/logistics/shipment/ScheduledLspShipmentTransport.java, contribs/freight/src/main/java/org/matsim/freight/logistics/shipment/ScheduledLspShipmentUnload.java
It just replaces the hard-code strings.
=> Freight (Logistics) use constants for shipment activity types

contribs/freight/src/main/java/org/matsim/freight/logistics/shipment/LoggedLspShipmentHandling.java, contribs/freight/src/main/java/org/matsim/freight/logistics/shipment/LoggedLspShipmentLoad.java, contribs/freight/src/main/java/org/matsim/freight/logistics/shipment/LoggedLspShipmentTransport.java, contribs/freight/src/main/java/org/matsim/freight/logistics/shipment/LoggedLspShipmentUnload.java, contribs/freight/src/main/java/org/matsim/freight/logistics/shipment/LspShipment.java, contribs/freight/src/main/java/org/matsim/freight/logistics/shipment/LspShipmentImpl.java, contribs/freight/src/main/java/org/matsim/freight/logistics/shipment/LspShipmentUtils.java
only some comments, no changes in code.
=> Freight (logisitcs): add comments to ShipmentLog

contribs/dvrp/src/main/java/org/matsim/contrib/zone/skims/FreeSpeedTravelTimeMatrix.java, contribs/dvrp/src/test/java/org/matsim/contrib/zone/skims/FreeSpeedTravelTimeMatrixTest.java
Somewhere along the way, the functionality to regenerate a travel time matrix cache file based on the config path got broken. I think it happened when we switched to `URL`, the main reason being that `IOUtils.getInputStream` only raises `UncheckedIOException`, in particular, it wraps it around `FileNotFoundException`, which, previously, we were listening for. A unit test has been added that verifies the correct behaviour all the way from loading the config.
=> fix: regenerate dvrp cache from config

contribs/dvrp/src/test/java/org/matsim/contrib/zone/skims/FreeSpeedTravelTimeMatrixTest.java
pipeline failure as logged here: https://github.com/matsim-org/matsim-libs/actions/runs/13361354804/job/37311478777
=> Update FreeSpeedTravelTimeMatrixTest to fix Windows Pipeline

contribs/application/src/main/java/org/matsim/application/prepare/freight/tripExtraction/ExtractRelevantFreightTrips.java
- adds an attribute if a trip is internal, outgoing, ingoing or transit if you extract long-distance freight for your selected region
=> Update attributes for long distance freight

contribs/drt/src/main/java/org/matsim/contrib/drt/prebooking/PrebookingManager.java
=> fix handling of prebooked stuck agents

contribs/common/src/main/java/org/matsim/contrib/common/timeprofile/TimeDiscretizer.java
Add a couple of messages to the assertions in TimeDiscretizer.
=> Friendly assertion messages in TimeDiscretizer

matsim/src/main/java/org/matsim/core/mobsim/qsim/qnetsimengine/QueueWithBuffer.java
was accidently given every time except the first 10 times before...
=> give 'future supressed' warning in QueueWithBuffer only once

.github/workflows/pr-title.yml
Add a check that the PR title follows conventional commits (#3827)
=> feat: check PR title following conventional commits

contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/edrt/run/EDrtModeOptimizerQSimModule.java, contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/eshifts/run/ShiftEDrtModeOptimizerQSimModule.java, contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/shifts/run/ShiftDrtModeOptimizerQSimModule.java, contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/preplanned/optimizer/PreplannedDrtModeOptimizerQSimModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DrtModeOptimizerQSimModule.java, contribs/drt/src/test/java/org/matsim/contrib/drt/config/ConfigBehaviorTest.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/benchmark/DvrpBenchmarkConfigConsistencyChecker.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/benchmark/DvrpBenchmarkTravelTimeModule.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/benchmark/DvrpBenchmarks.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetaxi/OneTaxiActionCreator.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/router/DvrpGlobalRoutingNetworkProvider.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/router/DvrpModeRoutingNetworkModule.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/run/DvrpConfigGroup.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/trafficmonitoring/DvrpOfflineTravelTimeEstimator.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/trafficmonitoring/DvrpOnlineTravelTimeEstimator.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/trafficmonitoring/DvrpTravelTimeModule.java, contribs/taxi/src/main/java/org/matsim/contrib/taxi/vrpagent/TaxiActionCreator.java, contribs/vsp/src/test/java/org/matsim/integration/drtAndPt/PtAlongALine2Test.java
Based on the discussions in https://github.com/matsim-org/matsim-libs/issues/3810 and https://github.com/matsim-org/matsim-libs/issues/3811, update ConfigGroup for dvrp with setters and getters.
=> chore(dvrp): update to setters and getters

.github/workflows/verify-merge-queue.yaml, .github/workflows/verify-push.yaml
We are using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/), so that we are able to auto generate a changelog. The format is described below:
`<type>[optional scope]: <description>` e.g.: fix(QSim): Correctly calculate travel times on links
Optionally, describe the change in more detail.
If the PR introduces a breaking change write: BREAKING CHANGE at the bottom of the message
=> add a dummy script

contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/insertion/spatialFilter/SpatialRequestFleetFilter.java
check class of DRTTask instead of BaseType
charging tasks have to base task. This way of operating covers those cases, and is also logically what is needed.
=> fix: SpatialRequestFleetFilter can now also understand tasks without BaseType

contribs/vsp/src/main/java/org/matsim/contrib/vsp/pt/fare/DistanceBasedPtFareParams.java
docs: add comment re reference year of pt prices
=> add comment re reference year of pt prices

matsim/src/main/java/org/matsim/core/network/turnRestrictions/TurnRestrictionsNetworkCleaner.java
So far turn restrictions have been reapplied as "car" always after cleaning the expanded network.
=> fix(core): make turn restrictions network cleaner truly mode dependent

contribs/accessibility/src/main/java/org/matsim/contrib/accessibility/AccessibilityFromEvents.java, matsim/src/main/java/org/matsim/core/controler/AbstractController.java, matsim/src/main/java/org/matsim/core/controler/ControlerListenerManagerImpl.java, matsim/src/main/java/org/matsim/core/controler/MatsimRuntimeModifications.java, matsim/src/main/java/org/matsim/core/controler/ReplayEvents.java, matsim/src/main/java/org/matsim/core/controler/events/ShutdownEvent.java, matsim/src/test/java/org/matsim/analysis/IterationTravelStatsControlerListenerTest.java, matsim/src/test/java/org/matsim/analysis/ScoreStatsControlerListenerTest.java
for information purpose in shutdown event consumers
=> feat(core): add optional exception message to shutdown event

matsim/src/main/java/org/matsim/core/router/speedy/SpeedyALT.java, matsim/src/main/java/org/matsim/core/router/speedy/SpeedyDijkstra.java
only consider starts of colored subgraphs for start node
=> fix(core): fix bug in turn restriction routing

matsim/src/main/java/org/matsim/core/network/turnRestrictions/TurnRestrictionsNetworkCleaner.java, matsim/src/main/java/org/matsim/core/router/speedy/SpeedyALT.java, matsim/src/main/java/org/matsim/core/router/speedy/SpeedyDijkstra.java, matsim/src/test/java/org/matsim/core/network/turnRestrictions/TurnRestrictionsNetworkCleanerTest.java
=> fix(core): Make TurnRestrictionsContext independent of link order

contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/path/LeastCostPathTreeStopCriteria.java
nodes may get visited twice with colored nodes
=> fix(core): only count visited nodes once in least cost path stop criteria

matsim/src/main/java/org/matsim/core/network/turnRestrictions/TurnRestrictionsNetworkCleaner.java
This change tracks the visited link ids when reapplying turn restrictions. This is necessary to prevent infinite loops in rare circumstances where colored links form a loop.
=> fix(core): Track visited link ids when reapplying turn restrictions

contribs/small-scale-traffic-generation/src/test/java/org/matsim/smallScaleCommercialTrafficGeneration/RunGenerateSmallScaleCommercialTrafficTest.java, contribs/small-scale-traffic-generation/src/test/java/org/matsim/smallScaleCommercialTrafficGeneration/TripDistributionMatrixTest.java
- fixes the missing implementation of the example data reader
=> test(small-scale-commercial-traffic): fix test

matsim/src/main/java/org/matsim/api/core/v01/Id.java
(I keep needing them in teaching at a time where talking about generating MATSim Ids is far in the future.)
=> feat: add convenience creators for Id<VehicleType>

contribs/freight/src/main/java/org/matsim/freight/carriers/CarriersUtils.java
Add the information of the carrier to the log message. 
Update the syntax for creating the log message on the way.
=> refactor(freight(carriers)): Improve log message

pom.xml
This should™ fix the tests in #4065 and #4048
=> fix(deps): add junit-jupiter-api to dependency management

pom.xml
This should fix the tests in #4064
=> build(deps): bump commons-logging:commons-logging from 1.2 to 1.3.5

contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/repeatedselective/RepeatedSelectiveInsertionSearch.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/selective/SelectiveInsertionSearch.java
Fix some filenames when working with various threads, each InsertionSearch creates its own stats csv.
=> fix(drt): Minor file name fixes

contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/parallel/partitioner/vehicles/ShiftingRoundRobinVehicleEntryPartitioner.java, contribs/drt/src/test/java/org/matsim/contrib/drt/optimizer/insertion/parallel/partitioner/ShiftingRoundRobinVehicleEntryPartitionerTest.java
Ensure that active request and vehicle partitions are matching.
=> fix(drt): Fixed ShiftingRoundRobinVehicleEntryPartitioner and provide unit test

contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/edrt/run/EDrtModeOptimizerQSimModule.java, contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/shifts/run/ShiftDrtModeOptimizerQSimModule.java, contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/preplanned/optimizer/PreplannedDrtModeOptimizerQSimModule.java, contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/services/optimizer/DrtServiceOptimizerQSimModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DefaultDrtOptimizer.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/DrtModeOptimizerQSimModule.java, contribs/drt/src/main/java/org/matsim/contrib/drt/schedule/DrtRoutingDriveTaskUpdater.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/schedule/AbstractRoutingDriveTaskUpdater.java, contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/schedule/ThreadLocalLeastCostPathCalculatorProvider.java
Performance improvement of drt by parallel timing updates.
Before:
After:
=> chore(drt): Parallel update schedule timings

contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/shifts/optimizer/ShiftBreakStopWaypoint.java, contribs/drt-extensions/src/main/java/org/matsim/contrib/drt/extension/operations/shifts/optimizer/ShiftChangeoverStopWaypoint.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/StopWaypoint.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/StopWaypointImpl.java, contribs/drt/src/main/java/org/matsim/contrib/drt/optimizer/insertion/InsertionGenerator.java
make it slightly more expressive instead of handling nulls
=> refactor(drt): make capacity change optional in waypoints

contribs/freight/src/main/java/org/matsim/freight/carriers/jsprit/MatsimJspritFactory.java, contribs/freight/src/main/java/org/matsim/freight/logistics/LSPUtils.java, contribs/freight/src/main/java/org/matsim/freight/logistics/examples/simulationTrackers/TourStartHandler.java
Change some logging levels and limit other logging calls.
=> refactor(freight): reduce logging

contribs/application/src/test/java/org/matsim/application/options/SampleOptionsTest.java, matsim/src/main/java/org/matsim/application/options/SampleOptions.java
Allow double sample options like 0.1. 
@rakow FYI
=> feat(application): introduce double sample options

contribs/freight/src/main/java/org/matsim/freight/logistics/examples/multipleChains/RunExampleTwoLspsGroceryDeliveryMultipleChainsWithToll.java
... now also defining the vehicle for the different carriers on the command-line args.
(No changes in productive code)
=> chore(freight:logistic): Update RunExampleSettings
